NativeScript/nativescript-cli

package.json
Change package.json to use vladimirov/fibers_1_0_5_fixes branch where node-fibers are built with all latest fixes. This is a temporary change that has to be removed after merging vladimirov/fibers_1_0_5_fixes into master of node-fibers repo. The temp change is required for testing purposes.
=> Use vladimirov/fibers_1_0_5_fixes branch

lib/services/platform-service.ts
Add appId option when starting android emulator in order to fix starting of the application (it is installed correctly on the device, but last call, that has to start the app, uses appid). Update common lib where support for genymotion emulator has been added.
https://github.com/NativeScript/nativescript-cli/issues/167
=> Fix android emulator starting

README.md
Minor wording tweak that I think clarifies this process.
=> Docs: Small tweak to iOS cert/provisioning profile wording

package.json
Update package.json to use ios-sim from its master branch. This is temporary in order to be able to test latest changes of node fibers (which are merged in ios-sim master).
=> Use ios-sim from master

lib/options.ts
Fix usage of shorthands, so when you specify -v to use verbose mode. Update common lib where shorthands for help command had been added.
=> Fix usage of shorthand options

package.json
Update package.json to use fibers version 1.0.5.1 (it is the same as the currently used from branch vladimirov/fibers_1_0_5_fixes). The only addition are prebuilt binaries that allow usage of fibers with nodejs 0.12
Use ios-sim-portable version 1.0.1 - it is the same as the master branch.
IMPORTANT: This pull request can be merged ONLY AFTER we publish version 1.0.1 of ios-sim-portable.  This requires merge of https://github.com/telerik/ios-sim-portable/pull/16
=> Update fibers and ios-sim usage

lib/services/android-project-service.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/219
Send keyStore* options to ant only if they are specified.
=> Fix android release build

package.json
Use ref-struct from telerik fork in order to support Nodejs 0.12.0
=> Add support for Nodejs 0.12.0

lib/options.ts
Due to yargs issues, we have to add copy-from as copyFrom and link-to as linkTo.
=> Fix copy-from and link-to options

lib/services/platform-service.ts
* Don't delete frameworkPath directory
=> * Use path.resolve for frameworkPath

README.md
=> Removed the insiders note as confirmed by Valio

lib/bootstrap.ts, lib/dynamic-help-provider.ts, resources/help.txt
In some cases we want to hide some parts of our help. For example if the user is on MacOS, information how to setup Windows or Linux system is not needed for him.
Add dynamicHelpProvider which is used to determine some context specific values.
Update common lib where we've added the following changes:
Add support for multilevel hierarchical commands. This way we can use commands like $ appbuilder appmanager upload android declared as "appmanager|upload|android".
Add support for passing multiple arguments to dynamic calls, by changing regular expressions.
Add DynamicHelpService which is used to check different conditions when printing our help.
Use _.isBoolean where possible. Add dynamicHelpProvider which should be implemented by each CLI.
Use lodash _.template as it uses microTemplate …
=> Show context specific help

resources/help.txt
Update common lib where a fix for hierarchical commands had been applied. Add help for new commands - '$ tns device android' and '$ tns device ios'
=> Fix hierarchical commands

config/config.json, lib/config.ts, lib/nativescript-cli.ts
Add config.json file inside new config directory. This file is required in order to allow user specific configurations. Modify nativescript-cli.ts in order to wrap resolving of config and errors inside fiber as the new implementation of config has .wait().
Update common lib, where the following changes are applied:
Rename the following config options:
- FIDDLER_HOSTNAME to PROXY_HOSTNAME
- PROXY_TO_FIDDLER to USE_PROXY
Add PROXY_PORT option to config with default value 8888. Add ConfigBase class which should be used as a base for CLI specific configs.
Required for https://github.com/NativeScript/nativescript-cli/issues/297 and https://github.com/NativeScript/nativescript-cli/issues/302
=> Enable proxy using for http requests

config/config.json, lib/config.ts, lib/nativescript-cli.ts
Merge release in master before 0.9.2
=> Merge release in master before 0.9.2

lib/options.ts
Yargs adds -- options to yargs.argv in two ways (--profile-dir is added as profile-dir and profileDir). In order to workaround this behavior, we had to add  all dashed options in both ways to our known options. Fix our validation logic, so we'll have to add only profile-dir.
Remove check for client name when validating -- options. This way options will be validated no matter if CLIENT_NAME( tns) or CLIENT_NAME_ALIAS (nativescript) is used on command line.
Fixes https://github.com/NativeScript/nativescript-cli/issues/251
=> Remove duplicate -- options

lib/commands/update-platform.ts, lib/declarations.ts, lib/definitions/platform.d.ts, lib/definitions/project.d.ts, lib/node-package-manager.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, test/stubs.ts
Currently we're copying only framework files. With latest version are released TNSDebugging.framework and Metadata folders as part of framework. This PR changes the logic so that we can update TNSDebugging.framework and Metadata. This PR fixes the case when the old and new xcode projects are different. Also fixes $tns platform update <platform>@<version> and $tns platform add <platform>@<version> commands.
https://github.com/NativeScript/nativescript-cli/issues/305
=> Fix update

lib/services/android-project-service.ts
In res directory there's values directory that is required for all android versions and directory called values-v21, which is required only for Android version 21. In case you do not have installed latest Android version, this directory should not be added to your project.
Add copyResValues method, which copies res/values directory and res/values-v<version_number> directory to your project. This way when we add directories for other android versions, they will not break builds for older ones.
Fixes https://github.com/NativeScript/nativescript-cli/issues/299
=> Fix build for android below 21

resources/help.txt
https://github.com/NativeScript/nativescript-cli/issues/322
=> Help for experimental versions

resources/help.txt
Add help for debug command. It is useful to have it, even if there's no "debug" command (it is 'debug android' or 'debug ios' now).
Update sha of common lib to latest (pointing the merge commit of iOSDebugging PR).
=> Fix help of debug command

lib/services/platform-service.ts
Delete dir where app will be copied on prepare. If we do not delete it, on Linux and Mac we receive EEXIST errors for symlinks inside app directory. Symlinks are common scenario when node_modules are used.
Fixes https://github.com/NativeScript/nativescript-cli/issues/394
=> Delete destination app dir when preparing project

package.json, preuninstall.js
Add preuninstall script that is executed before installation of the new version. It calls dev-preuninstall command and tries to kill adb server (as it may prevent us from successfully installing nativescript-cli when it is used from our resources).
=> Add preuninstall script

lib/services/android-project-service.ts
Instead, the project template will supply a custom ants hook to do the work
Also, cache the platformData
Also, starting ant through the user command interpreter falling back to cmd
See NativeScript/android-runtime#47
This pR is against the release branch. The one against master will be closed (https://github.com/NativeScript/nativescript-cli/pull/405)
=> Stop calling metadata generator and build twice for android platform

docs/man_pages/general/autocomplete-disable.md, docs/man_pages/general/autocomplete-enable.md, docs/man_pages/general/autocomplete-status.md
Move autocompletion code to a new shell file. In .bash_profile, .bashrc and .zshrc add code that executes this code when we want to enable autocompletion.
Autocomplete is now hierarchical command. The subcommands and their behavior is:
* `autocomplete` - checks if autocompletion is enabled. In case it is not, ask the user for confirmation. In case autocompletion is enabled, but it is the old one (where we've written some data to .bash_profile, etc.), silently remove the old code and use the new approach. In case the user chooses to not use autocompletion, call disableAutocCompletion in order to remove all autocompletion code from all shell profiles.
* `autocomplete enable` - enables autocompletion in case it is not already enabled.
* `autocomplete disable` - disables autocompletion in …
=> Improve autocompletion

docs/man_pages/project/testing/debug-ios.md, lib/services/ios-debug-service.ts, package.json
Switch the debugging on emulator for iOS to use the iOSEmulatorService so that it can benefit from logging in the terminal.
> **NOTE:** This requires the ios-sim-portable 1.0.6
=> Switch the debugging on emulator for iOS to use the iOSEmulatorService

README.md
and pointing to the official installation instructions instead
=> Removing mention of nodes-legacy

docs/man_pages/project/testing/emulate-android.md, docs/man_pages/project/testing/run-android.md, docs/man_pages/project/testing/run-ios.md, lib/bootstrap.ts, lib/providers/logcat-printer.ts, lib/services/platform-service.ts, test/platform-commands.ts, test/platform-service.ts
Should be merged after this https://github.com/telerik/mobile-cli-lib/pull/304
=> Logcat printer

docs/man_pages/project/testing/run.md
Run command's help is not shown correctly in the terminal as there's a new line after applying context sensitivity.
=> Fix help of run command

lib/project-data.ts, lib/services/android-project-service.ts, lib/services/project-service.ts, test/stubs.ts
https://github.com/NativeScript/nativescript-cli/issues/413
=> Fix appid inconsistent

lib/services/ios-project-service.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/459 in the CLI
=> Fix library add ios with spaces in path

lib/services/ios-project-service.ts
This replaces the top comment section in main.m from the legacy TNSBridgeApp to the project name.
=> Interpolate main.m file in iOS project template.

lib/config.ts, lib/project-data.ts, lib/services/project-data-service.ts, test/project-service.ts
https://github.com/NativeScript/nativescript-cli/issues/362
Should be merged after this PR https://github.com/telerik/mobile-cli-lib/pull/329
=> Remove .tnsproject and introduce package.json

lib/services/platform-service.ts, test/platform-service.ts, test/stubs.ts
https://github.com/NativeScript/nativescript-cli/issues/514
=> Process as platform specific files only these located in app folder

lib/services/android-project-service.ts
Whitelist MNC SDK
change all vars to lets
When building with MNC SDK, change minSdkVersion to be MNC, required for succesful build
Use latest common lib to support MNC emulator
See https://github.com/NativeScript/nativescript-cli/issues/507
=> Support for android MNC

lib/definitions/ws.d.ts, lib/services/android-debug-service.ts, lib/services/ios-debug-service.ts, lib/services/platform-service.ts, package.json
Right now the CLI is unable to debug iOS apps in any configuration. This change aims to gradually restore the broken functionality.
Restoring the debugger to its former glory is blocked by two things - missing functionality in `ios-sim-portable` implemented in https://github.com/telerik/ios-sim-portable/pull/29 and the refactoring of `IPlatformService.deployOnDevice`. I will update this branch with further patches as the blockers are removed.
=> Rework (and fix) iOS debugging

lib/services/android-project-service.ts
Programs built with it can run only on MNC devices.
We disable it until we create a good UI for the user to select target/min SDK
=> Forbid MNC SDK

lib/services/platform-service.ts, test/platform-service.ts
Treat only files with ".platform" right before file extension are treated as platform specific.
See https://github.com/NativeScript/nativescript-cli/issues/538
=> Fix rule for filtering platform specific files.

CHANGELOG.md, PLUGINS.md, docs/man_pages/index.md, docs/man_pages/lib-management/plugin-add.md, docs/man_pages/lib-management/plugin-remove.md, docs/man_pages/lib-management/plugin.md, package.json
=> Merge 1.1.0 in master

docs/man_pages/project/configuration/platform-add.md, lib/declarations.ts, lib/options.ts, lib/services/android-project-service.ts
* Add Android API Level 22 to supported versions. This way in case you have only API Level 22 installed, you will be able to use it and create Android project. Implements https://github.com/NativeScript/nativescript-cli/issues/551
* Add --sdk option to `$ tns platform add android` command. This option gives you the ability to specify the SDK that you would like to use. In case the value is below 17, an error will be raised. In case the value is not in the supported versions, a warning will be shown, that some functionality may not work as expected. Implements https://github.com/NativeScript/nativescript-cli/issues/552
=> Add support for different Android SDKs

docs/man_pages/general/autocomplete-disable.md, docs/man_pages/general/autocomplete-enable.md, docs/man_pages/general/autocomplete-status.md, docs/man_pages/general/autocomplete.md, docs/man_pages/general/doctor.md, docs/man_pages/general/feature-usage-tracking-disable.md, docs/man_pages/general/feature-usage-tracking-enable.md, docs/man_pages/general/feature-usage-tracking-status.md, docs/man_pages/general/feature-usage-tracking.md, docs/man_pages/general/help.md, lib/bootstrap.ts, lib/declarations.ts, lib/services/doctor-service.ts
See https://github.com/NativeScript/nativescript-cli/issues/480
=> Implement doctor command

lib/definitions/platform.d.ts, lib/services/android-project-service.ts, lib/services/plugins-service.ts, package.json, test/plugins-service.ts
https://github.com/NativeScript/nativescript-cli/issues/555
=> Polish xml merge

lib/services/android-project-service.ts
Inside tns-android resources, there are values-v<API_LEVEL> directories. Currently we were copying only values-v21 in case the current project targets API_LEVEL 21. Instead we should copy it when the project targets API_LEVEL 21 or upper (in case there's no newer directory, for example values-v22).
For example:
* `$ tns platform add android --sdk 22` - should copy values and values-v21 in your platforms/android/res dir
* `$ tns platform add android --sdk 21` - should copy values and values-v21 in your platforms/android/res dir
* `$ tns platform add android --sdk MNC` - should copy values and values-v21 in your platforms/android/res dir
* `$ tns platform add android --sdk 17` - should copy values in your platforms/android/res dir
=> Copy styles for supported Android versions

CHANGELOG.md
=> Update Changelog for 1.1.1

CHANGELOG.md, docs/man_pages/project/configuration/platform-add.md, lib/declarations.ts, lib/definitions/platform.d.ts, lib/options.ts, lib/services/android-project-service.ts, lib/services/plugins-service.ts, lib/tools/broccoli/trees/node-modules-tree.ts, package.json, test/npm-support.ts, test/plugins-service.ts
Merge changes for 1.1.1 release in master
=> Merge changes for 1.1.1 release in master

lib/options.ts, lib/services/ios-debug-service.ts
If nothing is specified, the client option defaults to true.
Merge after https://github.com/telerik/mobile-cli-lib/pull/365
=> Introduce default value for client option

lib/bootstrap.ts, lib/declarations.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, lib/services/project-files-manager.ts, test/npm-support.ts, test/platform-commands.ts, test/platform-service.ts, test/plugins-service.ts, test/project-files-manager.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/578
=> Handle platform specific files in plugin

package.json
Each command can use specific dashed options (`-- avd <name>` for example is valid for one command, but not for other). Add dashedOptions parameter to ICommand interface and make sure to use it for validation when it exists. In case there's no dashedOptions paramter, use the common options. In order to validate the options, delete yargs from require and require it again as yargs.options(this.options).argv is caching the results and calling it more than once with different options is giving strange results.
Also fixes https://github.com/NativeScript/nativescript-cli/issues/539
=> Add dashedOptions for each command

lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, package.json, test/npm-support.ts, test/platform-service.ts, test/stubs.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/520
https://github.com/NativeScript/ios-runtime/pull/202
=> Enable image resources from App_Resources in iOS

lib/tools/broccoli/node-modules-dest-copy.ts, test/npm-support.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/601
=> Doesn't handle the dependencies of devDependencies

docs/man_pages/project/creation/create.md, docs/man_pages/project/creation/init.md, lib/bootstrap.ts, lib/commands/init.ts, lib/constants.ts, lib/declarations.ts, lib/options.ts, lib/services/init-service.ts, lib/services/project-service.ts
Should be merged after this https://github.com/telerik/mobile-cli-lib/pull/371
https://github.com/NativeScript/nativescript-cli/issues/600
=> Init command

lib/declarations.ts, lib/node-package-manager.ts, lib/options.ts, lib/services/plugins-service.ts
Add ignoreScripts option, which should be used when during installation of modules you want to skip all scripts declared in package.json's of these modules. When you specify --ignoreScripts, we just add `--ignore-scripts` to npm install command.
=> Add ignoreScripts option

lib/services/ios-debug-service.ts
The update of JavaScriptCore that we use in the iOS bridge goes with an updated web inspector frontend. The updated frontend is not rendered properly in latest Safari, so as a workaround open an application that would be distributed with the iOS bridge package
Related to https://github.com/NativeScript/ios-runtime/pull/201
=> Open web inspector frontend in a standalone application instead of Safari

lib/definitions/libref.ts, lib/definitions/plugins.d.ts, lib/definitions/project.d.ts, lib/services/android-project-properties-manager.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/plugins-service.ts, test/android-project-properties-manager.ts, test/plugins-service.ts, test/stubs.ts
Should be merged after this PR - https://github.com/telerik/mobile-cli-lib/pull/368
https://github.com/NativeScript/nativescript-cli/issues/510
=> Support for android native libraries in plugin

lib/services/doctor-service.ts
Add OS detection
Warn users that to develop for iOS, they need OS X Maverics or later
Implements https://github.com/NativeScript/nativescript-cli/issues/615
=> Removed detection for iTunes

lib/services/android-project-service.ts, lib/services/platform-service.ts
During project preparation, we should not delete values directories as they contain specific information, which is important for android builds (strings.xml file for example).
NOTE: This fix is mandatory for integration of {N} inside AppBuilder
=> Do not delete values dirs

config/config.json, docs/man_pages/project/testing/debug-android.md, lib/config.ts, lib/declarations.ts
fixes https://github.com/NativeScript/nativescript-cli/issues/632
=> Allow the user to manually set Chrome app name

.settings/launch.json, lib/bootstrap.ts, lib/commands/livesync.ts, lib/config.ts, lib/declarations.ts, lib/providers/device-app-data-provider.ts, lib/services/android-debug-service.ts, lib/services/ios-debug-service.ts, lib/services/platform-service.ts, lib/services/usb-livesync-service.ts
Should be merged after this PR https://github.com/telerik/mobile-cli-lib/pull/376
=> LiveSync support

lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-project-service-base.ts, lib/services/platform-service.ts, test/stubs.ts
https://github.com/NativeScript/nativescript-cli/issues/510
=> Support for dynamic frameworks in iOS from plugins

docs/man_pages/project/testing/livesync-android.md, docs/man_pages/project/testing/livesync-ios.md, docs/man_pages/project/testing/livesync.md
Fix livesync help and html generation which was failing due to missing <% if(isHtml) { <%> sections.
Update common lib.
=> Fix livesync help

lib/services/android-debug-service.ts, package.json, test/android-project-properties-manager.ts
There are some unresolved futures in android debug service which leads to `Error: There are outstanding futures. Construction call stacks:` errors. Fix them and fix unit tests  on Windows.
=> Fix unresolved futures

lib/definitions/project.d.ts, lib/services/platform-service.ts, lib/services/project-data-service.ts, test/stubs.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/658
=> Fix platform remove

CHANGELOG.md, PLUGINS.md, docs/man_pages/project/testing/debug-android.md, docs/man_pages/project/testing/debug-ios.md, docs/man_pages/project/testing/livesync.md
-Fixed instances of non-existent list-devices command
-Fixed documentation for livesync when no platform is specifies
-Added changelog entries for 1.2.0
-Updated plugins.md with support for native libraries and "folders as modules" functionality.
=> Ikoevska/ns 120/changelog

lib/services/android-project-service.ts
1. Create new project
2. Add plugin that contains .jar file
Expected: The .jar file should  be added in libs folder of native project and in lib folder at project root
Actual:  the .jar file is not respected from cli.
=> Respect correctly .jar files from plugin

lib/config.ts
Set correct name for ERROR_REPORTING_SETTING_NAME in static config. Fixes https://github.com/NativeScript/nativescript-cli/issues/695
=> Fix exceptions tracking

lib/services/android-project-service.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/663
=> Validate java version

lib/services/ios-project-service.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/679
=> Add library with relative path to .xcodeproj file

lib/declarations.ts, lib/npm-installation-manager.ts, lib/services/platform-service.ts, test/stubs.ts
In some cases framework dir is missing in the npm cached package of the framework. Check if it exists and if not, remove the package from the cache and add it again.
Fixes https://github.com/NativeScript/nativescript-cli/issues/699
=> Make sure framework dir is part of the cached framework

lib/services/android-debug-service.ts, lib/services/ios-debug-service.ts
https://github.com/NativeScript/nativescript-cli/issues/682
https://github.com/NativeScript/nativescript-cli/issues/636
https://github.com/NativeScript/nativescript-cli/issues/375
Should be merged after this PR https://github.com/telerik/mobile-cli-lib/pull/406
=> Add timeout option to debug command

lib/services/ios-debug-service.ts
Fixes 
https://github.com/NativeScript/nativescript-cli/issues/652 and https://github.com/NativeScript/nativescript-cli/issues/671
=> Open correct debugger url when framework version is lower than 1.2.0

lib/services/ios-project-service.ts, lib/services/plugins-service.ts, lib/tools/broccoli/node-modules-dest-copy.ts
Should be merged after this PR https://github.com/NativeScript/node-xcode/pull/4
If the platform is added before the plugin, the plugin platforms directory inside `tns_modules` is not deleted. This way the native libraries are copied twice in project - in `lib` folder and `tns_modules` folder, which increases the package size of an application a lot.
=> Remove plugin platforms folder

README.md, docs/man_pages/index.md
=> Minor changes to include init command

lib/services/android-debug-service.ts
This ports the fix from master to release branches
See https://github.com/NativeScript/nativescript-cli/issues/632
=> Allow using of renamed Chrome on Mac

lib/services/android-debug-service.ts
https://github.com/NativeScript/nativescript-cli/issues/722
=> Do not build and install the app twice when debug command is executed

lib/declarations.ts, lib/providers/device-app-data-provider.ts, lib/services/usb-livesync-service.ts
Should be tested with this version of android runtime - http://nsbuild01:8080/build/view/tns-android/job/tns-android-stable/411/ 
Should be merged after this PR - https://github.com/telerik/mobile-cli-lib/pull/411
Fixes https://github.com/NativeScript/nativescript-cli/issues/742
=> Integrate livesync logic from android runtime

lib/services/ios-project-service.ts
https://github.com/NativeScript/nativescript-cli/issues/686
=> Support for building xcworkspace

lib/services/android-debug-service.ts, lib/services/usb-livesync-service.ts
See http://teampulse.telerik.com/view#item/299038
=> Fixes for android related commands

lib/services/plugins-service.ts, test/plugins-service.ts
Npm has a global configuration to save dependencies with exact versions or as ^ ones. This unit test must work in both configurations. Therefore, we check for one of the two possible outcomes.
Also, small code cleanups.
=> Fix add plugin unit test

lib/commands/update-platform.ts, lib/platform-command-param.ts, lib/services/platform-service.ts, test/platform-service.ts
When you execute `tns run <platform>`, but you have forgotten to add the platform before that, you go in inconsistent state. Make sure to add the platform for the user when one of the following is executed:
* `tns prepare <platform>`
* `tns build <platform>`
* `tns run <platform>`
* `tns update <platform>@<version>` - this will add the specified version in case you have not added the platform before that.
* `tns emulate <platform>`
This way we simplify the workflow, now you can just do:
1) `tns create app1`
2) `tns run android --path app1`
And the application will run on your attached device.
Resolves https://github.com/NativeScript/nativescript-cli/issues/774
Part of the implementation of: https://github.com/NativeScript/nativescript-cli/issues/475
=> Add platform on all commands

test/npm-support.ts, test/platform-commands.ts, test/plugins-service.ts
The changes include introduction of a common **resource-loader** class, which can be used to access files inside resources folder, along with logic for displaying tips after any command using **command-help.json** file if such a file exists.
Merge after https://github.com/telerik/mobile-cli-lib/pull/427
=> Update common with latest bits

lib/services/ios-project-service.ts
Fix: look for correctly named info.plist when adding a plugin
Fix: correctly merge plugin content when merging its info.plist
Fixes https://github.com/NativeScript/nativescript-cli/issues/797
=> Fix merging info.plist during plugin add

lib/bootstrap.ts, lib/constants.ts, lib/declarations.ts, lib/definitions/project.d.ts, lib/node-package-manager.ts, lib/options.ts, lib/services/platform-service.ts, lib/services/project-service.ts, lib/tools/broccoli/node-modules-dest-copy.ts, test/project-service.ts
Use npm to fetch tns-core-modules package. 
Create tns_modules folder from tns-core-modules package.
See issue https://github.com/NativeScript/nativescript-cli/issues/390
=> Use tns_modules from npm

lib/node-package-manager.ts, lib/services/platform-service.ts
See https://github.com/NativeScript/nativescript-cli/issues/819
Note: npm actually `assert` their parameters instead of calling the provided callback with an error.
In our code, this means that an exception is being thrown in async code which was running without being guarded in a fiber. The end result is process tear down without any chance for us to intervene.
We need to file a issue to npm to fix their code to call the callback with an error in this case.
=> Guard against errors in npm

lib/services/android-project-service.ts, lib/services/doctor-service.ts, test/stubs.ts
https://github.com/NativeScript/nativescript-cli/issues/687
=> Gradle support

lib/services/doctor-service.ts
Should be merged after this PR https://github.com/telerik/mobile-cli-lib/pull/445
=> Fix tns doctor command when javac is not added to PATH

lib/services/android-project-service.ts, lib/services/doctor-service.ts
Android runtime introduced gradle.settings file in order to produce apk named <projectName>-debug.apk or <projectName>-release.apk.
Currently the produced .apk files are named android-debug.apk or android-release.apk.
=> Respect settings.gradle file from template

lib/services/platform-service.ts
If the new version of runtime is not cached, tns platform update throws an error
Fixes https://github.com/NativeScript/nativescript-cli/issues/772
=> Fix platform update

lib/services/ios-project-service.ts
An example for such is the Facebook SDK.
ping @fealebenpae
=> Do not embed static frameworks

.idea/misc.xml, docs/man_pages/project/testing/build-android.md, lib/commands/build.ts, lib/declarations.ts, lib/definitions/platform.d.ts, lib/definitions/project.d.ts, lib/options.ts, lib/services/android-project-service.ts, lib/services/platform-service.ts
Part of https://github.com/NativeScript/android-runtime/issues/103
=> Implement command line option to run static bindings generator

lib/definitions/platform.d.ts, lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, test/npm-support.ts, test/platform-service.ts, test/stubs.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/832
=> Work correctly if iOS runtime version is lower than 1.3

lib/services/ios-project-service.ts
When you run `tns run ios`, nativescript-cli will add the ios platform in case you have not added it before that. But in case you have added the platform before that, but you have removed the  platforms dir, the call fails.
Make sure the platforms/ios directory exists before executing any action of copying the files.
=> Fix ios commands when platforms dir is removed

lib/services/ios-project-service.ts
<b>Changes:</b> Create `.xcscheme` for the main target before installing pods.
<b>Reason:</b> `xcodebuild` fails to build workspaces without scheme in the main target.
Addresses <b>issue</b> #831.
=> Create main target scheme before installing pods.

lib/services/platform-service.ts
In case there's tns_modules in app directory, they are copied on each prepare. Skip tns_modules as they are now installed as npm dependency. Warn the user that the tns_modules from app will not be used.
Fixes https://github.com/NativeScript/nativescript-cli/issues/854
=> Do not copy tns_modules from app dir

lib/services/ios-project-service.ts
Make sure the Podfile contains the "use_frameworks" directive by default.
Fixes #852
=> Initialize project Podfile

lib/services/ios-project-service.ts, test/ios-project-service.ts
Currently npm test shows this warning on OSX - "Skipping Cocoapods tests. They cannot work on windows" :smile_cat:
=> Run cocoapods test on darwin

lib/definitions/project.d.ts, lib/services/ios-project-service.ts, lib/services/plugins-service.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/827
=> Execute pod install when a plugin containing only Podfile is added after the ios platform

lib/android-tools-info.ts, lib/bootstrap.ts, lib/declarations.ts, lib/services/android-project-service.ts, lib/services/doctor-service.ts
Pass correct parameters to gradle build
We should pass correct parameters to android build. We need:
* Compile SDK - at least 21
* BuildTools version - at least 22
* AppCompat lib (Android Support) version - same as compile SDK
* Target SDK - the selected target by user - there's no need to have it
Add AndroidToolsInfo class that calculates all required and installed versions of required Android tools. This class prints warnings when the public method getToolsInfo is called without parameters and prints errors when the showWarningsAsErrors parameter is set to true. When `tns doctor` command is called, the checks will print warnings and when `tns platform add android` or `tns build/prepare... android` commands are used, the AndroidToolsInfo will break the execution when incorrect Android …
=> Pass correct parameters to gradle build

lib/android-tools-info.ts
In case ANDROID_HOME environment variable is not set, we show `Arguments to path.join must be strings` error. This is because we collect the information first and show the real errors after that, but we fail during information gathering.
Check androidHome before using it in path.join.
=> Fix errors when ANDROID_HOME is not set

lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts
Fixes http://nsbuild01.telerik.com:8080/build/view/TestApps-Release/job/tns-release-build-testapps-android-full/160/console
=> Fix broken platform add android command

lib/declarations.ts, lib/definitions/npm.d.ts, lib/node-package-manager.ts, lib/services/android-project-service.ts, lib/services/plugins-service.ts
See https://github.com/NativeScript/nativescript-cli/issues/575
=> Plugin remove works with --path option

lib/services/init-service.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/875
=> Configure tns-core-modules version when init command is executed

lib/definitions/xcode.d.ts, lib/services/ios-project-service.ts, package.json, test/ios-project-service.ts
Implement ability to use static libraries in iOS projects.
Implement unit tests.
Addresses issue #686
=> Support static libraries in plugins for iOS.

lib/services/android-project-service.ts
If android is not set to PATH and tns build android command is executed, undefined is not a function errror is thrown
=> Fix undefined is not a function error

lib/android-tools-info.ts, lib/declarations.ts, lib/services/android-project-service.ts
* Fix incorrect message for  selected target SDK (Bulgarian symbols were used)
* Improve message for build tools when the prefix and suffix have the same version (>=22 <=22) - https://github.com/NativeScript/nativescript-cli/issues/900
* Rename supportLibraryVersion to supportRepositoryVersion and improve messaging as Gradle does not work with Android Support Library - instead it works with Android Support Repository.
=> Improve android tools warnings

lib/android-tools-info.ts, lib/declarations.ts, lib/services/doctor-service.ts
In case gradle is not setup correctly or some of the required Android Tools are missing, `tns doctor` command show the warnings, but at the end a "No issues detected" message is shown. Make sure to prevent such message when there are issues by modifying validateInfo's return type to boolean and use it in doctor service.
=> Fix doctor command output

lib/services/ios-project-service.ts
Set the xcconfig to the project template, so that building from the Xcode project is the same as from the CLI: https://github.com/NativeScript/ios-runtime/pull/302/
If the added plugin has a `build.xcconfig` file in `platforms/ios`, an include directive gets appended to the `build.xcconfig` in the project template.
Example (incomplete) Facebook plugin:
```
package.json
platforms/ios/FBSDKCoreKit.framework
platforms/ios/build.xcconfig
```
FBSDKCoreKit is a static framework and has a dependency to CoreGraphics. So we add it In the build.xcconfig: `OTHER_LDFLAGS = $(inherited) -framework CoreGraphics`.
Ping @fealebenpae
=> Support xcconfig file from plugin - close #883

README.md
Update README in order to describe new sys requirements.
=> Update README.md for gradle builds

.gitignore, CHANGELOG.md, CocoaPods.md, README.md, docs/man_pages/lib-management/library-add.md, docs/man_pages/lib-management/library.md, lib/android-tools-info.ts, lib/commands/add-library.ts, lib/declarations.ts, lib/definitions/project.d.ts, lib/services/android-debug-service.ts, lib/services/android-project-service.ts, lib/services/doctor-service.ts, lib/services/init-service.ts, lib/services/ios-debug-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, lib/services/usb-livesync-service.ts, test/ios-project-service.ts, test/stubs.ts
=> Merge 1.3.0 in master

lib/services/usb-livesync-service.ts
Move platform preparation out of `beforeBatchLiveSyncAction` and call it once
before processing changed files.
Related to [PR 459](https://github.com/telerik/mobile-cli-lib/pull/459)
=> Don't prepare platform N times if N files have been changed.

lib/android-tools-info.ts
Add Android API Level 23 as supported version.
Implements https://github.com/NativeScript/nativescript-cli/issues/935
=> Add android-23 as supported version

.gitignore, Gruntfile.js, package.json
Use istanbul as a code coverage tool.
Code coverage is run on every build and one can check its output on the build console log.
=> Add code coverage as a dev dependency

lib/services/ios-debug-service.ts
Inspector websocket crashes when the message is too big so use a tcp socket instead
The corresponding PR in ios-runtime is https://github.com/NativeScript/ios-runtime/pull/317
=> Remove Inspector WebSocket

lib/services/ios-debug-service.ts
Remove trailing spaces and rename variable in order to prevent
```>> lib/services/ios-debug-service.ts[343, 28]: shadowed variable: 'socket'```
=> Fix lint errors

lib/npm-installation-manager.ts
NPM Cache gets broken in some cases. Make sure to validate the sahsum of the cached package. Also validate specific directories in our `tns` related packages from npm, for example tns runtimes must have "framework" directory in the root of the unpacked dir.
Fixes https://github.com/NativeScript/NativeScript/issues/763
=> Add checks for all cached packages

lib/services/doctor-service.ts
We do not use ant anymore, so we should remove the check.
Fixes https://github.com/NativeScript/nativescript-cli/issues/941
=> Remove check for ant version

lib/config.ts, lib/declarations.ts, lib/services/android-debug-service.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/923
=> Ability to specify android debug ui not only on OSX

setup/native-script.rb
Due to c++ dependencies, we do not always work with the latest major version of node.js
Therefore, we do not use the automatic dependency resolution of homebrew.
Instead, manually install well-known version of node.js distribution from the external tap 'versions'
=> Depend on node.js 0.12

setup/native-script.rb
Since NativeScript 1.3, we do not hard-code android-17. Stop installing it as dependency
=> Do not install Android SDK 17

docs/man_pages/project/testing/build-android.md, lib/android-tools-info.ts, lib/declarations.ts, lib/options.ts
Users should be able to select compileSdk. Add `--compileSdk` option and
DO NOT verify it against our min required compile sdk.
This implements:
https://github.com/NativeScript/nativescript-cli/issues/927
Set min required compileSdk to 22 according to:
https://github.com/NativeScript/nativescript-cli/issues/920
=> Allow specifying compileSdk

lib/services/ios-project-service.ts, test/ios-project-service.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/944
=> Update app deployment target to 8.0

lib/services/doctor-service.ts
In case Gradle's version is with three numbers ("2.2.3" for example), our
current check is failing and makes the doctor command unusable. Compare
current gradle version with min required one only after they are in the
same format.
Fixes https://github.com/NativeScript/nativescript-cli/issues/989
=> Fix check for Gradle version

lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, test/stubs.ts
Due to some policy restrictions on devices with apilevel 21+, android runtime is not able to delete sync directories. This way if some files are changed after livesync, changes are not applied on the device.
Fixes https://github.com/NativeScript/nativescript-cli/issues/943
=> Fix run/debug after livesync

lib/constants.ts, lib/definitions/project.d.ts, lib/project-data.ts, lib/services/platform-service.ts, test/stubs.ts
https://github.com/NativeScript/nativescript-cli/issues/947
=> Do not crash application after upgrade to 1.3.0

lib/services/usb-livesync-service.ts
Don't try to sync android if some file from app/App_Resources/iOS folder is changed
https://github.com/NativeScript/nativescript-cli/issues/942
Should be merged after https://github.com/telerik/mobile-cli-lib/pull/472
=> Skip files from sync

lib/services/ios-project-service.ts
Fix incorrect deployment target altering on `prepare` phase. This is caused by CocoaPods prepare step when a plugin is being processed.
See issue: https://github.com/NativeScript/nativescript-cli/issues/1012
Other related issues: https://github.com/NativeScript/nativescript-cli/issues/944
Re-target https://github.com/NativeScript/nativescript-cli/pull/1013
=> Fix deployment target altering in CocoaPods setup.

lib/bootstrap.ts, lib/constants.ts, lib/definitions/plugins.d.ts, lib/definitions/project.d.ts, lib/services/platform-service.ts, lib/services/plugin-variables-service.ts, lib/services/plugins-service.ts, lib/services/project-data-service.ts, lib/tools/broccoli/broccoli.d.ts, lib/tools/broccoli/builder.ts, test/npm-support.ts, test/plugin-variables-service.ts, test/plugins-service.ts, test/stubs.ts
https://github.com/NativeScript/nativescript-cli/issues/882
=> Plugin variables

lib/services/plugin-variables-service.ts
1. Add plugin that doesn't have plugin variables
2. Open pacakge.json
3. We've added:  "[plugin-name]-variables": {}
=> Don't save empty object into package.json file

lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, test/stubs.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1031
Should be merged after https://github.com/telerik/mobile-cli-lib/pull/479
=> Fix emulate-livesync-emulate

lib/commands/create-project.ts, lib/services/ios-project-service.ts, lib/services/plugins-service.ts
https://github.com/NativeScript/ios-runtime/pull/363
=> Merge xcconfig files

lib/services/android-project-service.ts
Gradle uses the third part of the identifier for apk name. Currently we are
checking for projectName (created from dir name). Check both of them when
searching for apk.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1041
=> Use correct .apk name

lib/services/android-project-service.ts
When tns init command is called in empty directory, there's no project data
and getting projectName from projectId is failing.
=> Fix tns init command

docs/man_pages/project/testing/build-android.md, docs/man_pages/project/testing/build-ios.md, lib/commands/build.ts, lib/declarations.ts, lib/definitions/platform.d.ts, lib/options.ts, lib/services/platform-service.ts
Add --copy-to option to build command that allows copying the built file (.apk or .ipa)
to a specified place. For example:
```
tns build android --copy-to ./
```
or
```
tns build android --copy-to ./myDir/out.apk
```
In case the output dir does not exist, it will be created. In case the specified value
for `copy-to` option is directory, the original filename will be used.
Required for easier integration of NativeScript in AppBuilder.
=> Add --copy-to option to build command

lib/declarations.ts, lib/npm-installation-manager.ts, lib/services/init-service.ts, test/npm-installation-manager.ts, test/stubs.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1054
=> Fix ENOENT error when add ios platform

config/config.json, lib/config.ts, lib/declarations.ts, lib/services/ios-project-service.ts, package.json, test/project-service.ts
Add `sandbox-pod` command execution to restirct write permissions outside project directory.
TeamPulse - [[Server] Sandbox Cocoa Pods](http://teampulse.telerik.com/view#item/302897)
Related: https://github.com/NativeScript/nativescript-cli/issues/1065
=> Add 'sandbox-pod' command. Implement test.

lib/services/android-project-service.ts
When you use --symlink for android runtime, CLI's modifying the original AndroidManifest.xml and res dirs.
So we should not symlink src directory and build.gradle, settings.gradle.
=> Fix symlink of android framework

lib/definitions/npm.d.ts, lib/definitions/platform.d.ts, lib/definitions/project.d.ts, lib/node-package-manager.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, lib/tools/broccoli/builder.ts, test/platform-commands.ts, test/plugins-service.ts, test/stubs.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1066
=> Fix failed ios build after second info-plist merge

setup/native-script.txt
Setup a fresh Windows machine for developing with NativeScript
Install JDK8, Android SDK, Gradle & Chrome. Setup Android SDK correctly.
=> A script to setup Windows machine for nativeScript development

setup/native-script.rb
Make Xcode installation entirely user driven.
Introduce simple y/n dialogs with the user.
Check that Xcode and Homebrew have been successfully installed.
Print output from called programs immediately.
Add warning about long JDK install
See https://github.com/NativeScript/nativescript-cli/issues/988
=> Fix mac setup

lib/services/plugins-service.ts, test/npm-support.ts
Preparing project should always call `npm install` just to make sure all dependencies
are installed. Currently we are not calling it when node_modules dir exists.
This was due to requirement that when you have node_modules and change something in
node_modules/tns-core-modules directory, `npm install` will override your changes.
The fact is that this is totally incorrect behavior on our side and also making changes
in `node_modules/<package_name>` is forbidden. Anyway, in case you make changes there,
calling `npm install` will not override them.
Remove the incorrect check and always call `npm install`.
Fix unit test which was passing due to missing npm install before. The problem with it now is that 
```
{scopedName:  "0.0.0-prealpha.3"}
```
Will create an object with property "scopedName" …
=> Always call npm install when preparing project

lib/services/platform-service.ts, test/project-service.ts
When `--frameworkPath` is used, we should follow this behavior:
Always install to `node_modules` under `platforms/<platform_name>/node_modules`
options used   | is frameworkPath File | is frameworkPath Directory
---------|--------|------------
frameworkPath + symlink | symlink to node_modules. **DO NOT DELETE node_modules**. | symlink to **frameworkPath dir**. Delete node_modules.
frameworkPath | Delete node_modules. | Delete node_modules.
=> Fix usage of --frameworkPath <directory> with --symlink

lib/npm-installation-manager.ts, lib/services/plugins-service.ts, test/npm-installation-manager.ts
In case there's node_modules dir and there's directory for each dependency defined
in package.json of the project, we should not call `npm install`. In case `node_modules` dir
does not exist and the project has dependencies or any of the dependencies is not installed,
we'll call `npm install`. Another case when we'll call `npm install` is when `--force` option is used.
This change is in order to allow modifications of modules inside `node_modules` directory.
Install latest available version if no matching version is found
In case CLI is version 1.4.x, on platform add we are trying to install latest available
1.4.x runtime. In case there's no 1.4.x version, the code fails. 
Instead we should install latest available version in this case.
=> Do not call npm install if everything is installed

lib/services/usb-livesync-service.ts
This one is mostly aimed at fixing the double app restart issue when livesyncing TypeScript projects. The first time you save a `.ts` file it gets synced to the device (completely unnecessarily), then you need another sync after you run your compiler.
-----
Changes:
- Exclude `*.ts` files. No need to livesync them.
- Include the excluded files match fix from `lib/common`
- Fix `app_resources` exclude mask too by using the proper `**/app_resources/** form.
=> Livesync typescript

test/stubs.ts
When source and target file are the same, copyFile produces empty file.
Add check and if they are the same, do not execute any action.
Move fs tests from appbuilder-cli to common. Add tests for copyFile.
=> Fix fs copyFile when source and target are the same

lib/definitions/plugins.d.ts, lib/services/plugins-service.ts, lib/tools/broccoli/node-modules-dest-copy.ts, test/plugins-service.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1027
=> Fix prepare for both platforms

Gruntfile.js, docs/man_pages/project/configuration/install.md, lib/commands/install.ts, lib/config.ts, lib/services/platform-service.ts, test/platform-commands.ts, test/platform-service.ts, test/stubs.ts
with --save-dev
* dedicated grunt watch for compilation
* execute 'prepare' hook
=> `tns install <module>` command should do npm install "nativescript-dev-<module>"

lib/commands/install.ts
If your modules depend on these vars, then they can't be reinstalled with `npm install`
=> remove environment vars from `tns install`

lib/android-tools-info.ts, lib/config.ts, lib/declarations.ts, lib/services/android-project-service.ts, lib/services/doctor-service.ts
* Remove requirement to have `<android-sdk>/tools` and `<android-sdk>/platform-tools` directories to your PATH - use them based on ANDROID_HOME variable.
* Based on the above point - replace all calls to `android` directly with correct path to the `android` executable.
* Remove requirement for JAVA added in your PATH - validate it by using JAVA_HOME.
* Improve error messages when ANDROID_HOME is not set - for example warning about missing compile SDK will inform you in case ANDROID_HOME is not set.
* Improve ANDROID_HOME checks - validate that directories like "extras", "tools", "platform-tools" exist (at least on of them).
* Validate JAVA version in doctor command.
* Sometimes `build-tools` directories are not called with version(`22.0.1`), but have the name: `build-tools-22.0.1` - make …
=> Improve Getting-started for Android

lib/services/ios-project-service.ts
References https://github.com/NativeScript/nativescript-cli/issues/945
Ping @Fatme @teobugslayer for a quick review
=> Always build --for-device with --release

lib/services/ios-project-service.ts
This reverts commit df0a894dbd86c3ee000c9225f04e874a701a8038.
A decision was made to instead implement a new command for publish builds
=> Revert "Always build --for-device with --release"

lib/npm-installation-manager.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1147
=> Skip sha verification when a package is not on npmjs.org

lib/android-tools-info.ts, lib/bootstrap.ts, lib/config.ts, lib/declarations.ts, lib/services/android-project-service.ts, lib/services/doctor-service.ts, lib/sys-info.ts
Fix doctor command, which checks adb and android incorrectly. Pass correct paths for verification.
Also make sure "No issues were detected" is printed when there are no issues.
=> Fix doctor command for android and adb

lib/definitions/project.d.ts, lib/project-data.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, test/npm-support.ts, test/platform-service.ts, test/stubs.ts
https://github.com/NativeScript/nativescript-cli/issues/1048
This PR should be merged after the corresponding in android runtime.
=> Support for include.gradle from plugins

lib/services/ios-project-service.ts, lib/services/platform-service.ts, test/stubs.ts
sandbox-pod install blocks arbitrary post-install scripts but returns with an exit code of 0. This is why we have to check the stderr for any data and fail if it is present.
Also help should not be displayed in case such a fail occurs.
=> Fail if sandbox install command fails

lib/services/platform-service.ts, test/npm-support.ts
Currently all `.ts` and `.js.map` files are copied to `platforms/<platform>/...` etc.
We do not need them in the real application for the moment. So ignore them.
Also fix problem with ignoring `tests` directory during release build - we were preparing collection of files to be copied, but finally we copy the whole app dir.
From now on we'll respect the filtered collection.
=> Do not copy .ts and .js.map files in real app

lib/services/platform-service.ts
When multiple devices with same platform are attached, `tns run <platform>` command should start the app on all of them.
Currently the application is started, but the call to commandsService (device|run) command is failing as more than one device is attached.
Fix this by calling the correct method from the devicesService.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1177
=> Fix run on multiple devices

lib/definitions/plugins.d.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, test/platform-service.ts
As our hooks (like typescript) are called before executing prepare method, we must be sure we have
all devDependencies installed in order to be able to execute before-prepare hooks.
This is mandatory for projects where typescript is enabled, but you do not have node_modules directory yet.
Steps to reproduce the bug:
1) `tns create app1`
2) `cd app1`
3) `tns install typescript`
4) `rm -rf node_modules`
5) `tns build android`
You'll see error:
```
Error: Cannot find module 'nativescript-dev-typescript/lib/before-prepare.js'
```
=> Install devDependencies before prepare

lib/definitions/plugins.d.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, test/platform-service.ts
The old fix for installing only devDependencies before preparing the project has a problem:
`npm install <devPackagesNames>` does not respect the versions from the devDependencies section and always installs the latest versions.
We cannot use `npm install <devPackageName>@<version>` as we do not know if they are real versions or paths or even "frog legs".
There's a magical flag `--dev` which should allow you to do:
`npm install <devPackagesNames> --dev` and it will respect the versions from devDependencies. Unfortunately this flag forces recursive installation of devDependencies all down the tree of packages.
Of course npm has another rabbit in the hat - `--only=dev`. However I couldn't get it work at all.
So the only solution I could think about is to install all dependencies before …
=> Install ALL dependencies and devDependencies before prepare

lib/services/ios-project-service.ts
Leftover warnings printed on the stderr are considered errors and as a result fail the `$ tns prepare ios` command. Make a more general regex for catching warnings.
Ping @Mitko-Kerezov @Fatme
=> Collect all warnings upon pod installing

lib/tools/broccoli/node-modules-dest-copy.ts
The new tns-core-modules package has .d.ts files. We should skip them when moving tns-core-modules to platforms dir.
The current logic is - copy everything from node_modules to tns_modules dir.
After that move everything from tns_modules/tns-core-modules dir to tns_modules and delete tns-core-modules.
Add logic to delete .ts files BEFORE moving the files from tns_modules/tns-core-modules dir to tns_modules.
=> Remove .ts from tns-core-modules package when moving it to platforms dir

Gruntfile.js, lib/messages.d.ts, lib/messages.ts, lib/nativescript-cli.ts, test/plugin-variables-service.ts, test/plugins-service.ts
Detailed explanation can be found here: https://github.com/telerik/mobile-cli-lib/pull/484
=> Restructure error messaging

lib/bootstrap.ts, lib/services/doctor-service.ts, lib/services/init-service.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, lib/services/usb-livesync-service.ts, lib/tools/broccoli/node-modules-dest-copy.ts
Merge release in master pre 1.5.0 (second time) and fix master:
Bootstrap does not know where to find "messages" as we have missed the require. Tell him where the messages class is located.
=> Merge release in master pre 1.5.0 (second time) and fix master

docs/man_pages/project/testing/dev-test-android.md, docs/man_pages/project/testing/dev-test-ios.md, lib/services/test-execution-service.ts
In `karma-nativescript-launcher` we call startTestRunner through spawn.
Communication between karma launcher and tns is through stdin.
This is causing exception in buildMetadata step when gradle wrapper is used.
For some reason it throws error in java code.
So, replace the spawn with fork in the launcher. Modify `startTestRunner` to wait for message from parent process and send "ready" state to the parent.
After that the parent (karma-nativescript-launcher) sends configuration data and the `startTestRunner` will execute the actions.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1199
As the current workflow of unit-testing is:
1) user calls `tns test android`
2) CLI starts a new process in which `tns dev-test android` is called
3) In case the dev-test command fails, the …
=> Fix unit test runner on Windows

setup/native-script.ps1, setup/native-script.rb
Rename the windows setup script to ps1, so it can be directly executed if the user has chocolatey installed already
=> Add instructions for use to setup scripts

lib/nativescript-cli.ts
Shelljs likes to report some warnings, which we do not want to show to our users.
So set it to silent mode by default. In case for any shelljs command you want to show the warnings, just set silent to false before executing it.
This will also fix some warnings that are currently shown when preparing plugins. (`cp - unable to find file...`).
=> Silent shelljs by default

setup/native-script.ps1
- Install node.js 5.1.0
- Set JAVA_HOME environment variable
- Do not change PATH
=> Improve Windows setup script

lib/providers/device-log-provider.ts
When the Android is using API Level 23, the device log is in different format and our current code fails.
Use new regex for API Level 23 and fix the incorrect code that was failing.
=> Fix device log for API 23

lib/services/android-project-service.ts, lib/services/doctor-service.ts, lib/sys-info.ts
When cocoapods are not installed on Mac machine, doctor is failing.
Fix this by skipping match check in case pods are not installed.
Add basic unit tests for doctor service.
Add unit test for the failing cocoapods check.
=> Fix cocoapods check and add unit tests for doctor service

lib/services/test-execution-service.ts, lib/services/usb-livesync-service.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1225 and https://github.com/NativeScript/nativescript-cli/issues/824
=> Fix livesync --emulator when the app is not installed on the iOS simulator

setup/native-script.rb
- rewritten as pure Ruby script, no longer tries to be a brew formula
- update installed node to 4 LTS
=> Mac setup improvements

lib/commands/prepare.ts, lib/definitions/platform.d.ts, lib/services/platform-service.ts, lib/services/test-execution-service.ts, lib/services/usb-livesync-service.ts, test/platform-service.ts
Check XML files for well-formedness. No validation is performed. The check should happen at least on build and livesync.
Whenever an invalid XML file is found:
- for livesync --watch operation, warn the user, but do not break the CLI
- for every other operation, abort it
Implementation detail: it happens actually on prepare.
See https://github.com/NativeScript/nativescript-cli/issues/1272
=> Check XML files for well-formedness

lib/services/ios-debug-service.ts, package.json
Fixes https://github.com/NativeScript/nativescript-cli/issues/1253
Should be merged after this PR https://github.com/telerik/ios-sim-portable/pull/48
=> Fix tns debug ios --emulator

lib/commands/create-project.ts, lib/definitions/project.d.ts, lib/npm-installation-manager.ts, lib/services/project-service.ts, lib/services/project-templates-service.ts, package.json, test/project-service.ts, test/project-templates-service.ts, test/stubs.ts
Add support for --template option when creating new project.
The value for `--template` can be anything that you can `npm install`. For example valid calls are:
* `tns create app1 --template tns-template-hello-world`
* `tns create app1 --template https://github.com/NativeScript/template-hello-world-ts/tarball/master`
* `tns create app1 --template ../myTemplate`
* `tns create app1 --template https://github.com/NativeScript/template-hello-world-ts.git`
* `tns create app1 --template https://github.com/NativeScript/template-hello-world-ts.git#master`
In case you use:
`tns create app1 --template typescript` or `tns create app1 --template tsc`, CLI will try to install `tns-template-hello-world-ts` template.
In case you use `tns create app1 --template typescript@1.2.0` we will install version …
=> Add support for different templates

lib/services/project-service.ts, test/project-service.ts
App's package.json contains information about application's entry point, so we should not delete it.
=> Do not delete app's package.json

lib/services/platform-service.ts
Write to the console the XML validator messages. They include the severity and kind of syntax error and its location.
=> Improve XML parser validation output

package.json
Update npm version to latest 2.x as the old one (2.6.1) has some bugs that prevent us from using git urls, installing some plugins, etc.
=> Update npm version to latest 2.x

lib/services/platform-service.ts, test/platform-service.ts
See https://github.com/NativeScript/nativescript-cli/issues/1272
=> Only warn about XML parsing errors

CHANGELOG.md
Add information about 1.5.1 release in CHANGELOG
=> Add information about 1.5.1 release in CHANGELOG

lib/services/usb-livesync-service.ts
See https://github.com/NativeScript/nativescript-cli/issues/1263
=> Timestamps for fast LiveSync

lib/android-tools-info.ts, lib/declarations.ts, lib/services/android-project-service.ts
When ANDROID_HOME environment variable is not set, we call childProcess exec and spawn with undefined command.
This leads to "futures left behind" errors.
Make sure the commands will be executed only in case they are not undefined.
Also make sure that `tns prepare android` will fail immediately in case ANDROID_HOME is not set (currently it shows warning for ANDROID_HOME and shows error for compile SDK).
Related issue: https://github.com/NativeScript/nativescript-cli/issues/1242
=> Fix tns doctor command

CHANGELOG.md, lib/android-tools-info.ts, lib/declarations.ts, lib/services/android-project-service.ts, lib/services/platform-service.ts, lib/services/usb-livesync-service.ts, test/platform-service.ts, test/test-bootstrap.ts
=> Merge 1.5.1 in master

lib/declarations.ts, lib/options.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts
Add baseConfig option that can be used to replace the default AndroidManifest.xml / Info.plist that is used for merge.
It should be passed to all build related commands. It can be passed to platform add command as well.
Required for AppBuilder integration.
=> Add baseConfig option

CocoaPods.md, PLUGINS.md
https://github.com/NativeScript/ios-runtime/issues/427
=> Update plugins docs

PLUGINS.md
<b>Description</b>: Update documentation with information regarding usage of cocoa touch static libraries in plugins for the iOS platform. See PR NativeScript/nativescript-cli#885 and PR https://github.com/NativeScript/docs/pull/159.
<b>Notes</b>: AFAIK these changes were automatically wiped out from here https://github.com/NativeScript/docs/pull/159.
=> Add Cocoa Touch Static Libraries documentation.

PLUGINS.md
As suggested here: https://github.com/NativeScript/nativescript-cli/pull/1321#discussion_r47071762
=> Fix header formatting of Plugins.md

README.md
Update System Requirements for Android development according to 1.5.x changes.
=> Update System Requirements for Android development

CHANGELOG.md, PLUGINS.md, README.md, docs/man_pages/project/testing/emulate-android.md, docs/man_pages/project/testing/run-android.md, lib/bootstrap.ts, lib/declarations.ts, lib/options.ts, lib/services/android-project-service.ts, lib/services/doctor-service.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, lib/services/usb-livesync-service.ts, package.json
Merge release in master.
Conflicts:
PLUGINS.md
lib/common
package.json
`logger` has been required in common lib, but due to some Proton requirements, it should be required from each CLI.
Fix this by adding it to bootstrap and update to latest common lib.
=> Merge release in master

lib/services/init-service.ts
Currently `tns init` command forces the application to use the default version of tns-core-modules.
For example in case your CLI is version 1.4.3, `tns init` in non-interactive terminal will set version 1.4.0 (latest 1.4.x) of tns-core-modules even in case you already have defined your version in your package.json
Use --tnsCoreModules option by default - if it is specified, it has highest priority.
In case the console is not interactive, check if package.json has entry in dependencies section for tns-core-modules and use it.
In case the console is interactive, show all available versions to the user and let him pick up the one he wants.
In case the console is not interactive and the package.json does not have entry for `tns-core-modules`, use the default logic.
Targeting release branch as …
=> Init command should not force tns-core-modules version

docs/man_pages/project/creation/create.md
Add help for --template option
=> Add help for --template option

docs/man_pages/project/creation/create.md
Fix help of create command which is breaking html help generation.
=> Fix help of create command

lib/services/usb-livesync-service.ts
Retargeted from https://github.com/NativeScript/nativescript-cli/pull/1335
=> UsbLiveSyncService minor cleanup.

lib/services/android-project-service.ts
Currently when `app/App_Resources/Android` contains AndroidManifest.xml or include.gradle, we treat the folder in a specail way and copy it on two places.
This will be handled from the runtime itself, so no need to do it anymore.
Related to https://github.com/NativeScript/android-runtime/pull/309
=> Do not consider App_Resources/Android as plugin

lib/bootstrap.ts, lib/commands/generate-help.ts
Implements https://github.com/NativeScript/nativescript-cli/issues/1302
=> Add command to generate HTML help

lib/services/android-debug-service.ts
This is cleaned-up version of https://github.com/NativeScript/nativescript-cli/pull/1227
To test it, you need this [runtime](http://nsbuild01.telerik.com/build/job/tns-android-PR/339/).
This pull request is releated to the changes [here](https://github.com/NativeScript/android-runtime/pull/273).
The android debugger now uses named sockets instead of ports hence the code rewrite in adndroid-debug-service to accommodate for that.
Contact @blagoev directly in order to merge this successfully into the respected main branches.
=> Implement Android debugging with unix sockets redirection

lib/services/ios-project-service.ts, package.json, test/ios-project-service.ts
Solves the #1089 for iOS.
If the file `app/App_Resources/iOS/Info.plist` exists the new behavior is triggered, otherwise we should be backward compatible.
On prepare we will get that `Info.plist` and merge it with each `platforms/ios/Info.plist` file from all plugins that have one. The CFBundleIdentifier will be set to package.json's nativescript.id and the result will be written to `platforms/ios/<proj-id>/<proj-id>-Info.plist`.
The *App_Resources Info.plist* has higher priority than the *plugin Info.plists*.
To use the new feature the hello-world template or the CLI will have to bring in a full blown `app/App_Resources/iOS/Info.plist`.
To be followed up by:
- https://github.com/NativeScript/template-hello-world/pull/37
- https://github.com/NativeScript/template-hello-world-ts/pull/4
=> Merge Info.plist from App_Resources and plugins into platforms/ios

lib/services/android-debug-service.ts
There is no help that this command argument works on android. Provide one
=> support no-client command on android debug commands

lib/services/platform-service.ts
When `--baseConfig` option is used for `tns platform add ios`, the command fails with ENOTEMPTY.
The reason is that we copy the baseConfig file before creating correct directories and when we try to rename `__PROJECT_NAME__` dir to real project name, it fails as we have already created this dir.
=> Fix baseConfig option for iOS

lib/services/doctor-service.ts
See https://github.com/NativeScript/nativescript-cli/issues/1294
How it works:
- install iOS runtime into a temporary directory
- create a simple Podfile into the template project
- run (sandobox-)pod
- verify nothing breaks
=> Verify CocoaPods

lib/definitions/platform.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/usb-livesync-service.ts, test/platform-commands.ts, test/stubs.ts
Implements https://github.com/NativeScript/nativescript-cli/pull/1243
=> Fast livesync for images in app folder

lib/services/livesync/livesync-service.ts
=> Set this._isInitialized after preparePlatform in order before-prepare hooks to work properly

lib/options.ts, lib/services/analytics-settings-service.ts
See https://github.com/NativeScript/nativescript-cli/issues/1412
- Change the default settings dir to be inside Roaming Windows profile
- Move the existing file to its new location, if applicable
- Remove the source comment which indicates that separate {N} provacy policy is needed - it is not
=> Move settings into Roaming Windows profile

lib/services/ios-project-service.ts
Related to:
* https://github.com/NativeScript/nativescript-cli/pull/1369 
* https://github.com/NativeScript/ios-runtime/pull/482
ping @PanayotCankov
=> Don't prepare Info.plist file from runtime template

config/config.json, lib/config.ts
The latter is a mechanism to disable all hooks, while the former only disables hooks not invoked through method decoration.
=> Separate disableCommandHooks from DISABLE_HOOKS

lib/definitions/platform.d.ts, lib/definitions/plugins.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/plugin-variables-service.ts, lib/services/plugins-service.ts, package.json, test/ios-project-service.ts, test/plugin-variables-service.ts, test/plugins-service.ts
Implements https://github.com/NativeScript/nativescript-cli/issues/1026
Removes the unneeded logic that merges configuration files
=> Out of the box support for application id in plugins

lib/npm-installation-manager.ts, lib/services/ios-debug-service.ts
See https://github.com/nativescript/ios-runtime/issues/474
=> Use Debugger UI from a dedicated npm package

lib/services/ios-project-service.ts
Apparently xcodebuild whith xcode 7.2 attempts to code sign the simulator build when CODE_SIGN_IDENTITY is set. This variable is set to `iPhone Developer` in the `build.xcconfig` generated.
For reasons beyond me though this code signing attempt fails with **CodeSign error: entitlements are required for product type 'Application' in SDK 'Simulator - iOS 9.2'. Your Xcode installation may be damaged.**
Explicitly setting code signing to **Don't code sign** effectively resolves the issue.
This eliminates https://github.com/NativeScript/nativescript-cli/issues/1428
Ping @rosen-vladimirov @teobugslayer
=> Don't code sign upon simulator build

tsconfig.json
In `tsconfig.json` we have to exclude `node_modules`, `coverage` and `scratch` dirs.
When they are huge (in my case scratch dir was 1.5 GB), TypeScript is not working at all in VS Code.
=> Exclude some dirs in tsconfig.json

lib/definitions/platform.d.ts, lib/providers/device-app-data-provider.ts, lib/providers/livesync-provider.ts, lib/services/android-project-service.ts, lib/services/livesync/android-livesync-service.ts, lib/services/platform-service.ts
Related:  https://github.com/NativeScript/nativescript-cli/issues/921
=> Speed up livesync on android device

lib/tools/broccoli/node-modules-dest-copy.ts
Instead of calling `afterPrepareAllPlugins` for all installed platforms.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1027
Ping @rosen-vladimirov and @teobugslayer for a quick review.
=> Call afterPrepareAllPlugins for the specific platform only

lib/services/doctor-service.ts
Install tns-ios with `--ignore-scripts` when the `$ tns doctor` verifies CocoaPods. Else the amount of text printed on the console is incomprehensible.
Ping @rosen-vladimirov @teobugslayer for a quick review
=> Ignore scripts when checking CocoaPods

Gruntfile.js
Currently `grunt lint` might take more than 2-3 minutes. The problem is in the src files passed.
In my case the scratch directory was around 2.5 GB and this was slowing down the linting, as we have included `!*.d.ts` files.
Make sure only lib and test directories are used when linting as our source code and tests are there.
Fixed mixed tabs and spaces in Gruntfile
=> Speed-up grunt lint

lib/services/ios-project-service.ts
Wherever possible use `spawn` instead of `exec`.
This minifies the chance of something going wrong wherever there are spaces, quotation marks and whatnots in the project's name.
Addresses #1455
Ping @rosen-vladimirov @teobugslayer
=> Use spawn wherever possible

lib/bootstrap.ts, lib/declarations.ts, lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, lib/xml-validator.ts, test/npm-support.ts, test/platform-commands.ts, test/platform-service.ts, test/plugins-service.ts, test/stubs.ts
For iOS we'll have full Info.plist in app/App_Resources/iOS.
Currently for Android we allow placing a file, that will be merged with default AndroidManifest from the runtime.
Change the Android implementation, so now the AndroidManifest placed in app/App_Resources/Android will be the full one.
In such file is not present in user's project, extract it from default template.
In case there's already such file and it doesn't seems correct, rename it to old.AndroidManifest.xml, extract correct manifest from template and inform the user that he'll have to merge the files manually.
=> Use AndroidManifest from App_Resources as full manifest

setup/native-script.ps1
- No longer uses BoxStarter, instead it is a plain PowerShell script
- Force re-installation of dependencies
- Can self-elevate when needed but in this case only PRODUCTION branch can be used
See https://github.com/NativeScript/nativescript-cli/issues/1429
=> More setup fixes for Windows

lib/services/android-project-service.ts, lib/services/platform-service.ts, test/npm-support.ts, test/platform-service.ts
Interpolate data in config files from App_Resources on prepare so `__PACKAGE__` and other placeholders will be replaced.
Ensure the file in the App_Resources is correct in the beginning of the prepare method and make sure all of the placeholders are interpolated after finishing the processing. The interpolating process will replace the placeholders in `platforms/<platform>` dir
=> Interpolate data in config files from App_Resources on prepare

lib/services/android-project-service.ts
* Correct the code, so AndroidManifest will not be backed up in case we are unable to find the manifest in the template (current code was always creating the backup and reverting it in case it fails on the extraction from template).
* Fix backup name - use guid in case AndroidManifest.backup exists.
=> Some improvements for AndroidManifest in App_Resources

package.json
When using `tns run ios` and `tns livesync ios` for iOS Simulator, we exit the process immediately instead of printing device logs.
=> Print iOS Simulator device logs

lib/commands/debug.ts, lib/services/android-debug-service.ts
Fix `tns debug android --emulator`. There were two issues:
* With latest changes in master/release branch, when there's no android device detected and user executes `tns debug android --emulator` an error is raised - "Cannot find connected devices...". Fix this by returning true in command's canExecute method when `--emulator` is passed.
* When there's no running emulator, CLI tries to start it (android-debug-service, debugOnEmulator method). The emulator is started and after that we try to execute action on the started device.
However devicesService (in this case the androidDeviceDiscovery) had not reported yet the started emulator as a new device. So when device's service execute method is called, it checks if there are devices (still thinks there aren't) and tries to start emulator …
=> Fix debug android --emulator

package.json
During the last refactoring we've lost the queue of futures. So we had some racing issues when the same file is saved multiple times.
Fix this by adding back the queue and adding some try-catch statements.
=> Fix ENOENT, EISDIR, EEXIST errors in livesync

setup/native-script.ps1, setup/native-script.rb
Focus these scripts on installing only the native platform dependencies.
The documentation will guide the user to install the CLI separately.
See https://github.com/NativeScript/NativeScript/issues/1556
=> Do not install the CLI

lib/services/test-execution-service.ts
We have to initialize devicesService when executing tns test command as currently it fails when calling livesyncBase.
=> Initialize devicesService on tns test

lib/services/livesync/livesync-service.ts, package.json
Pass .js.map and .ts as excluded patterns for livesync.
Fix livesync of TypeScript projects - make sure gaze does not trigger any livesync logic in case the file that's changed is excluded via any pattern from livesync data.
Currently when .ts file is change, gaze detects changes for .ts, .js and .js.map files and fails as only .js files exist in platforms dir.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1499
=> Fix livesync of TypeScript projects

lib/constants.ts, lib/services/karma-execution.ts, lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts, lib/services/test-execution-service.ts
Fix the following issues in unit test runner:
* Tests cannot start when application is not installed on device
* Karma does not start when there are no .js files in app dir (initial state of TypeScript projects).
* `tns test <platform> --watch` is not working for TypeScript projects
* `tns test <platform> --debug-brk` does not debug.
Change the way unit-tests are started. The current code was:
1) Start karma server
2) When start method of `karma-nativescript-launcher` is called, it spawns new CLI process (calls `tns dev-test` command with some arguments).
3) The new CLI process writes down some files in `node_modules/nativescript-unit-test-runner`
4) The new CLI process prepares the project.
5) The new CLI process changes the entry point of the application to point to …
=> Fix unit test runner

lib/services/ios-project-service.ts
=> Allow build.xcconfig in app/App_Resources/iOS/build.xcconfig

lib/declarations.ts, lib/options.ts, lib/providers/project-files-provider.ts, test/project-files-provider.ts
Fix LiveSync of platform specific / configuration specific files. Currently mappedFilePath does not respect the platform/configuration name.
Add base class that can parse the files and return correct on device filename.
Add unit tests for the provider.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1313
=> Fix livesync of platform/configuration specific files

lib/npm-installation-manager.ts, test/npm-installation-manager.ts
CLI should install latest compatible version of runtimes, based on it's current version. For example in case CLI's version is "1.6.0", when `tns platform add android` is called, CLI should install latest 1.6.x version of android runtime, no matter if 1.7.x exists.
This was not working correctly as it was using beta versions, incorrect sorting, etc.
Fix it by using semver methods and always use the `@latest` tag of the package. In case it doesn't match CLI version, try finding latest matching tag with maxSatisfying method of semver, which dismisses beta versions.
Required for publishing `@next` in npm.
=> Fix installation of latest compatible version

lib/services/livesync/android-livesync-service.ts
Livesync does not work when /data/local/tmp/<app-identifier> file exists on Android device.
This happens when a file with name app-identifier exists in /data/local/tmp directory on device. In this case CLI is not able to create directory.
https://github.com/NativeScript/nativescript-cli/issues/1416
ping @rosen-vladimirov @Mitko-Kerezov
=> Delete /data/local/tmp/<app-identifier> file if exists on Android device

lib/declarations.ts, lib/npm-installation-manager.ts, lib/services/platform-service.ts, test/stubs.ts
Our npmInstallationManager is using the passed `next` string as a version and searches for directory called `next` in the npm cache.
Instead it should use the real version. Fix this by getting the result of npm call addToCache, which returns object with information about cached package.
With this change you can call:
```
tns platform add android@next
```
Fixes https://github.com/NativeScript/nativescript-cli/issues/1563
=> Fix installation of runtime with next tag

test/npm-installation-manager.ts
In case CLI's version is marked as beta (has dash in it), CLI should consider installing beta versions of runtimes.
This is already working. Just add tests for this functionality.
=> Add tests for installing beta versions

lib/android-tools-info.ts
Set minimum required Android Build Tools 23.0.0
=> Update requirement for Android Build Tools

lib/android-tools-info.ts, lib/declarations.ts, lib/services/android-project-service.ts, lib/services/doctor-service.ts
Our system requirements point that JAVA_HOME must be set, but `tns doctor` is not strict about this.
With version 1.7.0 of the runtime, `jarsigner` from $JAVA_HOME/bin/jarsigner will be called explicitly, so we must be sure JAVA_HOME is correct.
`jarsigner` does not exist in JRE, so add logic to call it in order to verify that the currently set JAVA_HOME is correct.
Validate the information in the following order:
1) Check if JAVA_HOME is set. In case it is not, you cannot build for Android (`tns build android` will fail before starting).
2) Check if JAVA_HOME is correct by executing JAVA_HOME/bin/jarsigner - in case it does not exist - fail
3) Check if the version of the JAVA is correct by calling JAVA_HOME/bin/javac -version and compare it with min required one. In case it's lower - …
=> Verify JAVA_HOME is set correctly

docs/man_pages/project/configuration/platform-add.md, lib/declarations.ts, lib/definitions/project.d.ts, lib/nativescript-cli.ts, lib/options.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, test/platform-commands.ts, test/platform-service.ts
Add new option when adding platform: `--platform-template`. When it is
used, CLI will use the specified template instead of the default template
from the runtime. The path to the specified template will be saved in
project's package.json, so next time when platform is added, the same
template will be used.
In case when `--platform-template` is not passed, CLI will check the
package.json and if there's value for the template, it will be used.
Otherwise the default template from runtime will be used.
=> Add support for custom platform templates

lib/nativescript-cli.ts
When adding platform, CLI tries to copy some files from runtime to the native project.
When some of the files do not exist and `shelljs.config.fatal` is true, shelljs exits the process without warn.
Remove the option for the moment and consider better usage for it.
Original https://github.com/NativeScript/nativescript-cli/pull/1592
=> Remove shelljs.config.fatal

lib/commands/plugin/remove-plugin.ts, lib/definitions/plugins.d.ts, lib/services/plugin-variables-service.ts, lib/services/plugins-service.ts
When invalid plugin data is written in project's package.json, `tns plugin remove <name>` command fails.
In such cases `npm uninstall --save <name>` just removes the entry from package.json, so we should do the same.
By invalid data I mean invalid version (not existing version or path to non-existing file).
Plugin remove command's canExecute method is trying to install all plugins in order to get information about their native code, so it will be removed from `platforms` dir.
The installation fails when some plugin's data is invalid.
Catch the error and check package.json's dependencies instead.
Also make sure plugin variables data is removed from package.json when plugin is removed.
Currently it's been removed only when platform is added and plugin has native code.
Fixes …
=> Fix plugin remove command for invalid plugins

lib/config.ts, lib/services/doctor-service.ts
As we need to track new users separately from existing ones, we have to track AcceptFeatureUsageTracking in a separate project.
Also track `InstallEnvironmentSetup` with values 'correct' and 'incorrect' - it will be tracked only on post-install of CLI and will report if user's environment is correct.
Track `DoctorEnvironmentSetup` with values 'correct' and 'incorrect'. On post-install this feature will not be tracked.
=> Track Feature usage in a separate Analytics project

lib/android-tools-info.ts, lib/declarations.ts, lib/services/android-project-service.ts, lib/services/doctor-service.ts
Due to change in runtime, we do not need strict check for JAVA_HOME, so revert the logic introduced yesterday.
=> Revert strict check for JAVA_HOME

lib/services/livesync/ios-livesync-service.ts
CLI is destroying the socket too early and so the runtime cannot handle the message that we've sent.
As a result livesync is not working sometimes.
When we sent message, the socket will always receive data as result. If it's error, the result will contain it.
In any case, we should destroy the socket when data is received.
=> Fix livesync for iOS

lib/services/test-execution-service.ts
When using iOS Simulator we need the localhost enabled as ip for karma. This does not break the Android tests, so enable it for all configurations.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1612
> NOTE: Merge after 1.7.0 is released
=> Enable using localhost as ip for tests

lib/services/doctor-service.ts, setup/mac-startup-shell-script.sh, setup/native-script.ps1, setup/native-script.rb
* Asking permission from user for every installation - this includes an `all` option for eliminating subsequent questions
* Improved error handling - warning upon non-zero exit code, error if the command execution fails
* Adding `-V` option for `sudo gem install cocoapods`. This triggers a verbose output
* Outputting multiple license acceptances for android tools
* Creating ~/.cocoapods directory in case it does not exist
* Asking permission from user for every installation - this includes an `all` option for eliminating subsequent questions
* Improved error handling - warning upon non-zero exit code
* Initial check for latest .NET Framework installed - should be at least 4
* Check for correct Chocolatey installation
* Fixed the syntax in docs header on invoking the setup script from the …
=> Improve Setup Scripts

lib/services/test-execution-service.ts
When `tns test <platform>` is called and results are shown, the results page is refreshed as there's another navigation.
The problem is that CLI sets karma's `singleRun` option to true and also when browser is registered, `karma-nativescript-launcher` schedules execution of tests on the new browser.
In fact karma itself starts the tests on `browser register` event when the `singleRun` option is true. In our case we have double execution, so we receive the `execute` event two times (it's handled in `nativescript-unit-test-runner`).
We've handled the second execution to prevent tests running, but in fact, we should receive single `execute` event.
Fix this by passing watch option to `karma-nativescript-launcher`, where we'll not schedule new execution in case watch option is false. This way …
=> Fix double navigation when showing test results

lib/constants.ts, lib/services/android-project-service.ts, lib/xml-validator.ts
In case a plugin has plugin variable, during project preparation CLI replaces the usage of the variable in plugin's AndroidManifest with the value set in the current project's package.json.
This is not enough, we have to set the variables in all plugin's .xml files, so the value could be used in resource and later read from the JAVA code.
Enumarate plugin's files and replace plugin variables in all .xml files.
https://github.com/NativeScript/nativescript-cli/issues/1634
=> Replace plugin variables in all Android .xml files

lib/android-tools-info.ts
Replaced Android Support Repository name with Local Maven repository for Support Libraries.
Fixes #1619
=> Fixed android support repository name

lib/services/platform-service.ts
When `--baseConfig` is passed to prepare (or any other build related command) it should be respected.
Currently the option is respected only on `platform add`.
=> Respect --baseConfig on prepare

docs/man_pages/project/creation/create.md, lib/commands/create-project.ts, lib/constants.ts, lib/declarations.ts, lib/npm-installation-manager.ts, lib/options.ts, lib/services/project-service.ts, lib/services/project-templates-service.ts, test/project-commands.ts, test/project-service.ts
Added angular and ng values for --template option which will use https://github.com/NativeScript/template-hello-world-ng.
Added --ng option in the create command which is equal to --template ng and --template angular.
Added unit tests.
Fix copying hidden files when creating project.
Implements #1595
=> Simplified creating angular template project

test/stubs.ts
When path to node has spaces (C:\Program Files) the child process exec cannot run the command. Need to place it in "" to run it without errors.
Update FileSystemStub with new method from interface.
=> Fixed autocomplete

CHANGELOG.md
=> Update CHANGELOG for 1.7.1

setup/native-script.ps1, setup/native-script.rb
There are some cases where updating tools requires updating platform-tools and if the former is attempted before the latter the following error is raised:
`Skipping 'Android SKD Tools, revision 24.4.1'; it depends on 'Android SDK Platform-tools, revision 23.1 rc1' which was not installed`
Fix this by reversing order
Ping @rosen-vladimirov @teobugslayer
=> Install platform-tools before tools in setup scripts

lib/services/platform-service.ts
Apply --baseConfig before replacing placeholders in manifest. This way when there are placeholders in the file passed as `--baseConfig`, they will be replaced correctly.
=> Fix --baseConfig option

lib/config.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts
Use baseConfig when merging Info.plist files.
Disable analytics in AppBuilder.
=> AppBuilder fixes

lib/services/platform-service.ts
Do not display help for platform add command when adding an existing platform to the project.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1526
=> Fix warning when adding existing platform

lib/services/livesync/ios-livesync-service.ts
When restarting the application if pacakgeId and folder name does not match the name of the application should be the projectName.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1532
=> Fix livesynnc on iOS simulator-livesync

lib/commands/create-project.ts, lib/services/project-name-service.ts, test/project-commands.ts, test/project-name-service.ts
When creating project with name app a warning will appear and a prompt to create the project with name app or change the project name.
Implements the functionality described in https://github.com/NativeScript/nativescript-cli/issues/1203#issuecomment-203367786
=> Change the warning when creating project with name app

docs/man_pages/lib-management/plugin-add.md, docs/man_pages/lib-management/plugin-find.md, docs/man_pages/lib-management/plugin-remove.md, docs/man_pages/lib-management/plugin-search.md, docs/man_pages/lib-management/plugin.md, lib/bootstrap.ts, lib/commands/plugin/find-plugins.ts, lib/commands/plugin/list-plugins.ts, lib/declarations.ts, lib/definitions/plugins.d.ts, lib/node-package-manager.ts, lib/options.ts, lib/services/plugins-service.ts, package.json
Add list plugins registered in package.json file when executing tns plugin in project.
Add plugin find command to list the nativescript plugins available in npm. The command has --all and --count flags to change the output format.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1231
=> Add list dependencies

lib/commands/plugin/find-plugins.ts
When there are no plugins found with tns plugin find/search command the cli should show message for no plugins found instead of showing empty table with headers.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1665#issuecomment-206720900
=> Add message when no plugins found with tns plugin find

lib/declarations.ts, lib/options.ts, lib/services/platform-service.ts, lib/tools/broccoli/broccoli.d.ts, lib/tools/broccoli/builder.ts, test/npm-support.ts
Delete `<platform/app>/tns_modules`, if present, and make sure we restore it
on subsequent runs without the `--bundle` option set.
=> Add a --bundle option that disables node_modules -> tns_modules update.

lib/commands/build.ts, lib/commands/deploy.ts, lib/commands/run.ts, lib/declarations.ts, lib/definitions/project.d.ts, lib/options.ts, lib/services/android-project-service.ts, lib/services/project-data-service.ts
In order to support Static Binding Generation, we have to add some dev Dependencies to the project when platform Android is added.
As some of them do not work with Nodejs 0.x, we have to limit this functionality only to users who are using node 4.2.1 (the earliest version of 4.x that we support) or later.
Show warning in case the user has older node version.
Remove --staticBindings flag as it's turned on by default now.
=> Add devDependencies when adding Android platform

lib/services/ios-project-service.ts
Instead of passing architectures pass `-destination` parameter. This prevents a [bug in Xcode 7.2]( http://www.openradar.me/23857648)
This resolves https://github.com/NativeScript/nativescript-cli/issues/1606 and depends on https://github.com/telerik/ios-sim-portable/pull/57
=> Pass -destination when building for iOS Simulator

lib/services/ios-project-service.ts, test/ios-project-service.ts
Trying to run `pod install` with CocoaPods 1.0.0 issues an error in case the Podfile doesn't reference a target. Add the project target to the Podfile.
Upon specifying target to the Podfile, however, the path to the Pods' .xcconfig file changes - reflect that change in code.
In addition, truncate and write the Podfile upon each prepare in order to avoid duplication and errors.
Is related to https://github.com/NativeScript/ios-runtime/pull/545
Fixes https://github.com/NativeScript/nativescript-cli/issues/1611
=> Add a target to the Podfile

lib/declarations.ts, lib/services/livesync/livesync-service.ts
Add before livesync hook to be able to control the livesync data. Added property in livesync service to force full sync which will be passed to the livesync data.
=> Disable fast livesync with hook

README.md, lib/services/doctor-service.ts, setup/native-script.rb
This gem is required for creating xcsheme and merging xcconfig files with one another. iOS builds cannot be performed without it.
Update system requirements and setup script accordingly.
Merge after https://github.com/telerik/mobile-cli-lib/pull/648
Addresses https://github.com/NativeScript/nativescript-cli/issues/1674
Ping @rosen-vladimirov for code review
=> Add check for xcodeproj ruby gem in doctor service

lib/services/ios-project-service.ts, test/ios-project-service.ts
CocoaPods < 1.0.0 does not support Xcode 7.3 yet and leaves all .pbxprojects in XML plist format instead of the ASCII plist one. Use xcproj if the user's configuration requires it to fix the .pbxproject's format.
Merge after https://github.com/telerik/mobile-cli-lib/pull/646
Works https://github.com/NativeScript/nativescript-cli/issues/1639 around
=> Use xcproj if needed to fix .pbxproject format

lib/services/ios-project-service.ts
Cocoapods have versions like 1.0.0.beta.8, which are not valid semver versions.
Use only the major.minor.patch part of the versions as all 1.0.0 betas work correctly with XCode 7.3
Revert special code for XCode 7.2 that adds `-destination` flag when building for iOS Simulator. Revert to original code, as it's working fine with all other XCode versions.
=> Fix build for iOS

preuninstall.js
Due to issue in npm versions 3.0, 3.5.1, 3.7.3 (may be more 3.x versions) the NativeScript node_modules are removed before the preuninstall script is executed and it fails.
The issue is logged in the npm repository: https://github.com/npm/npm/issues/8806 but it is not fixed in version 3.1.1 as commented in the discusion.
Workaround for https://github.com/NativeScript/nativescript-cli/issues/1419
=> Hide npm preuninstall errors

lib/services/android-project-service.ts
Due to latest changes in Android runtime, we can no longer symlink `build-tools` directory from the runtime when `--symlink` is passed.
There are two major reasons:
- There are `.js` files in the build-tools, which use `require(<smth>)`. This is failing as node's searching for the installed modules from the original location of the file.
- During build, new files are generated in the build-tools directory. As they are unique (each one is project specific), we cannot symlink them.
=> Do not symlink build-tools directory

lib/declarations.ts, lib/definitions/lockfile.d.ts, lib/lockfile.ts, lib/tools/broccoli/builder.ts, test/npm-support.ts
When getting the stats for file from node_modules in the broccoli builder the event loop gets messed up from the Glob fiber and the cli fiber. That's why we need lock in the Glob fiber.
=> Fix the updating of changed node modules in platform folder

lib/services/ios-debug-service.ts
When --emulator is not passed, CLI will try to debug on iOS Simulator in case there's one started (or CLI will start it).
However the iOS debug service calls methods for debug on device and it fails.
Use correct methods when the detected devices is emulator.
Fixes `tns debug ios` when no devices are connected
=> Fix debugging for simulator when --emulator is not passed

lib/providers/livesync-provider.ts, lib/services/livesync/ios-livesync-service.ts
Currently we are creating new instance of the AndroidLiveSyncService and IOSLiveSyncService. When `--watch` option is used, CLI gets new instance for each change of a file. This leads to opening new socket every single time. The second changed file leads to process exit as the inspector runtime logic is triggered many times.
Fix this by caching the instances per device.
=> Fix livesync for ios devices

lib/services/livesync/ios-livesync-service.ts
Do not try creating the socket again when `--watch` is used. It's already created buddy, keep using it.
=> Fix livesync --watch for ios devices

README.md, lib/services/doctor-service.ts
Latest betas of CocoaPods include 1.0.0.betaX which is not a valid semver string. These versions are the only ones however, which work with Xcode 7.3 out-of-the-box.
Ping @rosen-vladimirov @vchimev @dtopuzov
=> Remove semver validation for CocoaPods version string

lib/services/init-service.ts
When the `tns-<platform>` key in the package.json of nativescript project has custom template the template key must be kept and the version key should be added. When the --framework-name and --framework-version are passed as arguments.
=> Include custom platform template when using tns init

lib/services/ios-project-service.ts
Only convert the main project's .pbxproject back to ASCII format as that's the only project modified by `node-xcode`.
Xcode and CocoaPods are able to parse data from .pbxproject files regardless of their format - Binary, ASCII or XML
=> Do not convert CocoaPods' .pbxproject back to ASCII format

lib/services/plugins-service.ts
When preparing nativescript plugins, we copy the whole directory to the native project.
This leads to a problem that node_modules dir of such plugins is also copied, while it should be flattened.
CLI had already flatten it, but the copy of node_modules is never deleted and we receive `.aar` files in iOS projects for example.
=> Remove node_modules when preparing nativescript plugins

docs/man_pages/index.md
The links to appstore and appstore upload must point to the publishing directory not to the project directory.
=> Fix help links in index page

lib/services/android-project-service.ts
When you use custom platform template, we still need build-tools dir from the runtime. Copy it no matter of the platform template.
=> Fix build for Android with custom platform template

lib/android-tools-info.ts, lib/config.ts, lib/providers/device-app-data-provider.ts, lib/services/android-project-service.ts, lib/services/livesync/android-livesync-service.ts, test/ios-project-service.ts, test/npm-support.ts, test/plugins-service.ts
The android debug bridge result handler checks if there are any errors after executing adb command.
Errors are copied from https://github.com/android/platform_frameworks_base/blob/master/core/java/android/content/pm/PackageManager.java and the handler checks if the result contains any of the errors.
The non-device Android debug bridge must be separated from the device-specific Android debug bridge. Non-device Android debug bridge can be injected through constructor and the device-specific Android debug bridge can be resolved using the $injector. This way the device-specific Android debug bridge will be unique for each device.
The adb commands should be executed through the custom adb wrapper to use the error handling.
Implements https://github.com/NativeScript/nativescript-cli/issues/979
=> Add Android debug bridge result handler

lib/services/ios-project-service.ts
Fix using xcproj for projects with space in the name. Currently this fails.
=> Fix xcproj touch

lib/commands/install.ts, lib/services/android-project-service.ts
If the current project already have some of the Android platform dependencies installed the installed version should be checked. If the installed version satisfies the Android platform the CLI should not install this dependency, if not the CLI should throw error to inform the user about the current version and the required version.
=> Check Android platform dependencies when adding platform

lib/services/ios-project-service.ts, lib/services/platform-service.ts, test/npm-support.ts, test/platform-commands.ts, test/platform-service.ts
When preparing iOS need to check if any plugin requires Cocoapods to be installed and configured correctly. If plugin contains Podfile in the platforms/ios directory and Cocoapods is not installed or not configured correctly the platform prepare should fail.
This fixes https://github.com/NativeScript/nativescript-cli/issues/1734
When preparing iOS and merging xcconfig files if the project requires xcodeproj to be used (Cocoapods version < 1.0.0 and Xcode version >= 7.3) need to check if xcodeproj is available and fail if it's not.
=> Add check for Podfile before preparing platform

lib/services/android-project-service.ts
When checking if platform dependency is installed in the current project before adding the platform need to check if the current version is valid or check in the node_modules directory for the installed plugin version.
=> Fix add android platform dependencies

lib/bootstrap.ts, lib/definitions/project.d.ts, lib/services/cocoapods-service.ts, lib/services/doctor-service.ts, lib/services/ios-project-service.ts, test/ios-project-service.ts
CocoaPods 1.0.0 and later requires a target for which the Podfile will install. We already add such a target when preparing the Podfile for projects - extract logic and reuse it in the doctor service.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1741
=> Add target to Podfile in tns doctor

README.md, setup/native-script.ps1, setup/native-script.rb
Where necessary, shorten:
* https://raw.githubusercontent.com/NativeScript/nativescript-cli/production/setup/native-script.rb to https://www.nativescript.org/setup/mac
* https://raw.githubusercontent.com/NativeScript/nativescript-cli/production/setup/native-script.ps1 to https://www.nativescript.org/setup/win
The shorthands actually redirect to the longer urls.
Only the urls which are used for starting the scripts have been shortened. I prefer we keep the urls in the code unchanged.
=> Shorten setup scripts links

lib/services/platform-service.ts, test/platform-service.ts
=> tests properly excluded on prepare

lib/services/project-data-service.ts
=> package.json indent preserved

lib/nativescript-cli.ts
Warn users that support from version 0.10.x will be removed in version 2.2.0.
=> Add warning for Node.js 0.10.x deprecation

setup/native-script.ps1, setup/native-script.rb
Related to https://github.com/NativeScript/nativescript-cli/issues/1731
=> Create Android default emulator

Gruntfile.js, test/npm-support.ts, test/platform-service.ts, test/project-service.ts
Allow linter for unit tests and fix all errors.
Add public method in liveSyncService that should be used to delete files when LiveSync operation is in progress.
This way, when user deletes file in Proton, the application will call `liveSyncService.deleteFiles` method for it and it will be removed from device.
=> Include linting of unit tests

lib/config.ts
Do not use $projectConstants in AndroidApplicationManager as it's not available in {N}.
=> Do not use $projectConstants as it's not available in {N}

docs/man_pages/project/testing/debug-android.md, docs/man_pages/project/testing/debug-ios.md, lib/services/android-debug-service.ts, lib/services/ios-debug-service.ts
Related to https://github.com/NativeScript/nativescript-cli/issues/1376
When you call `tns debug ios|android` (no `--debug-brk`) now we will build, deploy and start the application and attach the debugger. You can debug normally by placing breakpoint(s) in desired file(s). If you want to break somewhere initially you can use `debugger` keyword in your code.
The `--debug-brk` switch is still working as before in case you want to use it (not sure for what reason).
=> No debug break by default implementation added for iOS and Android

lib/services/ios-project-service.ts, lib/services/xcproj-service.ts
Related to https://github.com/NativeScript/nativescript-cli/issues/1739
=> message updated

docs/man_pages/project/testing/emulate-android.md, lib/services/platform-service.ts, test/platform-commands.ts, test/platform-service.ts
Related to https://github.com/NativeScript/nativescript-cli/issues/289
=> deployOnEmulator refactored

lib/services/karma-execution.ts, lib/services/test-execution-service.ts
Propagate the Karma server exit code and correctly fail the `tns test` command.
=> Exit with non-zero code on test failures.

docs/man_pages/project/creation/create.md, lib/commands/create-project.ts, lib/constants.ts, lib/declarations.ts, lib/options.ts, test/project-commands.ts
=> create --tsc option added + tests

lib/services/android-project-service.ts
Second attempt to fix https://github.com/NativeScript/nativescript-cli/issues/1296 :(
The result:
=> Validate drawable resources before building anything

lib/services/android-project-service.ts
This PR does a gradle clean each time the plugins are updated in any way, for example on plugin remove / add. This prevents problems concerning the android build. This is done automatically so the user doesn't have to take care of cleaning the native project manually when there is a change that will affect the build.
related to: https://github.com/NativeScript/android-runtime/issues/459
=> cli cleans android project when plugins are updated in anyway

lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts, lib/services/test-execution-service.ts
Related to #485 and https://github.com/telerik/mobile-cli-lib/pull/712
These files are needed for debug purposes.
=> .map and .ts files are excluded in release only

package.json
Update ios-sim-portable to latest version where support for Node.js 6.x.x is added. This version is exactly the same as 1.0.24.
=> Update ios-sim-portable to latest version

lib/services/android-project-service.ts
Up to now, gradle clean command was called with default parameters. Now cli passes all parameters to gradle build, so clean command is called with the right build dependencies.
ping: @rosen-vladimirov @enchev @hshristov
=> refactored code and passed buildOptions to prepare command

lib/commands/debug.ts, lib/services/ios-debug-service.ts
Debug command now will start and debug on emulator if no devices found or there are multiple devices + fixed debug in emulator.
=> Debug command and debug service improved

lib/services/android-project-service.ts
Change `applicationId` field in `app.gradle` for android projects 
[Need to add a Grade Android.defaultConfig #454](https://github.com/NativeScript/android-runtime/issues/454)
ping: @rosen-vladimirov @enchev @Plamen5kov
=> Add interpolation for app.gradle applicationId value in android projects

lib/services/livesync/android-livesync-service.ts, lib/services/livesync/ios-livesync-service.ts, lib/services/livesync/livesync-service-base.ts, lib/services/test-execution-service.ts
Remove the data.canExecuteFastSync. The check is made in the respective {N} service instead of in the base implementation
=> Execute batch sync when you live sync application with the --watch option

lib/services/livesync/android-livesync-service.ts, lib/services/livesync/ios-livesync-service.ts, lib/services/livesync/livesync-service-base.ts
When the application is installed on device for the first time with the livesync command, it always recompiles the app e.g:
tns livesync ios --watch
=> Fixed: the app is recompiled always when first time livesync 

lib/definitions/plugins.d.ts, lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/plugins-service.ts, lib/tools/broccoli/node-modules-dest-copy.ts, test/npm-support.ts, test/stubs.ts
Moved gradle clean command that executed in the wrong place (afterPrepareAllPlugins) to newly introduced: `beforePrepareAllPlugins`.
Had to introduce `beforePrepareAllPlugins` command for ios. In ios implementation is empty.
`grunt lint`: >> 253 files lint free.
ping: @rosen-vladimirov @PanayotCankov
=> added beforePrepareAllPlugins

lib/tools/broccoli/node-modules-dest-copy.ts
beforePrepareAllPlugins is now called only for speciffic platform depending on called command
=> beforePrepareAllPlugins is now called only for speciffic platform

docs/man_pages/project/testing/run-android.md, docs/man_pages/project/testing/run-ios.md, lib/commands/run.ts
You can do now:
`tns run android|ios --watch`
instead of
`tns livesync android|ios --watch`
Related to https://github.com/NativeScript/nativescript-cli/issues/1366
=> run command now can watch for changes

lib/npm-installation-manager.ts, lib/tools/broccoli/builder.ts
=> Fixed: Livesync both Android and iOS at the same time, only android updates

lib/definitions/xcode.d.ts, lib/services/ios-project-service.ts, test/ios-project-service.ts
NativeScript for iOS 2.1 has a minimum one of 8.0.
ping @ivanbuhov
=> Deprecate iOS deployment target check for frameworks

lib/declarations.ts, lib/device-sockets/ios/socket-request-executor.ts, lib/services/ios-debug-service.ts
=> debug break for ios fixed

docs/man_pages/lib-management/plugin-install.md, lib/bootstrap.ts, lib/commands/plugin/add-plugin.ts, test/plugins-service.ts
=> plugin install alias added

docs/man_pages/lib-management/plugin-update.md, docs/man_pages/lib-management/plugin.md, lib/bootstrap.ts, lib/commands/plugin/update-plugin.ts
=> Update plugin command added

lib/services/livesync/livesync-service.ts
1. connect two devices (iOS and Android).
2. create a new project: `tns create testProject`
3. run `tns platform add ios` and `tns platform add android`
4. run `tns livesync`
5. only the Android device will be synced, there will be a random exception when syncing the iOS device.
=> Fixed: Livesync not syncing on 2 devices when platform is not specified

lib/providers/livesync-provider.ts
This is done for performance improvements to avoid unarchiving Angular and NativeScript modules. At runtime the `tns_modules` from the deployed `ipa` bundle  will be used instead.
BTW, Livesync with `--watch` is not livesyncing `tns_modules` too, so at least this should be consistent now.
Related: https://github.com/NativeScript/ios-runtime/pull/611/files#diff-26b03154ad8867bf950c44b3bb6c9c86
=> Don't livesync tns_modules folder for iOS device

lib/services/livesync/android-platform-livesync-service.ts, lib/services/livesync/ios-platform-livesync-service.ts
The afterSyncActions are already futuristic, so we don't need the outer future
=> Remove the outer future

lib/services/platform-service.ts
=> Fixed: There is an error when running on iOS simulator and device simultaneously

lib/services/android-project-service.ts
Some arcane projects have no AndroidManifest.xml in App_Resources. When we add the new AndroidManifets it requires LaunchScreenTheme resources. Since these project had no splashscreen when they were created we had decided that we do not want to force feed them splash screens and sanitize the theme attribute and default theme meta in the AndroidManifest when we are coping it from the default template.
=> Do not force LaunchScreen when adding AndroidManifest.xml in old projects

lib/commands/debug.ts
The current logic in debug commnad changes the argument passed to stopApplication method from applicationId to projectName when using emulator. This behavior is correct in iOS, but it fails on Android. This fix corrects the issue.
=> Fixed: debug > stopApplication not working correctly on Android emulator

lib/services/android-project-service.ts, test/npm-support.ts, test/plugins-service.ts
1. Create a new {N} project.
2. Open it in Visual Studio Code. Run debug with "Sync on Android". This will start livesync and then debug.
3. Make a change in tns-core-modules. 
4. Run "Sync on Android" again. It will fail. This happens because the prepareProject called by livesync service will clean the android build folder with all apks. It is required by the debug service that is called after livesync.
In that situation we change only the js file and therefore it is not necessary to clean the whole build folder.  We could check whether the change is in platforms folder of particular module.  It so, we should clean the project. If not, it is safe to skip the clean process.
=> Fixed: Livesync+Debug on Android not working when there are changes in tns-core-modules

lib/services/android-debug-service.ts
1. Create a new {N} project.
2. Run `tns livesync android --watch`.
3. Do some changes in XML and JS files.
4. Stop tns process.
5. Open Visual Studio Code and start `Sync on Android` action.
6. Change JS file - you will see that the JS file is correct, but the XML one is not.
7. Change XML file - you will see that the XML file is correct, but the JS file is not.
Should be merged on top of #1985
=> Fixed: livesync + debug syncs wrong files on Android

lib/services/livesync/livesync-service.ts
1. create a new {N} project.
2. start `tns livesync ios --watch`.
3. make a change.
4. try to stop tns process with Ctrl+C. You will see ugly exception.
=> Fixed: There is an exception when stopping livesync --watch

lib/commands/debug.ts, lib/services/livesync/android-platform-livesync-service.ts, lib/services/livesync/ios-platform-livesync-service.ts, lib/services/livesync/livesync-service.ts, lib/services/livesync/platform-livesync-service-base.ts
This is a follow-up PR to #1993. Currently the "Successfully synced application" message can be found in two files. This PR creates a single method called `finishLivesync` in `platform-livesync-service-base` which improves the code. Note that `livesync-service` is not the best place for such message because it is platform agnostic, the message however is not.
=> Improved: The live sync successfull message appears twice in the code

lib/services/test-execution-service.ts
First call to `tns test <platform>` always fails as the file with Karma configuration is not sent to device. The reason is that it's created in `node_modules/unit-test-runner` after the project is prepared.
The second execution of the command will include the file, but it may not be correct. It's regenerated, but again after the project is prepared.
Fix the `test-execution-service` to prepare the project after the configuration file is created.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1636 and possibly https://github.com/NativeScript/nativescript-cli/issues/2016
Fixes the problem in Travis builds that console hangs and travis builds never end (prove of concept here: https://github.com/rosen-vladimirov/ns-unit-test-travis/pull/1 )
=> Fix first unit tests execution

lib/services/android-project-service.ts
When there's `platforms/android` directory, but in package.json there's no entry in `nativescript` for android platform, calling `tns build android` or any build related command will fail with error:
`Cannot read property 'version' of undefined`
The reason is that we are trying to check the version in package.json and check if it allows us to use gradle (previously Android builds required Ant).
Prevent the error and force using gradle in such case.
NOTE: The issue can be reproduced when working in new repository and you've added the platforms directory to `.gitignore` file. After adding android platform, you'll notice changes in your package.json. Instead of commiting them, I've called `git reset --hard` which removed them from package.json, but I still have the platforms directory.
=> Fix failing android build command by forcing use of gradle

lib/services/livesync/ios-device-livesync-service.ts
When a typescript file is changed its js.map file is also changed which causes an app restart
=> Enable live edit on typescript projects

lib/config.ts
Use the monkey tool to start Android applications on device. This way we do not have to care about the startPackageActivity name and we can start the application in case a custom activity is used.
Remove unused code and variables.
Fixes https://github.com/NativeScript/nativescript-cli/issues/2028
=> Use monkey to start Android applications

lib/config.ts
We need to check if there are any emulators installed for android to emulate on android.
Use the monkey tool to start Android applications on device. This way we do not have to care about the startPackageActivity name and we can start the application in case a custom activity is used.
Remove unused code and variables.
=> Get two fixes for Android

lib/services/android-project-service.ts
In case user had edited his AndroidManifest.xml, he may have removed the com.tns.ErrorReportActivity. In this case, NativeScript CLI thinks that the AndroidManifest.xml is not correct, creates a backup for it and extracts the default one from the template.
Remove the check for `com.tns.ErrorReportActivity`.
=> Fix using of custom AndroidManifest.xml

lib/services/livesync/ios-device-livesync-service.ts
In case of live edit on device, the getDevicePath does not return the absolute device path. So pass a relative path instead and the runtime would handle it.
=> Fix live edit on device

package.json
On some Mac OS machines, the process for reading iOS Simulator logs does not die when Ctrl + C is used. So CLI's process cannot die as well and Ctrl + Z should be used. However the processes for reading logs remain alive and zombies.
Make sure to kill the process on SIGINT, SIGTERM, etc. This way CLI's process should die as well.
Use new version of ios-sim-portable, where the child process is returned to the CLI, so we can kill it later.
=> Kill the process for iOS Simulator logs on SIGINT

lib/services/android-project-service.ts
When a user runs a command using the `--log trace` we don't enable verbose logging for the gradle build. The current workaround was to ask the user to go to platforms android and run the same command that CLI runs but with two additional flags.
In order to enable our users to provide us with better logs of error while building an application, this PR uses the `--log trace` command to pass two additional debug flags to the gradle build.
No difference in usage of commands.
e.g. `tns run android --log trace`
ping: @tzraikov @PanayotCankov @hdeshev
=> inherit verbose logging from --log trace command

lib/nativescript-cli.ts
During `tns debug ios` command, Ctrl + C does not kill the proecss. It looks like there are still resources that do not allow the process to die.
Implement a workaround - call process.exit when SIGINT (Ctrl + C) is received. There's no guarantee that this will release the other resources. However CLI's process will definitely die and console will be released.
Code is based on this PR: https://github.com/telerik/mobile-cli-lib/pull/791
=> Workaround Ctrl+C not exiting debug process

lib/declarations.ts, lib/device-sockets/ios/socket-proxy-factory.ts, lib/nativescript-cli.ts, lib/services/ios-debug-service.ts
`tns run ios` - on device
`tns livesync ios --watch`
`tns debug --watch`
.. etc
Depends on:
https://github.com/telerik/mobile-cli-lib/pull/807
=> A proper fix for all Ctrl+C issues

lib/services/ios-project-service.ts
Fixed trailing comma issue when setting DEVELOPMENT_TEAM in build.xcconfig
=> Fixed trailing comma issue when setting DEVELOPMENT_TEAM

lib/services/plugins-service.ts
During project preparation CLI's trying to detect if all dependencies from package.json are installed by listing contents of node_modules directory.
In case any of them are missing, CLI calls `npm install` inside the project. This executes all postinstall scripts of the dependencies and leads to slower prepare (and also slower builds in lots of cases).
The problem is that the code is reading the contents of node_modules directory, but scoped dependencies (used in all angular projects) are not in the root of node_modules.
So in all Angular projects each prepare calls `npm install`. Fix the listing of the directories to include scoped packages, so in case everything is installed, CLI will not call npm install on the next preparation of the project.
=> Stop calling npm install on each prepare of ng projects

lib/node-package-manager.ts
In many cases `npm install` command, that CLI calls, will raise EPEERINVALID error (on Linux and Mac OS X).
This error code indicates that some of the dependencies have peer dependencies that are not included in the project.
Npm 2 considers this case as error and raises EPEERINVALID error. However in npm 3 this case is treated as non-errornous case and instead of EPEERINVALID, only WARNINGIS are shown.
CLI uses npm 2 internally (as dependency), so whenever such case happens, it breaks its execution.
Until the dependency is updated, let's treat these errors as warnings and continue the execution. After we upgrade the dependency to npm 3 we'll have the same behavior.
=> Do not stop process when EPEERINVALID error is raised

test/stubs.ts
When we validate the hook arguments we try to resolve all of them but there is one argument which is not registered in the injector - hookArgs.
If some hook wants to use it we will try to resolve it and fail.
The solution is to skip the validation for the hookArgs argument.
=> Do not try to resolve hookArgs

package.json
iOS Simulator device logs are printed directly to process.stdout from the ios-sim-portable. However this makes it really difficult to filter the logs and provide them to different callers (for example AppBuilder CLI, NativeScript CLI, Proton).
In order to fix this, use the ios-sim-portable just to start the process of getting device logs. Filter them in the CLI itself.
Also change the logic in ios-log-filter to use process pid in case it's passed. For iOS Simulator we have filtered logs based on the PID of the application. With these changes, simulator logs are passed to ios-log-filter, so that's why we need process' PID there.
When application is restarted (during livesync for example), we set the PID again and the filter will use the new PID.
=> Fix getting ios simulator device logs

lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts
* `lib/services/android-project-service.ts`: unnecessary functionality deleting `AndroidManifest.xml`
* `lib/services/platform-service.ts`: unnecessary functionality checking for `tns_modules` in `app/` directory.
ping: @hshristov, @tzraikov @PanayotCankov, @hdeshev 
_Edit_: Expecting failing obsolete tests
=> removing unnecessary functionality

package.json
The validation of -- options passed on the command line depends on yargs module. Update it to latest versions as the previously used one didn't set correct values of options marked as strings.
Also in our code we pass object of valid options to yargs. Options which have `-` in the name are treated in a special manner in yargs. However instead of passing them with `-`, we pass their secondary representation (remove the `-` and capitalize the next letter).
This way, when the user passes option with `-`, yargs treat it with it's default behavior and does not respect our options for it (as we have not defined that we have option with `-`).
Example:
```JavaScript
var yargs = require("yargs");
var opts = {
"profile-dir": { type: "string" }
};
console.log(yargs(process.argv).options(opts).argv); …
```
=> Fix validation of -- options

lib/bootstrap.ts, lib/services/ios-log-filter.ts
This change makes the log output consistent between Android/iOS (device and simulator)
Merge after:
https://github.com/telerik/mobile-cli-lib/pull/822
=> Added CLI specific log filter for iOS

lib/services/android-debug-service.ts
Ctrl+C was not working after making several changes on Android when using `tns debug android --watch`
#2070
=> Fixed: Ctrl+C not working on Android debug+watch

.travis.yml, lib/definitions/plugins.d.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, lib/tools/node-modules/node-modules-builder.ts, lib/tools/node-modules/node-modules-dest-copy.ts
- Extract dependency resolution from the node_modules copy code.
- Decouple plugin preparation from node_modules copying.
- Reuse resolved dependencies for plugin preparation.
Fixes #2110
=> Prepare plugins independently of node_modules

lib/tools/node-modules/node-modules-builder.ts
There is old logic concerning `app/tns_modules` folder that is obsolete and we need to remove all logic from cli.
related to: https://github.com/NativeScript/nativescript-cli/pull/2099/commits/1514f277d72d7443c5ef85966e6aa0b45943dcf0
@tzraikov @hdeshev
=> remove logic concerning app/tns_modules folder

lib/services/livesync/ios-platform-livesync-service.ts
=> Fixed: Livesync not working when started for the first time on device

lib/bootstrap.ts, lib/commands/post-install.ts, lib/definitions/email-validator.d.ts, package.json, postinstall.js
=> Added email registration for NativeScript mailing lists as post install step

docs/man_pages/project/configuration/update.md, lib/bootstrap.ts, lib/commands/update.ts
=> Added tns update command

lib/bootstrap.ts, lib/commands/clean-app.ts, lib/definitions/platform.d.ts, lib/services/app-files-updater.ts, lib/services/platform-service.ts, test/app-files-updates.ts, test/test-bootstrap.ts
Cleaning up the target app dir turned out to be a hairy issue here. There is no way to know if the target app dir has been prepared without `--bundle` before the current prepare step. If it has, it needs to be cleaned up, but if it hasn't... it's highly likely that a custom webpack process ran just before preparing the app, and we should not touch anything.
The solution I came up with is the following:
- implement app cleanup as a separate command
- change the workflow to manually invoke `tns clean-app android` before bundling
- run your bundle process (webpack, etc)
- then finish up with a `tns build` or a `tns run` command.
I moved app updates (clean/copy) to a separate class, and added unit tests. This PR also fixes the test failure crash due to trying to send the assertion exception …
=> Do not copy app files to platform dir if using --bundle

lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/tools/node-modules/node-modules-dest-copy.ts
The PR introduces additional logic on beforePrepare in android builds to execute a node script that checks for dependencies consuming the public v8 API.
This is necessary in order to decide whether or not the optimized runtime package (stripped v8 symbols) should be used in the resulting APK.
@NativeScript/android-runtime
=> Check if plugin consumes v8 symbols

lib/definitions/platform.d.ts, lib/tools/node-modules/node-modules-builder.ts, lib/tools/node-modules/node-modules-dependencies-builder.ts, lib/tools/node-modules/node-modules-dest-copy.ts, test/npm-support.ts
Changes in this PR will allow copying of all `production` (non-dev) node_modules into the platform's `tns_modules` independent of whether they have been installed using `tns install` (npm 2.x) or npm install with `npm` version 3+.
The proposed implementation however will iterate through the production modules' package.jsons on every build. Traversal of all package's production dependencies is also a bit slower than before. I'll look into a way to address only changes on subsequent builds, and potentially optimize traversals.
Issue https://github.com/NativeScript/nativescript-cli/issues/2149 and the respective PR will most likely address preparing of modules on each rebuild. Has yet to be verified.
**There are currently 3 failing tests testing how and where npm_modules are copied into the …
=> Copy node_modules to platform on prepare (fix Node6/npm 3.x bug)

lib/tools/node-modules/node-modules-dest-copy.ts
This PR aims to partially revert changes made in #2152 such that `tns-core-modules` submodules will once again be copied directly into `tns_modules`.
@hdeshev @dtopuzov
=> Extract tns-core-modules on root level of tns_modules

lib/nativescript-cli.ts
Deprecate support for Node.js 0.12.x as it will not be supported after 2016 by Node.js Foundation.
Implements: https://github.com/NativeScript/nativescript-cli/issues/2164
=> Deprecate support for Node.js 0.12.x

lib/services/platform-service.ts
This allows for easier documentation workflows when using webpack.
=> clean-app command installs the platform if not present.

lib/services/ios-debug-service.ts
Sadly $npmInstallationManager.install does not install the package, it only inserts it in the cache through the npm cache add command
Since npm cache add command does not execute scripts our posinstall script that extract the Inspector Application does not execute as well
So until this behavior is changed this ugly workaround should not be deleted
=> Unzip NativeScript Inspector Application

lib/commands/appstore-upload.ts
=> Fixed appstore upload for iOS

lib/services/ios-log-filter.ts
=> Fixed `tns device log` throws exception

lib/commands/update.ts
=> `tns update` should check for platforms installed in package.json but missing in platforms folder

lib/services/project-changes-info.ts, test/stubs.ts
1. Clone nativescript and create `npm link` in tns-core-modules
2. Create a new {N} project
3. Run the project
4. Remove tns-core-modules folder from the project modules path
5. Execute `npm link tns-core-modules` 
6. Expected: the project should be prepared and build. Actual: both steps are skipped. 
Merge after:
https://github.com/telerik/mobile-cli-lib/pull/834
=> Fixes time mismatch issues with prepare when using symlinks

lib/tools/node-modules/node-modules-dest-copy.ts, test/plugin-prepare.ts
The new dependency analysis algorithm always passes all plugins and we need to keep track of prepared ones, so that we don't clean and prepare everything unnecessary (most painful on Android).
Related to #2110, #2152
Ping @Plamen5kov
=> Keep track of prepared plugins and avoid unnecessary cleans.

README.md
Update requirements for Node.js - we support Node.js 4, 6 and 7.
=> Update requirements for Node.js

lib/declarations.ts, lib/node-package-manager.ts, lib/services/analytics-service.ts, lib/services/plugin-variables-service.ts, package.json, test/project-service.ts
Update all TypeScript related dependencies in order to be able to use TypeScript 2.0
Merge after https://github.com/telerik/mobile-cli-lib/pull/831
=> Update TypeScript to 2.0

lib/services/plugins-service.ts, lib/tools/node-modules/node-modules-dest-copy.ts
No longer cleaning that up on plugin prepare only. Cleaning it up
every time we update tns_modules/<plugin> now.
Fixes an obscure issue introduced in #2194 -- not preparing plugins when building for an iOS device after preparing them for the simulator beforehand.
=> Always clean plugin "platforms" subdir.

lib/services/ios-project-service.ts, test/ios-project-service.ts
NativeScript 1.7.1 can work only with Cocoapods 0.39.0 or 0.38.2. However these versions are not longer usable and trying to execute `pod install` leads to error. This is described [here](http://blog.cocoapods.org/Sharding/).
Since NativeScript 2.0.0, CLI supports Cocoapods 1.0.0 or later. The changes here are a mix of around six older commits in NS CLI which were adding support for Cocoapods 1.0.0. I've extracted the minimum required changes, so we can use allow building of NativeScript 1.7.1 projects in AppBuilder.
The summary of the changes is:
Trying to run `pod install` with CocoaPods 1.0.0 issues an error in case the Podfile doesn't reference a target. Add the project target to the Podfile.
Upon specifying target to the Podfile, however, the path to the Pods' .xcconfig file changes …
=> Support Cocoapods 1.0.0 in NativeScript 1.7.1

lib/constants.ts, lib/declarations.ts, lib/definitions/project.d.ts, lib/node-package-manager.ts, lib/npm-installation-manager.ts, lib/services/android-project-service.ts, lib/services/init-service.ts, lib/services/ios-debug-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, lib/services/project-changes-info.ts, lib/services/project-service.ts, lib/services/project-templates-service.ts, package.json, test/npm-installation-manager.ts, test/npm-support.ts, test/platform-service.ts, test/project-service.ts, test/project-templates-service.ts, test/stubs.ts
PR removes the local npm2 dependency from CLI. Fix for: https://github.com/NativeScript/nativescript-cli/issues/1845
_Description_
Cache functionality is removed from `lib/node-package-manager.ts` and `lib/npm-installation-manager`. Other changes are made along the way to accommodate the lack of the cache add cache unpack functionality.
* On npm install template: template is saved to `tmp` folder in some cases and to cache in others, and then are extracted to app folder. If Template is not default, the default template was downloaded because it's the only one that has `App_Resources` folder. The `App_Resources` folder is copied to new template.
* On npm install core-framework (tns-ios, tns-android), tns-core-framework is saved to cache and extracted to `platforms/` folder
* On npm install …
=> remove npm2 dependency

setup/native-script.rb
Fix several issues reported in https://github.com/NativeScript/nativescript-cli/issues/2139:
* Execute brew commands without sudo - https://github.com/NativeScript/nativescript-cli/issues/2228.
* Remove Java home folder shell evaluation introduced in https://github.com/NativeScript/nativescript-cli/commit/f80953dfcac0093bc70186bb6809a01d6bfdba98#diff-31337fd644449cf05dae54e2c2a41294R106.
* Workaround xcodeproj requiring Ruby 2.2 (macOS default is 2.0) - https://github.com/CocoaPods/Xcodeproj/pull/393.
* Write environment variables to `.zprofile` in addition to `.profile`.
Tested on macOS Sierra and El Capitan VMs.
=> Updating macOS setup script with latest macOS/package requirements

lib/services/ios-project-service.ts, test/ios-project-service.ts
They are added from their original `node_modules` folder instead.
Closes https://github.com/NativeScript/nativescript-cli/issues/2227.
=> Remove use of lib/iOS folder for native plugins

lib/services/ios-project-service.ts, test/ios-project-service.ts
Previously when adding a framework to the Xcode project the path was wrongly calculated when `--path` is used:
The correct one should be:
```
CFC86276F86A4C9B9A1EC768 /* TNSWidgets.framework */ = {isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = TNSWidgets.framework; path = "$(SRCROOT)/../../node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework"; sourceTree = "<group>"; };
```
=> Fix native framework relative path calculation

lib/constants.ts, lib/declarations.ts, lib/definitions/project.d.ts, lib/node-package-manager.ts, lib/npm-installation-manager.ts, lib/options.ts, lib/services/android-project-service.ts, lib/services/doctor-service.ts, lib/services/init-service.ts, lib/services/ios-debug-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, lib/services/project-changes-info.ts, lib/services/project-service.ts, lib/services/project-templates-service.ts, package.json, test/npm-installation-manager.ts, test/npm-support.ts, test/platform-service.ts, test/project-service.ts, test/project-templates-service.ts, test/stubs.ts
=> added logging on install

lib/services/project-service.ts
when creating a project with `tns create <app_name> --template <package_name>` command, we didn't uninstall the package correctly when passed <package_name> parameter is an URL or .tgz file.
=> fixed installed module name when uninstalling module

lib/services/ios-debug-service.ts
Merge with https://github.com/telerik/mobile-cli-lib/pull/840.
Can be useful when debugging connection issues.
Example output:
```
(lldb) process attach --pid 581
Process 581 stopped
* thread #1: tid = 0xa0c738, 0x00007fff661e7000 dyld`_dyld_start, stop reason = signal SIGSTOP
frame #0: 0x00007fff661e7000 dyld`_dyld_start
dyld`_dyld_start:
->  0x7fff661e7000 <+0>: popq   %rdi
0x7fff661e7001 <+1>: pushq  $0x0
0x7fff661e7003 <+3>: movq   %rsp, %rbp
0x7fff661e7006 <+6>: andq   $-0x10, %rsp
Executable module set to "/usr/lib/dyld".
Architecture set to: x86_64h-apple-ios.
```
ping @KristinaKoeva
=> Print lldb output when attaching to the iOS Simulator with trace logging

lib/declarations.ts, lib/device-sockets/ios/socket-proxy-factory.ts, lib/options.ts, lib/services/ios-debug-service.ts
Open a web socket proxy when debugging is started with chrome option
=> Chrome dev tools

lib/definitions/project.d.ts, lib/services/cocoapods-service.ts, lib/services/ios-project-service.ts, test/cocoapods-service.ts, test/ios-project-service.ts
Currently the CLI does not merge the post_install hooks in the Podfile. When there are more than one post_install hooks, cocoapods will fail on pod install. The solution is to find all the post_install hooks in the merged Podfile and transform them to methods. After that post_install will be called with block in which all the transformed methods will be called.
=> Merge post_install hooks in Podfile

lib/services/platform-service.ts
[`prepareAppResources`](https://github.com/NativeScript/nativescript-cli/compare/buhov/fix-app-resources?expand=1#diff-513fe963f5d821a1cdb167ea91d70f1cR290) deletes the `appResourcesDestination` folder so we need to create it after its removal. This is needed because after [updating `shelljs`](https://github.com/NativeScript/nativescript-cli/pull/2243) [copying to non-existing destination](https://github.com/NativeScript/nativescript-cli/compare/buhov/fix-app-resources?expand=1#diff-513fe963f5d821a1cdb167ea91d70f1cL293) doesn't create the destination path.
=> Fix App Resources copying operation

.gitignore, .npmignore, .vscode/launch.json, Gruntfile.js, bin/nativescript, bin/nativescript.cmd, bin/tns, bin/tns.cmd, lib/device-sockets/ios/socket-request-executor.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, lib/services/project-templates-service.ts, package.json, test-scripts/istanbul.js, test-scripts/mocha.js, test/ios-project-service.ts, test/platform-service.ts, tsconfig.json
> NOTE: Merge only after https://github.com/telerik/mobile-cli-lib/pull/843 is merged
Add support for ES6 transpilation. Change dependency injection in order to match the `class` and `constructor` keywords.
Update istanbul to latest version as its previous versions do not support ES6.
Remove bluebird.d.ts as it conflicts with Promises from TypeScript's ES6 d.ts.
Remove bluebird as dependency - we will use native Promises from now on.
Add support for Node.js 4 and 5 - both versions have limited support for ES6 features, so in order to support them we have to:
- pass --harmony flag to Node.js
- do not use some features like default values of method arguments.
- do not use spread operator - it's implementation in Node.js 4 is limited only to arrays. Even this implementation has issues. So …
=> Transpile to ES6

lib/services/ios-debug-service.ts
Open app inspector command installs tns-ios-inspector which needs to be saved in the package.json as a `normal` or a `dev` dependency, because we do a diff of the package json before and after the installation. 
If the newly installed package is not saved our diff logic doesn't work correctly
ping: @pkoleva @dtopuzov
=> [iOS speciffic] Fix open app inspector command

lib/services/ios-debug-service.ts
how to use a custom inspector:
* `tns create <app_name>`
* `npm install <path_to_custom_inspector> --save-dev`
* `tns debug ios`
how to use normal inspector:
* `tns create <app_name>`
* `tns debug ios`
ping @dtopuzov, @pkoleva 
`tns debug ios --frameworkPath <path_to_custom_inspector>` is no longer possible.
To be merged after: https://github.com/NativeScript/nativescript-cli/pull/2294
=> [iOS speciffic] tns debug ios now works with custom inspector

lib/declarations.ts, lib/npm-installation-manager.ts, lib/services/ios-debug-service.ts, test/npm-installation-manager.ts, test/stubs.ts
the logic for dealing with npm is in the wrong place (ios-debug-service) so it's moved to npminstallation manager where it should be
@KristinaKoeva
=> moved caching logic to npminstallation manager

bin/nativescript.js, lib/nativescript-cli.ts
NOTE: Merge **only after** https://github.com/telerik/mobile-cli-lib/pull/851 is merged 
EDIT: PR in common is merged, this one can be merged.
As old versions of Node.js cannot be used anymore (after transpiling to ES6), we should break the process when such case happens.
Use only var instead of let, const, as only var keyword is supported in Node.js 0.10.x
Part of https://github.com/NativeScript/nativescript-cli/issues/2204
=> Break CLI process when Node is not supported

.gitmodules, .travis.yml
At the moment the submodule is initialized via ssh. This way the command `git submodule update --init` will work only for users who have write access to mobile-cli-lib.
This also requires custom logic when travis is used. In current implementation, travis automatically calls `npm install` before executing the scripts, but at this point the submodule is not initialized yet (as we have declared submodules variable to false).
So the `npm install` executed by travis, will fail in case the postinstall script uses some code from the submodule.
In order to fix this two changes are applied:
- change the sumodule to be used over https instead of ssh.
- modify .travis.yml to use submodule correctly and remove two manual steps which are executed by travis by default, there's no need the execute them …
=> Use https for submodule initialization

package.json
Updates transitive semver dependency which is blocking Android builds in some situations (#1122).
=> Update log4js version

postinstall.js, preuninstall.js
Fix postinstall and preuninstall scripts which incorrectly try to start `bin/nativescript.js`, which does not exist anymore.
=> Fix scripts

bin/nativescript.js, lib/commands/appstore-upload.ts, lib/commands/build.ts, lib/commands/deploy.ts, lib/commands/emulate.ts, lib/commands/run.ts, lib/definitions/platform.d.ts, lib/definitions/project.d.ts, lib/providers/livesync-provider.ts, lib/services/android-debug-service.ts, lib/services/android-project-service.ts, lib/services/ios-debug-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts
=> Fixed: TNS run command broken with using --watch

lib/services/ios-log-filter.ts
Fixes #2266
> *Merge after* https://github.com/telerik/mobile-cli-lib/pull/847
=> Fixed: CLI crashes/stops responding after ~80 console.logs

lib/tools/node-modules/node-modules-dest-copy.ts
**Related to** https://github.com/NativeScript/nativescript-cli/pull/2156
The *temporary* logic for extracting every single piece of `tns-core-modules` at root level of `tns_modules` is removed as discussed back during the `2.4` release.
iOS livesync logic should in turn be revised, so we can ensure it doesn't break following these changes.
=> Treat tns-core-modules as a normal npm module

lib/services/ios-project-service.ts, package.json
iOS signing was failing android builds.
xcconfig provisioning profiles are no longer passed as command line args to xcodebuild.
=> iOS signing fixes

.vscode/launch.json, lib/constants.ts, lib/services/project-service.ts
See [issue](https://github.com/NativeScript/nativescript-cli/issues/2301) for more info.
_Problem_
People get confused because there are two `package.json` files, one in the root folder and one in `app/` folder. The two `package.json` files have the same dependencies and devDependencies, which is the main reason for the confusion.
_Solution_ 
The solution discussed with @valentinstoychev was to keep the `app/package.json` as simple as possible, and if possible to add some comments to each key in the `app/package.json` to explain what is the purpose of it. Because there are no comments in the `.json` format, IMO it's best to describe the functionality in the documentation.
This PR is not final and is only one possible solution. We can decide we want to apply different solution to the …
=> delete all unnecessary keys from app/package.json

lib/services/android-project-service.ts
**Depends on**: https://github.com/NativeScript/android-runtime/pull/664
Moved native plugin clean logic to android build.gradle. Now when removing a plugin with android libraries in the form of jars and aars, the android build directory is invalidated, such that a full build will be necessary the next time the project is ran.
Addresses https://github.com/NativeScript/nativescript-cli/issues/2270
=> Invoke gradle fullClean on android after removing a native plugin

lib/services/project-templates-service.ts
the --template option should be able to take name@version as parameter and successfully install the package if such exists
=> fix the --template option

lib/android-tools-info.ts
the previous link pointed to a missing page, the new link points to documentation depending on the platform that the command is being executed on
fix for: https://github.com/NativeScript/nativescript-cli/issues/1922
Ping: @pkoleva
=> fix for tns-doctor command

lib/services/android-project-service.ts
This PR is to help the users understand what needs to be done, when the template they're using is old.
When there's an old template with missing `app.gradle` there's an error on copy added a verbose log that helps the user take care of updating the template.
This present's an opportunity for a known issues page in the documentation, to which we can refer when we feel the need to.
@valentinstoychev @tsonevn
=> fix behavior with old templates

lib/services/android-debug-service.ts, lib/services/ios-debug-service.ts
Otherwise we would have to update our logic on every Chrome update
=> Open specific version of Chrome Dev Tools

package.json, tsconfig.json
TypeScript 2.0 does not add "use strict"; in files which just declare class and does not export it. This breaks Node 4 because of the class keyword.
Also fix : https://github.com/NativeScript/nativescript-cli/issues/2370
=> Update TypeScript to 2.1

lib/bootstrap.ts, lib/commands/devices.ts, lib/definitions/emulator-platform-service.d.ts, lib/services/emulator-platform-service.ts, lib/services/platform-service.ts, test/npm-support.ts, test/platform-commands.ts, test/platform-service.ts, test/stubs.ts
Fixed: Devices services not initialized! error when executing `tns emulate ios`
Fixed: cannot specify which emulator to start
=> Fixed: tns emulate --device id not working

lib/node-package-manager.ts, lib/services/doctor-service.ts
Fixes #2363 
See #2409 for comments
=> Fixed: Confusing report for a problem with CocoaPods during installation

lib/services/platform-service.ts
CLI should exit and show error message when using the following command:
`tns emulate android --device <device_id>`
and when device_id points to a non existing emulator.
=> Fixed: Show error message when --device <device id> is invalid

lib/services/emulator-platform-service.ts
=> Fixed: "tns emulate android" fails with a space in the name of the home directory

lib/options.ts
When set to false this command causes confusion because changes in node_modules are not synced!
=> Changed the syncAllFiles option to be true by default

lib/services/ios-provision-service.ts
As the code is transpiled to ES6, spread operator from TypeScript is transpiled to spread operator in JavaScript.
However this usage is not available in Node.js 4:
```TypeScript
let { normalizedPropertyName, projectConfigurations } = this.validateUpdatePropertyInfo(propertyName, propertyValues, configurations);
// Replaced with:
let data = this.validateUpdatePropertyInfo(propertyName, propertyValues, configurations),
normalizedPropertyName = data.normalizedPropertyName,
projectConfigurations = data.projectConfigurations;
```
This is limitation of Node.js 4 itself. Spread operator is not available there (it's available only for arrays, i.e.
```JavaScript
const arr = [ 1, 2, 3 ]
console.log([ 0, ...arr ]);
[ 0, 1, 2, 3 ]
```
=> Fix support for Node.js 4

lib/services/platform-service.ts
The following command doesn't exit: `tns run ios --release --justlaunch` because of the watch option that is enabled by default.
=> Fixed: the app doesn't exit when using --release and --justlaunch

lib/device-sockets/ios/socket-proxy-factory.ts
Debug should stay connected and watch for changes when executing:
`tns debug ios --chrome --watch`
=> Fixed: debug exits unexpected when using --chrome and --watch options

lib/services/test-execution-service.ts
The stack trace: 
`TypeError: Cannot read property 'ios' of undefined
at FiberFuture.Future.wait (/Users/raikov/work/nativescript-cli/node_modules/fibers/future.js:566:15)
at fiberBootstrap.run (/Users/raikov/work/nativescript-cli/lib/services/test-execution-service.ts:133:36)
at fiber (/Users/raikov/work/nativescript-cli/lib/common/fiber-bootstrap.ts:10:3)
- - - - -
at <anonymous> (/Users/raikov/work/nativescript-cli/lib/services/test-execution-service.ts:239:104)
at Function.settle (/Users/raikov/work/nativescript-cli/node_modules/fibers/future.js:249:26)
at FiberFuture.Future.wait (/Users/raikov/work/nativescript-cli/node_modules/fibers/future.js:565:10)
at fiberBootstrap.run (/Users/raikov/work/nativescript-cli/lib/services/test-execution-service.ts:133:36)
at fiber …
=> Fixed: test command fails with exception

docs/man_pages/project/testing/debug-android.md, lib/services/android-debug-service.ts
`--get-port` flag was previously used only by the VSCode extension to print the forwarded debug port. This PR removes the flag and prints the debug port on every run of `tns debug android`.
Depends on: https://github.com/telerik/mobile-cli-lib/pull/878
=> Remove --get-port flag

lib/definitions/ws.d.ts, package.json, test/stubs.ts, test/test-bootstrap.ts
Currently we are using `node.d.ts` from version `0.11.x`. In order to get latest updates, remove our own version of node.d.ts and use the one from `@types`. Use the version for Node 6.
Fix code according to new definitions. Introduce ICliGlobal interface in order to describe the global object that's used from CLI (we add some properties to the global object).
Add definition file for `xmlhttprequest` module.
Add definitions for Eqatec Analytics.
Modify `ws.d.ts` according to latest changes.
=> Use node.d.ts from @types

lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, test/stubs.ts
If app's built with the `--release` option, the settings are recorded in `.nsprepareinfo` in the `platforms/android` directory. If the file is present, and follow up builds are not built in release, then the project directory is cleaned manually to ensure that no build artifacts specific to just release (like the android snapshot binaries) are packaged into the debug application.
File changes:
- exposed an android-specific private method as public to the `IPlatformProjectService` and created a stub on the ios side.
- added conditions to clean the build directories on prepare when targeting `android`
**Addresses** https://github.com/NativeScript/nativescript-cli/issues/2443
=> clean-up after release build in android to prevent runtime errors

lib/services/livesync/livesync-service.ts
_Problem:_
When the command `tns debug android` is ran the expected behavior is
* application is started
* debug is started
* link is shown to the user so that he can open it in chrome and start debugging
Currently the debugger is not started and link is not shown
_Solution:_
While refactoring an argument was forgotten, and this causes the behavior described above.
* added forgotten argument (`applicationReloadAction`) in [this line](https://github.com/NativeScript/nativescript-cli/blob/c851b88c98ec53a00a589eea9a90a8e971f2afd8/lib/services/livesync/livesync-service.ts#L110) and everything is working as expected.
ping @rosen-vladimirov
=> added missing action so debug is enabled right after the first command

lib/services/ios-provision-service.ts
As the code is transpiled to ES6, spread operator from TypeScript is transpiled to spread operator in JavaScript.
However this usage is not available in Node.js 4:
```TypeScript
let { normalizedPropertyName, projectConfigurations } = this.validateUpdatePropertyInfo(propertyName, propertyValues, configurations);
// Replaced with:
let data = this.validateUpdatePropertyInfo(propertyName, propertyValues, configurations),
normalizedPropertyName = data.normalizedPropertyName,
projectConfigurations = data.projectConfigurations;
```
This is limitation of Node.js 4 itself. Spread operator is not available there (it's available only for arrays, i.e.
```JavaScript
const arr = [ 1, 2, 3 ]
console.log([ 0, ...arr ]);
[ 0, 1, 2, 3 ]
```
=> Fix support for Node.js 4 (#2414)

bin/nativescript.js
At the moment when you have CLI 2.4.x and you try installing newer version (2.5.x), installation fails with EEXIST error for bin/tns. The problem is that in 2.5.0 we've tried to simplify the files that we have in CLI's bin dir.
However `npm` acts a little bit strange to these changes. In NativeScript 2.4.x, when CLI is installed globally, npm makes symlink to CLI's `bin/nativescript.js` file. We've removed this file, and in version 2.5.x the symlink should point to `bin/tns` file. However during upgrade (when you have version 2.4.x or earlier installed globally) npm does not delete the symlink to `bin/nativescript.js` and later fails.
This can be fixed by manually uninstalling 2.4.x version and installing 2.5.x after that.
In order to allow upgrade to version 2.5.x when you already have …
=> Fix upgrade of CLI

lib/services/plugins-service.ts
Problem:
See more in this issue.
Because of the way promises are executed, a new project was created twice and was overridden twice with only one framework file being added each time. The proper implementation reads the previously changed .proj file and augments it with the new .framework file.
Fix for:  https://github.com/NativeScript/nativescript-cli/issues/2460
=> fix for  #2460

lib/nativescript-cli-lib-bootstrap.ts, lib/nativescript-cli-lib.ts, package.json, test/nativescript-cli-lib.ts
The entry point of current cli is used only from `bin/tns`. In fact the `main` entry in package.json is used when you want to require the module, but CLI is never required. It's installed globally and spawned from it's bin dir (`bin` key in package.json defines which is the "entry" point when package is installed globally).
So I've changed the entry point to a file, that does not use commandDispatcher - when requiring {N} CLI as library, we'll not execute commands.
In order to allow executing specific device operations (like device detection through events), require the mobile-cli-lib's appbuilder bootstrap in the entry point. This will be fixed with other PR's and finally we'll not have to require this bootstrap.
=> Allow require of nativescript-cli as library

lib/options.ts, lib/services/livesync/livesync-service.ts
If you want to watch for changes in node_modules or package.json a --sync-all-files or --syncAllFiles flag needs to be passed. By default only the app/ folder is being watched during any livesync.
Furthermore even with the --syncAllFiles flag enabled only production dependencies will be watched and livesynced.
=> node_modules is not watched by default

lib/services/livesync/livesync-service.ts
https://github.com/paulmillr/chokidar#path-filtering
Resolves:
https://github.com/NativeScript/nativescript-cli/issues/2472
=> Ignore .DS_Store file changes on Mac

PublicAPI.md, lib/bootstrap.ts, lib/commands/create-project.ts, lib/definitions/project.d.ts, lib/nativescript-cli-lib-bootstrap.ts, lib/services/project-service.ts, test/nativescript-cli-lib.ts, test/project-commands.ts, test/project-service.ts
In order to allow creating a new NativeScript project when {N} CLI is required as a library, we should add createProject method to public API. This requires some modifications in method's implementation - we cannot rely on `$options` as it is not populated correctly when the CLI is used as a library. Pass object describing the project that we have to create. Fix unit tests accordingly and uncomment (and fix) all tests in project-service.
Add unit tests that will check if a method is really exposed in public API.
Add PublicAPI.md file, which describes all methods that can be used when using CLI as a library.
=> Expose createProject to public API

lib/definitions/platform.d.ts, lib/definitions/project.d.ts, lib/project-data.ts, lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts, lib/services/project-templates-service.ts, test/npm-support.ts, test/platform-commands.ts, test/platform-service.ts, test/project-data.ts, test/project-service.ts, test/project-templates-service.ts, test/stubs.ts
Add tracking from which template a project is created. This will give us better picture of the usage of CLI and the types of projects that the users are creating.
Track the project type (Angular, TypeScript, JavaScript) when any of the commands is executed:
* prepare
* deploy
* run
* livesync
This will allow us to better understand the type of projects that the users are building.
Implements https://github.com/NativeScript/nativescript-cli/issues/2478
=> Add tracking for the project types that users are creating and working with

lib/services/livesync/livesync-service.ts, lib/services/livesync/platform-livesync-service.ts, lib/services/platform-service.ts, lib/services/project-changes-service.ts
In case you try adding/removing directories in your `app` dir, `chokidar` (the file system watcher that we are using now instead of `gaze`) raises `addDir`/`unlinkDir` events.
However we do not have handles for these events, so we do not execute anything. After that, when we add a file in the newly created dir, `chokidar` sends `add` event, we handle it and try to process the file.
This works fine for iOS and Android devices, but it does not work at all for iOS Simulator, as we have not transferred the new directory to `platforms` dir.
Add required handles for `addDir` and `unlinkDir` methods.
Also currently there's a problem when already existing directory is renamed. In this case its modified time (`mtime`) is not changed, so the projectChangesService disregards the change and doesn't …
=> Fix livesync/run issue

lib/node-package-manager.ts
Whenever CLI spawns `npm install <smth>`, we do not set stdin and stdout
of the spawned process. This way in case any of the npm scripts executed
during install requires input from user, it cannot be handled in any
way.
So pass the current stdin and stdout to the spawned npm process. This
way in case a postinstall script is executed and it requires input from
user, the users will be able to enter required information in the same
place where `tns` command has been executed (same terminal).
This fixes postinstall execution of `nativescript-plugin-firebase`. Fixes #2521
=> Pass current stdio to npm install process

lib/node-package-manager.ts, lib/services/livesync/livesync-service.ts, lib/services/livesync/platform-livesync-service.ts, lib/services/platform-service.ts, lib/services/project-changes-service.ts
Cherry-pick multiple fixes from release branch:
In case you try adding/removing directories in your `app` dir, `chokidar` (the file system watcher that we are using now instead of `gaze`) raises `addDir`/`unlinkDir` events.
However we do not have handles for these events, so we do not execute anything. After that, when we add a file in the newly created dir, `chokidar` sends `add` event, we handle it and try to process the file.
This works fine for iOS and Android devices, but it does not work at all for iOS Simulator, as we have not transferred the new directory to `platforms` dir.
Add required handles for `addDir` and `unlinkDir` methods.
Also currently there's a problem when already existing directory is renamed. In this case its modified time (`mtime`) is not changed, so the …
=> Cherry pick fixes from release

lib/services/livesync/platform-livesync-service.ts
When `.nprepareinfo` file is uploaded on device, we construct the device file path with `path.join` function. On Windows this function returns path similar to `\\data\\local\\tmp`, which is not working for Unix based OSes (Android in this case).
Fix this by converting the path to Unix style.
=> Fix uploading of .nsprepareinfo on Windows

docs/man_pages/project/creation/create.md
--copy-from option is deleted in 2.5 release, so we should remove it from the docs
=> removed --copy-from from help

lib/node-package-manager.ts, lib/npm-installation-manager.ts, lib/services/platform-service.ts
Implement rollback of package.json contents of project if npm installation fails for whatever reason during installation of a NS plugin or platform.
Addresses #2487 
master-based PR: #2531
=> Rollback package.json if plugin installation fails

lib/services/platform-service.ts
When `.nsbuildinfo` file is uploaded on device, we construct the device file path with `path.join` function. On Windows this function returns path similar to `\\data\\local\\tmp`, which is not working for Unix based OSes (Android in this case).
Fix this by converting the path to Unix style.
=> Fix uploading of .nsbuildinfoon Windows

lib/services/project-changes-service.ts
On macOS sometimes we recive ENOENT errors during livesync operations (`tns run ios`). This is due to the following:
- incorrect detection if a file is modified - we check if the project dir's mTime and cTime values are bigger than the .nsprepareinfo. However in some cases they are equal, which means the dir has been modified in the same moment when the `.nsprepareinfo` is saved. In order to fix this, mark the files/dirs as modified in case the modified time of `.nsprepareinfo` and the respective file are the same.
- In some cases we are not able to sync files to iOS Simulator as chokidar does not raise correct events on macOS when directory is renamed immediately after it's being created.
After adding a file to this directory we throw ENOENT, as such dir does not exist in Simulator's …
=> Fix ENOENT errors on macOS during livesync

lib/services/livesync/livesync-service.ts
* Ignore .DS_Store file changes on Mac
https://github.com/paulmillr/chokidar#path-filtering
Resolves:
https://github.com/NativeScript/nativescript-cli/issues/2472
* Updated to ignored: '**/*.DS_Store'
=> Ignore .DS_Store file changes on Mac (#2473)

lib/services/livesync/platform-livesync-service.ts, lib/services/platform-service.ts, lib/services/project-changes-service.ts
Merge LiveSync fixes from release branch
=> Merge LiveSync fixes from release branch

lib/definitions/platform.d.ts, lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, test/platform-commands.ts, test/platform-service.ts, test/stubs.ts
The android runtime (3.0) has had its gradle wrapper version updated where daemon processes are used by default.
Daemons are used to prevent the overhead of having to initialize the JVM on every build command, thus lowering the build time dramatically. The fact that the process remains alive appears to be a problem in Windows environments as the daemon locks the `platforms/android` directory.
The changes in this PR ensure that the currently running daemons will be terminated, and the lock over the platforms directory released, so that it may be freely removed.
Addresses #2528
=> stop gradle daemons when removing platform

setup/native-script.rb
Write ANDROID_HOME and JAVA_HOME variables in `.bash_profile` instead of `.profile`
=> Write variables to .bash_profile

lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts, test/stubs.ts
=> apply PR #2452 based to master

lib/commands/install.ts, lib/commands/update.ts, lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/livesync/livesync-service.ts, lib/services/platform-project-service-base.ts, lib/services/platform-service.ts, lib/services/plugin-variables-service.ts, lib/services/plugins-service.ts, lib/services/project-data-service.ts, lib/services/project-service.ts, test/services/project-data-service.ts, test/stubs.ts
In case the CLI is `required` as a library (used in a long living process, not as a command-line interface), trying to create a project multiple times leads to errors.
The problem is in the `projectDataService` which caches the path to first created project file (package.json) and uses it for all consecutive operations.
In other cases, when CLI had to use the projectDataService, it always had to call `projectDataService.initialize` method.
Instead of relying on a magically called initialize method, modify the service methods to work with any project dir and execute the required operation for it.
This will fix the creation of multiple projects as all operations will work with currently passed project directory.
Also remove the code that creates a `package.json` file during …
=> Fix creating multiple projects in a single process

lib/commands/build.ts, lib/commands/deploy.ts, lib/commands/run.ts, lib/declarations.ts, lib/services/platform-service.ts
The commands build, deploy and run should pass Android specific options: `keyStorePath, keyStoreAlias, keyStorePassword, keyStoreAliasPassword` to the services.
This will fix building of projects for Android in release config.
=> Pass Android release options for build/deploy/run

lib/commands/add-platform.ts, lib/commands/appstore-upload.ts, lib/commands/build.ts, lib/commands/clean-app.ts, lib/commands/debug.ts, lib/commands/deploy.ts, lib/commands/emulate.ts, lib/commands/install.ts, lib/commands/livesync.ts, lib/commands/platform-clean.ts, lib/commands/prepare.ts, lib/commands/run.ts, lib/commands/update-platform.ts, lib/commands/update.ts, lib/declarations.ts, lib/definitions/platform.d.ts, lib/definitions/project.d.ts, lib/platforms-data.ts, lib/providers/livesync-provider.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/livesync/android-device-livesync-service.ts, lib/services/livesync/ios-device-livesync-service.ts, lib/services/livesync/livesync-service.ts, lib/services/livesync/platform-livesync-service.ts, lib/services/platform-service.ts, lib/services/test-execution-service.ts, test/platform-service.ts
Each commit fixes different issue, so each commit can be checked on its own.
When user tries to add invalid platform, CLI should prints user-friendly
message. Instead it fails that cannot read `getPlatformData` of
`undefined`. The reason is a change in platforms-data `getPlatformsData`
method. Fix it to return undefined when there's no platform specific
data. This way the code will detect the invalid platform and will fail
with user-friendly message.
Fixes https://github.com/NativeScript/nativescript-cli/issues/2587
During adding of Android platform, users can specify targetSdk via
`--sdk` command line option. This has been broken in previous commit.
As our services should not rely on `$options`, sdk must be passed as
parameter whenever it could be used. It turns out some common methods …
=> Fix several issues in `@next` version

lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts
See more info: https://github.com/NativeScript/nativescript-cli/issues/2586
_Problem_
Sometimes on prepare, there were platform specific files like `name.android.js` that weren't processed correctly.
=> added forgoten parameter

lib/constants.ts, lib/services/platform-service.ts, test/platform-service.ts
Instead of always installing the latest runtime version, respect the one written in `package.json` `nativescript` key.
Ping @TsvetanMilanov @rosen-vladimirov @Plamen5kov
=> Respect runtime version written in package json

lib/commands/platform-clean.ts, lib/definitions/platform.d.ts, test/platform-commands.ts
Fixed the platform-clean to execute only when the Platform is Valid and Installed. Add the "platform|clean" module to the test injector - now after platform|clean the code is actually executed.
=> Improve platform-clean command check for Platform

lib/services/android-project-service.ts
_problem_:
We needed id set in package.json to be exactly 3 components long.
_solution_
Take the last component of the id instead of the third one.
=> take last parameter of id for packageName

lib/services/platform-service.ts, test/npm-support.ts, test/platform-commands.ts, test/platform-service.ts
Return the same error when invoking:
tns <command> --device id|name
for both platforms to be:
Cannot resolve the specified connected device by the provided index or identifier. To list currently connected devices and verify that the specified index or identifier exists, run 'tns device'.
=> Equalize the non-existent device error message #2446

lib/services/android-project-service.ts
Log a message if during before-prepare on android an exception is thrown (most likely caused by previously traversed cyclic dependencies) when spawning a node child process to check for plugins depending on the public V8 being exposed by the runtime.
It is important to note that the likely cause, for the process throwing an exception, can be viewed as a separate issue, as having cyclic production dependencies slows down the prepare step considerably.
More info: https://github.com/NativeScript/nativescript-cli/issues/2561#issuecomment-286057592
Addresses: https://github.com/NativeScript/nativescript-cli/issues/2561
=> Handle `node check-v8-dependants.js` throwing an exception

lib/services/project-service.ts, test/project-service.ts
If the template specified by the --template parameter doesn't contain the App_Resources folder, we take the App_Resources folder from the default template and use that instead.
=> add App_Resources from default template if missing #2513

lib/definitions/platform.d.ts, lib/services/livesync/platform-livesync-service.ts, lib/services/platform-service.ts
_Problem_:
Plugin authors do unnecessary changes, because they lack the information about files about to be synced. This workflow causes too much trouble, which can be easily avoided if cli provides more information to the plugin authors, who will then be able to handle the erroneous behavior.
_Solution_:
Introduced `hookArgs.filesToSync` parameter which contains all changed files as a string array. If no files are marked as changed `filesToSync` is `undefined`.
Plugin authors needed more information on what files have changed during livesync and we now provide this information through `hookArgs.filesToSync`, which is a string array full with all detected changed files. `hookArgs` is a parameter of the `before-(after)-prepare-hook.js` files, that gets resolved by an injector.
=> provided more information to plugin authors

lib/android-tools-info.ts, lib/declarations.ts, lib/services/android-project-service.ts, lib/services/doctor-service.ts, lib/services/emulator-platform-service.ts, lib/sys-info.ts, test/stubs.ts
Due to changes in Android SDK, we have to update the checks in CLI. While gathering system information, we check the android executable, which is no longer returning correct results.
We use the android executable to find information about installed Android SDKs and to construct correct paths based on ANDROID_HOME. Fix this by listing directories inside ANDROID_HOME and find the information about installed SDKs from there.
Fix messages pointing to `android` executable to point to `sdkmanager` (in case it exists).
In order to fix this, we rely on the emulator executable, which is the real thing we need as it is the one that allows us to work with Android Emulators (this is changed in mobile-cli-lib).
Fix sys-info checks and get correct path to emulator according to latest changes. 
PR In …
=> Fix getting info for Android tools

lib/services/android-debug-service.ts
Remove the `v8only` flag from Chrome DevTools debug url to enable use of more inspector agents ([1.2](https://chromedevtools.github.io/debugger-protocol-viewer/1-2/) vs [v8 - node](https://chromedevtools.github.io/debugger-protocol-viewer/v8/))
=> Change android debug url

lib/bootstrap.ts, lib/nativescript-cli-lib-bootstrap.ts, lib/services/ios-log-filter.ts
We need to pass the project directory only for the ios-log-filter in the NS CLI. That's why we can use the projectData instead of adding it as a parameter.
Common lib reference: https://github.com/telerik/mobile-cli-lib/pull/905
=> Fix iOS device log filter

lib/commands/platform-clean.ts, lib/definitions/platform.d.ts, lib/services/platform-service.ts, test/platform-service.ts, test/stubs.ts
Consider the following situation: There is a new version of NativeScript available (3.0) and I have existing projects using older version (2.5). I don't want to upgrade immediately for various reasons (too many effort required on my side, I'm just before releasing the app, etc). The current behaviour of the `tns platform clean` command is that it will first remove the specified platform and then the latest available platform (3.0) will be added. This is inconvenience in the described scenario.
As a developer, I would expect when I run `tns platform clean` the version of the platform added to be the same as before running the command (2.5).
Related to issue: [TNS platform clean android #2496](https://github.com/NativeScript/nativescript-cli/issues/2496)
=> platform clean should preserve the nativescript version used #2496

CHANGELOG.md, package.json
Bump version to 2.5.3.
Add release notes for 2.5.3.
=> Release notes for {N} CLI 2.5.3

lib/services/livesync/android-device-livesync-service.ts
When migrating from fibers to promises, we've placed incorrect await, which prevents us when trying to remove a file from project during livesync operation.
Fix the code, so removed files will be synced correctly.
=> Fix removing of file on android during livesync

lib/services/livesync/ios-device-livesync-service.ts
We need to pass the project name instead of the app identifier to kill the application on the simulator.
Common lib reference https://github.com/telerik/mobile-cli-lib/pull/916
=> Fix stop application on iOS simulator

lib/services/livesync/livesync-service.ts, lib/services/local-build-service.ts, lib/services/project-service.ts
Delete @exportedPromise decorator as we no longer need it
Stop stopping device detection interval when deploying on iOS devices. These operations no longer conflict as the code is located in an external dependency.
Merge after https://github.com/telerik/mobile-cli-lib/pull/917
=> Stop stopping device detection interval

PublicAPI.md, lib/commands/appstore-upload.ts, lib/commands/build.ts, lib/commands/debug.ts, lib/constants.ts, lib/definitions/debug.d.ts, lib/definitions/platform.d.ts, lib/definitions/project-changes.d.ts, lib/definitions/project.d.ts, lib/project-data.ts, lib/providers/livesync-provider.ts, lib/services/android-debug-service.ts, lib/services/android-project-service.ts, lib/services/ios-debug-service.ts, lib/services/ios-project-service.ts, lib/services/local-build-service.ts, lib/services/platform-service.ts, lib/services/project-changes-service.ts, lib/services/project-service.ts, lib/services/test-execution-service.ts, test/nativescript-cli-lib.ts, test/npm-support.ts, test/platform-commands.ts, test/platform-service.ts, test/project-data.ts, test/project-service.ts, test/stubs.ts
The isValidNativeScript project method is used in Fusion. However the implementation is not correct. Fix it to have correct behavior.
In order to fix it, modify projectData.initialize method - there's obsolete code for migration from .tnsproject to package.json - we do not need it anymore, so remove it.
Also fix a case where failing builds do not fail the build process (incorrect argument passed to childProcess.spawnFromEvent).
Update documentation for PublicAPI.
Also in case CLI's executed in non-interactive terminal and there's no DEVELOPMENT_TEAM set, tns build ios --for-device fails with message "Console is not interactive and no default action specified" which does not give any info to the users.
So in this case add more descriptive error message.
=> Fix isValidNativeScript project

lib/services/android-project-service.ts
In case you try building application, it will fail in case the following conditions are applied:
* build on Windows
* build for Android
* build in release
* path to project dir has spaces
* path to certificate (keystore) has spaces OR the certificate(keystore) name itself has spaces OR the password has spaces
The problem is in Node.js's `child_process` when `spawn` is used - on Windows it has issues when both the command (in our case this is the FULL PATH to gradlew.bat executable in platforms dir of the project) and ANY of the arguments passed to `child_process's spawn` have spaces.
As we are also setting the current working directory of the spawned process to be the path to `<project dir>/platforms/android`, change the `command` passed to `spawn` to be just `gradlew`. This way we'll …
=> Fix Android builds when gradle args and project dir have spaces

lib/services/livesync/ios-device-livesync-service.ts
The liveEdit method returns Promise, but we do not await it, which could lead to incorrect behavior.
=> Fix missing await for liveEdit

.travis.yml
Fix the issue with syncing files when copying a folder recursively in the app multiple times. The problem was that the `mkdir` command was executed multiple times. The fix is in the mobile-cli, where the folder is checked for existence and not created multiple times.
=> Fix multiple mkdir commands for the same directory #2653

lib/commands/debug.ts, lib/device-sockets/ios/socket-request-executor.ts, lib/services/ios-log-filter.ts
We need to check if the justlaunch flag is passed before we set the should dispose property to false. If we set it to false unconditionally when we pass justlaunch flag the process will never exit.
Fixes https://github.com/NativeScript/nativescript-cli/issues/2654
=> Fix ios-device-operations dispose

config/config.json, docs/man_pages/general/autocomplete-disable.md, docs/man_pages/general/autocomplete-enable.md, docs/man_pages/general/autocomplete-status.md, docs/man_pages/general/autocomplete.md, docs/man_pages/general/doctor.md, docs/man_pages/general/error-reporting.md, docs/man_pages/general/help.md, docs/man_pages/general/info.md, docs/man_pages/general/proxy-clear.md, docs/man_pages/general/proxy-set.md, docs/man_pages/general/proxy.md, docs/man_pages/general/usage-reporting.md, docs/man_pages/index.md, lib/config.ts
At the moment users can set proxy by manually editing the file `<cli installation dir>/config/config.json`.
However this has two issues:
- the proxy does not support authentication
- if you install newer version of CLI, the file is overwritten, so you have to set it again.
Fix both issues by:
- creating command that sets the proxy.
- (currently) for Windows introduce support for authenticated proxy - username and password are stored via Windows Credential Manager API functions.
Expected workflow:
`$ tns <command that makes http request>`
Your proxy requires a username and password. You can run
tns proxy set <hostname> <port> <username> <password>
In order to supply NativeScript with the credentials needed.
`$ tns proxy set 127.0.0.1 8888 user pass`
Sucessfully setup proxy.
`$ tns proxy …
=> Add command for setting proxy

lib/services/livesync/platform-livesync-service.ts
Add filter for files which are hidden in linux/Mac to be skipped when livesync-ing the app. Some IDEs create them to backup the currently edited file and this causes a re-deploy/re-run of the Application although it's not necessary.
=> skip the hidden files when livesyncing

lib/options.ts
The Watch Option was completely overriden by the Justlaunch option, every time. This is a newly introduced issue. Now, the justlaunch will take precedence if it's set to true and the watch will be set to false in this case, no matter what's passed for watch.
=> Fix watch incorrectly being overrided by justlaunch always

CHANGELOG.md
Updated Changelog with fixed and implemented issues for the RC release, so new things can be browsed easily
=> Updated Changelog for 3.0.0 RC

lib/definitions/platform.d.ts, lib/services/livesync/platform-livesync-service.ts, lib/services/platform-service.ts, test/stubs.ts
In order to unsderstand the workflow of our users, we need to track how many builds they are executing, how many livesync operations, etc. We also need to know if the operation is for device or emulator (iOSSimulator).
This will allow us to focus the development and provide better features in the future.
=> Track the amount and device type of builds and livesync operations

README.md
- OS X is replaced with macOS to match the current naming convention
- Installation instructions are replaced with a link to the documentation to avoid duplication
=> Update the README with older and more useful version

lib/services/ios-project-service.ts, test/ios-project-service.ts
Add configuration build passing to the xcodebuild when producing the IPA, so that we include the TNSLiveSync framework when built in debug mode and actuall the LiveSync works.
=> Adding configuration build parameter to the archive functionality

lib/definitions/project.d.ts, lib/services/ios-project-service.ts, lib/services/platform-service.ts
We pass provision in-place of projectId downstream since any is assignable from everything and everything is assignable to any.
=> We passed incorrectly provision in-place of projectId

lib/services/ios-project-service.ts
When build for iOS Simulator fails, we do not break the process and hide the error. In any case when build operation fails, we should break the process.
=> Throw error in case build for simulator fails

lib/bootstrap.ts, lib/commands/debug.ts, lib/commands/run.ts, lib/constants.ts, lib/declarations.d.ts, lib/definitions/debug.d.ts, lib/definitions/platform.d.ts, lib/device-sockets/ios/socket-proxy-factory.ts, lib/nativescript-cli-lib-bootstrap.ts, lib/services/android-debug-service.ts, lib/services/debug-data-service.ts, lib/services/debug-service-base.ts, lib/services/debug-service.ts, lib/services/ios-debug-service.ts, lib/services/platform-service.ts, lib/services/test-execution-service.ts, test/debug.ts, test/stubs.ts
We need to add debug service to the public API of the {N} CLI. This service should have method which starts debugging and returns the chrome devtools url. With this service it will be possible to use the CLI as a library and start debugging.
This PR includes:
- Return the results from the action in devicesService.execute(action)
- Remove the this.$options from both android and ios debug services
- Remove the projectData dependency from both android and ios debug services
- Add the new debug service which will be used in the public API
Common lib reference: https://github.com/telerik/mobile-cli-lib/pull/927
=> Add debug method to the public API

lib/services/platform-service.ts
When we look for "FileChanges" we divide them in categories:
-- FileChanged
-- AppResources Changed
The FileChanged is triggered for all files, excluding the ones in App_Resource directory. The CopyAppFiles method copies all /app files though, therefore including the App_Resource files. The functionality to clean-up the App_Resources folder from the /app is in the prepare which is not executed in this case.
This will be refactored, as soon as I add some tests to cover the functionality and ensure we don't do introduce many regression bugs.
=> Remove App_Resources, when the changes are in the other files.

lib/commands/debug.ts, lib/declarations.d.ts, lib/definitions/debug.d.ts, lib/device-sockets/ios/socket-proxy-factory.ts, lib/services/android-debug-service.ts, lib/services/debug-data-service.ts, lib/services/ios-debug-service.ts, lib/services/test-execution-service.ts
When trying to debug on iOS Simulator (via NativeScript Inspector), we often receive `Error: connect ECONNREFUSED 127.0.0.1:18181` error.
There are two different problems. First one is incorrect identifying of the application's PID - we are using `_.trimStart` method totally incorrectly and in case your application identifier has numbers in it, they'll also be replaced in the search PID string. For example in case your app id is `org.nativescript.app10`, and the real PID of the running application is 18129, the current usage of `trimStart` method will give you the PID 8129.
Fix this by applying regular expression and find the correct PID.
The second problem is that there's some delay between opening the NativeScript Inspector and the debugged application on the device. In many cases the …
=> Fix connect ECONNREFUSED error when trying to debug on iOS Sim

lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/local-build-service.ts, lib/services/platform-service.ts
In order to not emit `buildOutput` event multiple times during build in a long running process (fusion) we have to detach event handlers after build is done.
Merge after https://github.com/telerik/mobile-cli-lib/pull/940
=> Detach event handlers after action is done

package.json
Currently we have logic to find the intially attached (at the moment of starting the CLI) iOS devices. Its executed at the beginning of each device related commands and it checks on 500ms for device found.
However this is a problem as we may find one device and skip the others devices (in case more than one device is attached). So first CLI operations are excuted only for one device. The next operations however are executed over all devices found. For example `tns run ios` we execute several operations - install on all devices, upload files to all devices, etc. However in case the install operation is executed, only the first device is discovered. After that the upload files operations are executed on all devices. Due to the fact that the application is not installed on the other devices, …
=> Increase the timeout of initial ios device detection

lib/services/android-debug-service.ts, lib/tools/node-modules/node-modules-builder.ts
When executing `tns debug android` for slow emulators/devices we have logic to wait several seconds until debugger is attached.
However we've missed to `await` the `sleep` method and in fact we are not waiting at all. Add the missing await, which fixes the `tns debug android` command.
A while ago, we had a logic to find out which node_modules should be processed. However it is not used anymore (removed in https://github.com/NativeScript/nativescript-cli/pull/2152/ ).
So remove the code - we do not need it anymore.
=> Fix debug android command

lib/services/livesync/android-device-livesync-service.ts
Original issue in android-runtime: https://github.com/NativeScript/android-runtime/issues/591
Changing .css and .xml files in a NativeScript project would not change permissions in the temporary sync dir on the device. This could result in showing outdated views on subsequent installs of the application on the same device without using the CLI's livesync service.
The proposed changes will always chmod 777 the sync directory, thus allowing the runtime to remove any previous livesync artifacts.
Relies on changes made in https://github.com/telerik/mobile-cli-lib/pull/943
=> Change livesync dir permissions on device even if app is not restarted

lib/commands/debug.ts
Currently the `tns debug ios` command tries to find already built result for iOS Simulator. The problem is incorrect value passed to `buildForDevice` property. It should be set based on the current device.
=> Fix debug for iOS devices

lib/services/ios-debug-service.ts
During `tns debug ios`, in case you make changes, the application must be restarted and the debugger must attached again. However, in many cases we kill the old lldb process and immediately try to start the new one. The childProcess.kill operation finishes, but lldb process does not die immedietely. So in some occasions, the attach of new debugger fails. This leads to multiple errors - you cannot start this application on simulator anymore, you cannot exit CLI's process with `Ctrl + C`, etc.
Fix this by attaching to "close" event of the processes and waiting for them to be really finish their execution.
=> Fix debug on iOS simulator with watch

PublicAPI.md, docs/man_pages/general/extension-install.md, docs/man_pages/general/extension-uninstall.md, docs/man_pages/general/extension.md, lib/bootstrap.ts, lib/commands/extensibility/install-extension.ts, lib/commands/extensibility/list-extensions.ts, lib/commands/extensibility/uninstall-extension.ts, lib/definitions/extensibility.d.ts, lib/definitions/platform.d.ts, lib/definitions/require.d.ts, lib/nativescript-cli.ts, lib/services/extensibility-service.ts, lib/services/require-service.ts, test/nativescript-cli-lib.ts, test/services/extensibility-service.ts
Implement extensibilty of CLI that allows anyone to add packages that add new functionality to NativeScript CLI. The packages are installed in a specific directory, so they are persisted through CLI's updates.
The directory where extensions are installed contains a package.json and each extension is npm package installed there.
The extensions can be maintained in two different ways:
- navigate to the directory where extensions are installed and use `npm` for install/uninstall/update of packages.
- use CLI's commands to update them: `tns extension install <name>`, `tns extension uninstall <name>`, `tns extension`
Implement extensibilityService that executes all operations and expose it to public API. In {N} CLI the extensions are loaded in the entry point, before parsing command line …
=> Implement extensibility model for CLI

lib/commands/test-init.ts, lib/node-package-manager.ts
Often when running `tns test init` it is unclear that there are unmet peer dependencies that are critical to `karma`'s proper execution.
When executing `test init` in a NativeScript, project karma testing frameworks' (`karma-jasmine/qunit/mocha`) peer dependencies will be implicitly installed. These dependencies are `jasmine-core`, `qunit`, and `mocha` respectively, depending on the framework selected from the interactive console prompt.
=> Install karma peer dependencies on `test init`

PublicAPI.md, lib/commands/debug.ts, lib/definitions/debug.d.ts, lib/services/debug-service.ts, lib/services/ios-debug-service.ts, test/nativescript-cli-lib.ts, test/services/debug-service.ts
When using Chrome DevTools to debug iOS applications, CLI returns a url that points to a specific commit of the dev tools. This way, in case a new version of the dev tools introduces a breaking change, the debugging will still work.
However, in some cases (inside Electron app), we cannot use the remote url, so we must use the bundled one. So introduce a new option (only available when requiring CLI as a library), that defines that the returned url will use the bundled dev tools.
The default behavior (used in CLI), will still return the url that includes remote url.
Also change the definition of `debug` method in the interface, so now the DebugService can safely implement it.
Add a new check in the debug service - in case the device's status is not Connected, we are unable to start debug …
=> Improve debugService public API

lib/commands/emulate.ts
During refactoring we've decided to pass the whole `$options` object from commands to services. However we've forgotten to change the emulate command.
Pass correct argument which will fix the issue.
=> Fix emulate command

lib/bootstrap.ts, lib/commands/emulate.ts, lib/declarations.d.ts, lib/definitions/project-changes.d.ts, lib/definitions/project.d.ts, lib/node/pbxproj-dom-xcode.ts, lib/node/xcode.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/ios-provision-service.ts, lib/services/platform-service.ts, lib/services/project-changes-service.ts, package.json, test/ios-project-service.ts, test/mocha.opts, test/npm-support.ts, test/platform-service.ts, test/project-changes-service.ts, test/stubs.ts, test/tns-appstore-upload.ts
- Issuing `tns <prepare|build|deploy etc.> ios --provision <provision uuid or name/specifier>` will now update the native Xcode and invalidate the prepare step and native build if necessary (in case it was used with different provision than the last time).
- In case in the xcconfig was used a PROVISIONING_PROFILE_SPECIFIER the build will set a "Manual" signing style in the Xcode project similar to the behaviour triggered with PROVISIONING_PROFILE. Also when one of these two is provided in the xcconfig, if the --provision was never used, any DEVELOPMENT_TEAM or CODE_SIGN_SPECIFIED will be cleared off the pbxproj so the values from the xcconfig can be respected. There is room for improvement to allow a behaviour that once --provsion was used, if it is not used in subsequent command and the …
=> Make --provision work with distribution certificates and able to update the project after initial prepare

lib/services/doctor-service.ts
Update the Doctor to check for the Python's SIX package via executing help("six") in python, instead of using PIP as by default it appears Mac has the Python and Six package, but can be missing the PIP.
=> Fix the six package detection in release

package.json
During detecting devices, CLI will try to check if there are iOS devices. However the ios-device-lib has an issue in version 0.4.0 and it fails that the binary cannot be found in case 32-bits Node is used.
So use latest version of the lib, where the issue is fixed.
=> Fix working with 32 bit Node on Windows

lib/commands/debug.ts
When `--justlaunch` flag is passed, CLI automatically disposes the `ios-device-lib` after execution of the command. However this closes all opened device sockets and breaks the debug command.
So whenever you try `tns debug ios --justlaunch [--chrome]`, the debug application (NativeScript Inspector) or Chrome DevTools is unable to connect to device socket and fails with error.
Fix this by keeping the `ios-device-lib` alive whenever we try debug for ios. This way the debug application will be able to connect to the device.
NOTE: `tns debug ios --justlaunch [--chrome]` cannot release the terminal as it has to keep the ios-device-lib alive.
=> Fix `tns debug ios --justlaunch`

lib/commands/debug.ts, package.json
When Xcode 8 or later is installed, ios-sim-portable will spawn `xcrun simctl terminate <device id> <app id>` in order to stop the application.
For earlier version the command for stopping the app is `killall <app name>`. So pass correct args to the method.
NOTE: Merge only after the ios-sim-portable version is bumped (i.e. after merging https://github.com/telerik/ios-sim-portable/pull/90).
NOTE2: Merge after https://github.com/telerik/mobile-cli-lib/pull/953
Fixes https://github.com/NativeScript/ios-runtime/issues/761
and
https://github.com/NativeScript/nativescript-cli/issues/2732
=> Pass correct args to ios-sim-portable's stopApplication

lib/npm-installation-manager.ts, lib/services/project-service.ts, test/project-service.ts
CLI tries to install `tns-core-modules` during project creation. In case the template does not have `tns-core-modules` in it, CLI will install latest version of `tns-core-modules` which may (and most probably is) be incompatible with the runtime and other dependencies of the project.
In such cases ensure the CLI installs version of tns-core-modules that matches its own version, i.e. when CLI is 2.5.2, it should install latest 2.5.x core modules.
Also ensure exact versions are installed and persisted by `npmInstallationManager`.
=> Fix installation of tns-core-modules during project creation

lib/npm-installation-manager.ts, lib/services/project-service.ts, package.json, test/npm-installation-manager.ts
When searching for the ios/android runtimes respect the current version of the CLI and don't search only for matching versions - i.e. if I have CLI 2.5.4 don't look for runtimes >= 2.5.4 only, as they can be available only up to 2.5.2 which is still fine and working for us. So I've changed it to look for 2.5.x or major.minor.*any* compatible versions of the packages, when searching for them.
Replaces $npm.install with the $npmInstallationManager.install 
Updated the semver, to add the prerelease function missing in the last version
=> Respect current version of CLI when searching for runtimes

.travis.yml, .travis/add-publishConfig.js
Set `rc` tag to the publishConfig section for the release branch.
Requested by @dtopuzov.
=> Update Travis CI Scripts

lib/bootstrap.ts, lib/declarations.d.ts, lib/definitions/platform.d.ts, lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/livesync/livesync-service.ts, lib/tools/node-modules/node-modules-builder.ts, lib/tools/node-modules/node-modules-dependencies-builder.ts, lib/tools/node-modules/node-modules-dest-copy.ts, test/npm-support.ts, test/plugin-prepare.ts, test/plugins-service.ts, test/stubs.ts, test/tools/node-modules/node-modules-dependencies-builder.ts
CLI has logic to find which are the "production" dependencies, i.e. which should be copied from `node_modules` to `platforms` dir.
However, when the project has a lot of dependencies (more than 15), on some machines the code leads to error: "Maximum callstack size exceeded". On other machines the code tooks significant time to execute.
After investigation, it turned out the recursion inside `node-modules-dependencies-builder` is incorrect and it adds each package many times to the result array.
Fix the recursion and change the class NodeModulesDependenciesBuilder to be stateless - instead of using properties in `this` object when calculating the production dependencies, the methods will persist the results through the passed args.
This way the whole class can be safely added to …
=> Fix getting production dependencies code

lib/declarations.d.ts, lib/node-package-manager.ts, lib/services/plugins-service.ts
Some npm versions (like 3.9.6) do not report result when package is already installed and `--dry-run` is passed.
This breaks the `JSON.parse()` of the result as it is an empty string.
In this case just parse the original output of `npm install` and search for a result like:
```
<project dir>
`-- nativescript-barcodescanner@1.0.0
```
In case this operation also fails to find which is the installed package, try to find the name from the user specified value.
For example:
```
$ tns plugin add nativescript-barcodescanner@1.0.0
```
The name is `nativescript-barcodescanner` and the version is `1.0.0`.
In case a scoped package is passed, the parsing should also work correctly.
In case a package, that is not NativeScript plugin, is installed via `tns plugin add` command, we have logic to revert …
=> Fix getting information for installed npm package

test/ios-entitlements-service.ts, test/ios-project-service.ts, test/test-bootstrap.ts
Currently unit tests from master branch are failing on Windows and Linux. Fix them by applying the following:
- Fix expected path in entitlements test - use `path.join` instead of hardcoded `/` - on Windows the path separator is `\`
- Ignore tests for merging xcconfig files as they can work only on macOS, where ruby is installed. The tests will be ran only in case you are executing them on macOS.
- Require "colors" module in test-bootstrap. During test execution I've noticed some "undefined" statements printed on the terminal. It turned out these are `logger.warn` statements. However the logic in the logger is to print `<message>.yellow`.
When `colors` is not required, the strings do not have `yellow` property, so instead of seeing the real message, the loggger has been printing …
=> Fix unit tests on non-macOS

lib/services/ios-project-service.ts
When we're executing
`tns build {platform} --forDevice`
we don't need to fire up the Simulator. We've changed the common lib to respect a flag named `isBuildForDevice` and in this case not to start the Simulator if no real devices are found attached.
Here we're just passing this `isBuildForDevicе` when running build forDevice
=> Prevent starting a simulator when build --forDevice

lib/nativescript-cli-lib-bootstrap.ts, lib/services/ios-log-filter.ts, test/services/ios-log-filter.ts
Whenever an ios device log is triggered with logLevel INFO `console.log` statements are not seen on the console for ios 8 and ios 9 devices due to a difference in their formats.
Fix this and add tests.
=> Fix ios logs with logLevel INFO

README.md
Changing it with a link to the forums.
=> Remove reference to Google groups in README

docs/man_pages/project/testing/debug-android.md, docs/man_pages/project/testing/debug-ios.md, docs/man_pages/project/testing/debug.md
Changed the documentation according to real/desired behavior of the debug command.
=> Updated md files for the debug command.

lib/services/platform-service.ts, test/npm-support.ts
fixes NativeScript/android-runtime#759
=> Fix prepare for android when building with webpack

lib/constants.ts, lib/npm-installation-manager.ts
Cache structure has changed in npm 5.
Do not rely on said structure but instead use the profile-dir for caching the inspector.
Fixes https://github.com/NativeScript/nativescript-cli/issues/2855
Ping @TsvetanMilanov @rosen-vladimirov
=> Conform ios inspector code with npm 5

PublicAPI.md, lib/commands/extensibility/install-extension.ts, lib/definitions/extensibility.d.ts, lib/services/extensibility-service.ts, package.json, test/nativescript-cli-lib.ts, test/services/extensibility-service.ts
In case you install extension, the method automatically loads it. However calling `loadExtensions` after that loads it again, so our `$injector` fails.
In order to fix this, remove the loading from the `installExtension` method and expose `loadExtension(name)` method.
So in the future in case someone wants to load a new an extension after calling `loadExtensions`, they'll be able to use the new method.
Update ios-device-lib
Update `ios-device-lib` to 0.4.3. The new version includes a fix for long living processes where detaching iOS device causes a huge memory consuption and core dump.
=> Expose loadExtension to fix double loading of packages

lib/services/android-project-service.ts, lib/tools/node-modules/node-modules-dest-copy.ts
Flatten scoped npm plugins containing native code when copying into android/src. This is necessary to properly handle plugin flavors (F1, F2, etc.) when building for android.
```
@progress/nativescript-ui-pro -> nativescript-ui-pro
tns-core-modules -> tns-core-modules
```
branches off commit https://github.com/NativeScript/nativescript-cli/pull/2835
Edit: Includes fix:
Preparing a scoped dependency containing platforms wouldn't remove them in the prepared tns_modules location because the path built was wrong.
`assets/app/tns_modules/@scope/nativescript-with-native-dep` used to preserve its `platforms` dir
=> Flatten scoped module when copying into android/src

lib/services/itmstransporter-service.ts
The http-client was refactored and was sending the requests in chunks. Added Content-Length header to prevent the "request" module from using chunks.
=> Fix the `tns publish ios` command

lib/definitions/platform.d.ts, lib/services/ios-project-service.ts
On Windows and Linux we are unable to execute macOS specific commands. During project preparation for iOS we need to know the data from specified provison. In this scenario, pass the data from it as a non mandatory parameter.
This way the default behavior will be kept, but we'll have a way to skip the `security` command which fails on Windows.
=> Pass mobileProvisionData to prepare

lib/services/extensibility-service.ts, test/services/extensibility-service.ts
In the CLI the error is visible, but not in clients that are using it.
http://teampulse.telerik.com/view#item/345796
=> Return information about the error if loadExtension fails

lib/services/livesync/livesync-service.ts
In case one wants to stop livesync for all devices emit events for each device instead of one event for them all.
=> Emit liveSyncStopped for every device

lib/android-tools-info.ts, lib/commands/add-platform.ts, lib/commands/build.ts, lib/commands/clean-app.ts, lib/commands/debug.ts, lib/commands/deploy.ts, lib/commands/install.ts, lib/commands/platform-clean.ts, lib/commands/prepare.ts, lib/commands/remove-platform.ts, lib/commands/run.ts, lib/commands/update-platform.ts, lib/commands/update.ts, lib/services/android-project-service.ts, lib/services/livesync/debug-livesync-service.ts, lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts, package.json, test/platform-commands.ts, test/stubs.ts
Allow preparing Android project without the requirement to have ANDROID_HOME set.
The change is in the required services, which should work without ANDROID_HOME in some cases.
However the commands should not allow this, so move the validation in the commands.
Also addresses: https://github.com/NativeScript/nativescript-cli/issues/2905
=> Allow prepare for Android without ANDROID_HOME

lib/platforms-data.ts
When trying to execute `tns platform add <platform>@<version>` we fail with message: `Cannot read property 'platformProjectService' of undefined`
The reason is incorrect check when getting platforms-data where we do not expect the version. Split the incoming string by `@` and use the real platform when trying to get the platforms data.
=> Fix adding specific platform

lib/commands/update-platform.ts
`tns platform update` command should install the latest platform in case it is not installed. Currently this fails (regression from previous commit).
Fix this by calling correct validate method.
=> Fix platform update command

lib/services/ios-project-service.ts
In debug builds we add CFBundleURLSchemes that's required to restart the app on Windows.
However, in case the Info.plist of the application already has the same key, the module we are using is not merging the values correctly.
Fix this by manually merging the values.
Fixes https://github.com/NativeScript/nativescript-cli/issues/2892
=> Fix merging of CFBundleURLSchemes in debug builds

.travis.yml, CHANGELOG.md, lib/bootstrap.ts, lib/commands/debug.ts, lib/commands/post-install.ts, lib/constants.ts, lib/definitions/subscription-service.d.ts, lib/services/ios-project-service.ts, lib/services/subscription-service.ts, package.json, postinstall.js, test/commands/post-install.ts, test/post-install.ts, test/services/subscription-service.ts
`tns debug <platform>` command should start emulator in case device is not attached. The current command does not start emulator as we have passed `skipInferPlatform` - when this option is used, devicesService does not know for which platform to start the emulator.
Fix this by passing correct options.
Fixes #2916
On postinstall CLI asks the users if they want to subscribe for NativeScript's newsletter. This check has been broken in 3.0.0 because of incorrect await.
In order to add tests for this functionality, introduce a new service that handles the check and sending of information about the user's mail.
Add the following tests:
- ensure postinstall.js calls correct CLI command
- ensure the post-install-cli command calls the new service
- ensure the new service works correctly
Fixes …
=> Fix asking for user's emails on postinstall and starting of emualtor on tns debug

lib/android-tools-info.ts, package.json
Add Android 26 as verified version
Implements https://github.com/NativeScript/nativescript-cli/issues/2894
Update version to 3.2.0
=> Add Android 26 as verified version

lib/definitions/plugins.d.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, test/platform-commands.ts, test/platform-service.ts
`gradle clean` cleans the configurations made by the CLI. This PR will recreate them when running with bundle.
=> Fix android with webpack

lib/declarations.d.ts, lib/node-package-manager.ts
Npm 5 return different object after performing `npm install --dry-run`.
It contains `{
added:[].
removed:[]
updated:[] 
...
}`
Fixes [#2870](https://github.com/NativeScript/nativescript-cli/issues/2870), [#2871](https://github.com/NativeScript/nativescript-cli/issues/2871)
=> Different npm install result from npm 5.

CHANGELOG.md, lib/definitions/plugins.d.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, test/platform-commands.ts, test/platform-service.ts
Cherry-pick from master: fix android with webpack (#2925)
Update changelog
=> Cherry-pick "fix android with webpack" from master

lib/commands/debug.ts, lib/constants.ts, lib/definitions/debug.d.ts, lib/definitions/livesync.d.ts, lib/services/android-debug-service.ts, lib/services/android-project-service.ts, lib/services/debug-service-base.ts, lib/services/debug-service.ts, lib/services/init-service.ts, lib/services/ios-debug-service.ts, lib/services/ios-project-service.ts, lib/services/livesync/debug-livesync-service.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, lib/services/xcconfig-service.ts, package.json, test/ios-entitlements-service.ts, test/platform-commands.ts, test/platform-service.ts, test/plugins-service.ts, test/project-templates-service.ts, test/services/debug-service.ts, test/services/extensibility-service.ts, test/services/subscription-service.ts, test/stubs.ts, test/tools/node-modules/node-modules-dependencies-builder.ts, test/xcconfig-service.ts
Fix corresponding tests
https://github.com/telerik/mobile-cli-lib/pull/980
=> Update TS to latest release

lib/config.ts, package.json
Track all exceptions from CLI in a separate analytics project.
Also track the result of `tns error-reporting enable/disable` in the same project where the exceptions are tracked.
Update common-lib where the following changes had been applied:
Allow tracking exceptions in a different Analytics project. In case the specified CLI wants to track exceptions to a separeate project, it can do it by setting the new property in staticConfig - `ANALYTICS_EXCEPTIONS_API_KEY`.
Allow tracking the result of `tns error-reporting enable/disable` to the same project where exceptions tracking is sent.
Speed up check if current Analytics request is sent - we check on 1000ms, while in fact it takes between 150 and 400ms. So make the check on 100ms.
=> Track exceptions in separate Analytics project

lib/node-package-manager.ts, lib/npm-installation-manager.ts
* The parameter of `failWithoutHelp` should be a string, not an Error object.
* Remove console.error().
* Move check for tgz.
If the path to the tgz is wrong we will try to get a latest compatible version, which will exec `npm view dist-tag --json`. However, npm view over tgz file has different behavior with npm 3, 4, and 5.
npm 3 will return a parse error.
npm 4 return 500 internal server error.
npm 5 try to find package.json in the current working directory and return information about this package.
=> Error handling fixes.

CHANGELOG.md, lib/node-package-manager.ts
In case some plugins (like `nativescript-plugin-firebase`) try to prompt the user on postinstall, users are unable to answer the question when `tns plugin add <name>` is used.
The reason is that the stdin of current process is not passed to the stdin of the `npm install` process and the user has no way to input the result.
Fix this by using "inherit" of current stdio when the console is interactive.
Fixes #2521 again.
Fixes https://github.com/NativeScript/nativescript-cli/issues/2950
=> Fix plugins prompts on postinstall

Gruntfile.js, package.json, test/stubs.ts
Some rules in our tslint.json require passing `--type-check` flag to `tslint` executable.
However grunt-tslint does not support it. So remove the `grunt-tslint` and spawn the `tslint` via npm script.
Add the new `tslint` script, so now the project can be linted by calling:
* grunt lint
* grunt tslint:build /for backwards compatibility/
* npm run tslint
Fix the errors that are received after passing `--type-check` flag.
Disable all linter errors for all automatically generated files (for messages).
PR in mobile-cli-lib: https://github.com/telerik/mobile-cli-lib/pull/984
=> Replace grunt-tslint with direct calling to tslint

lib/tools/node-modules/node-modules-dest-copy.ts
If the scope dependency is not at the root of `node_modules` it will be deleted. We need to traverse the scope dependency directory and append all subdirectory to its name. Then we will get the real name of the dependency like is written in the `package.json` and we can use `productionDependencies.hasOwnProperty(dir)`
=> Fix remove of non-production dependencies.

lib/services/ios-project-service.ts, package.json
Remove `updateCFBundleURLSchemes`  method since we fixed session.patch logic for merging  CFBundleURLTypes.
Fix [#2936](https://github.com/NativeScript/nativescript-cli/issues/2936)
* Note merge after new version of plist-merge-patch is released. Until this happened npm install will fail.
=> Fix CFBundleURLTypes merging.

lib/node-package-manager.ts
If there are not satisfied peer dependencies the result of the `npm install --json --dry-run` will contain information about this peer dependency. 
We take the first property from the object and assuming that this is the newly installed dependency, but in this case, it is not.
Fix [#2965](https://github.com/NativeScript/nativescript-cli/issues/2965)
=> Fix unmet peer dependency break adding of platform.

lib/services/livesync/livesync-service.ts
When CLI is used as a library, the LiveSync method can be called consecutive times for the same projects, but with different device identifiers. For example we may want to start LiveSync on devices with identifiers [ A, B, C ] and later we would like to add devices with identifiers [ D, E ].
In the second call, CLI should detect that LiveSync is already running and execute initial sync only for newly added devices. However the current check for unique device identifiers is not correct and it always returns empty array as we first add the new devices to the old ones and then compare the new array with the already modified old array of devices.
Check the difference before adding new device identifiers to the old ones.
=> Fix LiveSync calls cosecutive times

lib/services/ios-provision-service.ts
`tns prepare ios --provision` command which is supposed to list and filter provisions for the connected devices should not start ios simulator.
[#2889](https://github.com/NativeScript/nativescript-cli/issues/2889)
=> Remove emulator launch from ios-provision-service.

lib/definitions/livesync.d.ts, lib/services/livesync/livesync-service.ts
In case we are in the action chain lambda and some error occurs we don't need to wait for the same action in `stopLiveSync` method.
[#2975](https://github.com/NativeScript/nativescript-cli/issues/2975)
=> Fix recursive calling of actions.

lib/services/livesync/livesync-service.ts
`liveSyncStarted` event is currently raised before starting initial LiveSync operation. However this makes sense if the name was `liveSyncStarting`.
So move the event at the end of the initialSync logic - this way it will be raised for each device when the LiveSync is really started.
=> Emit `liveSyncStarted` when the application is really livesynced

lib/services/debug-service.ts, test/services/debug-service.ts
When CLI is used as a library, the method for debug returns incorrect result - previously the return type of the method we are calling was `string[]`, we've changed it to `string` but forgot to remove the `_.first(result)`.
So now the debug returns incorrect URL. Remove the `_.first` and return the result directly.
=> Fix debug when using CLI as library

lib/bootstrap.ts, lib/commands/debug.ts, lib/commands/run.ts, lib/constants.ts, lib/definitions/livesync.d.ts, lib/definitions/platform.d.ts, lib/definitions/plugins.d.ts, lib/definitions/project-changes.d.ts, lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/livesync/livesync-command-helper.ts, lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, lib/services/project-changes-service.ts, lib/tools/node-modules/node-modules-builder.ts, lib/tools/node-modules/node-modules-dest-copy.ts, test/debug.ts, test/platform-service.ts, test/plugin-prepare.ts, test/project-changes-service.ts, test/stubs.ts
* Introduce new parameter prepareNative to indicate that native code preparation is explicitly required. 
* Cache additional data in .nsprepareinfo file:   
* nativePlatformStatus - indicates whether native platform should be added, prepared or there's no need to do so;   
* projectFileHash - saves package.json file's contents hash for the current platform. We use this for better heuristics for checking whether package.json is changed. 
* Re-factoring i.e. extract common code to methods
Fixes https://github.com/NativeScript/nativescript-cli/issues/2986
=>  Separate preparation of JS from native code

npm-shrinkwrap.json, package.json
In case during `tns run ios` the application is uninstalled manually and after that a change is applied, CLI should install the app and continue with livesync operation. However it fails with EPIPE. The problem was in ios-device-lib - it is fixed in 0.4.8 version.
https://github.com/NativeScript/nativescript-cli/issues/2988
=> Fix EPIPE during livesync on iOS

lib/services/livesync/ios-device-livesync-service.ts
During fast sync we shouldn't clear all listeners handling `error` event. If we do then any error raised is treated as unhandled and leads to a crash.
=> Fix error handling during fast sync

lib/definitions/livesync.d.ts, lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts
Each device can use different build types - cloud or local. So the `skipNativePrepare` option should be passed per each device, not for the whole livesync operation.
=> Move skipNativePrepare to deviceDescriptors

lib/device-sockets/ios/socket-proxy-factory.ts
On Windows closing a socket on the non-nodejs side leads to errors on the nodejs side.
Add error handling for these types of errors.
In addition, only exit the process whenever `--watch` is not set if the app is killed during debugging.
=> Add error handling for debug sockets

lib/constants.ts, lib/services/ios-debug-service.ts, lib/services/livesync/ios-device-livesync-service.ts
Timeout is in seconds so 9000 seems a bit overdue.
=> Set correct timeout on LiveSync

docs/man_pages/project/testing/run.md, lib/commands/debug.ts, lib/commands/run.ts, lib/definitions/livesync.d.ts, lib/services/livesync/livesync-command-helper.ts, test/debug.ts
Last part of implementing https://github.com/NativeScript/nativescript-cli/issues/2470
=> Fix run without platform on ios.

lib/services/project-changes-service.ts
In case you have built your application and you add a new npm package as dependency, the LiveSync will always rebuild the app, no matter of the change applied afterwards. The problem is in our project-changes-service that persists shasum of the package.json. However it is never reset, so we always have the hashed shasum of the package.json when the applcation has been build for the first time. Fix this by setting the correct value for projectFileHash - this way the checks are correct and applying change in .js (.xml, .css) files will not trigger rebuild of app.
=> Fix rebuilding application every time when a change is applied

PublicAPI.md, lib/definitions/livesync.d.ts, lib/services/livesync/ios-livesync-service.ts, lib/services/livesync/livesync-service.ts, lib/services/livesync/platform-livesync-service-base.ts
Whenever application is reinstalled on iOS device, we have to execute full sync operation due to iOS runtime requirements.
However, in case the application is uninstalled manually during LiveSync, CLI will reinstall it, but the code that checks if a full sync is required will return false. The problem is that the `isRebuilt` property (renamed to `isReinstalled` now) really checks if the application has been rebuild during current check and expectedly this returns false.
In order to fix this, change the return type of `ensureLatestAppPackageIsInstalledOnDevice`, so it will give the required information if a full sync should be executed.
Also improve the information that we emit in liveSyncExecuted event:
* add new property - `isFullSync` - it can be used to indicate the current operation
* …
=> Fix LiveSync on iOS when app is uninstalled manually

lib/commands/test.ts, lib/definitions/platform.d.ts, lib/definitions/plugins.d.ts, lib/definitions/project.d.ts, lib/providers/project-files-provider.ts, lib/services/platform-service.ts, lib/services/plugins-service.ts, lib/services/test-execution-service.ts, lib/tools/node-modules/node-modules-builder.ts, lib/tools/node-modules/node-modules-dest-copy.ts, test/plugin-prepare.ts, test/plugins-service.ts, test/project-files-provider.ts
Implement processing configuration specific files on build, run and debug. There was some initial logic to process debug configuration by default, but when configuration is explicitly passed we did not respect it.  For example:
`tns build android --release`
Now if the passed argument is valid configuration we process specific files, taking the parameter into consideration.
https://github.com/NativeScript/nativescript-cli/issues/2934
common lib PR: https://github.com/telerik/mobile-cli-lib/pull/986
=> Respect configuration when preparing project files

lib/commands/test.ts
Options are passed as function argument and should not be called with this.
=> "This" is not the correct property invoker in current context

lib/services/platform-service.ts
Some plugins require `platforms/<platform>` to exist on their `before-prepare` hooks. Make sure the directory actually exists and let the plugins handle the rest.
Merge after https://github.com/telerik/mobile-cli-lib/pull/994
Ping @rosen-vladimirov @nadyaA @TsvetanMilanov
=> Ensure platforms directory exists prior to preparing

lib/definitions/livesync.d.ts, lib/services/livesync/livesync-service.ts
In case `stopLiveSync` is called during livesync, we should await the current action and emit `liveSyncStopped` event. At the moment, we have the following behavior:
1. In case stopLiveSync is called with deviceIdentifiers, we emit `liveSyncStopped` immediately for all of them. However there may be pending actions, for example build + deploy for current device. We cannot stop the actions, so you receive `liveSyncStopped` and application is installed/updated on device after that.
Fix this by persisting the current action and await it before emitting `liveSyncStopped` event.
2. In case we are currently rebuilding the application and some changes are applied during build, we'll update the `actionsChain`. At this point we'll have several actions in the chain. In case stopLiveSync method is …
=> Emit liveSyncStopped event when LiveSync operation is really stopped

lib/commands/debug.ts, lib/definitions/livesync.d.ts, lib/services/livesync/livesync-command-helper.ts
* minor cli refactoring (keeping method API consistent between run and debug)
* method comments for a better world
=> move device discovery to debug command as it is done for run command

lib/services/livesync/livesync-service.ts
Whenever stopping on all devices we should emit `liveSyncStopped` for each device.
=> Emit liveSyncStopped properly when stopping on all devices

lib/services/livesync/android-device-livesync-service.ts, lib/services/livesync/platform-livesync-service-base.ts
_problem_
Related issue: https://github.com/NativeScript/nativescript-cli/issues/2657
Possibly related to https://github.com/NativeScript/nativescript-cli/issues/2485
* emulators with API level >= 23 the installed application doesn't have the permissions to write in `/data/local/tmp/<application_name>/` and disrupts livesync in some scenarios
* on devices the problem with permissions is even worse and even on API level 22, the application still doesn't have permissions to write in `/data/local/tmp/<application_name>/`
_solution_
The CLI will take care of notifying the runtime and deleting all files after livesync is done, regardless of whether the application needs to be restarted or not.
Edit: tested on iOS and Android: new/delete/modify work, but renaming only works on android, I'll fix …
=> livesync deletes files and cleans temp folder afterwards

lib/services/ios-project-service.ts
User can change the application identifier inside his Info.plist file by setting CFBundleIdentifier, but our plist merge logic will overwrite the identifier with the one inside package.json.
Fixes https://github.com/NativeScript/nativescript-cli/issues/2825
https://github.com/NativeScript/android-runtime/pull/810
Steps to tests.
1. tns create testApp
2. tns platform add ios
3. Edit CFBundleIdentifier iniside app/AppResources/iOS/Info.plist
4. tns build ios
=> Add check for application identifier ios

lib/services/ios-entitlements-service.ts, test/ios-entitlements-service.ts
In case during `tns run ios` the application is uninstalled manually and after that a change is applied, CLI should install the app and continue with livesync operation. However it fails with EPIPE. The problem was in ios-device-lib - it is fixed in 0.4.8 version.
https://github.com/NativeScript/nativescript-cli/issues/2946
=> Fix tns run ios on case sensitive file system

lib/commands/debug.ts
`tns debug <platform>` will check all available devices and will prompt the user to select device for debugging. In case the terminal is not interactive, it will select the emulator/device with highest API level.
However, adding `--start` causes failure as the described logic is not used. So ensure we have this behavior even when `--start` is used.
https://github.com/NativeScript/nativescript-cli/issues/3021
=> Fix `tns debug <platform> --start` inconsistent behavior

lib/declarations.d.ts, lib/services/doctor-service.ts, lib/services/versions-service.ts
Doctor crashes because of invalid environment.
Related issue: NativeScript/nativescript-cli#2810
_problem_
* doctor crashes when `xcodebuild` can't be found (when xCode build tools aren't installed).
* provide a more detailed message for: "Your components are up to date"
_solution_
* don't verify xCode project if xcodeVersion and cocoaPods aren't verified
* list the components that are up to date for the user
=> doctor doesn't crash on missing xcode tools

lib/services/ios-project-service.ts, npm-shrinkwrap.json, package.json
Fixes #3020 and related issues by reading the `embedded.mobileprovision` from the built `.app`, detecting the type of the provision that is used and then sending the correct export method when exporting the `.ipa`
=> Fix IPA export

lib/services/livesync/livesync-command-helper.ts
In case there are attached, but not trusted devices, `tns run <platform>` command prints error that it is unable to find devices and cannot start emulator when platform is not specified.
But the platform has been specified, so improve the error message in such cases.
=> Fix message when unable to find devices for LiveSync

lib/npm-installation-manager.ts, test/npm-installation-manager.ts
This has been fixed in CLI 2.5.5, but it never get into our master or release branch:
Not merged PR: https://github.com/NativeScript/nativescript-cli/pull/2800
Merged PR in 2.5.5: https://github.com/NativeScript/nativescript-cli/pull/2793
I've just cherry-picked the commit from PR 2800.
The problem arises when we have CLI 3.1.3 for example, but a template has versions 3.1.0, 3.1.1, 3.2.0, 3.2.1...
In this case CLI should install template 3.1.1, but instead it uses latest (3.2.1). The problem is that we have been using semver comparison based on CLI's version (~3.1.3), while in fact we should get only major and minor numbers from it (~3.1.0)
=> Improve get latest compatible version to search for major.minor.*x* versions

npm-shrinkwrap.json, package.json
This will fix issue with starting iOS Simulator when a fake device id is passed. Instead we will fail with correct error from now on.
As we are now using shrinkwrap file, the version of ios-sim-portable is always strict, so set it to strict in package.json as well.
Related to: https://github.com/NativeScript/nativescript-cli/issues/2728
Merge after https://github.com/telerik/mobile-cli-lib/pull/1000
=> Update ios-sim-portable to 3.1.0

npm-shrinkwrap.json, package.json
In case when there's no device attached and no simulator running, `tns run ios` should start default iOS Simulator. However, this fails. The problem is resolved in `ios-sim-portable` 3.1.1.
Bump the version, so the issue will be resolved.
=> Fix tns run ios when no simulator is running

lib/services/project-changes-service.ts, test/project-changes-service.ts
_problem_
On Mac, renaming isn't caught as a change by the incremental prepare.
_effect_
When livesync is ran and a file in the `app/` folder is renamed, the change is not properly applied in the application.
_solution_
Add check for access time so renamed files are prepared.
_Edit_: Checking folder access times before traversing files in it can save us a lot of time checking files.
=> make livesync work with renamed files and folders

setup/native-script.ps1
- update the commands to use the new android executable
- fix the path to be set for ANDROID_HOME
=> Fix setup script for Windows #3048

lib/definitions/livesync.d.ts, lib/definitions/platform.d.ts, lib/definitions/project.d.ts, lib/services/ios-project-service.ts, lib/services/livesync/livesync-command-helper.ts, lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts, test/platform-service.ts
Passing `--provision` to `tns run <ios>` is not respected. Fix this by including additional option in the deviceDescriptors. This allows us to pass different provisions for each device, however in CLI's commands we'll set one provision for all devices.
Also fix passing `--teamId` option - during previous refactoring we've broken the code for it and it has not been respected. Remove the unused alias `teamIdentifier` and use `teamId` in all cases.
Rename `IAddPlatformCoreOptions` to `IPlatformOptions` as it is better name of the purpose of the interface.
=> Fix passing provision to `tns run ios` and passsing `--teamId`

docs/man_pages/project/testing/build-ios.md
Adding info how to use --provision in build command.
=> Documented `--provision` option in build-ios.md

PublicAPI.md, lib/definitions/debug.d.ts, lib/services/android-debug-service.ts, lib/services/debug-service-base.ts, lib/services/ios-debug-service.ts, test/services/android-debug-service.ts, test/services/ios-debug-service.ts
URLs starting with `chrome-devtools://devtools/` cannot be opened in chrome with code.
However, we can open the urls in https://chrome-devtools-frontend.appspot.com/, so add new option in Public API that allows using the remote version.
Keep the current default behavior, i.e. for Android we are using the `bundled` DevTools, for iOS we are using a commit pointing to Chrome 55.
In case both `useBundledDevTools` and `useHttpUrl` are passed, the value of `useBundledDevTools` is disregarded.
Add unit tests for all of the cases.
Currently CLI uses specific SHA of dev tools, that corresponds to Chrome 55. However, we may need different version for Android or iOS, so add new option. This will also allow specifying it from public API, so external calls may pass the commit SHA.
=> Add option to use chrome-devtools fronted from appspot

PublicAPI.md, lib/definitions/livesync.d.ts, lib/services/livesync/livesync-service.ts, test/services/livesync-service.ts, test/stubs.ts
Currently stopLiveSync method does not emit correct events in some cases. For example, when there's only one attached device and its identifier is passed to `stopLiveSync` method, we do not emit `liveSyncStopped` event. Fix the code and add unit tests to assure `liveSyncStopped` event is raised correctly.
Add new public method `getLiveSyncDeviceDescriptors` to `liveSyncService` - its purpose is to get information for current LiveSync operation.
=> Fix stopLiveSync method

lib/services/platform-service.ts
When we prepare the platform for cloud build we skip the native prepare.
After this partial prepare, the platform directory contains only .js files.
In order to make a local build we should add the native part of the platform
which fails with `ENOTEMPTY: directory not empty, rename`.
=> Fix native platform add after cloud build.

lib/services/livesync/platform-livesync-service-base.ts
Whenever two platform-specific files from `App_Resources` which are of different platforms need to be synced, one of them gets filtered out because it is for the wrong platform. However, instead of it being filtered out its path remains `null`. This causes a null-reference exception when trying to define whether the file should be synced or not.
Ping @TsvetanMilanov @rosen-vladimirov 
Fix for https://github.com/NativeScript/nativescript-cli/issues/3073
Merge after https://github.com/telerik/mobile-cli-lib/pull/1003
=> Fix simultaneous livesync error

lib/tools/node-modules/node-modules-dest-copy.ts
In case a plugin depends on a scoped package, for example `@angular/core`, trying to use the plugin from local path with npm 5 will fail.
The recommended approach is to declare the scoped package (`@angular/core`) as a devDependency of the plugin. After that, declare both the plugin and the scoped package as dependencies of your project. In case the plugin is installed from local directory, npm 5 creates symlink in node_modules. This means that all files inside `<plugins dir>/node_modules` will be visible for CLI, including the dev dependencies. During project preparation CLI copies `node_modules` from the project to `<project dir>/platforms/<platform>...` directory. We have a specific logic to process only dependencies of each package, i.e. we should remove `@angular/core` from the …
=> Fix prepare of scoped packages

lib/services/ios-log-filter.ts, test/services/ios-log-filter.ts
Our regex doesn't match `console.log` from app deployed on a iOS simulator. The reason that we have logs from this kind of application is that the cli set PID to the installed application. However, when the cli is required, the app is installed with `justlaunch` options the PID is not set which cause missing logging.
Merge after https://github.com/telerik/mobile-cli-lib/pull/1005 and update sha
=> Improve iOS log filter regex.

setup/native-script.rb
=> Install arm image when HAXM is not available

docs/man_pages/project/testing/build-ios.md, lib/commands/appstore-upload.ts, lib/commands/build.ts, lib/commands/debug.ts, lib/commands/deploy.ts, lib/commands/prepare.ts, lib/commands/run.ts, lib/definitions/platform.d.ts, lib/definitions/project-changes.d.ts, lib/definitions/project.d.ts, lib/options.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/ios-provision-service.ts, lib/services/local-build-service.ts, lib/services/platform-service.ts, lib/services/project-changes-service.ts, test/ios-project-service.ts, test/platform-commands.ts, test/platform-service.ts, test/project-changes-service.ts, test/stubs.ts
Depends on:
https://github.com/NativeScript/nativescript-cli/pull/3069
This PR will:
- Update the export options plist and list the provisioning profile so Xcode9 can export when working with manual signing style and the --provision switch.
- Provide --quiet to xcodebuild and -quiet to the gradle tools so they log only errors by default. The command line args with which these commands are called will be printed in place of the verbose output. You can switch to --log trace for full output.
- Provide -allowProvisioningUpdates to xcodebuild when working with Xcode version > 9.0 so when passing team, xcodebuild may generate automatically managed provisioning profiles for you  
(THIS ONE IS MY FAVOURITE!!!)
- --teamId now behaves like --provision, it will require prepare if the last time other …
=> Fix xcode9 provision, provide --quiet by default, enable -allowProvisioningUpdates

test/ios-project-service.ts
Due to recent changes in `ios-project-service`, some unit tests cannot work on Windows and Linux, so ignore them in case the OS is not macOS.
=> Fix unit-tests on Windows and Linux

docs/man_pages/general/proxy-set.md
Update the proxy set command's `--help` manual to give directions on how to set up the proxy configurations for `npm` and `Gradle`.
Related to https://github.com/NativeScript/nativescript-cli/issues/2816
=> Update proxy-set manual

PublicAPI.md, lib/commands/debug.ts, lib/constants.ts, lib/declarations.d.ts, lib/definitions/debug.d.ts, lib/definitions/livesync.d.ts, lib/services/debug-service.ts, lib/services/livesync/livesync-service.ts, test/services/debug-service.ts
Includes but is not limited to:
* `enableDebugging` - each promise is now resolved with an object
* added docs for `debuggerAttached` event
* added `debuggerDetached` event and docs for it
Ping @rosen-vladimirov @TsvetanMilanov @nadyaA
=> Debug improvements

lib/services/debug-service.ts
Whenever iOS inspector is used in favor of chrome, `null` is passed to `getDebugInformation` which causes `url.parse` to fail.
Add a `null` check in order to safeguard the method.
Ping @TsvetanMilanov @rosen-vladimirov
=> Only return debugInfo if url is passed

PublicAPI.md, lib/declarations.d.ts, lib/definitions/debug.d.ts, lib/services/debug-service.ts, test/services/debug-service.ts
`debuggerAttached` event should emit full information required for debugging. However, the deviceIdentifier is missing, so add it.
Update PublicAPI.md according to latest changes.
=> Emit deviceIdentifier in debuggerAttached event

lib/services/livesync/livesync-service.ts
Fixes:
1. When debugging is enabled no fast sync should be performed - we should always full sync
1. We shouldn't swallow the exception from the first time when trying to attach a debugger the second time
=> Minor LiveSync+Debug fixes

lib/services/ios-debug-service.ts, lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts, npm-shrinkwrap.json, package.json
In case we are unable to start application on iOS device just before attaching a debugger, CLI will raise unhandled rejection. The problem is that we want to start two actions in parallel - start of application and attaching a debugger. We do not await the start application and when an error is raised in it, Unhandled Rejection is raised. In order to prevent this, use Promise.all - this way in case any of the operations fail, we'll receive it as error in the same method. 
In LiveSync service we attach to deviceLost event in order to stop LiveSync operation in case device is detached. However we are attaching it on every change, so at some point CLI prints warning: `Warning: Possible EventEmitter memory leak detected. 11 deviceLost listeners added. Use emitter.setMaxListeners() to increase …
=> Debug fixes when CLI is used as a library

lib/services/analytics/analytics-service.ts, lib/services/analytics/eqatec-analytics-provider.ts, lib/services/livesync/livesync-service.ts
Fix tracking of LiveSync action - it has been always tracked even when Build is required, so the workflow of user seemed like:
- Build
- LiveSync
- Deploy
- LiveSync
Now it will be:
- Build
- Deploy
- LiveSync
Also update common lib, where the following changes are applied:
Fix tracking of Node.js version in Eqatec and user sessions count
Whenever a new eqatec monitor is started, we should track the version of Node.js. However, the current code was calling `trackFeatureCore` which always tracks to the Eqatec Analytics projects used for Feature trackings.
This way, when any eqatec monitor is started, we've been sending information for Node.js version to the feature tracking projects. Fix this by passing the api key of the project in which we want to track the information.
Also fix the user …
=> Fix tracking of Node.js version, LiveSync action and user sessions count

lib/definitions/livesync.d.ts, lib/services/livesync/livesync-command-helper.ts, lib/services/livesync/livesync-service.ts, lib/services/test-execution-service.ts
If there are attached multiple devices to be livesynced and only one to be
debugged, the debug options should be applied only to this one device.
Having them in live sync data is incorrect.
=> Assign debug options to device not to whole live sync data

lib/bootstrap.ts, lib/commands/build.ts, lib/commands/deploy.ts, lib/commands/run.ts, lib/constants.ts, lib/definitions/project.d.ts, lib/nativescript-cli-lib-bootstrap.ts, lib/options.ts, lib/services/local-build-service.ts
* Introduce `ILocalBuildService` so that it can be reused
* Register `localBuildService` so that other services can use it
* Fail in `localBuildService` if building for `android` in `release` but not all of the `--key*` flags have been passed.
Merge after https://github.com/telerik/mobile-cli-lib/pull/1014
=> Introduce interface for localBuildService

lib/services/livesync/livesync-service.ts, test/services/livesync-service.ts
When LiveSync operation is started we set `usbLiveSyncService.isInitialized` to true. This variable is used in several `before-prepare` hooks.
For example `nativescript-dev-typescript` has the following logic:
- When before-prepare hook is executed it checks if the `usbLiveSyncService.isInitialized` property is set to true. In this case it does nothing. The idea is that when LiveSync watch process is started, the plugin has started `tsc --watch` process, so there's no need to do anything on `before-prepare`.
However, in a long living process, where the project may be changed, whenever we stop LiveSync process, we must set usbLiveSyncService to false. In case we do not do it, the property remains true and the before-prepare hook of the other project does nothing and the project is not …
=> Fix execution of before-prepare hooks in a long living process

lib/services/android-project-service.ts, lib/tools/node-modules/node-modules-dependencies-builder.ts, test/debug.ts
**Problem**:
The CLI will execute gradle clean when a plugin with a native counterpart is added/removed, that will force removal of all build artifacts, including the infamous `configurations` directory, where the CLI copies all plugin `include.gradle` scripts. The user may call `gradle clean` on their own however, that will remove `configurations` and the CLI will not regenerate it on a consecutive build, because it would not have detected a change in the plugins in order to copy the gradle scripts over. As a result builds that follow will not include any of the android plugins.
**Proposed Solution**:
Hand over the control over android plugins to the Gradle script, it will generate its own configurations and copy files where necessary as it sees fit. NativeScript CLI's only …
=> Stop copying android plugin code, stop writing configurations dir

lib/services/android-project-service.ts
The new logical branch in the android preparation step of the CLI should be used when the runtime version is detected to be `3.3.0` or greater. 
However the current version check of `is greater or equal than 3.3.0` does not satisfy `prerelease` versions in the form of `3.3.0-2017...`. 
In order to allow builds from the master branch of the `tns-android` package to be used, the validation of major + minor version should be sufficient.
Follow up of the previous PR https://github.com/NativeScript/nativescript-cli/pull/3032
=> Normalize platform version when determining android prepare routine

lib/device-path-provider.ts, npm-shrinkwrap.json, package.json
In some cases `tns_modules` dir may appear in project's app dir. The issue is caused by sending Ctrl + C while `ios-sim-portable` is executing `xcrun simctl` command.
In this case, it returns empty string for applicationPath instead of breaking the CLI process. Add new check if the projectRoot on device is not empty string and update ios-sim-portable.
https://github.com/NativeScript/nativescript-cli/issues/3016
=> Fix tns_modules added to app dir

lib/services/ios-project-service.ts
It tries to predict a linker error and stop earlier, but there are cases where it fails to do so correctly.
We now start building without any preliminary checks on libraries and let it fail with whatever error it does.
fixes #2967
=> Remove iOS static library verification

lib/bootstrap.ts, lib/commands/appstore-upload.ts, lib/commands/build.ts, lib/commands/deploy.ts, lib/commands/prepare.ts, lib/declarations.d.ts, lib/definitions/livesync.d.ts, lib/definitions/platform.d.ts, lib/options.ts, lib/services/analytics/analytics-service.ts, lib/services/livesync/livesync-command-helper.ts, lib/services/livesync/livesync-service.ts, lib/services/local-build-service.ts, lib/services/platform-service.ts, lib/services/prepare-platform-js-service.ts, lib/services/prepare-platform-native-service.ts, lib/services/prepare-platform-service.ts, lib/services/project-changes-service.ts, lib/services/test-execution-service.ts, lib/tools/node-modules/node-modules-builder.ts, test/npm-support.ts, test/platform-commands.ts, test/platform-service.ts, test/stubs.ts, test/tns-appstore-upload.ts
Create interfaces to separate the prepare functionality in js and native parts.
Ensure better isolation and encapsulation of project preparation process.
Merge after https://github.com/telerik/mobile-cli-lib/pull/1018
https://github.com/NativeScript/nativescript-cli/issues/2968
=> Separate native and JS prepare code

lib/nativescript-cli-lib-bootstrap.ts
In case CLI is used as a library, the device logs are no longer captured after application is restarted. The problem is the newly added logic for Android devices that stops the logcat process when CLI calls `stopApplication` and starts it when `startApplication` is called.
However, in `startApplication` there's a check if `$options.justlaunch` is false - only then the device log operation is started again.
When CLI is used as a library, we have hardcoded the `justlaunch` option to true in order to prevent duplicate logs for iOS devices. So the solution to resolve Android logs issues is to remove the setting of justlaunch option.
However, this caused the duplicate logs issue for iOS devices. Investigating it further, it turned out to be a memory leak when iOS device is detached. It's fixed …
=> Fix missing console.logs on Android when CLI is used as library

lib/commands/generate-help.ts, lib/commands/post-install.ts, lib/config.ts, test/commands/post-install.ts, test/platform-commands.ts, test/platform-service.ts, test/plugins-service.ts, test/stubs.ts
In case any command fails, we execute help command in order to show the help content. This leads to multiple trackings, i.e. - user executes only one command, but in Analytics we see two commands.
Instead of executing help command, introduce new method in htmlHelpService, that prints the help to the terminal and call it instead. Use the same method in the help command itself.
Rename htmlHelpService to helpService - it has been incorrectly named from the beginning.
Remove `helpTextPath` from staticConfig interface - this property is not used for more than 2 years.
Introduce tests for `helpService` - get the tests from AppBuilder CLI.
Submodule PR: https://github.com/telerik/mobile-cli-lib/pull/1021
=> Do not track help command when other command fails

lib/services/extensibility-service.ts, test/services/extensibility-service.ts
Installing and loading extensions is based on the `--profileDir` value. In case a relative path is passed, the extensions cannot be loaded as the resolve is not correct.
Resolve the full path, so the loading will work correctly.
=> Fix passing relative path for profileDir when extensions are used

lib/services/analytics/analytics-service.ts, test/services/analytics/analytics-service.ts, test/stubs.ts
In case we are unable to start the Analytics Broker process, CLI will fail. But analytics errors should not break user's workflow, so catch the error and ensure the actions will continue. 
Add tests to verify the behavior.
Also limit the waiting for broker to start to 10 seconds.
=> Do not break CLI process in case analytics fail

PublicAPI.md, lib/commands/post-install.ts, lib/config.ts, lib/npm-installation-manager.ts, lib/options.ts, lib/services/extensibility-service.ts, lib/services/user-settings-service.ts, test/android-project-properties-manager.ts, test/commands/post-install.ts, test/debug.ts, test/ios-project-service.ts, test/npm-installation-manager.ts, test/npm-support.ts, test/platform-commands.ts, test/platform-service.ts, test/plugin-variables-service.ts, test/plugins-service.ts, test/project-service.ts, test/services/extensibility-service.ts
Currently CLI's configuration directory is used from `$options.profileDir`. When user passes `--profileDir <path>`, the `$options.profileDir` value is populated.
In case user does not pass anything, a default value is set. All services that require configuration directory use the `$options.profileDir`. However, this causes several issues:
- `$options` is intended for use only when CLI is used as a standalone command line. In case you are using it as a library, the `$options` object will not be populated.
- Unable to test local installations of extensions when CLI is used as library - there's no way to set the custom profileDir when using CLI as a library. So the extensions are always loaded from the default location.
In order to resolve these issues, move the logic for profileDir in …
=> Use profileDir from settingsService

lib/commands/test.ts, lib/services/test-execution-service.ts
In case you try using npm scripts that come with `nativescript-dev-webpack` and you also have `nativescript-unit-test-runner` in your project, the scripts hang. The problem is that `nativescript-unit-test-runner` has a hook that resolves `testExecutionService`. In its constructor it sets that analytics broker should not be disposed. However, this is incorrect - it should not be disposed only in case we execute tests with livesync enabled. In order to fix this, move the logic in the commands. This way the hook will not change the disposing of the analytics broker, so once CLI process finishes, analytics broker process will be disconnected and CLI's process will die gracefully.
Fixes: https://github.com/NativeScript/nativescript-cli/issues/3164
Also update submodule, where the following …
=> Fix hanging commands when webpack and unit tests are used

lib/node-package-manager.ts
Solves Issue https://github.com/NativeScript/nativescript-cli/issues/3217
This pull request changes the implementation to search for the correct object by name. It does no longer depend on the position and should be more reliable especially as the `--json` flag is experimental as described in the npm documentation: https://docs.npmjs.com/misc/config#json
As described in the comment of the current implementation of `parseNpmInstallResults` we just use the first object of the `updated` array.
https://github.com/NativeScript/nativescript-cli/blob/e181f034264d82f40d3cbbfbdfd6599f5b2064c7/lib/node-package-manager.ts#L158-L160
But when I execute the following command:
```
npm install tns-ios --json --dry-run
```
`tns-ios` is not the first element in the `updated` array. The output looks …
=> parse npm install results correctly 

CHANGELOG.md, lib/services/ios-project-service.ts
Some commits exist only in release branch - get them in master
=> Cherry pick commits from release branch

test/nativescript-cli-lib.ts
Expose API for getting installed applications for a specific device when CLI is required as library. Add the new method to `devicesService`.
Add required tests for exposing methods from `devicesService`.
=> Expose API for getting installed applications

README.md
Added a single line to document this small and simple but important feature `tns --help` to load HELP info in the console rather than launching in a browser or text editor window.
Read a few issues where users have asked about preventing HELP loading in the browser (including a `-nobrowser` request) or text editor (when users computer has set a text editor as default app to open HTML files) and found the `--help` command hidden in a response from @Fatme, so I thought it would be great to add that little command into the CLI command docs :)
=> README.md - CLI Command --help to load info in the console

lib/services/project-changes-service.ts
When checking if files are changed we should ignore all files ending in `.(something)` as these files are hidden on mac and usually shouldn't be modified anyway.
This will make livesync work a bit faster when `--sync-all-files` flag is used, because there are a number of `.(something)` directories inside.
=> ignore .(anything) files when checking for changes

docs/man_pages/project/testing/debug-ios.md, lib/declarations.d.ts, lib/definitions/debug.d.ts, lib/services/ios-debug-service.ts
Changes in this PR:
- add the `--inspector` flag - a counterpart to `--chrome` which will open the Safari Web Inspector to debug the iOS application with
- add a message when using the `--chrome` flag that it is a default now
- update the `tns debug ios help` to reflect the changes in `--chrome` and the addition of `--inspector`
Addresses https://github.com/NativeScript/nativescript-cli/issues/3171
=> Make debug-ios default to Chrome DevTools

docs/man_pages/project/testing/build-android.md, docs/man_pages/project/testing/build-ios.md, docs/man_pages/project/testing/run-android.md, docs/man_pages/project/testing/run-ios.md, lib/commands/appstore-upload.ts, lib/commands/base-bundler.ts, lib/commands/build.ts, lib/commands/clean-app.ts, lib/commands/deploy.ts, lib/commands/prepare.ts, lib/commands/run.ts, lib/declarations.d.ts, lib/options.ts, lib/services/app-files-updater.ts, lib/services/livesync/livesync-command-helper.ts, lib/services/test-execution-service.ts, test/npm-support.ts
If `--bundle` is passed a bundling plugin needs to be present to process the option, else undefined behavior will follow, especially if one makes use of plugins like `nativescript-dev-typescript` that have logic regarding `--bundle` option.
Part of https://github.com/NativeScript/NativeScript/issues/5129
Ping @PanayotCankov @dtopuzov @MartoYankov
=> Fail if --bundle is specified but no bundler

lib/commands/base-bundler.ts
In case the project does not have dependencies or dev-dependencies CLI should fail with correct message when `--bundle` is passed.
Ping @rosen-vladimirov @KristianDD
=> Safeguard bundle option check

lib/declarations.d.ts, lib/services/analytics/google-analytics-provider.ts, npm-shrinkwrap.json, package.json
The `proxy-lib` package provides required methods for setting and getting proxy. Its implementation is more secure when stroing credentials, so switch to it instead of current implementation.
Remove the credentials-manager from CLI as it is no longer needed.
Remove the CredentialsManager.exe as well and its source code.
Fix the error `Cannot read property ExceptionMessage of null` when wokring behind proxy - add correct null checks.
Fix tracking to google analytics behind proxy - pass the proxy URL to Universal Analytics module.
=> Use proxy-lib package when working behind proxy

npm-shrinkwrap.json, package.json
Remove moment.js as dependency as it is not used in the code.
Update shrinkwrap as several dependencies have been added, but shrinkwrap has not been regenerated since then.
Merge after https://github.com/telerik/mobile-cli-lib/pull/1034
=> Remove moment as dependency

PublicAPI.md, lib/definitions/livesync.d.ts, lib/services/livesync/livesync-command-helper.ts, lib/services/livesync/livesync-service.ts, lib/services/test-execution-service.ts
Drop the logic that special cases `release` or `bundle` builds and rely on the service instead.
@rosen-vladimirov @KristianDD 
Fixes https://github.com/NativeScript/nativescript-dev-webpack/issues/342
=> Respect --bundle option in run command

lib/commands/clean-app.ts, lib/definitions/platform.d.ts, lib/definitions/project-changes.d.ts, lib/services/app-files-updater.ts, lib/services/platform-service.ts, lib/services/project-changes-service.ts, test/app-files-updates.ts, test/stubs.ts
When switching the value of `--bundle` (i.e. passing it or not passing it) between two builds the latter build should clear the app directory inside platforms prior to building.
Ping @rosen-vladimirov @KristianDD
=> Clean app directory when bundle flag is switched

lib/commands/clean-app.ts, lib/definitions/platform.d.ts, lib/definitions/project-changes.d.ts, lib/services/app-files-updater.ts, lib/services/platform-service.ts, lib/services/project-changes-service.ts, test/app-files-updates.ts, test/stubs.ts
NOTE: Cherry-picked from master
When switching the value of `--bundle` (i.e. passing it or not passing it) between two builds the latter build should clear the app directory inside platforms prior to building.
=> Clean app directory when bundle flag is switched (#3265)

lib/definitions/platform.d.ts, lib/services/platform-service.ts, lib/services/prepare-platform-native-service.ts, lib/tools/node-modules/node-modules-builder.ts
Includes:
* Always clean platforms/app when `--bundle` is passed because we may end up with duplicate symbols
* Do not use `$options` in `$nodeModulesBuilder` as CLI may be `require`d as a library where `$options` is not used at all
Ping @rosen-vladimirov @sis0k0
=> Always clean platforms/app when --bundle is passed

lib/definitions/platform.d.ts, lib/services/platform-service.ts, lib/services/prepare-platform-native-service.ts, lib/tools/node-modules/node-modules-builder.ts
> NOTE: Cherry-picked from master
* Always clean platforms/app when `--bundle` is passed
* Do not use $options in $nodeModulesBuilder
Whenever CLI is required as a library `$options` flags are not set. Hence `$options` should only be used where one knows CLI is truly run as a command-line interface - i.e. in commands.
=> Always clean platforms/app when --bundle is passed (#3269)

lib/services/subscription-service.ts, test/services/subscription-service.ts
Fixed the grammar on the newsletter subscription request line
=> minor grammatical update

lib/services/prepare-platform-native-service.ts
[This PR](https://github.com/NativeScript/nativescript-cli/pull/3269) doesn't take into account the whole CLI logic which deals with preparing the project, so this is an augmentation to make it work.
fix for: https://github.com/NativeScript/nativescript-cli/issues/3280
=> fix(prepare): clean appresources after bundle flag is passed

lib/android-tools-info.ts, lib/declarations.d.ts, lib/services/android-project-service.ts, lib/services/doctor-service.ts, test/android-tools-info.ts, test/stubs.ts
Currently Gradle cannot work with JAVA 9, so detect if it has been used and break the build for Android. Also the check will print warning when `tns doctor` is called.
In some cases javac version is a single number, for example 9. In this case our validation fails to detect the correct version and to check if we support this version.
In order to resolve this issue, use the `appendZeroesToVersion` method in order to make the versin semver valid.
Change the return type of `validateJavacVersion` method - it does not require to return a Promise.
Add unit tests for `validateJavacVersion` method.
Also update submodule, where the following change is applied:
The command `javac -version` prints result to stderr when JAVA 8 is used and to stdout when JAVA 9 is used. Current check in CLI uses the …
=> Add check for JAVA 9

lib/device-sockets/ios/socket-proxy-factory.ts, test/services/ios-debug-service.ts
When generating a port to start a websocket on, use the same logic as is present in the android debug service - get the first available available port in a range, and reuse it for the next debug session of the same application if it is still available
Fixes https://github.com/NativeScript/nativescript-cli/issues/3183 and https://github.com/NativeScript/nativescript-cli/issues/3261
=> Generate debug port in range for Chrome DevTools websocket - iOS

lib/device-sockets/ios/socket-proxy-factory.ts
When we close the websocket we have to destroy the device socket as well.
We need to wait the close event on the device socket instead of end.
=> Fix debug device/web socket closing

lib/declarations.d.ts, lib/npm-installation-manager.ts, lib/services/ios-project-service.ts, test/npm-installation-manager.ts
* Currently it is never updated and is left at the first version ever installed in `~/.local`.
As a result newly published inspector packages are not used unless the user installs
them explicitly in the project or deletes the cache manually.
* The iOS inspector package version must be determined according to project's iOS runtime
version instead of the version of CLI as it has been till now
=> fix(ios-inspector): Update cached inspector package to latest compatible version

npm-shrinkwrap.json, package.json
Update proxy-lib to latest version - 0.4.0 - the major change in this version is that it allows using it without having Visual C++ redistributable installed on the users Windows machine.
=> Update proxy-lib to 0.4.0

lib/android-tools-info.ts
Add version 27 of Android SDK as verified, so users will use it by default when it is installed.
The current CLI logic finds appCompat version that matches the selected SDK version. However, the latest appCompat version is 26.0.0-alpha, so in case we have Android SDK 27, we are unable to find matchin appCompat.
In order to resolve the issue and allow using Android SDK 27, get latest available appCompat version when there's no matching one.
=> Allow using Android SDK 27

npm-shrinkwrap.json, package.json
Update marked dependency to latest version and regenerate `npm-shrinkwrap`.
This is done as `marked`  `0.3.6` has some security vulnerabilities, which have been resolved in `0.3.9` as can be seen from the [Github analysis](https://github.com/NativeScript/nativescript-cli/network/dependencies) 
Ping @TsvetanMilanov @KristianDD @rosen-vladimirov
=> Update marked dependency

lib/services/doctor-service.ts, lib/services/platform-service.ts, test/npm-support.ts, test/platform-commands.ts, test/platform-service.ts, test/plugins-service.ts
In case terminal is not interactive, the spinner we are using during `tns doctor` or `tns platform add ...` is printing a lot of messages and polutes the output.
So in case we are in non-interactive environment, print the spinner message a single time. In order to achieve this, use the newly introduce method in $progressIndicatior from submodule;
Add getSpinner method to $progressIndicator
Add `getSpinner` method to $progressIndicator - it will return a new instance of clui.Spinner in case terminal is interactive. In case it is not - a mocked instance will be returned.
This way in CI builds the spinner will not print tons of repeated messages.
Implements https://github.com/NativeScript/nativescript-cli/issues/2127
Merge after https://github.com/telerik/mobile-cli-lib/pull/1040
=> Do not use spinner in CI environment

PublicAPI.md, lib/declarations.d.ts, lib/device-sockets/ios/socket-proxy-factory.ts, lib/services/ios-debug-service.ts, lib/services/livesync/ios-device-livesync-service.ts, test/services/debug-service.ts, test/services/ios-debug-service.ts
When `tns debug ios` is used, each change of application's code will trigger restart of app and Chrome DevTools will be disconnected. CLI prints the "new" URL and in case you copy it and paste it immediately in the browser, you'll receive empty DevTools. The problem is that the URL is printed before application is launched successfully on simulator.
In order to resolve this issue, try connection on port 18181 - the connection will be successfull only when the application is running. Wait 10 seconds to connect and throw error in case we are unable to connect for this time.
Also fix incorrect behavior of connectionError event - the thrown error should contain the deviceIdentifier, but it was missing.
NOTE: Merge after https://github.com/telerik/mobile-cli-lib/pull/1041
=> Fix livesync + debug on iOS Simulator

lib/definitions/livesync.d.ts, lib/services/livesync/livesync-service.ts, test/services/livesync-service.ts
Whenever using CLI as a library, calling livesync multiple times leads to multiple typescript/sass watchers.
This happens due to the fact that `currentWatcherInfo.pattern` is an array and checking two arrays for equality with `!==` is bound to return `true` at all times. `toString()` both arrays and check the string literals instead.
Ping @KristianDD @rosen-vladimirov
=> Fix multiple typescript/sass watchers

lib/services/ios-debug-service.ts, test/services/ios-debug-service.ts
The `debug-brk` option was broken in a previous commit as we were trying to connect to the backend port (18181). The problem is that connecting to it makes the runtime thinks debugger is attached and it continues to next statements.
Instead of connecting to the port, check if it is in LISTEN state.
Fixes https://github.com/NativeScript/nativescript-cli/issues/3338
=> fix(debug): debug-brk option does not work for iOS Simulator

lib/services/platform-service.ts
Introduce a `cleanApp` hook which occurs whenever CLI needs to clean the app directory in `platforms`.
Ping @rosen-vladimirov @KristianDD
=> feat(build): introduce cleanApp hook

PublicAPI.md, lib/android-tools-info.ts, lib/declarations.d.ts, lib/definitions/livesync.d.ts, lib/device-sockets/ios/socket-proxy-factory.ts, lib/services/doctor-service.ts, lib/services/ios-debug-service.ts, lib/services/livesync/ios-device-livesync-service.ts, lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts, npm-shrinkwrap.json, package.json, test/npm-support.ts, test/platform-commands.ts, test/platform-service.ts, test/plugins-service.ts, test/services/debug-service.ts, test/services/ios-debug-service.ts, test/services/livesync-service.ts
NOTE: Merge after https://github.com/telerik/mobile-cli-lib/pull/1044
This PR will duplicate some commits that we've already cherry-picked from master to release branch. However, this will allow us to start using Merge commits from now on and automatically merge release in master.
=> chore: merge release in master

lib/npm-installation-manager.ts
This addresses an out-of-memory problem with the installation of the tns-ios-inspector module from @next. There is a `maxBuffer` size allowed for the `stdout` or `stderr` of the child process. It seems with the updated inspector sources we exceed that. The default `maxBuffer` size is `200 * 1024` bytes according to NodeJS' docs. 50KB more seem to resolve the problem.
=> fix(CLI): Increase inspector installer memory buffer.

lib/services/android-project-service.ts
With the [update of the android plugin for gradle to `3.0.1`](https://github.com/NativeScript/android-runtime/issues/938) there's a breaking change in the folder structure where the CLI searches for the application file:
old search path: `<project_name>/platforms/android/app/build/outputs/apk/`
new search path: `<project_name>/platforms/android/app/build/outputs/apk/debug/`
Another change will also be introduced in the `tns-android@4.0.0` project template which will stop renaming the final application file:
old default name: `<project-name>-<build-version>[-abi].apk`
new default name: `app-<build-version>.apk`
This PR handles both scenarios and is backward compatible.
=> refactor: add logic for finding apk name

lib/services/ios-project-service.ts
Remove the unneeded `xcodebuild` command that CLI executes when building iOS projects
=> fix(build): Speedup iOS build

lib/commands/appstore-upload.ts, lib/commands/build.ts, lib/commands/prepare.ts, lib/definitions/livesync.d.ts, lib/definitions/platform.d.ts, lib/definitions/project-changes.d.ts, lib/services/app-files-updater.ts, lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts, lib/services/prepare-platform-service.ts, lib/services/project-changes-service.ts, lib/services/test-execution-service.ts
Speedup LiveSync with the following optimizations:
* Upon a file change **do not check all of node_modules for changes** unless `--syncAllFiles` is passed. This was unnecessary and leads to a **2 s delay** in angular projects
* With the previous implementation, whenever a file change was detected CLI used to delete all files in `platforms/.../app` directory, then **copy all files from the project's app directory** and then **only upload the changed ones**. Change the implementation so that **only changed files are copied and uploaded**.
Ping @rosen-vladimirov @KristianDD
=> refactor(livesync): speedup livesync

CONTRIBUTING.md, README.md, package.json
The initial `npm install` in the repo is reporting errors because of the postinstall script, which expects that the 'ts' files are already transpiled. Maybe we should suggest running it with `--ignore-scripts`?
The other change is running grunt from the local installation of the package, because you may not have a global instance. Maybe the grunt invocation can be moved to a npm script?
=> docs: update build instructions in readme and contributing guide

docs/man_pages/project/testing/build-android.md, docs/man_pages/project/testing/deploy.md, lib/commands/build.ts, lib/definitions/project.d.ts, lib/services/local-build-service.ts, lib/services/platform-service.ts
* Expose cleanNativeApp method for Sidekick
* Fix run, deploy and build commands when clean option is specified
* Fix help of build and deploy commands
=> feat(sidekick): Support clean option when executing local builds in Sidekick

lib/commands/run.ts, lib/definitions/livesync.d.ts, lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts
Enable LiveSync whenever a bundling plugin is present. Allow the bundling plugin to instruct CLI on what files should be watched and enable plugins to call `startSyncFilesTimeout` method in order to sync files modified by the bundling plugin itself.
Enables https://github.com/NativeScript/nativescript-cli/issues/3349
Ping @KristianDD @rosen-vladimirov
=> feat(livesync): enable livesync with bundling

lib/services/android-project-service.ts, lib/services/doctor-service.ts, lib/services/ios-project-service.ts, lib/services/xcproj-service.ts, lib/sys-info.ts, npm-shrinkwrap.json, package.json
Should be merged after this PRs:
https://github.com/telerik/mobile-cli-lib/pull/1052
https://github.com/NativeScript/nativescript-doctor/pull/27
=> feat(doctor): Integrate nativescript-doctor package

PublicAPI.md, lib/bootstrap.ts, lib/definitions/project.d.ts, lib/services/analytics-settings-service.ts, lib/services/analytics/google-analytics-custom-dimensions.d.ts, lib/services/analytics/google-analytics-provider.ts, lib/services/playground-service.ts, test/platform-commands.ts, test/plugins-service.ts, test/services/playground-service.ts
We need to track users that export their projects from playground and opens them in CLI or Sidekick. To support that we introduce playground key in nativescript key in package.json file. For example:
```
{
"nativescript": {
"playground": {
"id": "some user quid",
"usedTutorial": false // is not obligatory. In case it is present, can be true or false
}
}
}
```
In  case when package.json file contains playground key, {N} CLI reads playground data and saves it in userSettings file. If usedTutorial=true is already saved in userSettings file, {N} CLI does not overwrite it. After that {N} CLI deletes playground key from package.json file.
In case when package.json file does not contain playground key, {N} CLI checks if playground key is already saved in userSettings file. If this is the case, …
=> feat(Analytics): Respect playground key from package.json file

lib/constants.ts
In case project template has a preconfigured plugins data (for example API keys), it will be stored in the template's package.json.
After creating the project, CLI removes all keys except the one defined in `PackageJsonKeysToKeep` array from `app/package.json` file.
So it removes the predefined configuration of the pluginData.
Fix this by adding the entry "pluginsData" in the array, so we'll keep it as well.
=> feat(create): Keep pluginsData key from template's package.json

lib/declarations.d.ts, lib/node-package-manager.ts, lib/services/extensibility-service.ts, test/ios-project-service.ts, test/npm-support.ts, test/platform-commands.ts, test/plugins-service.ts, test/project-service.ts, test/services/extensibility-service.ts
In case user executes any command that is registered in extension, but this extension is not installed, they'll receive error:
`Unknown command ...`. Instead of showing this, it is better to tell them how to get access to this command.
In order to achieve this, implement a new logic in `extensibilityService` to find commands registered in all extensions. CLI searches npm (via npms API) for packages that have the keyword `nativescript:extension`.
After that, CLI gets the package.json of the latest version of each dependency (via registry.npmjs.org) and searches for nativescript key in it. In case it has nativescript key, CLI reads the commands value inside it. The value should be string array containg all commands registered in extension's bootstrap.
When user writes down a command that is …
=> feat(extensibility): Add hint how to get access to a command from extension

lib/definitions/platform.d.ts, lib/services/platform-service.ts, test/stubs.ts
Introduce `shouldPrepare` hook.
Needed in order for plugins to be able to state when a project should undergo the prepare process.
=> refactor: introduce shouldprepare hook

lib/services/livesync/platform-livesync-service-base.ts, lib/services/prepare-platform-service.ts
Fix LiveSync not respecting rapid file changes (like transpilation, or copying directories for example).
Fix this by not passing `filesToSync` to `updateApp` method of `AppFilesUpdater`. This way each file will be copied upon every LiveSync action and we won't miss out any files.
=> fix(livesync): respect rapid file changes

README.md
=> docs: update the configure proxy usage section

lib/services/app-files-updater.ts, lib/services/prepare-platform-js-service.ts, lib/services/prepare-platform-native-service.ts, test/app-files-updates.ts
patches https://github.com/NativeScript/nativescript-cli/pull/3356
addresses #3400 and #3401
=> fix(prepare): disregard app_resources's dir name when preparing in platforms/

lib/definitions/livesync.d.ts, lib/services/livesync/livesync-service.ts
The target platforms may be used in plugins that implement the `before-watchPatterns` hook. See https://github.com/NativeScript/nativescript-dev-webpack/pull/454.
=> refactor: provide platforms to before-watchPatterns hooks

lib/bootstrap.ts, lib/commands/post-install.ts, lib/definitions/terminal-spinner-service.d.ts, lib/services/doctor-service.ts, lib/services/platform-service.ts, lib/services/terminal-spinner-service.ts, npm-shrinkwrap.json, package.json, test/npm-support.ts, test/platform-commands.ts, test/platform-service.ts
Should be merged after this https://github.com/NativeScript/nativescript-doctor/pull/28
=> Getting started improvements

lib/bootstrap.ts, lib/commands/build.ts, lib/commands/debug.ts, lib/commands/deploy.ts, lib/commands/run.ts, lib/declarations.d.ts, lib/definitions/livesync.d.ts, lib/definitions/platform.d.ts, lib/helpers/bundle-validator-helper.ts, lib/helpers/deploy-command-helper.ts, lib/helpers/livesync-command-helper.ts, lib/services/platform-service.ts, test/stubs.ts
Includes:
* Refactor CLI so that it allows passing a `buildAction` parameter to services that execute `run` and `deploy` commands
* Introduce `helpers` directory - place classes/files here that are neither commands, nor services
* Refactor logic for verifying bundle options - extract it into a helper and reuse it instead of using the inheritance approach
* Add forgotten bundle options check in `deploy` command
=> refactor: allow pass buildaction

lib/definitions/platform.d.ts, lib/definitions/project.d.ts, lib/services/android-project-service.ts, lib/services/ios-project-service.ts, lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts, test/platform-commands.ts, test/stubs.ts
_problem_
The CLI can't find `.apk` file to install on passed `--release` option. Read more [in this issue](https://github.com/NativeScript/nativescript-cli/issues/3411)
_solution_
respect `--release` option when generating apk find path
=> fix: find correct apk name when --release passed

docs/man_pages/index.md, docs/man_pages/project/configuration/prepare.md, docs/man_pages/project/testing/run.md
=> docs: document run platform

lib/services/app-files-updater.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/3428
=> fix(nsconfig):app resources not filtered on prepare

lib/commands/debug.ts
Pass `deviceDebugMap` correctly in order to fix `tns debug`
It is used [like this](https://github.com/NativeScript/nativescript-cli/blob/7bb22488067fe7ea6079a1c00972bce8589f4761/lib/helpers/livesync-command-helper.ts#L90)
Ping @Fatme @rosen-vladimirov
=> fix: pass devices for debugging correctly

lib/npm-installation-manager.ts
Whenever installing the platform `tns-android` or `tns-ios` do not print `Installing  <platform>` (with two spaces) but instead print only a single space between the words
Ping @rosen-vladimirov @Fatme
=> fix: stop printing double spaces

docs/man_pages/index.md, docs/man_pages/project/configuration/resources-update.md, docs/man_pages/project/configuration/resources/resources-update.md, docs/man_pages/project/configuration/update.md, lib/bootstrap.ts, lib/commands/resources/resources-update.ts, lib/declarations.d.ts, lib/services/android-project-service.ts, lib/services/android-resources-migration-service.ts, lib/services/prepare-platform-native-service.ts, test/debug.ts, test/npm-support.ts, test/platform-service.ts, test/plugins-service.ts, test/stubs.ts
Introduce the 'tns resources-update android' command. By design, upon execution it should migrate the directory structure of App_Resources/Android to the new v4 structure - the one that supports the inclusion of java source files, arbitrary assets, and any resource files in the App_Resources/Android/src/main directory structure. Additional, user-defined flavors can also be created taking advantage of the new dir structure.
=> feat: introduce resources update command

lib/services/livesync/livesync-service.ts
In case the user has an android emulator and a device attached we shouldn't build twice - the build artifact is eligible to be installed on both devices.
Fixes https://github.com/NativeScript/nativescript-cli/issues/3442
=> fix: stop build twice for android

lib/services/user-settings-service.ts
In case when user executes some command and by some reasons user settings file is not a valid json, {N} CLI throws "Unexpected token in JSON at position 0" error. After that user is not able to execute any cli command until the file exists.
=> fix(userSettings): Don't fail when user settings file is not a valid json

lib/services/platform-service.ts
Pass all arguments to install application - during cloud build the package file's location may already be known.
=> fix: pass all args to installapplication

lib/project-data.ts, test/project-data.ts
Currently CLI tracks Angular, TypeScript and JavaScript project types. Add a new project category - `Vue.js`. The project will be tracked as `Vue.js` when it has nativscript-vue in the package.json.
=> feat(analytics): Track Vue.js project type

lib/declarations.d.ts, lib/definitions/platform.d.ts, lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts
Should be merged with this PR https://github.com/NativeScript/nativescript-dev-typescript/pull/44
=> Use moduleResolution classic when syncAllFiles option is not specified

lib/services/android-plugin-build-service.ts
Don't merge before: https://github.com/telerik/mobile-cli-lib/pull/1063
Problem:
Plugins contained within an npm scope, like `@nota/nativescript-accessibility-ext` fail to build because their android plugin name becomes `@nota/nativescript-accessibility-ext`, both `@` and `/` are illegal characters in an Android package name.
Proposed solution:
Split the plugin name string by a forward slash (`/`) and take the last element, effectively removing all forward slashes, and omitting the npm scope name, if any.
=> fix(plugin-build): strip npm scope names from android plugin names

lib/definitions/platform.d.ts, lib/helpers/livesync-command-helper.ts, lib/services/android-debug-service.ts, lib/services/ios-debug-service.ts, lib/services/ios-log-filter.ts, lib/services/livesync/android-device-livesync-service.ts, lib/services/livesync/ios-device-livesync-service.ts, lib/services/livesync/livesync-service.ts, lib/services/platform-service.ts, test/services/android-debug-service.ts, test/services/ios-debug-service.ts, test/services/ios-log-filter.ts
This PR improves the overall behaviour of the IOSLogFilter within the CLI. We now filter data based on the following core assumption:
- all messages coming from the related NS app contain the following artefact: `<app-name>(NativeScript)?[<pid>]`, where (NativeScript) might be missing
- all relevant multiline messages do not contain iOS artefacts like `May 24 15:54:52 Dragons-iPhone NativeScript250(NativeScript)[356] <Notice>:` and directly follow a message with the first artefact
Relying on these principles, we pass messages even if they are multiline (`console.dir`, stack-traces, etc).
Unit tests have been slightly updated to reflect the currently expected behaviour.
This PR should address this issue: https://github.com/NativeScript/nativescript-cli/issues/3105 and is also related to …
=> update(cli): Improve filtering of iOS logs

docs/man_pages/project/testing/debug-android.md, docs/man_pages/project/testing/debug-ios.md, docs/man_pages/project/testing/run-android.md, docs/man_pages/project/testing/run-ios.md
fix for: https://github.com/NativeScript/nativescript-cli/issues/3361
=> docs: add syncallfiles flag to help
