NativeScript/nativescript-cli

lib/services/android-project-service.ts

The tns-android template uses by default sdk 17. If the user does not have it installed, we try to update it.
To do so safely, we have a white list of well-tested sdks. We match the white list with the installed sdks and take the newest one.
This commit depends on https://github.com/telerik/tns-android/commit/990f725d845364e33ca77d4e54212e0c2342bc55
Implements https://github.com/NativeScript/nativescript-cli/issues/173

Allow updating target android sdk during "platform add"

---

package.json

See http://blogs.msdn.com/b/typescript/archive/2015/01/16/announcing-typescript-1-4.aspx for the goodies

Update to TypeScript 1.4

---

lib/services/platform-service.ts
resources/help.txt

http://teampulse.telerik.com/view#item/283764

Run application on iOS device on OSX

---

lib/bootstrap.ts
lib/commands/debug.ts
lib/declarations.ts
lib/definitions/platform.d.ts
lib/options.ts
lib/services/platform-service.ts
package.json
resources/help.txt

Implement debug command

---

package.json

Add cli-table as dependency as it is used in common lib. Merge all latest changes from common-lib.

Add cli-table as dependency

---

lib/options.ts
lib/services/ios-project-service.ts
lib/services/platform-service.ts

* Build for emulator by default
Currently device option is added both in common options and in options. I removed the device option from ns options and changed the default behavior of build command.

* Remove device option

---

lib/commands/build.ts
lib/services/platform-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/123

Prepare platform before building

---

README.md
resources/help.txt

Note that I haven't touched the debug command.

Refined the docs

---

lib/node-package-manager.ts
lib/options.ts
lib/services/platform-service.ts
test/platform-commands.ts
test/project-service.ts
test/stubs.ts

Adjustments from the big refactoring in the AppBuilder CLI

Sync TNS with latest common lib

---

bin/nativescript
bin/tns

This fixes https://github.com/NativeScript/nativescript-cli/issues/257

Fix Bash passing unescaped arguments to node

---

package.json

Set version to 0.9.1 for the next hotfix release..

Set version to 0.9.1

---

lib/bootstrap.ts
lib/config.ts
lib/mobile-platforms-capabilities.ts
lib/services/analytics-settings-service.ts

Add specific mobilePlatformCapabilities, to know what is supported by current CLI. Swap names of CLIENT_NAME and CLIENT_NAME_ALIAS. Update common lib, where several fixes had been applied.

Add mobilePlatformsCapabilities

---

lib/config.ts

ConfigBase implements Config.IConfig. Fix Configuration extends ConfigBase and implements IConfiguration.

Fix Config implementation

---

package.json

Set version to 0.9.2

---

lib/services/ios-project-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/312

Replace CFBunlderIndentifier placeholder with projectId

---

CHANGELOG.md
README.md
lib/services/android-project-service.ts
lib/services/ios-project-service.ts
package.json
resources/help.txt

Conflicts:
lib/definitions/project.d.ts
lib/services/android-project-service.ts
lib/services/ios-project-service.ts
test/stubs.ts

Merge release 0.9.2 into master

---

package.json

Set version to 0.9.3

---

resources/help.txt

Fixes for autocomplete command

---

lib/constants.ts
lib/definitions/platform.d.ts
lib/definitions/project.d.ts
lib/services/android-project-service.ts
lib/services/ios-project-service.ts
lib/services/platform-service.ts
test/platform-commands.ts
test/stubs.ts

Should be merged after this https://github.com/NativeScript/template-hello-world/pull/16

Change app structure - move tns_modules inside app folder

---

lib/bootstrap.ts
lib/providers/commands-service-provider.ts
test/platform-commands.ts

Introduced `commandsServiceProvider`

Update to latest common lib

---

lib/services/ios-debug-service.ts

Should be merged after this https://github.com/telerik/mobile-cli-lib/pull/251

Use correct function from postNotificationClient

---

package.json

Update package.json to set version to 0.10.0

Set version to 0.10.0

---

README.md

The documentation for the command and its sub-commands is in https://github.com/NativeScript/nativescript-cli/pull/424

Adding autocomplete to the readme. 

---

docs/man_pages/device/device-ios.md
package.json

The following improvements are included:
* Update marked-terminal to latest version, which supports nested lists.
In common lib:
* Make the logo of the CLI in HTML Help a link to index.html page.
* In console help replace `&nbsp;` with space.
* In console help replace all links with their text.
* In console help remove the inner borders of cli-tables.

Improve help service

---

README.md
docs/man_pages/general/help.md
docs/man_pages/index.md

Updated the help for the help command as it now opens the browser

---

Gruntfile.js
package.json

Set the build version in package.json to 1.0.0-RC for the next public release.

Set version to 1.0.0-RC

---

CHANGELOG.md
Gruntfile.js
README.md
docs/man_pages/general/help.md
docs/man_pages/project/configuration/prepare.md
docs/man_pages/project/testing/build.md
docs/man_pages/project/testing/debug.md
docs/man_pages/project/testing/emulate.md
docs/man_pages/project/testing/run.md
lib/bootstrap.ts
package.json

Conflicts:
lib/providers/commands-service-provider.ts
package.json

Merge 1.0.1 in master

---

package.json

Set version in package.json
Stop using CancellationService on unix OSes

Prepare for 1.0.2 release

---

lib/bootstrap.ts
lib/commands/plugin/add-plugin.ts
lib/commands/plugin/remove-plugin.ts
lib/declarations.ts
lib/definitions/platform.d.ts
lib/definitions/plugins.d.ts
lib/options.ts
lib/services/android-project-service.ts
lib/services/ios-project-service.ts
lib/services/platform-service.ts
lib/services/plugins-service.ts
lib/tools/broccoli/node-modules-dest-copy.ts
package.json
test/platform-commands.ts
test/platform-service.ts
test/plugins-service.ts

`tns plugin add <plugin>` where `plugin` can be `local folder path`, `github url`, `node module that is published in npm` - This command should install plugin locally in node_modules folder, save it to `package.json` and prepare it if some platform is added. If no platforms are added the installed plugins are prepared on `platform add step`.
`tns plugin remove pluginName` removes the specified plugin

Initial version of plugin commands

---

lib/services/project-service.ts

https://github.com/NativeScript/nativescript-cli/issues/271

Validate copy-from option

---

lib/services/platform-service.ts

https://github.com/NativeScript/nativescript-cli/issues/281

Report message when platform gets successfully removed

---

lib/tools/broccoli/trees/node-modules-tree.ts
test/npm-support.ts

This PR fixes broken npm support.
Fixes https://github.com/NativeScript/nativescript-cli/issues/567

Fix broccoli funnel

---

lib/commands/prepare.ts
lib/commands/run.ts
lib/services/platform-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/606

Validate platform in canExecute function

---

docs/man_pages/project/configuration/install.md

Fix help for install command, --path option description changed.

Fix help for install command

---

docs/man_pages/lib-management/library-add.md

Fixing library-add as requested by Vasil Chimev

---

lib/declarations.ts
lib/node-package-manager.ts
lib/options.ts
lib/services/android-project-service.ts
lib/services/platform-service.ts
lib/services/plugins-service.ts

Merge latest fixes from release branch in master. The fixes are part of AppBuilder integration with latest {N} version

Merge release in master

---

package.json

Set version to 1.2.0

---

lib/services/usb-livesync-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/654
Should be merged after https://github.com/telerik/mobile-cli-lib/pull/388 and https://github.com/telerik/mobile-cli-lib/pull/391

Fix livesync

---

lib/commands/add-library.ts
lib/services/android-project-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/607

Fix library add

---

CHANGELOG.md

Set correct date of 1.2.1 release in changelog

Set correct date of 1.2.1 release

---

LICENSE

Supersedes https://github.com/NativeScript/nativescript-cli/pull/718

Add the copyright year and owner

---

lib/services/android-debug-service.ts

https://github.com/NativeScript/nativescript-cli/issues/682

Add default option for android debugger

---

lib/services/usb-livesync-service.ts

https://github.com/NativeScript/nativescript-cli/issues/706
Should be merged after this PR https://github.com/telerik/mobile-cli-lib/pull/404

LiveSync support for iOS simulator

---

docs/man_pages/project/testing/debug-ios.md
lib/services/android-debug-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/748

Detach debug tools properly

---

CHANGELOG.md
docs/man_pages/project/testing/livesync-ios.md

Fix documentation for iOS livesync (iOS Simulator).

Fix livesync docs

---

lib/services/usb-livesync-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/776

Fix livesync ios --emulator --watch if the file is not at project root level

---

lib/services/android-project-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/779

Trim library path

---

lib/services/android-project-service.ts
lib/services/platform-service.ts

Only syntax changes for ES6, TS 1.5 and strict mode.

ES6 & strict mode fixes

---

lib/services/ios-project-service.ts

Change resources destination directory path by removing 'icons' subdir. 
Fixes adding of all types of resources to 'icons' subdirectory.
Template project is also updated. See https://github.com/NativeScript/ios-runtime/pull/267
Contributes to https://github.com/NativeScript/nativescript-cli/issues/683 .

Change resources destination directory path.

---

lib/services/android-project-service.ts
lib/services/plugins-service.ts
package.json

Fixes https://github.com/NativeScript/nativescript-cli/issues/807
Fixes https://github.com/NativeScript/nativescript-cli/issues/806

Release 1.2.4

---

lib/commands/create-project.ts

See https://github.com/NativeScript/nativescript-cli/issues/760

Warn users when creating applications named 'app'.

---

lib/services/android-project-service.ts

This should be merged after corresponding PR in android-runtime

Pass sdk option to build.gradle file

---

lib/services/android-project-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/840

Fixes gradle building for Android

---

lib/commands/deploy.ts
lib/commands/run.ts
lib/definitions/platform.d.ts
lib/services/ios-project-service.ts
lib/services/platform-service.ts

Part of https://github.com/NativeScript/android-runtime/issues/103

Add --static-bindings to run and deploy commands

---

lib/services/android-project-service.ts

Currently when creating Android project, we copy the full src directory from android framework. After that we execute `copyResValues` which is totally not needed as we've already copied everything. Instead we have to clean the copied values as currently if you target android sdk 19 for example, we'll still copy res/values-v21 directory in the project and the build will fail.
Check all `values-v<SDK>` directories and remove the ones that have higher version than currently targeted one.

Clean res dir of Android project

---

lib/services/android-project-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/860

Fixes https://github.com/NativeScript/nativescript-cli/issues/860

---

lib/services/android-project-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/838

Throw an error when add library command is executed with eclipse project

---

lib/services/usb-livesync-service.ts

See https://github.com/NativeScript/nativescript-cli/issues/811

Fix livesync with platform specific files

---

lib/services/plugins-service.ts

Fixes this regression bug - http://nsbuild01.telerik.com:8080/build/view/CLI/job/CLI-stable-tests-full-linux/222/artifact/Report.html

Show correct warning if the plugin does not support the currently installed platform.

---

lib/services/ios-project-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/772

Update metadata generator folder when platform update ios command is executed

---

package.json

Set version to 1.4.0

---

package.json

Set version to 1.3.1

---

CHANGELOG.md
README.md
docs/man_pages/index.md
lib/android-tools-info.ts
lib/services/android-project-service.ts

Merge post 1.3.0 release in master
Conflicts:
package.json

Merge post 1.3.0 release in master

---

lib/services/ios-project-service.ts

Related to https://github.com/NativeScript/ios-runtime/pull/325 and https://github.com/NativeScript/ios-runtime/issues/308.

Add internal folder to ios framework directories

---

lib/services/ios-project-service.ts

Add missing wait for dynamic libraries.

Fix dynamic library adding

---

lib/services/doctor-service.ts

https://github.com/NativeScript/nativescript-cli/issues/949

Warning if pods are not installed and for old CocoaPods versions

---

lib/services/usb-livesync-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/942

Sync files that are in App_Resources

---

docs/man_pages/project/testing/build-android.md

Make it explicit that `--static-bindings` is an experimental feature.

update documentation for --static-bindings option

---

lib/services/ios-project-service.ts

Fix formatting of error message regarding validation failure of static libs when building for iOS platform.

Error message formatting

---

package.json

Use node-inspector from NativeScript fork.

Use node-inspector from NS fork

---

lib/definitions/platform.d.ts
lib/services/android-project-service.ts
lib/services/ios-project-service.ts
lib/services/platform-project-service-base.ts

Fixes http://nsbuild01.telerik.com:8080/build/job/CLI-release-tests-full-linux/102/artifact/Report.html

Fix frameworkVersion

---

lib/services/ios-project-service.ts

1. Add plugin that has Podfile
2. Try to remove the plugin
Note: Don't prepare or add platform between step1 and step2

Fix plugin remove if the plugin has Podfile

---

lib/definitions/project.d.ts
lib/services/android-project-service.ts
lib/services/ios-project-service.ts
lib/services/platform-service.ts
test/stubs.ts

Should be merged after telerik/mobile-cli-lib#479

Fixes #1031

---

lib/tools/broccoli/builder.ts
lib/tools/broccoli/node-modules-dest-copy.ts
test/npm-support.ts

Rebased the [last PR](https://github.com/NativeScript/nativescript-cli/pull/1068) from master.

Npm scope support

---

lib/services/plugins-service.ts

Fixes the issue1 - https://github.com/NativeScript/nativescript-cli/issues/883

Fix EISDIR error when the plugin is specified with path to local folder

---

CHANGELOG.md
lib/definitions/platform.d.ts
lib/definitions/project.d.ts
lib/npm-installation-manager.ts
lib/services/android-project-service.ts
lib/services/ios-project-service.ts
lib/services/platform-service.ts
lib/services/plugins-service.ts
package.json
test/platform-commands.ts
test/plugins-service.ts
test/project-service.ts
test/stubs.ts

Merge 1.4.3 in master
Set version to 1.5.0

Merge 1.4.3 in master

---

lib/tools/broccoli/builder.ts

Fixes http://nsbuild01:8080/build/view/TestApps-Stable/job/tns-ios-stable-build-testapps-cocoapods-xcode7/35/consoleFull

Fix " Cannot read property 'toLowerCase' of undefined" error

---

lib/services/plugins-service.ts

1. Create {N} project
2. tns plugin add nativescript-unit-test-runner
3. tns prepare ios

Fix  ENOENT, open '~/myApp3/node_modules/.bin/package.json/'

---

package.json

Fix warning for invalid semver version

Update ios-sim-portable dependency

---

README.md
lib/services/android-project-service.ts
lib/services/doctor-service.ts
setup/native-script.rb
setup/native-script.txt

See https://github.com/NativeScript/NativeScript/issues/1024

Use gradle wrapper instead of global gradle

---

setup/native-script.txt

Add messages to the user about installed products

---

lib/android-tools-info.ts

See https://github.com/NativeScript/nativescript-cli/issues/1021

Fix warning when attempting to use too old version of Android SDK

---

lib/services/android-project-service.ts

See https://github.com/NativeScript/nativescript-cli/issues/1086

Fix --key-store-path path

---

lib/services/android-project-service.ts

fix for:
NativeScript/android-runtime#263
@Fatme  @teobugslayer

cli acknowledges gradle.properties file on platform add android command

---

PLUGINS.md

Changes after https://github.com/NativeScript/nativescript-cli/pull/1163

Cosmetic changes to Plugins.md

---

lib/services/platform-service.ts

This ensures that next prepare command will retry preparing
Fixes https://github.com/NativeScript/nativescript-cli/issues/1148

When prepare fails, delete entire app dir

---

lib/services/doctor-service.ts

Check if pod version is a valid semver version

Fix doctor command

---

lib/services/init-service.ts
lib/services/platform-service.ts

See https://github.com/NativeScript/nativescript-cli/issues/1167

Check for devices before building the project

---

lib/services/plugins-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/1204

Use npm api to install all project dependencies

---

lib/services/usb-livesync-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/1210
Should me merged after this PR https://github.com/telerik/mobile-cli-lib/pull/535

Fix ENOENT error when livesyncing deleted .xml or .css file

---

package.json

Fixes https://github.com/NativeScript/nativescript-cli/issues/1206

Bump ios-sim version

---

lib/commands/livesync.ts
lib/providers/device-log-provider.ts
lib/services/platform-service.ts

https://github.com/NativeScript/nativescript-cli/issues/1130

Show application output from livesync command

---

lib/android-tools-info.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/1242

Fix "ANDROID_HOME environment variable is not set correctly"  error

---

lib/commands/prepare.ts
lib/services/platform-service.ts

Add missing wait in prepare command.
Make sure the whole message for invalid xml is red.

Fix prepare command

---

package.json

Set version to 1.5.1

---

package.json

See https://github.com/NativeScript/nativescript-cli/issues/1247

Don't stop adb uninstall

---

lib/services/usb-livesync-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/1210

Fix ENOENT err

---

lib/services/android-project-service.ts

See https://github.com/NativeScript/NativeScript/issues/1213

Allow building of projects with spaces in directory names on Windows

---

lib/services/platform-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/1285
Should be merged after this PR https://github.com/telerik/mobile-cli-lib/pull/561

Prepare empty directories

---

lib/services/android-debug-service.ts

fix output when multiple devices are available

make getport command deterministic

---

package.json

Update node-inspector to 0.7.4.1

Update node-inspector to 0.7.4.1

---

docs/man_pages/project/creation/create.md

Fix --template help

---

lib/services/android-debug-service.ts

See https://github.com/NativeScript/nativescript-cli/issues/1377

Fix debugging of two apps at the same time

---

lib/definitions/project.d.ts
lib/services/android-project-service.ts
lib/services/ios-project-service.ts
lib/services/platform-service.ts
test/ios-project-service.ts
test/stubs.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/1362

Fix crash when launching applications on iOS device in debug mode

---

lib/services/doctor-service.ts
lib/services/platform-service.ts
package.json

See https://github.com/NativeScript/nativescript-cli/issues/1382

Add spinner to long running operations

---

lib/services/doctor-service.ts

Use spinner.message function instead spinner.update

Fix `undefined is not a function` error.

---

lib/providers/livesync-provider.ts

Should be merged after this PR https://github.com/telerik/mobile-cli-lib/pull/587

Respect additiional fast sync file extensions

---

lib/commands/deploy.ts

FIxes https://github.com/NativeScript/nativescript-cli/issues/1403

Don't print incorrect message when `tns deploy ios --release` command is executed

---

lib/services/analytics-settings-service.ts

Use the new Analytics SDK and track more information.
Implements https://github.com/NativeScript/nativescript-cli/issues/1420

Use new Analytics SDK

---

lib/device-sockets/ios/socket-proxy-factory.ts

This change is necessary for NativeScript VSCode plugin.

Log socket path on running 'tns debug ios'

---

lib/services/ios-debug-service.ts

See https://github.com/NativeScript/ios-runtime/issues/474

Fixed reversed if, code cleanup

---

lib/services/platform-service.ts

Remove old code that is starting the deployment before preparing the project.

Fix emulate android command

---

lib/services/android-project-service.ts

Remove ANT support

---

package.json

Fixes issues with Genymotion being first in the PATH

Update node-winreg dependency

---

CHANGELOG.md

Update CHANGELOG for 1.6.1

---

extending-cli.md

Updates to extending-cli

---

Gruntfile.js

Introduce `grunt rebuild`

---

CHANGELOG.md
package.json

Update package.json and CHANGELOG for 1.6.2 release

Update package.json and CHANGELOG for 1.6.2 release

---

package.json

Set version to 2.0.0

---

CHANGELOG.md

Update CHANGELOG for 1.7.0 release

Update CHANGELOG for 1.7.0 release

---

package.json

Set version to 1.7.1

---

setup/native-script.ps1

Ping @teobugslayer @rosen-vladimirov

Typo in native-script.ps1

---

setup/native-script.ps1
setup/native-script.rb

Changes for *Windows* 
* In case `ANDROID_HOME` environment variable is not set, try to determine the correct path to `android-sdk` through `android.bat`'s location
* Use `android.bat` executable relative to `android-sdk`, set in `ANDROID_HOME` environment variable, for sdk updates
* Split android sdk updates into single command calls in order to avoid problems with license agreements
Changes for *Mac*:
* In case `ANDROID_HOME` environment variable is not set, try to determine the correct path to `android-sdk` - either use homebrew's symlink or through `android` executable's location
* Use `android` executable relative to `android-sdk`, set in `ANDROID_HOME` environment variable, for sdk updates
* Split android sdk updates into single command calls in order to avoid problems with license …

Improve Setup Scripts' Android bits

---

lib/services/ios-project-service.ts

Instead append the current plugin's Podfile contents if not already present.

Do not truncate `platform/ios/Podfile` upon each plugin prepare

---

lib/services/analytics-settings-service.ts

Each sessions count should be tracked per project for which it is started. Currently we were using the same counter for all sessions.
Fix this by using separate counter for each project.
Remove the old key ("SESSIONS_STARTED") and use it as current value for the new key (`SESSIONS_STARTED_<analytics_project_key>`) in case it existed.

Track sessions count per analytics project

---

lib/services/init-service.ts

When the `tns-<platform>` key in the package.json of nativescript project has custom template the template key must be kept and the version key should be added.

Include custom platform template when using tns init -f

---

README.md
lib/bootstrap.ts
lib/declarations.ts
lib/services/doctor-service.ts
lib/services/ios-project-service.ts
lib/services/xcproj-service.ts
test/ios-project-service.ts

Add an entry in the docs as well.
In addition: hide warnings from CocoaPods whenever running `$ tns doctor`.
Ping @rosen-vladimirov for code review

Add xcproj check to tns doctor

---

lib/services/versions-service.ts

When getting the current version of the tns-core-modules the version in project's package.json can be `^<version>` or `*` so the version in the package.json of the installed tns-core-modules is the correct version.

Fix get current tns-core-modules version

---

LICENSE
lib/config.ts
lib/services/project-data-service.ts
lib/services/project-service.ts

Use correct copyright message.
Add required fields in `package.json` when project is created. This way there will be no warnings during `tns create <app>`.
Also improve the message (use markdown).
Add message on postinstall to show that NS CLI is installed successfully and where to follow us.

Project creation improvements

---

lib/services/livesync/ios-livesync-service.ts

Sometimes when `--watch` is used, the socket is closed from the other side. We have to attach to close event of the socket and set our internal variable to null. This way next time when a file is changed, we'll create a new socket.
Sometimes on SIGINT, SIGTERM or process.exit we do not have `this.socket`, but we try to call `destroy` method of the socket, which fails.
Also make sure correct events are added when livesync to device.

Fix iOS socket issues

---

docs/man_pages/project/testing/build-android.md

in the next release this option will be enabled by default
ping: @rosen-vladimirov, @ikoevska

removed the --static-bindings option from help

---

lib/config.ts

Merge some fixes required for AppBuilder integration.

Merge appbuilder branch for 1.7.1 in release

---

lib/config.ts

Use the startPackageActivity name from the new constant.

Use startPackageActivity from constant

---

CHANGELOG.md
package.json

Ping @TsvetanMilanov @dtopuzov

Changelog for 2.0.1

---

lib/tools/broccoli/node-modules-dest-copy.ts
test/npm-support.ts

Related to: https://github.com/NativeScript/nativescript-cli/issues/1783

Flatten only dependencies with valid package.json

---

lib/services/ios-debug-service.ts
package.json

TypeScript updated and unreachable code deleted.

typescript updated

---

lib/services/platform-service.ts

Related to https://github.com/NativeScript/nativescript-cli/issues/352

deployOnEmulator() will call deployOnDevice()

---

lib/android-tools-info.ts

Related to https://github.com/NativeScript/nativescript-cli/issues/1729

Min Java version raised

---

README.md
lib/android-tools-info.ts

Descriptions changed

---

docs/man_pages/project/configuration/platform-clean.md
lib/bootstrap.ts
lib/commands/platform-clean.ts
test/platform-commands.ts

Clean command

---

lib/services/android-project-service.ts
lib/services/platform-service.ts
lib/services/xcproj-service.ts

Related to https://github.com/NativeScript/nativescript-cli/issues/1732 and https://github.com/telerik/mobile-cli-lib/pull/717

Separate methods used instead getSysInfo()

---

lib/services/android-project-service.ts

https://github.com/NativeScript/nativescript-cli/issues/1296#issuecomment-227668320

drawable code removed

---

lib/providers/livesync-provider.ts

Fast livesync without app restart in Angular apps if you use `templateUrl` instead `template` in your component. For example:
```TypeScript
import {Component} from "@angular/core";
@Component({
selector: "my-app",
templateUrl: "component.html",
})
export class AppComponent {
public counter: number = 16;
public get message(): string {
if (this.counter > 0) {
return this.counter + " taps left";
} else {
return "Hoorraaay! \nYou are ready to start building!";
}
}
public onTap() {
this.counter--;
}
}
```
```HTML
<StackLayout>
<Label text="Tap the button" class="title"></Label>
<Button text="Tap" (tap)="onTap()"></Button>
<Label [text]="message" class="message" textWrap="true"></Label>
</StackLayout>
```
If you change something in the HTML only the page will be reloaded without application …

HTML files fast synced as well (Angular)

---

lib/services/platform-service.ts

Related to https://github.com/NativeScript/nativescript-cli/issues/1620

Can execute improved

---

lib/android-tools-info.ts
lib/commands/livesync.ts
lib/commands/plugin/add-plugin.ts
lib/commands/plugin/remove-plugin.ts
lib/providers/livesync-provider.ts
lib/services/android-project-properties-manager.ts
lib/services/emulator-settings-service.ts
lib/services/init-service.ts
lib/services/ios-debug-service.ts
lib/services/ios-project-service.ts
lib/services/livesync/android-livesync-service.ts
lib/services/livesync/livesync-service-base.ts
lib/services/platform-service.ts
package.json
test/platform-commands.ts

The lodash.d.ts is now for version 4.0.0 but for our usage it is OK.
From the lodash changelog (https://github.com/lodash/lodash/wiki/Changelog) you can see that from version 4.0.0 to version 4.13.1 there are no breacking changes.

Update lodash to 4.13.1

---

lib/services/livesync/ios-livesync-service.ts

Fixed Ctrl+C not working when live syncing

---

lib/services/android-project-service.ts

update cli to exclude special logic for older versions of node
> filewalker is removed because it's no longer necessary
ping @rosen-vladimirov @enchev @hshristov

support for node 0.12

---

lib/config.ts

Update submodule to latest SHA. Merge after https://github.com/telerik/mobile-cli-lib/pull/710
Ping @rosen-vladimirov @tzraikov @PanayotCankov

Pull configuration logic

---

lib/bootstrap.ts
lib/config.ts
lib/services/analytics-service.ts

We need to create analytics service in the NS CLI to implement the NS specific logic for sending analytics data.

Move analytics service registration

---

lib/services/livesync/android-livesync-service.ts

Fixed: `tns livesync android` not updating application consistently

---

lib/bootstrap.ts
lib/services/livesync/android-livesync-service.ts
lib/services/livesync/ios-livesync-service.ts
lib/services/livesync/livesync-service-base.ts
lib/services/livesync/platform-livesync-service-base.ts

Common lib PR https://github.com/telerik/mobile-cli-lib/pull/756

Split livesync-service-base so that we could have different implementations for AppBuilder and NativeScript

---

lib/commands/plugin/add-plugin.ts

Related to https://github.com/NativeScript/nativescript-cli/issues/1881

return false if plugin is already installed

---

lib/services/ios-project-service.ts

Related to https://github.com/NativeScript/nativescript-cli/issues/1959

x86_64 support added

---

lib/services/android-debug-service.ts

refactored debug start of applications
improved debug command speed by 500 ms
related to https://github.com/NativeScript/android-runtime/pull/535

support debug started flag

---

test/debug.ts
test/stubs.ts

1. Test that debugLivesync flag is true when executing debug --watch command
2. Test that beforePrepareAllPlugins will not call gradle when livesyncing
3. Test that beforePrepareAllPlugins will call gradle with clean option when *NOT* livesyncing

Added tests for debug + livesync

---

lib/tools/broccoli/node-modules-dest-copy.ts

Just wanted to fix a typo that bothered me on occasion 😄

Fix typo in node-modules-dest-copy broccoli tool

---

lib/bootstrap.ts
lib/commands/devices.ts
lib/services/ios-project-service.ts

Add device alias command

---

lib/services/ios-project-service.ts

Implemented https://github.com/NativeScript/nativescript-cli/issues/2067

Added teamid option for run,debug and livesync commands

---

lib/services/ios-debug-service.ts

Fixed: node processes increase after every change with debug --watch

---

config/config.json
lib/config.ts

Implements https://github.com/NativeScript/nativescript-cli/issues/2049

Set default for using sandbox-pod to false

---

lib/services/android-project-service.ts

related to: https://github.com/telerik/mobile-cli-lib/pull/821
* don't blow up when there is no app folder

make sure we warn the user if there is no app folder instead of crash

---

lib/services/ios-log-filter.ts
package.json

#2129 
* Merge after [https://github.com/telerik/mobile-cli-lib/pull/827]( https://github.com/telerik/mobile-cli-lib/pull/827)

Filter iOS log to show original file location for ts files

---

lib/npm-installation-manager.ts
lib/services/ios-debug-service.ts
lib/services/platform-service.ts

Support frameworkPath when installing tns-ios-inspector

---

lib/commands/devices.ts

Fixed: `tns devices <platform>` throws an exception

---

CocoaPods.md
lib/services/doctor-service.ts

http://blog.cocoapods.org/Sharding/
This pull request goes with https://github.com/NativeScript/docs/pull/566.

Update min supported pod version

---

lib/services/platform-service.ts

Typo fixed

---

package.json
test/npm-support.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/2242

Update ShellJS to v0.7.5

---

lib/services/plugins-service.ts

enables adding plugins with path to local tgz file
ping @dtopuzov

fix plugin add command when adding tgz

---

lib/services/livesync/android-device-livesync-service.ts
lib/services/livesync/ios-device-livesync-service.ts

Fixed: livesync should continue to work after app crash

---

lib/services/app-files-updater.ts
lib/services/livesync/livesync-service.ts

Fixes: Provision to watch files in symlinked directories for livesync command

---

lib/services/android-debug-service.ts

CLI changes for https://github.com/NativeScript/android-runtime/pull/652

enable v8-inspector support

---

lib/services/platform-service.ts

Fixed: emulate command not working for iOS

---

lib/android-tools-info.ts

related to https://github.com/NativeScript/android-runtime/commit/3a92285af04a626b8fc4ad4534ac0d0a1d5acff7

check for Android build tools >=25.0.2

---

lib/commands/update.ts

Error: Could not backup project folders!

Fixed: tns update crashes with error message

---

lib/services/livesync/platform-livesync-service.ts
lib/services/platform-service.ts

*!! MERGE AFTER: https://github.com/telerik/mobile-cli-lib/pull/876 !!*

Fixed: getfile/putfile operate with global files (not local ones)

---

.travis.yml

Update Travis NPM token.

---

.travis.yml

The travis CLI tool must have broken the config the first time.

Second attempt at fixing travis key.

---

lib/options.ts
lib/services/livesync/livesync-service.ts

fix for #2469 applied in master not with cherry picking, because it would be too much of a murge hasste because of fibers refactoring

applied hotfix in master

---

lib/node-package-manager.ts
lib/services/platform-service.ts

Fix android custom platform template installation.

---

package.json

see more https://github.com/NativeScript/nativescript-cli/issues/2491

fix for #2491

---

package.json

Set version to 2.5.2

---

lib/definitions/project.d.ts
lib/services/project-service.ts
test/project-commands.ts
test/project-service.ts

We need a method in the public API to check if a directory contains valid NativeScript project.

Add isvalid {N} project method

---

lib/commands/appstore-upload.ts
lib/commands/build.ts
lib/commands/run.ts
lib/definitions/platform.d.ts
lib/definitions/plugins.d.ts
lib/definitions/project.d.ts
lib/providers/livesync-provider.ts
lib/services/android-project-service.ts
lib/services/ios-debug-service.ts
lib/services/ios-project-service.ts
lib/services/livesync/livesync-service.ts
lib/services/livesync/platform-livesync-service.ts
lib/services/platform-service.ts
lib/services/plugins-service.ts
test/ios-project-service.ts
test/npm-support.ts
test/platform-service.ts
test/stubs.ts

* fixed up a couple of interfaces
* renamed methods
* removed some obsolete code
* moved `--available-devices` flag to run command

refactoring in order to start moving functionality from emulate to run command

---

test/npm-support.ts

fixed missing colon

---

lib/nativescript-cli-lib-bootstrap.ts

Fix justlaunch casing

---

lib/device-sockets/ios/socket-proxy-factory.ts

Currently `tns debug ios` fails as we have changed the code to and now socketFactory returns a promise.
Fix the implementation so the Safari debugger will work.

Fix debug ios command

---

docs/man_pages/project/testing/run-android.md
docs/man_pages/project/testing/run-ios.md
lib/commands/emulate.ts

update documentation and deprecation message

---

CHANGELOG.md
package.json

- Bump version to 2.5.4
- Add changelog for 2.5.4

Prepare release 2.5.4

---

setup/native-script.rb

- Change homebrew to use cask for android sdk installation
- Replaced android command tool with sdkmanager

Fix installation scripts for Mac

---

PublicAPI.md
test/nativescript-cli-lib.ts

Docs mainly.
Merge after https://github.com/telerik/mobile-cli-lib/pull/948

Expose service for configuration

---

lib/node-package-manager.ts
lib/services/doctor-service.ts

Reverts NativeScript/nativescript-cli#2749

Revert "Merge release in master"

---

CHANGELOG.md

Updated Changelog for 3.0.0 release

---

lib/nativescript-cli.ts

Do not exit with exit code 0 upon an uncaught exception
Ping @yyosifov @rosen-vladimirov

Set correct exit code upon ucaught exception

---

CHANGELOG.md
package.json

- Bump version to 3.0.1
- Changelog for 3.0.1

Release notes for 3.0.1

---

.travis.yml
.travis/add-publishConfig.js

Set `rc` tag to the publishConfig section for the release branch.

Update Travis CI Scripts

---

lib/providers/livesync-provider.ts

The Angular issue with refreshing the App is now resolved and we can again sync .css/.html files.

Add .html to the fast-sync files

---

README.md

Adding a small section describing the default behavior of the Entitlements.

Add a section for Entitlements

---

CHANGELOG.md
package.json

Increase version to 3.0.1 and add changelog

Increase version to 3.0.2 and add changelog

---

PublicAPI.md
lib/bootstrap.ts
lib/services/analytics-service.ts
test/nativescript-cli-lib.ts

Required so that we can track fusion's features separately.
Merge after https://github.com/telerik/mobile-cli-lib/pull/971
Ping @TsvetanMilanov @rosen-vladimirov

Expose a way to set projectApiKey for analytics

---

lib/services/ios-project-service.ts

We will use custom URL scheme to open iOS app from the browser. 
This way we will support app restart on Windows. 
Related to:  https://github.com/NativeScript/ios-runtime/issues/746

Add CFBundleURLSchemes when building for iOS in debug.

---

test/project-service.ts

Currently our tests regarding templates taken from `<url>.git` and `<url>/tarball/master` perform wrong checks.
They download the template from said source and then download the template from npm. One cannot expect that the files in both package will always be equal.

Fix unit tests

---

lib/services/debug-service.ts

This reverts commit 5b1141c1bcc8362acce97d2b69422de19959942e.
In case a second debug attempt fails just throw the error.

Revert "Restart app upon debugging"

---

lib/commands/run.ts

https://github.com/NativeScript/nativescript-cli/issues/2903

Pass correct release arguments to run command

---

LICENSE

Fix LICENSE years

---

lib/commands/run.ts
lib/services/livesync/livesync-command-helper.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/2361. Adds the changes from https://github.com/telerik/mobile-cli-lib/pull/985.

Fix itunes error after run android

---

lib/services/livesync/android-device-livesync-service.ts

(android) Don't restart application twice after it crashes for any reason.
_problem_
scenario:
* livesync is running and the user crashes the application (e.g. delete `app.js` in js template)
* user realizes mistake and fixes it (e.g undo delete of `app.js`)
* livesync starts the application twice
_solution_
pass the unsuccessful reload check to the provided process for checking if an application should be restarted
_effect_
The expected behavior after this PR is, after a crash or in other cases where the runtime socket is not started or crashing, there won't be two restarts of the device.
>Note: I tested these scenarios on iOS, and there seem to be no such issues.

don't restart application twice on crash

---

lib/services/ios-project-service.ts

Fix small typo in ios-project-service.ts

---

npm-shrinkwrap.json
package.json

Update ios-device-lib to latest version - 0.4.10. The main fix there is a case where CLI may hang while awaiting for notification from iOS application.

Update ios-device-lib to 0.4.10

---

lib/services/android-project-service.ts

Fix https://github.com/NativeScript/nativescript-cli/issues/3224

Fix build if android-runtime version is "next".

---

lib/options.ts
lib/services/ios-debug-service.ts

add --inspector flag to tns options

---

package.json

Bump version to 4.0.0 for the next major release.

Bump CLI version.

---

package.json

Revert version to 3.4.1

---

README.md

Add waffle.io badge to waffle board in order to give more visibility to the current issues status

chore: add waffle.io badge

---

package.json

Set version to 3.4.2

---

.github/ISSUE_TEMPLATE.md

Also add a link to the playground to reproduce the issue easily

Change StackOverflow with {N} Forum

---

lib/services/doctor-service.ts
lib/services/ios-project-service.ts

Support brew version of Cocoapods
Fixes https://github.com/NativeScript/nativescript-cli/issues/3276

feat(doctor): Support xcodeproj from brew

---

docs/man_pages/index.md

docs: run can be ran with no args 

---

.gitattributes

Discussed in https://github.com/NativeScript/docs/pull/1071

chore: set line endings for shell scripts

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

Update version.
Update Changelog.

chore(release): Preapre for 3.4.3 release

---

docs/man_pages/lib-management/plugin-build.md
docs/man_pages/lib-management/plugin.md
lib/bootstrap.ts
lib/commands/plugin/build-plugin.ts
lib/definitions/android-plugin-migrator.d.ts
lib/services/android-plugin-build-service.ts
test/stubs.ts

introduce tns plugin build command which builds android plugins. I've included man markdown articles for the new command.
Associated with the `plamen5kov/rebuild-aar` branch.

feat(command): introduce tns plugin build command 

---

lib/helpers/livesync-command-helper.ts

This is currently not possible so throw an error if this is the case
Ping @sis0k0 @rosen-vladimirov

feat: fail if bundling both platforms

---

vendor/gradle-plugin/build.gradle

newer versions of google's m2repository is resolved from maven

fix: add maven repository

---

npm-shrinkwrap.json
package.json

Also this PR fixes 2 of security vulnerabilities problems - https://nodesecurity.io/check/nativescript

Remove unused plistlib library

---

lib/constants.ts
lib/services/android-project-service.ts

Fixes https://github.com/NativeScript/nativescript-cli/issues/3477

Fix invalid version rc when adding android platform

---

npm-shrinkwrap.json
package.json

In order to fix vulnerabilities problems we need to update the version of request module - https://nodesecurity.io/check/nativescript

Update request module version

---

npm-shrinkwrap.json
package.json

chore: Bump version to 4.0.1

---

npm-shrinkwrap.json
package.json

chore: Bump version to 4.1.0

---

CHANGELOG.md

Merge release into master

---

npm-shrinkwrap.json
package.json

Update common lib sha and ios-sim version

Update common lib and ios-sim version

---

CHANGELOG.md

Update Changelog for 4.0.2 release

chore: Update Changelog for 4.0.2 release

---

lib/services/livesync/android-device-livesync-service.ts

Currently the LiveSync operations on Android devices uses a hardcoded port - 18182 to wait for a message from the runtime and determines if we should clean the LiveSync temp directories on the device.
The port forwarding is executed every time on all of the devices. This is a problem  when the hardcoded port is already used by another application.
In order to fix this, execute the port forwarding only once per device and persist the port. Use the newly introduced method in android-process-service, which will check if there's already a forwarded port for the specified abstract port. In case there's no such forwarding, a new free port is taken and the forwarding is executed. Once CLI finishes its work, the port forwarding is removed.
This ensures we'll execute only one port forwarding per …

fix: Remove hardcoded port for livesync on Android

---

npm-shrinkwrap.json
package.json

chore: Update version to 4.2.0

chore: Update version to 4.2.0

---

npm-shrinkwrap.json
package.json

Fixes https://github.com/NativeScript/nativescript-cli/issues/3625

Update ios-sim to latest version

---

README.md

Update the diagram reference in the README, so it will be rendered correctly in https://www.npmjs.com/package/nativescript
The diagram of CLI is not rendered in https://www.npmjs.com/package/nativescript
After publishing this version in npm, the diagram will be rendered correctly.

docs: Update diagram reference

---

npm-shrinkwrap.json
package.json

chore: Bump version to 4.1.2

---

CHANGELOG.md

docs: Update Changelog for 4.1.2

---

lib/bootstrap.ts
lib/constants.ts
lib/declarations.d.ts
lib/definitions/pacote-service.d.ts
lib/definitions/pacote.d.ts
lib/definitions/project.d.ts
lib/node-package-manager.ts
lib/services/pacote-service.ts
lib/services/project-service.ts
lib/services/project-templates-service.ts
npm-shrinkwrap.json
package.json
test/project-service.ts
test/project-templates-service.ts
test/stubs.ts

The user is not able to use template v2 with predefined firebase config file.
The user is able to use template v2 with predefined firebase config file.

Allow project creation with template v2 with predefined firebase config

---

.travis.yml

Update the token for publishing rc and next version through travis.

fix: Update token for publishing next and rc

---

.travis.yml

Sidekick crashes on windows machines
Sidekick should start normally

chore: update common lib to get fix for detecting iOS devices on Win

---

npm-shrinkwrap.json
package.json

chore: Bump version to 4.3.0

---

CHANGELOG.md

docs: update Changelog for 4.2.0

docs: update Changelog for 4.2.0

---

CONTRIBUTING.md

Update the label required for a feature request submission

Update feature request lavel

---

lib/services/livesync/android-livesync-tool.ts

Fix minor typo
Ping @KristianDD @Fatme

fix: minor typo

---

.github/ISSUE_TEMPLATE.md
CHANGELOG.md
README.md
lib/commands/post-install.ts
lib/services/platform-environment-requirements.ts
npm-shrinkwrap.json
package.json

chore: merge release in master

chore: merge release in master

---

lib/services/platform-environment-requirements.ts
test/services/platform-environment-requirements.ts

QR is not shown when env is not properly configured.
QR is shown when env is not properly configured.

chore: generate QR code when env is not properly configured

---

lib/definitions/plugins.d.ts
lib/services/livesync/playground/preview-app-plugins-service.ts
lib/services/plugins-service.ts
lib/tools/node-modules/node-modules-dest-copy.ts
test/services/playground/preview-app-plugins-service.ts

refactor: remove projectData from PreviewAppPluginsService in order to work from Sidekick

---

lib/definitions/qr-code.d.ts
lib/services/livesync/playground/qr-code-generator.ts
lib/services/qr-code-terminal-service.ts

No messages are shown above the QR code on preview command
Messages are shown above the QR code on preview command

fix: show color messages above the QR code on preview command

---

lib/services/livesync/playground/preview-sdk-service.ts

chore: show warning when files to upload exceed the maximum allowed size of 15MB

---

lib/services/livesync/playground/qr-code-generator.ts

fix: improve texts shown on preview command

---

lib/services/livesync/playground/preview-sdk-service.ts
npm-shrinkwrap.json
package.json

A white screen is shown on device when preview command is executed.
Show loading page on device when preview command is executed.

feat: show loading page on device on preview command

---

lib/services/livesync/playground/preview-sdk-service.ts

fix: don't show loading page on device

---

lib/commands/create-project.ts
lib/common/services/help-service.ts

fix: propose preview instead of run on project creation

---

lib/tools/node-modules/node-modules-builder.ts

See issue
See issue
Fixes/Implements/Closes https://github.com/NativeScript/nativescript-cli/issues/4033

fix: remove node modules when prepare with bundle flag

---

lib/tools/node-modules/node-modules-builder.ts

Merge release branch into master

---

lib/services/livesync/livesync-service.ts

Related to https://github.com/NativeScript/nativescript-cli/issues/2670#issuecomment-432565568

fix: stop making a full rebuild on livesync when the --clean flag is set

---

docs/man_pages/project/testing/preview.md

docs: unified the beta warning in the preview help

---

CHANGELOG.md

prepare changelog for 5.0.0 release

docs: prepare changelog for 5.0.0 release

---

lib/services/livesync/playground/preview-app-livesync-service.ts

refactor: extract preview sync hook to separate method

---

lib/services/project-service.ts

Related to: https://github.com/NativeScript/nativescript-cli/issues/4096#issuecomment-436224330

fix: use the specified template version while extracting its package

---

npm-shrinkwrap.json
package.json

chore: bump version to 5.0.2

---

PublicAPI.md

Docs for the public api for preview 

---

npm-shrinkwrap.json
package.json

chore: update doctor to 1.8.1 version

---

npm-shrinkwrap.json
package.json

fix: update nativescript-preview-sdk version to 0.3.1 and cli's version to 5.0.3

---

CHANGELOG.md

chore: add changelog for 5.0.3 release

---

npm-shrinkwrap.json
package.json

chore: set version to 5.2.0

---

npm-shrinkwrap.json
package.json

Related to: https://github.com/NativeScript/nativescript-cli/issues/4218

fix: fix stopApplication on Simulator while the app is on a breakpoint

---

CHANGELOG.md

docs: update CHANGELOG for 5.1.1

docs: update CHANGELOG for 5.1.1

---

docs/man_pages/index.md

`Preview` is not shown when `tns help` command is executed
`Preview` is shown when `tns help` command is executed

fix: add preview to html's docs

---

lib/services/ios-project-service.ts

See issue.
See issue.
Fixes/Implements/Closes https://github.com/NativeScript/nativescript-cli/issues/4343

fix: objective-C source code not added from App Resources

---

npm-shrinkwrap.json
package.json

chore: set version to 5.3.0

---

docs/man_pages/project/testing/run.md

docs: add missing options in the run help

---

lib/services/livesync/ios-device-livesync-service.ts

fix: shouldRestart will now return true if the app is not running instead of throwing an exception

---

npm-shrinkwrap.json
package.json

fix: update lodash because of "a potential security vulnerability"

---

docs/man_pages/project/testing/run.md
npm-shrinkwrap.json
package.json
resources/assets/image-definitions.json

chore: merge release-patch in release

chore: merge release-patch in release

---

docs/man_pages/project/testing/build-android.md
docs/man_pages/project/testing/build-ios.md

docs: fix help for `--copy-to` option

---

yarn.lock

chore: update the yarn.lock

---

npm-shrinkwrap.json
package.json

chore: set version to 5.2.3

---

CHANGELOG.md

update Changelog for 5.2.2 and 5.2.3 releases

chore: update Changelog for 5.2.2 and 5.2.3 releases

---

README.md

fix: change nativescript image in readme.md

---

npm-shrinkwrap.json
package.json

chore: update nativescript-dev-xcode lib

---

npm-shrinkwrap.json
package.json

fix: update ns-dev-xcode to fix extension framework removal

---

Gruntfile.js

fix(grunt): generate unit testing dependencies on grunt rebuild command

---

lib/definitions/plugins.d.ts
lib/definitions/project.d.ts
lib/services/android-project-service.ts
lib/services/ios-project-service.ts
lib/services/plugins-service.ts
lib/services/prepare-platform-native-service.ts
test/stubs.ts

chore: remove legacy code from ios-project-service

---

CHANGELOG.md

chore: add changelog for 5.3.2 release

---

CHANGELOG.md
lib/bootstrap.ts
lib/commands/appstore-list.ts
lib/commands/appstore-upload.ts
lib/declarations.d.ts
lib/services/apple-portal/apple-portal-application-service.ts
lib/services/apple-portal/apple-portal-cookie-service.ts
lib/services/apple-portal/apple-portal-session-service.ts
lib/services/apple-portal/definitions.d.ts
lib/services/itmstransporter-service.ts

chore: merge release into master

---

CHANGELOG.md

chore: add changelog for 5.3.3 and 5.3.4

---

CHANGELOG.md

chore: add changelog for 5.3.1 release

---

lib/services/ios-project-service.ts

chore: update watchapp beta warning

---

lib/services/test-execution-service.ts
resources/test/karma.conf.js

Related to: https://github.com/NativeScript/nativescript-vscode-extension/issues/251

fix (test command): generate source maps when debug-brk is set

---

lib/options.ts

fix: do not use HMR when debugBrk is set as we will restart the app on each LiveSync

---

npm-shrinkwrap.json
package.json

chore: set version to 6.0.0

---

CHANGELOG.md

update changelog for 5.4.0 release

docs: update changelog for 5.4.0 release

---

lib/commands/build.ts
lib/commands/deploy.ts
lib/commands/prepare.ts
lib/controllers/deploy-controller.ts

Rel to: https://github.com/NativeScript/nativescript-cli/issues/4637

fix: fix the application crash on device on deploy command

---

lib/controllers/preview-app-controller.ts

`tns preview` command doesn't respect changes
`tns preview` works

fix: fix tns preview

---

lib/data/build-data.ts

`tns build ios --for-device` command doesn't produce .ipa as `--for-device` option is not respected and the application is built for simulator.

fix: respect `--for-device` option when building for iOS device

---

lib/services/webpack/webpack-compiler-service.ts

fix: increase the max process's size in order to prevent "JavaScript heap out of memory error"

---

lib/controllers/deploy-controller.ts

`tns deploy ios --justlaunch` builds the application always for simulator as `device.isEmulator` option is not respected on build.

fix: fix deploy on iOS devices

---

lib/controllers/run-controller.ts

fix: build only once when there are more than one android devices

---

lib/services/project-changes-service.ts

fix: initialize nativeChanged with true when checking for changes

---

CHANGELOG.md

docs: update Changelog for 5.4.2

---

lib/controllers/migrate-controller.ts

fix: update  the migrate versions to newer ones

---

lib/common/services/hooks-service.ts

Rel to: https://github.com/NativeScript/nativescript-cli/issues/4770

fix: fix the execution of hooks when there is unresolved injected dependency

---

lib/commands/appstore-upload.ts
lib/definitions/build.d.ts
lib/services/ios-project-service.ts

fix: fix publish command

---

lib/controllers/migrate-controller.ts

fix: migrate tns-platform-declarations as well

---

lib/controllers/migrate-controller.ts

fix: update dependencies to latest rc versions

---

lib/controllers/migrate-controller.ts

fix: update the version of nativescript-dev-webpack plugin on migrate command

---

lib/controllers/preview-app-controller.ts

Currently CLI doesn't detach the PREPARE_READY_EVENT on stopPreview and this led to executing multiple times the livesync operation from sidekick.

fix: fix preview from Sidekick

---

lib/helpers/deploy-command-helper.ts

fix: add skipNativePrepare to buildData

---

lib/controllers/migrate-controller.ts

fix: show warning for less only when the project has nativescript-dev-less plugin as dependency

---

lib/controllers/migrate-controller.ts

chore: update migrate dependencies

---

docs/man_pages/general/migrate.md
docs/man_pages/project/configuration/prepare.md
docs/man_pages/project/testing/build-android.md
docs/man_pages/project/testing/build-ios.md
docs/man_pages/project/testing/build.md
docs/man_pages/project/testing/debug-android.md
docs/man_pages/project/testing/debug-ios.md
docs/man_pages/project/testing/preview.md
docs/man_pages/project/testing/run-android.md
docs/man_pages/project/testing/run-ios.md
docs/man_pages/project/testing/run.md
docs/man_pages/project/testing/test-android.md
docs/man_pages/project/testing/test-ios.md

docs: update `tns migrate` docs based on the latest changes

---

lib/services/webpack/webpack-compiler-service.ts

Rel to: https://github.com/NativeScript/nativescript-cli/issues/4497

fix: don't override `--env.production` and `--env.verbose` when provided from user

---

lib/controllers/preview-app-controller.ts
test/services/playground/preview-app-livesync-service.ts

Fixes/Implements/Closes https://github.com/NativeScript/nativescript-cli/issues/4861

fix: preview for app downloaded from playground fails

---

CHANGELOG.md

update Changelog for 6.0 release

chore: update Changelog for 6.0 release

---

lib/controllers/migrate-controller.ts

fix: bump the version of `nativescript-unit-test-runner` from migrate

---

lib/controllers/run-controller.ts

fix: fix issues when stopping the livesync process

---

lib/controllers/migrate-controller.ts

fix: add forgotten migrate dependencies for Vue and Angular apps

---

docs/man_pages/general/migrate.md
lib/controllers/migrate-controller.ts

Related to: https://github.com/NativeScript/nativescript-angular/issues/1895

fix(migrate): include forgotten Angular dependency from the code-sharing apps

---

CHANGELOG.md

docs: changelog for 6.0.2

---

config/test-dependencies.json

Fixes: https://github.com/NativeScript/nativescript-cli/issues/4746

fix: hardcode karma-webpack to 3.0.5

---

npm-shrinkwrap.json
package.json

chore: bump version to 6.0.4

---

lib/services/android-project-service.ts

fix: aab name changed to include build mode(debug, release)

---

npm-shrinkwrap.json
package.json

Fixes https://github.com/NativeScript/nativescript-cli/issues/4926

chore: update doctor version

---

npm-shrinkwrap.json
package.json

chore: bump version to 6.2.0

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

Bump version and update changelog.

release: cut 6.1.2 release

---

lib/controllers/prepare-controller.ts
lib/controllers/preview-app-controller.ts
test/controllers/prepare-controller.ts

fix: avoid marking mode checks in iOS commands

---

npm-shrinkwrap.json
package.json

Rel to: https://github.com/NativeScript/nativescript-cli/issues/5005

fix: update the version of nativescript-dev-xcode

---

npm-shrinkwrap.json
package.json

Rel to: https://github.com/NativeScript/nativescript-cli/issues/5020

fix: update ios-device-lib to the latest version

---

lib/services/prepare-data-service.ts

Rel to: https://github.com/NativeScript/nativescript-cli/issues/4963

fix: unify the casing of hookArgs.prepareData.platform from prepare and run commands

---

npm-shrinkwrap.json
package.json

chore: bump version to 6.3.0

---

lib/controllers/migrate-controller.ts

chore: add trace for shouldMigrate caching

---

CHANGELOG.md

chore: create changelog for 6.2.1 release

---

lib/constants.ts
lib/controllers/update-controller.ts

Fixes/Implements/Closes https://github.com/NativeScript/nativescript-cli/issues/5149

fix: update scoped core package

---

lib/commands/update.ts

Fixes/Implements/Closes https://github.com/NativeScript/nativescript-cli/issues/5115

fix: update requires migrate for invalid versions

---

docs/man_pages/cloud/cloud-setup.md

Updated documentation for cloud builds

---

lib/common/mobile/android/android-emulator-services.ts
lib/common/mobile/emulator-helper.ts

Related to: https://github.com/NativeScript/nativescript-cli/issues/5069

feat: support API 29 emulators during available devices detection

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

release: cut 6.3.1 release

---

CHANGELOG.md

release: cut 6.3.2 release

---

CHANGELOG.md

release: prepare changelog for 6.3.3

---

lib/common/logger/logger.ts

Related to: https://github.com/NativeScript/nativescript-cli/issues/5255

docs: warn when the log level is TRACE or ALL as the CLI might print sensitive data

---

npm-shrinkwrap.json
package.json
test/ios-project-service.ts

closes https://github.com/NativeScript/nativescript-cli/issues/5306
Dependent on this being merged and published first: https://github.com/NativeScript/nativescript-doctor/pull/60

feat(node): support for node 14+

---

npm-shrinkwrap.json
package.json

closes https://github.com/NativeScript/nativescript-cli/issues/5330

feat(android): doctor support for android 30

---

lib/controllers/platform-controller.ts
lib/services/platform/platform-validation-service.ts

fix: platform clean not adding the platform back

---

lib/services/project-data-service.ts

fix: platform sometimes not in lower case

---

lib/common/prompter.ts

Fixes https://github.com/NativeScript/NativeScript/issues/9131

fix: prompter returning undefined instead of value

---

docs/man_pages/general/resources.md
docs/man_pages/project/configuration/resources/resources.md

`ns resources --help` command is not working.
`ns resources --help` command print out the options to use `ns resources` with.
Fixes #5471

docs: resources help

---

lib/common/dispatchers.ts
lib/options.ts

`ns --version` command prints out only the current version of the cli.
`ns --version` command prints out the current version and the latest available version of the cli with an instruction for update.

feat: version command check update

---

lib/services/project-data-service.ts

fix: runtime version detection for tags

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #5603
Updated the link to https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages

fix: Update link to commit message guidelines

---

lib/services/doctor-service.ts

`ns doctor android` prints an error:
```
Cannot read property 'toLowerCase' of null
```
It fails because null is passed as `platform` to `PlatformEnvironmentRequirements.getEnvVerificationMessage()`.
No error

Fix error when printing environment verification message

---

lib/controllers/run-controller.ts

feat: add watchAction hooks

---

lib/controllers/migrate-controller.ts

`ns migrate` will auto bump core deps and runtimes to latest 8.3.

feat: migrate for 8.3

---

lib/services/platform-environment-requirements.ts

fix: handle unknown/undefined platform edge case

---

vendor/gradle-plugin/build.gradle

fix: get `targetSdkVersion` from props

---

config/test-dependencies.json
package-lock.json

fix(testing): pin karma-jasmine to 4.0.2

---

lib/services/android-project-service.ts

Simple PR which first adds support for unsigned APKs (needed for f-droid) and also refactor the regexps into one

fix(android): support unsigned apks

---

lib/base-package-manager.ts
lib/bootstrap.ts
lib/commands/preview.ts
lib/common/dispatchers.ts
lib/constants.ts
lib/declarations.d.ts
lib/options.ts
lib/package-installation-manager.ts
lib/package-manager.ts
lib/services/android-plugin-build-service.ts
lib/services/pacote-service.ts
lib/yarn2-package-manager.ts
test/controllers/add-platform-controller.ts
test/package-installation-manager.ts
test/plugins-service.ts
test/services/extensibility-service.ts

feat: yarn2+ support

---

lib/services/ios-native-target-service.ts

In an extensions.json file you can specify a single set of  `targetBuildConfigurationProperties` which are applied to both debug and release, I want to be able to apply different properties to debug vs release.
Allows you to specify different build properties for debug and release for extensions.
So as not to break existing it adds a new property `targetNamedBuildConfigurationProperties` where you can specify 'release' or 'debug' properties.
e.g.
```
"targetNamedBuildConfigurationProperties": {
"debug"
"MTL_ENABLE_DEBUG_INFO" : "INCLUDE_SOURCE",
},
"release": {
"MTL_ENABLE_DEBUG_INFO" : "NO",
}
}
```

feat(extensions): Allow seperate release /debug build configuration properties for extensions

---

package-lock.json
package.json
yarn.lock

feat: allow running on visionOS

---

package.json

chore: 8.6.2 next

---

lib/commands/create-project.ts
lib/constants.ts
lib/controllers/migrate-controller.ts
lib/declarations.d.ts
test/project-commands.ts

`ns migrate` would not update to {N} 8.7 with latest flavor updates.
`ns migrate` will now update to {N} 8.7 with latest flavor updates.

feat: support for solid/solidjs templates and migrations for 8.7

---

lib/common/mobile/android/logcat-helper.ts

* `ns run android`
* Restart the app
There is no log output to the console after the app restarts because the regex passed to the monitoring stream is incorrect. ( and in any case doesn't match the tighter regex used later)
Console output continues after the app restarts.

fix(android): logging after app restart

---

Gruntfile.js
package-lock.json
package.json

closes https://github.com/NativeScript/NativeScript/security/dependabot/17

fix(security): axios 1.11.0
