- lib/commands/debug.ts
- lib/definitions/livesync.d.ts
- lib/helpers/livesync-command-helper.ts
Allow passing of `skipNativePrepare` for the LiveSync operation. Whenever building in the cloud one wouldn't need to prepare the project natively
Merge after https://github.com/telerik/mobile-cli-lib/pull/1065
> refactor: allow pass skipnativeprepare

- lib/services/doctor-service.ts
- npm-shrinkwrap.json
- package.json
Related to this PR https://github.com/NativeScript/nativescript-doctor/pull/30
Should be merged after this PR https://github.com/telerik/mobile-cli-lib/pull/1064
Fixes cloud builds regression problem.
> Get sysInfos based on specified platform

- lib/services/doctor-service.ts
During commands like prepare, build, run, etc. CLI checks the local environment for specified platform. In case there are issues, the full system information should be printed.
However, in case everything is fine, CLI should not print the information. Fix this by removing incorrect line that prints all of the info.
> fix: Do not print sysinfo if everything is fine

- lib/constants.ts
- lib/services/project-data-service.ts
- test/services/project-data-service.ts
In case plugin name has dot (`.`) in its name, the `plugin remove` command fails.
The reason is the way we are trying to remove plugin related data from the `nativescript` key of application's package.json.
We are using `.` to concatenate the keys inside nativescript key and later we are trying to split by `.` in order to find which key should be deleted.
This works in most of the cases, but when the plugin name has `.` in it, our logic fails as the split operation finds the dot.
Fix this by using some symbols that are not allowed in npm for plugins names. Use symbols that will rarely be used in the same sequence.
Fixes https://github.com/NativeScript/nativescript-cli/issues/3451
> fix: Plugin remove command fails in case plugin name has dot

- lib/declarations.d.ts
- lib/services/doctor-service.ts
- lib/services/info-service.ts
- lib/services/versions-service.ts
Currently when doctor command is executed, NativeScript components versions information is displayed as table. With this PR NativeScript components versions will be displayed with terminal spinners.
In case when component is up to date with latest available version, success spinner will be displayed.
In case when for component update is available, warn spinner will be displayed.
In case when component is not installed, fail spinner will be displayed.
This PR changes also the behaviour of `tns info` command. When `tns info` command is executed,  NativeScript components versions information also will be displayed with terminal spinners.
Should be merged with this PR https://github.com/telerik/mobile-cli-lib/pull/1066
> Add spinner when checking for NativeScript components versions

- lib/services/platform-environment-requirements.ts
Rename the generic `SKIP_ENV_CHECK` to `NS_SKIP_ENV_CHECK` in order to mitigate any potential clashes with other tools.
Ping @Fatme @rosen-vladimirov
> refactor: rename skipenv variable

- lib/constants.ts
- lib/definitions/platform.d.ts
- lib/definitions/project.d.ts
- lib/services/android-project-service.ts
- lib/services/ios-project-service.ts
- lib/services/platform-service.ts
- test/platform-commands.ts
- test/platform-service.ts
- test/stubs.ts
This PR adds support for multiple .apk files produced from gradle build in following cases:
1. When productFlavors are used
Add this to `app/App_Resources/app.gradle` file
```
flavorDimensions "arch", "mode"
productFlavors {
demo {
dimension "mode"
}
full {
dimension "mode"
}
x86 {
dimension "arch"
}
arm {
dimension "arch"
}
arm64 {
dimension "arch"
}
}
```
2. When splits option is used
Add this to `app/App_Resources/app.gradle` file
```
splits {
abi {
enable true //enables the ABIs split mechanism
reset() //reset the list of ABIs to be included to an empty string
include 'arm64-v8a', 'armeabi-v7a', 'x86'
universalApk true
}
}
```
> Support multiple .apk files produced from gradle build

- lib/constants.ts
- lib/definitions/project.d.ts
- lib/services/assets-generation/assets-generation-service.ts
- lib/services/project-data-service.ts
- resources/assets/image-definitions.json
Fix the generation of asset - the filter is incorrect and fails with `Cannot read property 'splashImages' of null, TypeError: Cannot read property 'splashImages' of null`
Also fix the scale - it has been incorrectly declared as number, when it is string (1x, 2x, etc.). Use the scale correctly by parsing it and use it when generate the image.
Also fix the using of resizeOperation property - it was not passed correctly for iOS assets.
chore: Update to latest common lib
> fix(assets): Fix asset genration 

- CHANGELOG.md
> chore: Update CHANGELOG for 4.0.0rc

- lib/services/ios-entitlements-service.ts
- lib/services/ios-project-service.ts
- test/ios-entitlements-service.ts
- test/ios-project-service.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/3481
> Do not create empty .entitlements file

- lib/services/platform-service.ts
In case when productFlavors or split option is used in .gradle file more than on .apk files are produced. Print warning that will be used the last one produced from build.
> Print warning when more than one package is produced from build

- lib/definitions/simple-plist.d.ts
- lib/services/ios-project-service.ts
- lib/services/itmstransporter-service.ts
- npm-shrinkwrap.json
- package.json
- test/ios-project-service.ts
In case when produced Info.plist is not a binary file, `tns publish ios` command fails because `bplist-parser` is not able to parse non-binary plist files. This PR replaces `bplist-parser` module with `sample-plist` that is able to parse binary and xml files.
Fixes https://github.com/NativeScript/nativescript-cli/issues/3470
> Fix (publish): Remove binary-plist and use simple-plist instead

- lib/commands/create-project.ts
- lib/commands/post-install.ts
- lib/definitions/project.d.ts
- lib/services/project-service.ts
- test/project-commands.ts
- test/project-service.ts
Introduce postCommandAction that is executed when the command succeeds.
Use the action to print additional information to user how to continue after command is finished.
Show some information on successful postinstall - instruct the users how to use local builds, cloud builds and playground.
> feat(commands): Introduce postCommandAction

- npm-shrinkwrap.json
- package.json
Ora's definition files are not needed in production package, so move it as devDependency.
> fix: Move @types/ora as devDependency

- docs/man_pages/project/configuration/resources/resources-generate-splashes.md
Fix the help of `tns generate splashes` command as the content for `--background` option is incorrect.
> docs: Fix the help of `tns generate splashes` command

- lib/services/android-resources-migration-service.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/3510
> fix(AppResources): try recover if resources update fails

- lib/services/platform-service.ts
In cloud builds, when we try to prepare the project for iOS, sometimes we fail as the `cleanDestinationApp` does not pass correct arguments to `ensurePlatformInstalled` method.
When we have cloud builds, the last argument should declare that the native prepartion should be skipped. When we do not pass it, the logic determines that the platform is not fully added and tries to add it again.
The whole `platforms/ios` directory is deleted and then we try preparing the project again. At some point the code fails as there are missing files in the `platforms/ios` (we have deleted them).
Pass the correct arguments, so the prepare will skip the native part in the mentioned case.
Trying to build application for iOS with webpack in Sidekick leads to error.
Correct arguments are passed and the …
> fix: Prepare for iOS with cloud builds fails on non macOS

- npm-shrinkwrap.json
- package.json
In case `xcrun simctl` throws some error, CLI does not handle it very well.
Improve the logic in ios-sim-portable and update its version in order to resolve the issue.
In case simctl is not configured correctly, CLI fails with `process.send is not a function`.
CLI prints the message from simctl, which shows the user what is misconfigured
> fix: Incorrect error is shown when xcrun simctl is not configured

- CHANGELOG.md
> chore: Update Changelog for 4.0.0

- lib/services/analytics/analytics-service.ts
In case the usage reporting is disabled, the verbose log of CLI still prints that will send information to Google Analytics. In fact it does not do it. The problem is that the message is printed before checking the state of the usage reporting.
Fix this by placing the printing in the correct method.
Fixes https://github.com/NativeScript/nativescript-cli/issues/3536
> fix(analytics): Message for tracking in GA is always printed

- PublicAPI.md
- test/nativescript-cli-lib.ts
Expose the `getAppProcessId` method from `androidProcessService`, so it can be called when using CLI as a library.
> NOTE: Merge after https://github.com/telerik/mobile-cli-lib/pull/1086
> feat(API): Expose androidProcessService - getAppProcessId

- lib/services/project-data-service.ts
- test/services/project-data-service.ts
In case you delete `App_Resources/iOS` directory, the `getAssetsStructure` method fails as it tries to read `Content.json` files from the deleted directory. Instead of failing, just return empty arrays for the images. This is already working this way for Android.
Add test for the case
Trying to generate/get assets structure fails when App_Resources/iOS is deleted
The generation of assets will work for Android in this case.
Fixes https://github.com/NativeScript/sidekick-feedback/issues/168 .
> fix(assets-generation): Do not fail in case some App_Resources are missing

- lib/definitions/android-plugin-migrator.d.ts
- lib/services/android-plugin-build-service.ts
- test/services/android-plugin-build-service.ts
In case the path to project has space in the name and there's Android plugin that should be build, the build operation fails. The reason is usage of exec - change it to spawn, which handles the spaces correctly.
feat: Add `buildAndroidPlugin` hook, which is executed just before spawning the gradle build for specific plugin. The hook can be used to modify plugin's structure before building the plugin.
Building of the plugin fails in case there's a space in the path to app.
Plugins can be successfully build.
Fixes https://github.com/NativeScript/nativescript-cli/issues/3560
> fix: Build plugins when path to project has space

- lib/services/project-service.ts
- test/project-service.ts
In case CLI is used as a library and `isValidNativeScriptProject` is called multiple times, it does not return correct results after the first time.
The problem is that it uses the singleton object - projectData. Change the implementation to use projectDataService, this way the method will always return correc results.
In case CLI is used as a library and `isValidNativeScriptProject` is called multiple times, it does not return correct results after the first time.
In case CLI is used as a library and `isValidNativeScriptProject` is called multiple times, it returns correct results.
> fix(API): isValidNativeScriptProject returns incorrect result

- lib/services/debug-service.ts
- test/services/debug-service.ts
The tracking if Inspector or Chrome is used as a debug tool is incorrect - currently it sends "Inspector" when `--inspector` is not specified. `Chrome` is sent only when `--chrome` is passed.
Fix the tracking and add tests.
Tracking for used debug tools is not correct - "Chrome" is the default option, but it is tracked only when `--chrome` is passed.
Tracking sends correct information when Inspector is used and when Chrome is used.
Fixes https://github.com/NativeScript/nativescript-cli/issues/3593
> fix: Tracking for used Debug tool is incorrect

- lib/constants.ts
- lib/services/project-templates-service.ts
- lib/services/subscription-service.ts
- npm-shrinkwrap.json
- package.json
- test/project-templates-service.ts
- test/services/subscription-service.ts
Do not track paths to projects when local template is used. Instead track `localTemplate_<name from template's package.json or dirname>`.
Also fix the prompter for emails as we need to show information how to unsubscribe from the newsletter.
Add tests for the behavior.
Fixes https://github.com/NativeScript/nativescript-cli/issues/3595
> fix(GDPR): Do not track local project paths

- npm-shrinkwrap.json
- package.json
Currently CLI detects iOS Devices with Wi-Fi sync enabled. However, we can only detect them, but we are not able to deploy and livesync applications on them. This also breaks the workflow with devices connected by USB, but with Wi-Fi sync enabled.
So detect only the USB connected devices and disregard the ones connected with Wi-Fi sync enabled. This is handled in the 0.4.11 version of ios-device-lib, so just update the version: https://github.com/telerik/ios-device-lib/releases/tag/v0.4.11
Devices with Wi-Fi sync enabled are detected by CLI, but it cannot work with them. Also devices connected with USB cable and Wi-Fi sync enabled are not usable as CLI fails to deploy/livesync the applications.
Devices with Wi-Fi sync enabled are not detected anymore.
Devices connected with USB cable and …
> fix: Detect iOS devices connected by USB only

- npm-shrinkwrap.json
- package.json
- vendor/gradle-plugin/build.gradle
- vendor/gradle-plugin/gradle/wrapper/gradle-wrapper.properties
Currently in case you have JAVA 9 or 10, CLI does not allow you to build your application. Remove the check for max JAVA version from nativescript-doctor and use the rc version of the package in CLI.
in case you have JAVA 9 or 10, CLI does not allow you to build your application.
CLI allows building apps with JAVA 9 or 10.
Implements https://github.com/NativeScript/nativescript-cli/issues/3605
> feat: Allow using JAVA 8+

- lib/bootstrap.ts
- lib/commands/debug.ts
- lib/declarations.d.ts
- lib/definitions/debug.d.ts
- lib/definitions/ios-debugger-port-service.d.ts
- lib/definitions/ios-log-parser-service.d.ts
- lib/definitions/project.d.ts
- lib/device-sockets/ios/notification.ts
- lib/device-sockets/ios/socket-request-executor.ts
- lib/helpers/livesync-command-helper.ts
- lib/services/ios-debug-service.ts
- lib/services/ios-debugger-port-service.ts
- lib/services/ios-log-parser-service.ts
- lib/services/ios-project-service.ts
- lib/services/livesync/ios-device-livesync-service.ts
- lib/services/platform-project-service-base.ts
- npm-shrinkwrap.json
- package.json
- test/services/ios-debug-service.ts
- test/services/ios-debugger-port-service.ts
- test/services/ios-log-parser-service.ts
- test/stubs.ts
The inspector listening socket is being closed 30 sec. after the last activity on it (opening, disconnection, etc). It had to be closed in order to have the hardcoded port number 18181
available for other apps after finishing (or never starting) a
debugging session. Without this timeout the first app that opened
the port would take it as long as it's running and would prevent
any subsequent debugging attempts of another app on the same iOS device;
or even the same app on another iOS Simulator on the same Mac machine.
This leads to unavailability to run fast sync on multiples simulators.
From now on, the port is printed from `ios-runtime` in devices logs. {N} CLI parses the logs and searches for specified string. The string should be in following format:
```
NativeScript debugger has …
```
> Get debugger port from device logs

- lib/constants.ts
- lib/definitions/project.d.ts
- lib/services/project-service.ts
- lib/services/project-templates-service.ts
- test/project-service.ts
- test/project-templates-service.ts
- test/stubs.ts
Currently when a project is created the content of the template is placed inside the `app` directory of the newly created project.
This leads to some issues when you want to support more complex scenarios, for example it is difficult to add configuration file (like nsconfig.json or webpack.config.js) in the root of the project.
The suggested solution to allow templates to be the full application is to check the template from which the application is created. In case the template contains a nativescript key and templateVersion property in it, check its value.
In case it is v1, use the old way, i.e. place the content of the template in the app directory of the created project.
In case it is v2 place the content of the template at the root of the application.
In case it is anything else - …
> feat: Allow templates to be full applications

- lib/services/ios-debugger-port-service.ts
CLI should be able to execute fast sync on devices and iOS Simulator (single instance) when using older runtime version (4.0.1 and prior).
However, currently it just hangs as the promise that should return the port for fast sync, is never resolved. Fix this by resolving the promise in this case.
LiveSync of .css files on iOS devices and Simulators when iOS Runtime is 4.0.1 or earlier, just hangs.
LiveSync of .css files is executed successfully.
> fix: Unable to fast sync changes with iOS runtime 4.0.1 and earlier

- npm-shrinkwrap.json
- package.json
In case iOS device is disconnected during LiveSync an unhandled rejection is thrown. The problem is in ios-device-lib, so update it to latest version - 0.4.12, where the issue is fixed.
Changelog: https://github.com/telerik/ios-device-lib/releases/tag/v0.4.12
1. Start livesync on iOS device: `tns run ios`
2. Apply some changes
3. After they are applied, disconnect the device
4. Unhandled rejection is thrown
Disconnecting the device does not throw any error.
> fix: Unhandled rejection is thrown when disconnection iOS Device

- lib/services/project-service.ts
`tns create template-tab-navigation-ng --template https://github.com/NativeScript/template-tab-navigation-ng#master` does not work
`tns create template-tab-navigation-ng --template https://github.com/NativeScript/template-tab-navigation-ng#master` works as expected
> Fix project creation

- lib/definitions/platform.d.ts
- lib/services/android-project-service.ts
- lib/services/doctor-service.ts
- lib/services/ios-project-service.ts
- lib/services/platform-environment-requirements.ts
- npm-shrinkwrap.json
- package.json
Update calls to `nativescript-doctor` package to pass projectDir where applicable. This allows the package to verify installed Java Compiler version against the project's Android runtime.
This is required in case the installed Java version is 10 or above and the Androud runtime in the project is older than 4.1.0. In this case the user cannot build this application for Android, but have to update the Android runtime version or downgrade the Java version.
> feat: Validate Java compiler version based on runtime version

- lib/declarations.d.ts
- lib/device-sockets/ios/notification.ts
- lib/device-sockets/ios/socket-proxy-factory.ts
- lib/services/ios-debug-service.ts
- lib/services/ios-debugger-port-service.ts
- lib/services/ios-log-parser-service.ts
- lib/services/livesync/ios-livesync-service.ts
- npm-shrinkwrap.json
- package.json
- test/services/ios-debugger-port-service.ts
In case multiple iOS Simulators are running and `tns debug ios` is called, CLI prompts you to select you on which device/simulator to debug.
Selecting the device and trying to debug your application leads to error as CLI does not pass correctly the device identifier.
Fix this by passing the correct device identifier.
Also update ios-sim-portable to latest version, where several fixes for this case are applied
The `tns debug ios --start` command fails as we do not get the port from iOS Application on device in this case. In order to fix this, start the log parsing in case --start option is passed.
Also fix the attaching to ATTACH_REQUEST_EVENT_NAME - we've incorrectly attached to device's application manager, which does not emit such event. Fix it by attaching to `iOSNotification`, which …
> fix: iOS debug issues 

- npm-shrinkwrap.json
- package.json
- test/ios-project-service.ts
Fix issue with C++ source code files being added to Resources instead
of Sources group. Add unit tests.
> fix(node-xcode): Update to 1.5.1 tag

- lib/services/doctor-service.ts
- lib/services/versions-service.ts
Don't show components info when `tns doctor` command is executed outside of project directory. Don't print warning twice when `tns doctor` command is executed and env is not properly configured.
In case when some issues are detected, `checkEnvironmentRequirements` prints the detected warnings. (actually canExecuteLocalBuilds print them). In case when no issues are found, we need to print them from `printWarnings` method.
> Fix doctor

- lib/commands/remove-platform.ts
After upgrading `nativescript-doctor`, the version of the Java is
validated against the current Android runtime version. In case the
runtime version cannot work with Java 10, `nativescript-doctor` does not
allow the operation to continue. This breaks the `platform remove`
command, as it checks the system requirements first, before executing
the actual removal. However, this is no longer required as the code for
removing the platform is `try-catched` and in case the current
environment is not setup correctly, it will try to remove the
platforms/<platform> dir and the respective key in package.json.
So remove the environment validation from this command. Also remove the
`validatePlatformInstalled` call from the `canExecute` method of the
command, as it is actually called in the …
> fix: platform remove command fails with old Android runtime

- lib/commands/platform-clean.ts
- lib/commands/update-platform.ts
- lib/definitions/platform.d.ts
- lib/services/doctor-service.ts
- lib/services/platform-environment-requirements.ts
- lib/services/platform-service.ts
- npm-shrinkwrap.json
- package.json
- test/platform-commands.ts
- test/stubs.ts
Add logic to validate environment based on the specified runtime version. This is required for the cases where the runtime version is not specified in the project's package.json but we need to verify if a runtime version can be used
For `tns platform update <platform>` command validate the runtime version that will be installed based on the passed argument. This has two cases:
1. In case version is specified: `tns platform update android@4.0.1` - we'll get the 4.0.1 version and validate if it can be used with currently installed Java compiler version.
2. In case version is not specified: `tns platform update android` - we'll not validate the java version here as we know we'll install at least 4.1.0 runtime, which is compatible with all Java versions
For `tns platform clean <platform>` …
> fix: platform update/clean commands may fail with Java 10

- lib/services/android-debug-service.ts
- lib/services/ios-debug-service.ts
- test/services/android-debug-service.ts
- test/services/ios-debug-service.ts
The console.log from application should be shown in the terminal when `tns debug <platform>` command is executed.
When `tns debug android --start` is used, the console.log messages are not visible as noone has started reading them. Add logic to read and filter them based on the PID of the application.
When `tns debug ios [--start]` is used with older runtime (4.0.1 for example) with iOS Simulator, the device logs are not shown as the filtering is based on the projectName, but noone has set this projectName to the filter. So we filter everything. Fix this by setting the projectName to the filter instance.
Fix the `tns debug ios --justlaunch` and `tns debug ios --start --justlaunch` which are always printing console.logs, while in fact they shouldn't.
Missing console.logs when `tns debug …
> fix: Device logs are not properly shown with debug command

- lib/constants.ts
- lib/services/android-project-service.ts
In case when `tns run android` command is executed, the app is restarted twice on device. The first restart is when the fullSync is executed and the second one is when `app.gradle` file is interpolated. Actually once the `__PACKAGE__` placeholder is replaced inside `app.gradle`, there is no need to replace it again. This PR skips the interpolation of `app.gradle` file when there is no placeholder inside it.
Steps to reproduce: 
1. `tns create myApp`
2. `tns run android`
The application is restarted twice on device.
The application is restarted only once on device.
> Touch app.gradle file only if __PACKAGE__ placeholder exists

- lib/commands/update-platform.ts
In case when no platform is added and `tns update android` command is executed, `The platform android is not added to this project` error is thrown.
1. `tns create TestApp`
2. `tns platform update android` (now installs 4.0.1)
> Fix tns update command when no platform is added

- npm-shrinkwrap.json
- package.json
In some cases, when iOS device is detached during LiveSync, an error will be shown - `TypeError: Assignment to constant variable`. The issue is in `ios-device-lib`, so update to its latest version, where it is fixed.
> fix: TypeError is thrown when iOS device is detached during LiveSync

- lib/definitions/debug.d.ts
- lib/definitions/ios-debugger-port-service.d.ts
- lib/definitions/ios-log-parser-service.d.ts
- lib/definitions/project.d.ts
- lib/services/ios-debug-service.ts
- lib/services/ios-debugger-port-service.ts
- lib/services/ios-log-parser-service.ts
- lib/services/livesync/android-device-livesync-service.ts
- lib/services/livesync/android-livesync-service.ts
- lib/services/livesync/ios-device-livesync-service.ts
- lib/services/livesync/ios-livesync-service.ts
- lib/services/livesync/platform-livesync-service-base.ts
- test/services/ios-debugger-port-service.ts
- test/services/ios-log-parser-service.ts
When CLI is used as a library (in NativeScript Sidekick for example), calling methods for run and debug currently fails. The problem is with the parsing of the iOS logs, which was introduced several days ago.
The logic uses `$projectData` from the `$injector`. However, when CLI is used as a library, the `$projectData` is never initialized. Instead of using `$projectData` pass the project directory and construct new project data (from `$projectDataService`) where required.
Trying to run application on iOS device/simulator fails in Sidekick.
You can successfully run application on iOS device/simulator with Sidekick.
> fix: Run and debug fail for iOS in Sidekick

- npm-shrinkwrap.json
The `integrity` value of the `xcode` package is not corect, which prevents npm of installing the package and CLI respectively. Can be reproduced with npm 5 or 6 by wiping the npm cache and trying to install current rc version.
> fix: Shrinkwrap is incorrect which prevents CLI from installing

- npm-shrinkwrap.json
- package.json
`tns debug ios` fails when you have only iOS device attached.
Also `tns devices` command takes 18 seconds when there's no iOS Simulator running.
`tns debug ios` allows you to debug application on iOS Device.
Also `tns devices` command takes around 4 seconds when there's no iOS Simulator running.
> fix: `tns debug ios` fails to show chrome url

- CHANGELOG.md
> docs: Update Changelog for 4.1.0

- lib/services/project-changes-service.ts
In case when when something is changed in `app/App_Resources/iOS` folder, `tns run android` command executes full application build. Actually there is no need to rebuild the application in this case. Make the `appResourcesDirectoryChanged` to be checked per platform so no rebuild is triggered.
> Make appResourcesChanged check to be executed per platform

- lib/device-sockets/ios/packet-stream.ts
- lib/device-sockets/ios/socket-proxy-factory.ts
- lib/services/livesync/android-device-livesync-service.ts
- lib/services/livesync/ios-device-livesync-service.ts
When `tns debug ios` command is executed with node10, a deprecation warning is shown
```
(node:93714) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
Deprecation warning is shown when `tns debug ios` command is executed using node v10
No deprecation warning is shown using node v10
> fix: fix a deprecation warning that is shown when debug command is executed using node v10

- lib/services/project-data-service.ts
When we don't find an asset in the default image definitions(image-definitions.json) we skip width and height parsing. Then the image generation fails because width and height are undefined.
Now we set the correct size even we don't find default asset properties.
Fixes  https://github.com/NativeScript/sidekick-feedback/issues/199.
> Fix assets generation

- lib/services/project-service.ts
An error is thrown when the user tries to create project with template v2.
The user is able to create project with template v2.
Steps to reproduce: 
1. `tns create --template https://github.com/rosen-vladimirov/test-tns-template-v2/tarball/master`
> fix(project): fix project creation when template v2 is used

- vendor/gradle-plugin/build.gradle
When CLI builds plugins, the build.gradle file uses the jcenter repository as default. However, it has been quite unstable in the last few weeks, so we'll try using google's repository as default.
> fix: Use google as default repo when building plugins

- lib/definitions/livesync.d.ts
- lib/services/debug-service.ts
- lib/services/ios-debug-service.ts
- lib/services/livesync/android-livesync-service.ts
- lib/services/livesync/ios-device-livesync-service.ts
- lib/services/livesync/ios-livesync-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/livesync/platform-livesync-service-base.ts
In case when `tns run ios --justlaunch` command is executed on real iOS device, the console should be released and the process should exit. Actually the process does not exit because a device's log process is started and this prevents the console to be released. So this PR fixes this behaviour.
Fixes https://github.com/NativeScript/nativescript-cli/issues/3644
The console is not released when `tns run ios --justlaunch` command is executed.
The console is released when `tns run ios` command is executed.
> Fix  `tns run ios --justlaunch`

- npm-shrinkwrap.json
- package.json
In case you have a long living process, the CLI should be able to access files to different applications. However, file connections on iOS device require to be closed after finishing operation. Currently this fails, but it is fixed in the latest version of ios-device-lib
> fix: File connections to iOS device work for a single app only

- docs/man_pages/lib-management/plugin-add.md
- docs/man_pages/lib-management/plugin-install.md
Currently they are in separate articles and there is no alias in articles
There should be aliases in both articles.
Fixes
https://github.com/NativeScript/nativescript-cli/issues/3677
> docs: add alias to plugin add/install

- lib/services/ios-debugger-port-service.ts
- lib/services/platform-project-service-base.ts
When trying to run application on iOS in Sidekick for the first time (when the iOS platform is not added yet to the project), the run fails with error "Cannot read property version of undefined".
The problem is in the call to `platformLiveSyncService.prepareForLiveSync` which tries to start parsing device logs before starting the liveSync action. However, at this point, the application does not have the platform added yet and the code that tries to get the version of `tns-ios` from project's package.json fails. In order to resolve this, ensure the code for getting framework version from package.json will return undefined instead of failing.
When undefined is returned, we know CLI will add the latest compatible iOS runtime version. We know that this version will print the port for …
> fix: Unable to run app on iOS in Sidekick

- lib/commands/test-init.ts
When tests are initialized, the `tns test <platform>` command fails in case karma 2.0.3 is used. In order to fix it, until karma resolves the issue on their side, hardcode the version of karma that is installed by CLI on `tns test init` command.
Also install mocha when it is selected for testing framework. In case we do not install it, the test command fails again.
`tns test init --framework mocha && tns test <platform>` command fails to execute the tests.
The command executes the tests.
Fixes: https://github.com/NativeScript/nativescript-cli/issues/3689 and https://github.com/NativeScript/nativescript-cli/issues/2283
> fix: Trying to run unit test fails with latest karma

- lib/commands/test-init.ts
Trying to execute execute tests with jasmine fails, as during initialization we have written incorrect data in karma.config.js file.
The error is: `Error: No provider for “framework:undefined”! (Resolving: framework:undefined)`
The problem is that during initalization we set undefined for framework value. Fix the initalization code to enter correct data in karma.config.js
> fix(unit-testing): Fix tests executed with jasmine

- lib/device-path-provider.ts
- npm-shrinkwrap.json
- package.json
Fixes https://github.com/NativeScript/nativescript-cli/issues/3545
Should be merged after these PRs:
https://github.com/telerik/ios-sim-portable/pull/106
https://github.com/telerik/mobile-cli-lib/pull/1092
> Use async API from ios-sim

- lib/services/prepare-platform-native-service.ts
These checks are no longer needed. They also cause the CLI to rebuild the .aar files on every change when using `tns run android --bundle`.
- The first check:
The CLI watches the `App_Resources` folder and will execute the logic
for preparing them whenever there's a change.
- The second check:
The CLI will try to detect changes in node_modules by comparing the
timestamps of every file there on every change. When there's a change,
it will set the `modulesChanged` flag to true. Therefore, the `bundle` flag is not needed.
fixes #3707
> fix(livesync): stop forcing native prepare when using --bundle

- lib/services/project-changes-service.ts
The reasons for this change are described in the issue below.
fixes #3710
> fix(livesync): check node_modules for changes only with `--sync-all-files`

- README.md
Fixes the [extending the CLI](https://github.com/NativeScript/nativescript-cli#extending-the-cli) document URL.
The URL leads to a not found page.
The URL leads to the proper page.
> docs: fix extending CLI url in the readme

- lib/services/android-project-service.ts
Starting from tns-android v4.2.0-2018-06-29-02, `babel-traverse`, `babel-types`, `babylon` and `lazy` are no longer required by the runtime but the CLI will still install them on `tns platform add android`.
The CLI will install the above-mentioned dependencies only for older Android Runtime versions improving the execution time of the command with a few seconds.
> fix: install the Android project dependencies only when needed

- lib/services/project-templates-service.ts
- test/project-templates-service.ts
Fix data send to google analytics when `tns create --template <localTemplatePath>` command is executed.
Expected: `localTemplate_tns-template-hello-world`
Current: `localTemplate_livesync-hello-world.tgz`
`tns create myApp --template <localTemplatePath>` sends wrong data to google analytics 
`tns create myApp --template <localTemplatePath>` sends correct data to google analytics
> chore: fix the template name that will be send to google analytics

- lib/definitions/ios-debugger-port-service.d.ts
- lib/definitions/ios-log-parser-service.d.ts
- lib/definitions/livesync.d.ts
- lib/services/ios-debug-service.ts
- lib/services/ios-debugger-port-service.ts
- lib/services/ios-log-parser-service.ts
- lib/services/livesync/android-livesync-service.ts
- lib/services/livesync/ios-livesync-service.ts
- lib/services/livesync/livesync-service.ts
- test/services/ios-debugger-port-service.ts
`tns run ios` does not print the logs from iOS simulator
`tns run ios` prints the logs from iOS simulator
> chore: fix console.log regression after introducing ios-sim async api

- lib/services/ios-project-service.ts
- test/ios-project-service.ts
`tns build ios --release --for-device` fails with Xcode 10 beta 2.
This PR should fix it.
Fixes #3723.
> fix: xcode10 build

- npm-shrinkwrap.json
- package.json
Fixes the behaviour of `tns run ios --device fakeId`
`tns run ios --device fakeId` throws unhandled error
`tns run ios --device fakeId` shows correct error
> Update ios sim lib to 4.0.1

- lib/npm-installation-manager.ts
- lib/services/android-project-service.ts
- lib/services/platform-service.ts
- test/npm-support.ts
- test/platform-commands.ts
- test/platform-service.ts
The current logic for adding native platform is:
1. Install the runtime package (tns-ios or tns-android) as a dependency of the project
2. Copy all files from the `<project dir>/node_modules/<runtime package>/framework` to `<project dir>/plaforms/<platform>/...` (specific places there).
3. Uninstall the runtime package, so it is no longer dependency of the project.
This solution becomes really slow when the project has a lot of dependencies. For example, for `tns-template-master-detail-ng`, all these steps take around 2 mins and 5 seconds on Windows (without SSD) and around 40 seconds on macOS (with SSD).
In order to speed up this process, remove the installing and uninstalling of the runtime package. Instead of this, use the `pacote` package to extract the runtime to a directory in the …
> feat: Speed up adding native platform

- lib/services/project-service.ts
The `Project Service Tests project service integration tests creates valid project from local directory template` test was failing on MAC. (the `npm i` in the project was also making `npm i` in the template because of the symlink).
All tests are passing on MAC
> fix: fix failing test for creating a project from local directory template on MAC

- lib/constants.ts
- lib/declarations.d.ts
- lib/definitions/android-plugin-migrator.d.ts
- lib/node-package-manager.ts
- lib/services/android-plugin-build-service.ts
- lib/services/android-project-service.ts
- test/services/android-plugin-build-service.ts
- test/stubs.ts
- vendor/gradle-plugin/build.gradle
- vendor/gradle-plugin/gradle/wrapper/gradle-wrapper.properties
> feat: use runtime Gradle version during plugin AAR build

- lib/definitions/project.d.ts
- lib/services/android-project-service.ts
- lib/services/ios-project-service.ts
- test/stubs.ts
In case CLI executes any Gradle operation, it always prints `Gradle build...` message. Fix this by printing specific message for each operation, for example "Gradle clean..." when clean is executed.
Also make some methods private as they are used only in AndroidProjectService and they were incorrectly added to the IPlatformProjectService interface.
When CLI calls gradle clean (for example if you call `tns build android --bundle && tns build android`), `Gradle build...` is printed, while executing clean operation.
CLI prints correct information for the gradle task.
> fix: During all gradle operations "Gradle build" message is printed

- lib/services/project-service.ts
In some cases the `after-createProject` may not be executed as we have missed the `await` of the promise.
> fix: after-createProject hook may not be executed

- lib/services/android-plugin-build-service.ts
- lib/services/livesync/livesync-service.ts
- test/services/android-plugin-build-service.ts
Check the below-mentioned issue.
The livesync is rebuilding the app on each aar or include.gradle change.
Related to #3610
> fix: start tracking the AAR and include.gradle changes during livesync

- lib/commands/debug.ts
- lib/declarations.d.ts
- lib/helpers/livesync-command-helper.ts
- lib/services/test-execution-service.ts
- test/debug.ts
Speed up device detection by:
* removing duplicate calls to all device detection services
* cache the Promise of initialize method - this way even when multiple calls are executed simultaneously, the result of the first one will be used. This allows Sidekick to call the method asynchronously.
* do not execute iOS device detection in case `--emulator` is passed
Remove several public methods from the service - make them protected as we already have tests for them.
Remove all calls to detectCurrentlyAttachedDevices method outside of the service - the initialize method will do it anyway, so no need to call it externally.
Remove duplicate calls in the startLookingForDevices method - previously it had to filter which device detection services to call. As now each device detection service checks …
> feat: Speed up device detection

- lib/commands/appstore-upload.ts
- lib/commands/build.ts
- lib/commands/prepare.ts
- lib/constants.ts
- lib/definitions/files-hash-service.d.ts
- lib/definitions/project-changes.d.ts
- lib/services/android-plugin-build-service.ts
- lib/services/files-hash-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/platform-service.ts
- lib/services/project-changes-service.ts
- lib/services/test-execution-service.ts
- test/project-changes-service.ts
- test/services/android-plugin-build-service.ts
- test/stubs.ts
Currently all changes in `node_modules` are skipped as we do not check for changes in case `--syncAllFiles` is not passed.
In fact the meaning of this option is for LiveSync operations and by default CLI does not watch for changes in node_modules. However, the separate commands like prepare, build, test and even the initial LiveSync must check the node_modules and prepare the correct files.
In latest versions (4.1.x) we were always checking all `node_modules` even during change of a single file during LiveSync. After that we've applied a change in the current master branch to skip node_modules check in case specific option is passed to the projectChangesService. The problem with latest approach is that we've missed this option is always passed based on syncAllFiles.
This led to the …
> feat: Improve rebuild of native plugins and node_modules checks

- docs/man_pages/project/testing/debug-ios.md
- lib/commands/debug.ts
- lib/definitions/debug.d.ts
- lib/definitions/ios-debugger-port-service.d.ts
- lib/definitions/livesync.d.ts
- lib/helpers/livesync-command-helper.ts
- lib/services/ios-debug-service.ts
- lib/services/ios-debugger-port-service.ts
- lib/services/livesync/ios-livesync-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/test-execution-service.ts
- test/services/ios-debugger-port-service.ts
Add support for --timeout option that can be passed to debug command.
Fix help of debug command.
The default timeout for `debug ios` command is 5 seconds.
The default timeout for `debug ios` command is 10 seconds. Also adds support for `--timeout` option.
> Increase the default timeout for debug command from 5 to 10 seconds

- lib/services/pacote-service.ts
The live sync is not working on Android P.
There is an infinite loader when a nonexisting runtime is specified in the package.json.
The live sync is working on Android P.
An error is shown when a nonexisting runtime is specified in the package.json.
Related to issue #3602
> fix: handle invalid runtime versions and Android P livesync

- lib/helpers/livesync-command-helper.ts
- lib/services/livesync/ios-livesync-service.ts
Move the message from `ios-livesync-service` to `livesync-command-helper`.
This way the message will not be displayed from sidekick.
The message `Skipping node modules folder!...` is displayed from sidekick
The message `Skipping node modules folder!...` will not be displayed from sidekick
> Do not show "Skipping node_modules folder!..." message from Sidekick

- lib/services/pacote-service.ts
- lib/services/project-service.ts
- test/project-service.ts
Fixes http://nsbuild01:8080/build/view/enterprise-templates/job/template-find-a-doctor-ng-PR-check-iOS11/8/console
`tns create myApp --template myFolder/myTemplate.tgz` does not work
`tns create myApp --template myFolder/myTemplate.tgz`  works
> Fix project create when template option is specified with local .tgz

- lib/constants.ts
- lib/services/plugins-service.ts
- lib/services/project-changes-service.ts
- test/ios-project-service.ts
- test/plugins-service.ts
- test/project-changes-service.ts
Skip the preparation of plugins' native files in case there's no change of the files since last operation when the files have been prepared.
Do this by using hash sums of files in each plugin's `platforms/<platform>` dir in case such exists. This way, in case you apply a change outside of the `<plugin dir>/platforms/<platform>` dir, the plugin's native files will not be prepared again. This way application will not be rebuilt as there's no need to do this.
Add logging in projectChangesService's checkForChanges method in order to know which files are changed. This will help us to understand why prepare is triggered.
Whenever a change in `node_modules` is detected, CLI prepares the native resources. For example this leads to regeneration of Podfile whenever a change in `.js` or even `.css` …
> fix: Skip preparation of plugins native files in case they are not changed

- vendor/gradle-plugin/build.gradle
Using certain plugins that request newer versions of Google Support will fail out during gradle building of the plugin because apparently jcenter being first quits out after that search.  Which then causes the application to fail to build
Those plugins will now build correctly, letting the application then build properly.
Fixes/Implements/Closes 
#1081 & #3751
> Update the Gradle script to put JCenter at bottom of search list.

- npm-shrinkwrap.json
- package.json
When trying to detect devices on Mac machine without Xcode an unhandled error is thrown.
The operation promise is rejected and later caught by the CLI.
> chore: update ios-sim-portable version

- lib/services/livesync/ios-device-livesync-service.ts
Modifying an `xml` file restarts the application during LiveSync
Modifying an `xml` file doesn't restart the application during LiveSync
> fix: ios fast sync restarts app

- lib/services/livesync/android-livesync-tool.ts
Fixes non working ctrl + c when `tns run android` command is executed
ctrl + c does not work when `tns run android` command is executed
ctrl + c works when `tns run android` command is executed
> Dispose android livesync sockets

- PublicAPI.md
Rename `getAvailableEmulators` to `getEmulatorImages` as we return information for all emulator images - running and not.
Rename the events `emulatorImagesFound` and `emulatorImagesLost` to `emulatorImageFound` and `emulatorImageLost` as emitted data contains a single emulator image.
Add docs for deviceEmitter
> chore: rename exposed methods and events for emulators

- lib/constants.ts
- lib/services/project-service.ts
Remove confusing keys from project's package.json when Template v2 is used. Remove `name` and `version` as the users may decide we will use the values to set project name and version of the application.
After project is created and template v2 is used, the package.json contains a lot of confusing and unneeded keys:
```JSON
{
"nativescript": {
"id": "org.nativescript.app7",
"tns-android": {
"version": "4.1.3"
},
"tns-ios": {
"version": "4.1.1"
}
},
"name": "tns-template-master-detail-ng",
"displayName": "Master-Detail with Firebase",
"templateType": "App template",
"version": "4.1.2",
"description": "NativeScript Application",
"author": "Telerik <support@telerik.com>",
"license": "SEE LICENSE IN <your-license-filename>",
"keywords": [
"telerik",
"mobile",
"nativescript",
"{N}",
"tns", …
```
> fix: remove keys from package.json after project is created

- lib/services/pacote-service.ts
`pacote` package does not work very well with relative paths, so ensure we pass full path to the `extractPackage` method. When trying to pass `.tgz` with relative path for template and the `.tgz` is located next to `.git` dir, the `pacote` package tries to download the repository instead of using the local .tgz package. Once full path is passed, it works correctly.
Follow the steps below and you'll receive an error:
1. Clone any v2 template repo, for example https://github.com/rosen-vladimirov/test-tns-template-v2: `git clone https://github.com/rosen-vladimirov/test-tns-template-v2`
2. Pack the template: `cd test-tns-template-v2 && npm pack && cd ..` - this will produce a `test-tns-template-v2.tgz` in `test-tns-template-v2` dir.
3. From any outside dir (not the `test-tns-template-v2`) try …
> fix: Unable to create project from local path of template v2

- lib/definitions/livesync-global.d.ts
- lib/definitions/livesync.d.ts
- lib/services/livesync/android-device-livesync-sockets-service.ts
- lib/services/livesync/android-livesync-service.ts
- lib/services/livesync/android-livesync-tool.ts
- lib/services/livesync/device-livesync-service-base.ts
- lib/services/livesync/livesync-service.ts
Fixes the following problems with android livesync with sockets:
1. Ensure .end is always called.
2. Don't use doSync in refreshApplication - in case doSync fails and is called inside `refreshApplication` method, {N} CLI will not stop livesync.
3. Call `await doSyncPromise.then(...)`
4. Call `socket.destroy()` in order to fix ctrl +c problem with node version < 10
> Fix android livesync with sockets

- lib/services/ios-debugger-port-service.ts
- lib/services/livesync/livesync-service.ts
`tns run ios` command will fail with:
`Unable to apply changes on device: xxxxxx. Error is: Invalid Version: rc`.
The application will be build and deployed
Fixes/Implements/Closes #[3803](https://github.com/NativeScript/nativescript-cli/issues/3803).
> fix: run ios fails if tns-ios version contains tags

- CHANGELOG.md
Whenever CLI returns information for available emulators/simulators, the returned object for each of the image has a status property.
For Android the status is "Running" or "Not running", for iOS it is "Connected" or "Disconnected".
Unify the status properties - use "Running" and "Not running" for both of the images.
Also, for iOS images, the imageIdentifier property has not been populated - fill it with the value of the identifier property, so the API will be consistent for both Android and iOS.
As the property has not been populated for iOS Simulators, the events "emulatorImageFound" and "emulatorImageLost" were never triggered in case you add new iOS Simulator images. Now this should work correctly.
Fix unit tests on Windows - the split by EOL when parsing the output of avdmanager …
> fix: status of iOS Sim images and Android Emulator images are different

- lib/services/livesync/android-device-livesync-sockets-service.ts
During livesync we show the old application logs once more.
During livesync we do not show any application logs.
> fix: stop starting logcat helper when starting the app only for livesync

- CHANGELOG.md
- lib/services/ios-debugger-port-service.ts
- lib/services/livesync/android-device-livesync-sockets-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/project-service.ts
Merge release branch into master
> Merge release into master

- lib/definitions/ios-debugger-port-service.d.ts
- lib/services/ios-debug-service.ts
- lib/services/ios-debugger-port-service.ts
- test/services/ios-debugger-port-service.ts
Sometimes when debug command is executed, an error is thrown because {N} CLI is not able to get debugger's port from device's logs. Currently {N} CLI tries 10 times (the retryCount) to get the  port every 500 miliseconds. If the port is not found, an error is thrown. This PR calculates the retry count based on timeout option.
In case no timeout option is specified {N} CLI will try 20 times to get the port (this is the difference with the current behaviour).
In case when calculated retry count is lower then 10, {N} CLI will try 10 times to get the port.
> Respect timeout option when getting debugger port

- lib/services/ios-project-service.ts
- npm-shrinkwrap.json
- package.json
- test/ios-project-service.ts
- test/project-service.ts
Add support for building projects with Xcode 10
> feat: Add support for building projects with Xcode 10

- docs/man_pages/lib-management/plugin-create.md
- docs/man_pages/lib-management/plugin.md
- lib/bootstrap.ts
- lib/commands/plugin/create-plugin.ts
- lib/declarations.d.ts
- lib/options.ts
- test/plugin-create.ts
- test/stubs.ts
`tns plugin create` command added to CLI. The command will clone the plugin seed and execute the initial seed configuration script to prepare a new project for developing a NativeScript plugin.
> feat: add create plugin command

- lib/services/livesync/android-livesync-tool.ts
A `Cannot set property 'socket' of null` exception is shown on each socket connection timeout.
The socket timer is cleared on timeout and the exception is not thrown.
related to #3818
> fix: clear the socket timer on timeout

- lib/definitions/pacote-service.d.ts
- lib/services/pacote-service.ts
- test/project-service.ts
- test/services/pacote-service.ts
Pacote does not respect the proxy settings set with `tns proxy set ...`. Pass the required options and add unit tests for the pacote service (use sinon instead of mocking with injector for the `pacote` and `tar` packages as the service is our wrapper for pacote).
Unable to create project when working behind proxy.
Project can be created when working behind proxy
Fixes https://github.com/NativeScript/nativescript-cli/issues/3824 
NOTE: Merge after https://github.com/telerik/mobile-cli-lib/pull/1131
> fix: pacote does not respect CLI's proxy configuration

- lib/services/ios-debug-service.ts
- npm-shrinkwrap.json
- package.json
Reconnect to dev tools dialog is shown when livesyncing to iOS simulator when debug command is executed.
Reconnect to dev tools dialog is not shown when livesyncing to iOS simulator when debug command is executed.
1. Open new project from Sidekick
2. Click run on device with debugger
3. Make change in some `.js` file
4. Reconnect to dev tools dialog is shown
> Fix connect to port

- docs/man_pages/lib-management/plugin-create.md
- lib/commands/plugin/create-plugin.ts
- test/plugin-create.ts
Extension of https://github.com/NativeScript/nativescript-cli/pull/3800
Accepting .tar.gz path/URL for custom plugin seed.
+ test
+ help
> feat: add template option to plugin create command

- lib/device-sockets/ios/socket-proxy-factory.ts
- lib/services/ios-debug-service.ts
`tns debug ios --inspector` does not work
`tns debug ios --inspector` works
> Fix `tns debug ios --inspector`

- lib/definitions/livesync.d.ts
- lib/services/livesync/android-device-livesync-sockets-service.ts
- lib/services/livesync/android-livesync-tool.ts
Every time a new LS operation is started a new socket connection is established with the application
A connection is reused if possible for sync operations. And a connection is established in advance when the application is restarted.
Fixes/Implements/Closes #3843
> feat: use long living socket connection for sync

- lib/helpers/livesync-command-helper.ts
- lib/nativescript-cli.ts
- lib/services/analytics/analytics-service.ts
- lib/services/android-project-service.ts
- lib/services/ios-project-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/plugins-service.ts
- test/services/ios-log-parser-service.ts
- tslint.json
`grunt lint` command does not print an error in case some await is missing
`grunt lint` command prints an error in case some await is missing
> Add no-floating-promises options to tslint in order to ensure all promises are properly handled

- lib/services/livesync/android-device-livesync-sockets-service.ts
When executing `tns run android --justlaunch` CLI continued running.
When executing `tns run android --justlaunch` CLI should exit.
> fix: command with justlaunch option doesn't exit

- npm-shrinkwrap.json
- package.json
Comparing the old shasums and new shasums takes a lot of time as we use find for searching in a map. Instead, just check if we have the entry we are looking for.
In bigger projects (for example with more than 20 000 files including node_modules), the comparison may take more than 100 seconds, which breaks the LiveSync for Android as the socket is closed after 70 seconds without action.
So, in case you have a huge project and try `tns run android`, you'll probably receive:
```
Unable to apply changes on device: 192.168.3.101:5555. Error is: Socket Error:
Error: write ECONNABORTED.
```
After the change, the time for comparing 24 000 shasums is 25 ms instead of more than 100 seconds
> fix: comparing shasums takes a lot of time

- lib/declarations.d.ts
- lib/definitions/livesync.d.ts
- lib/helpers/livesync-command-helper.ts
- lib/options.ts
- lib/services/livesync/android-device-livesync-service.ts
- lib/services/livesync/android-device-livesync-sockets-service.ts
- lib/services/livesync/device-livesync-service-base.ts
- lib/services/livesync/ios-device-livesync-service.ts
- lib/services/livesync/ios-livesync-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/livesync/platform-livesync-service-base.ts
This PR introduces a new option - `--hmr`. If passed it will enable --bundle by default and will not restart the application when you change a js/ts file
Related to #3875.
> feat: add --hmr option

- lib/constants.ts
- lib/services/subscription-service.ts
- test/services/subscription-service.ts
On postinstall CLI checks if the user had subscribed for NativeScript newsletter if not, prompts for email. However, the messages seems obligatory, while it is not.
Reformat it, so the users can easily skip it in case they do not want to subscribe for the newsletter.
The prompter on postinstall seems mandatory.
The prompter on postinstall does not seem so mandatory.
> fix: prompter for mail on postinstall is very obligatory

- lib/node-package-manager.ts
nativescript-cli assumes that npmjs.org is used. If another (local) repo like artifactory is used, `tns add platform` (and probably other steps) fails as it hard-wired tries to pull packages from npmjs.org
read npm registry from npm config instead of hard-wiring it to npmjs.org, fixes #3866
> fix: read npm registry from npm config

- lib/services/livesync/ios-device-livesync-service.ts
{N} CLI is not able to sync .js files on ios
{N} CLI is able to sync .js fles on ios
> chore: fix canExecuteFastSync for ios devices

- .github/ISSUE_TEMPLATE.md
- README.md
- lib/commands/post-install.ts
- lib/services/platform-environment-requirements.ts
As we are looking to deprecate usage of the community forum by the end of September, this PR replaces most references of the forum with appropriate Stack Overflow links.
Replaces https://github.com/NativeScript/nativescript-cli/pull/3872
> replacing forum references with stack overflow

- CHANGELOG.md
> docs: update Changelog for 4.2.4

- lib/constants.ts
- lib/definitions/files-hash-service.d.ts
- lib/definitions/livesync.d.ts
- lib/helpers/livesync-command-helper.ts
- lib/services/android-project-service.ts
- lib/services/files-hash-service.ts
- lib/services/livesync/android-device-livesync-service-base.ts
- lib/services/livesync/android-device-livesync-service.ts
- lib/services/livesync/android-device-livesync-sockets-service.ts
- lib/services/livesync/device-livesync-service-base.ts
- lib/services/livesync/ios-livesync-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/livesync/platform-livesync-service-base.ts
- lib/services/platform-service.ts
- test/debug.ts
- test/services/livesync/android-device-livesync-service-base.ts
`tns run android` command transfers all files on initial sync. Actually there is no need to transfer all files on device because the installed `.apk` contains them. So after the application is installed on device, calculate the hashes for files inside `\plaforms\android\app\*` and upload the hash file on device. When the initial sync is executed {N} CLI compares the hashes and no file is transferred on device because all files are the same (no change is occurred). This PR speeds up the initial livesync with around 15seconds for angular application.
LiveSync for android always transfer all project files on device but actually no need to do it.
LiveSync for android is faster.
> Speed up android livesync

- docs/man_pages/project/configuration/generate.md
- lib/bootstrap.ts
- lib/commands/generate.ts
- lib/declarations.d.ts
- lib/options.ts
- npm-shrinkwrap.json
- package.json
This PR introduces a new command - `tns generate`. The command uses [schematics-executor](https://github.com/NativeScript/schematics-executor) for performing project modifications. The modifications are described with schematic rules, which are part of schematic collections. Each collection is distributed inside a node package. The default collection used by the `tns generate` command is [@nativescript/schematics](https://github.com/nativescript/nativescript-schematics).
The command has one required argument - the name of the executed schematic. For example, if we want to run the __component__ schematic, the executed command is:
```
tns generate component
```
The executed schematic may have options. They are provided __without__ the '--' prefix.
In the following example, the command …
> feat: add generate command

- CHANGELOG.md
In case the device identifier contains only numeric symbols or in case it looks like a number (16089e09 for example), CLI fails to work with it.
The problem is that CLI thinks an index is passed to it, so it removes "one" from the passed number and tries to find the device on the new index.
The other issue is with the `isNumber` helper method which works incorrectly when the string looks like number. Improve the logic in the method and rename it. We cannot parse safely values with exponent (`1e6` for example), but we do not need such functionality.
The new method name and tests reflects the described behavior.
Before using the identifier as an index, check if we'll find device with the specified identifier.
When device with numeric identifier is attached, CLI fails to work with it.
CLI …
> fix: unable to work with devices with numeric identifiers

- lib/definitions/livesync.d.ts
- lib/services/livesync/livesync-service.ts
- test/services/livesync-service.ts
Webpack process does not stop when ctrl+c is pressed while executing `tns preview --bundle` command
Webpack process stops when ctrl+c is pressed while executing `tns preview --bundle` command
Should be merged with this: https://github.com/NativeScript/nativescript-dev-webpack/pull/661
> chore: stop webpack compiler when ctrl+c is pressed while executing `tns preview --bundle` command

- lib/services/livesync/playground/preview-app-plugins-service.ts
- test/services/playground/preview-app-plugins-service.ts
In case when QR code is scanned with 2 different devices with the same version of preview app, {N} CLI will compares 2 times plugins from preview app with local plugins.
{N} CLI compares **2 times** plugins from preview app with local plugins when QR code is scanned with 2 different devices with the same version of preview app.
{N} CLI compares **only once** plugins from preview app with local plugins when QR code is scanned with 2 different devices with the same version of preview app.
> chore: persist warnings per preview app's version when comparing plugins from preview app with local plugins

- lib/definitions/preview-app-livesync.d.ts
- lib/services/livesync/playground/preview-app-livesync-service.ts
- lib/services/livesync/playground/preview-app-plugins-service.ts
- test/services/playground/preview-app-livesync-service.ts
- test/services/playground/preview-app-plugins-service.ts
`tns preview --bundle` does not work on android devices
`tns preview --bundle works on android devices`
> chore: provide external plugins to webpack in order to fix `tns preview --bundle` command on android devices

- lib/services/livesync/livesync-service.ts
In case when `.js` file is changed and after that `.html` file is changed, preview app is restarted on device. Actually {N} CLI needs to reset filesToSync after syncing on preview app.
Preview app is restarted on `.html` change
Preview app is not restarted on `.html` change
> chore: reset filesToSync and filesToRemove when syncing on preview app

- lib/definitions/preview-app-livesync.d.ts
- lib/services/livesync/livesync-service.ts
- lib/services/livesync/playground/preview-app-constants.ts
- lib/services/livesync/playground/preview-app-livesync-service.ts
- lib/services/livesync/playground/preview-sdk-service.ts
- npm-shrinkwrap.json
- package.json
- test/services/playground/preview-app-livesync-service.ts
> refactor: start using getInitialFiles instead of applyChanges during the first Preview sync

- lib/services/platform-service.ts
- lib/services/project-changes-service.ts
Platform prepare is never skipped when executing cloud build for iOS from sidekick. The reason for this is the `signingChanged` property from `changesInfo` is always true and thus `shouldPrepare` is always true. `signingChanged` property is set to true inside `ios-project-service` because `pbxproject` file  does not exist. Actually locally from sidekick `pbxproject` file is never created. So the file never exists. This PR speeds the the cloud build for iOS with around 2-3 sec.
Local prepare is not skipped when no project's file is changed.
Local prepare is skipped when no project's file is changed.
> Skip local prepare when executing cloud build from sidekick and no project's file is changed

- lib/commands/preview.ts
An error is not thrown when the project does not have bundling plugin and `tns preview --bundle` command is executed
An error is thrown when the project does not have bundling plugin and `tns preview --bundle` command is executed.
> chore: validate bundle option from preview command

- lib/definitions/plugins.d.ts
- lib/definitions/preview-app-livesync.d.ts
- lib/services/livesync/playground/preview-app-livesync-service.ts
- lib/services/livesync/playground/preview-app-plugins-service.ts
- lib/services/plugins-service.ts
- test/services/playground/preview-app-plugins-service.ts
A warning is shown for plugin with only .js files when `tns preview --bundle` command is executed
A warning is not shown for plugin with only .js files when `tns preview --bundle` command is executed
> chore: don't show warnings for {N} plugins without native code  when bundle option is provided

- lib/bootstrap.ts
- lib/commands/preview.ts
- lib/declarations.d.ts
- lib/helpers/network-connectivity-validator.ts
Rel to: https://github.com/NativeScript/nativescript-cli/issues/3813
No error message is shown when no internet connection and `tns preview` command is executed
An error message is shown when no internet connection and `tns preview` command is executed
> chore: check network connectivity when `tns preview` command is executed

- lib/commands/appstore-upload.ts
- lib/commands/build.ts
- lib/commands/clean-app.ts
- lib/commands/prepare.ts
- lib/commands/preview.ts
- lib/declarations.d.ts
- lib/definitions/livesync.d.ts
- lib/definitions/preview-app-livesync.d.ts
- lib/helpers/deploy-command-helper.ts
- lib/helpers/livesync-command-helper.ts
- lib/helpers/preview-command-helper.ts
- lib/services/livesync/ios-livesync-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/livesync/playground/preview-sdk-service.ts
- lib/services/livesync/playground/qr-code-generator.ts
- lib/services/platform-environment-requirements.ts
- lib/services/platform-service.ts
- lib/services/test-execution-service.ts
- test/helpers/preview-command-helper.ts
- test/ios-project-service.ts
- test/npm-support.ts
- test/platform-service.ts
- test/project-changes-service.ts
- test/services/playground/preview-app-livesync-service.ts
- test/services/preview-sdk-service.ts
> Pass the HMR option to the hooks and preview URL

- lib/services/ios-project-service.ts
- test/ios-project-service.ts
In the iOS Project template we have include for plugins-debug.xcconfig (or plugins-release.xcconfig when building in release mode). CLI should produce such file, but it does not do it when the project does not have build.xcconfig in its App_Resources and neither of the plugins have such file. With previous Xcode versions, this case was leading to warnings in the output, however they are errors now and the build fails.
Fix this by adding an empty file in such case.
Build fails for iOS in case the following circumstances are fulfilled:
* Xcode 10 is used
* application does not have build.xcconfig file in `App_Resources/iOS/build.xcconfig`
* none of the plugins have build.xcconfig file in `<plugin dir>/platforms/ios/build.xcconfig`
The application can be build in case the mentioned …
> fix: build with Xcode 10 may fail for missing plugins...xcconfig file

- PublicAPI.md
Typo on #428 & #613. Minor fix on #239, #259
There is no break on code
> Typo on #428 & #613

- lib/commands/add-platform.ts
`tns platform add ios` should not be executed on non-macOS system. Currently in the master branch it exits silently, add correct error, so the user will know that it is not okay.
> fix: `tns platform add ios` should not be executed on non-macOS

- lib/constants.ts
- lib/definitions/project.d.ts
- lib/services/cocoapods-service.ts
- lib/services/ios-project-service.ts
- test/cocoapods-service.ts
- test/ios-project-service.ts
In case multiple plugins have Podfile with post_install hook, CLI modifies the hook of each of them by renaming the hook's function and calling it in the single post_install that is allowed for Podfile (placed at the bottom of the project's Podfile). However, when some change in node_modules is detected, CLI processes all Podfiles again and tries to apply them to project's Podfile. The "apply" is check if the plugin's Podfile is already added to project's one and in case not - adding it again. Whenever all Podfiles are processed, the "afterPrepareAllPlugins" method checks the final project's Podfile and replaces the post_install hooks from all plugins with a new functions (by adding index to the name) and calls them inside a newly added post_install function.
This is not working as when …
> fix: Project's Podfile is regenerated incorrectly

- lib/services/livesync/playground/preview-app-livesync-service.ts
Skip platform prepare when `tns preview --bundle` command is executed and some  changed files are reported by webpack. In this case we just need to send a message to pubnub.
> chrore: don't prepare the platform when webpack emits changed files on preview command - just send a message to pubnub.

- lib/definitions/livesync.d.ts
- lib/services/livesync/android-device-livesync-sockets-service.ts
- lib/services/livesync/android-livesync-tool.ts
Remove files synchronously (not in parallel) in order to ensure header and content of files are sent in correct order.
When something unexpected happens, the error from runtime is not propagated to the client.
When something unexpected happens, the error from runtime is propagated to the client.
1. Create new project
2. Execute `tns run android`
3. Add new folder and file inside it to the`app` folder
4. Ensure the folder is successfully transferred to device
5. Remove the folder
6. The command is successfully executed but actually the folder is not removed from device
> chore: sync correctly deleted files on android devices

- lib/services/livesync/playground/preview-app-livesync-service.ts
‘tns preview’ + scan QR  
Change something in *.js file and missing name of the changed file in console. 
‘Project successfully prepared (ios) 
Successfully synced changes for platform ios. 
Start syncing changes for platform ios. 
Preparing project... 
Project successfully prepared (ios) 
Successfully synced changes for platform ios. 
’ 
The changed file's name is not shown in logs when `tns preview` command is executed
The changed file's name is shown in logs when `tns preview` command is executed
> fix: add changed file name in logs when `tns preview` command is executed

- lib/tools/node-modules/node-modules-dest-copy.ts
The `<project dir>/platforms/<platform>/.../tns_modules` directory should contain only the `.js` code of the application. However, in case nativescript plugin is installed in the `node_modules` directory of another package (not directly inside the project), its platforms directory is copied to `tns_modules` as well. This leads to error when trying to build application that has such structure with Xcode 10.
After copying the `node_modules` to `tns_modules` recursively remove all `platforms` directories of all nativescript plugins inside node_modules.
Build with Xcode fails when nativescript plugin is installed as dependency in node_modules (i.e. it is not installed directly in the node_modules dir of the project.
Build succeeds
Fixes
> fix: native frameworks/code is added to tns_modules dir

- lib/android-tools-info.ts
- lib/declarations.d.ts
- lib/services/android-plugin-build-service.ts
- lib/services/android-project-service.ts
- npm-shrinkwrap.json
- package.json
- test/stubs.ts
In the past there was a requirement to have a local installation of the Android Support Repository in order to use libraries from there. However, since some time, the new versions are not downloaded locally and they must be used from the Google repository.
Currently this is not possible in NativeScript as {N} CLI always passes the Support Library version to gradle based on the local installation.
Remove the requirement for local installation and never pass the version to gradle. This way the apps will use the value specified in the `build.gradle` and they can overwrite it in `app.gradle`.
Update nativescript-doctor to latest version, which allows building project without local Androud Support Repository
You cannot use new versions of Android Support Library. Defining it in `app.gradle` …
> feat: remove requirement for Android Support Repository local installation

- lib/common/services/livesync-service-base.ts
- lib/services/livesync/platform-livesync-service-base.ts
"Successfully transferred myfile.js." message is shown on success livesync.
"Successfully transferred myfile.js on device myDeivce" message is shown on success livesync.
> fix: log device identifier on success message when `tns run` command is executed

- lib/services/livesync/playground/preview-sdk-service.ts
- test/services/preview-sdk-service.ts
If some error is thrown from application, {N} CLI stops command execution
If some error is thrown from application, {N} CLI does not stop command execution
1. Run `tns preview` command
2. Scan QR code
3. Throw some error from application
> fix: don't fail if some unhandled error occurs in application

- lib/definitions/project.d.ts
- lib/services/project-templates-service.ts
- test/project-templates-service.ts
In case you try to create application from scoped package, for example `@nativescript/some-package-name`, CLI fails with `npm install` error.
The problem is that CLI thinks everything after `@` is a version and sets the package name that has to be installed to empty string.
Fix the parsing and add tests
The following command fails:
```
tns create myApp --template "@angular/core" 
```
The following command succeeds:
```
tns create myApp --template "@angular/core" 
```
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/3934
> fix: unable to create project from scoped package template

- config/config.json
- lib/config.ts
- lib/declarations.d.ts
- lib/services/livesync/livesync-service.ts
- lib/services/livesync/playground/preview-app-livesync-service.ts
- lib/services/livesync/playground/preview-sdk-service.ts
- npm-shrinkwrap.json
- package.json
Should be merged after this PR: telerik/nativescript-preview-sdk#6
> feat: pass msvKey and msvEnv to preview-sdk in order to respect different min supported versions of preview app

- lib/services/cocoapods-service.ts
With NativeScript 5.0.0-2018-09-25-12302 having fi. `nativescript-plugin-firebase` and `nativescript-imagepicker` in your project will fail because there's some whitespace missing.
Building [this app](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/tree/master/demo-ng) fails because this is how the Pods are merged (mind the line `# End Podfilepost_install` near the end):
```
use_frameworks!
target "demong" do
pod 'Firebase/Core', '~> 5.6.0' 
pod 'Firebase/Auth'
#pod 'Firebase/Database'
pod 'Firebase/Firestore'
#pod 'Firebase/RemoteConfig'
#pod 'Firebase/Crash'
pod 'Fabric'
pod 'Crashlytics'
def post_installnativescript_plugin_firebase_0 (installer)
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config| …
```
> Having two plugins with Podfiles and a postinstall script fails with tns 5.x

- lib/services/platform-service.ts
- test/npm-support.ts
- test/platform-commands.ts
- test/platform-service.ts
"Platform android successfully added. V4.2.0" message is shown on every change when `tns preview --bundle` command is executed.
"Platform android successfully added. V4.2.0" message is not shown on every change.
> fix: skip platform add on every change when `tns preview --bundle` command is executed

- lib/options.ts
`tns run android --justlaunch` command does not exit
`tns run android --justlaunch` command  exits
> chore: set options.watch to false when --justlaunch is passed to command

- lib/android-tools-info.ts
- npm-shrinkwrap.json
- package.json
Allow using the SDK 28 for compileSdk of applications by adding it in the verified versions.
> feat: allow using Android SDK 28 for compilation

- lib/common/helpers.ts
- lib/services/ios-debug-service.ts
- npm-shrinkwrap.json
- package.json
related to https://github.com/NativeScript/nativescript-cli/issues/3937
> fix: detach from the Native iOS debugger in order to avoid app freeze on unhandled exceptions

- lib/services/livesync/playground/preview-app-livesync-service.ts
- test/services/playground/preview-app-livesync-service.ts
An error is thrown on projects with `.nsconfig` file when `tns preview` command is executed
Works correctly on projects with `.nsconfig` file when `tns preview` command is executed
1. `tns create myApp --template https://github.com/NativeScript/template-hello-world-ng/tarball/master`
2. cd myApp 
3. `tns preview`
4. Apply a change in the code
> fix: works correctly with projects with `.nsconfig` file on `tns preview` command

- lib/services/livesync/playground/preview-app-livesync-service.ts
When `tns preview` command is executed and the QR code is scanned with Android device, the Preview app on this device asks for initial sync of the files. At this point CLI starts preparing the project and once the files are prepared, it sends them to device.
However, this operation may take some time, especially for code sharing projects, which have a lot of dependencies and webpack is used. Meanwhile the Preview app on device sees that it had not received the files within 10 seconds and sends a new message to get the initial files.
So CLI starts another process of preparation and trying to sync the changes. Based on the time required, this may become an indefinite loop.
Fix this by caching the promise for initial sync and in case device asks again, CLI will use the already pending …
> fix: initial sync on Preview app (Android) leads to loop

- lib/services/livesync/android-device-livesync-service-base.ts
Hashes were generated twice on full sync on android devices -once from `getLocalToDevicePathsToTransfer ` and the second time from `updateHashes` method
Hashes are generated only once on full sync on android devices
> fix: don't generate local hashes twice on full sync on android devices

- lib/services/livesync/playground/preview-app-plugins-service.ts
- test/services/playground/preview-app-plugins-service.ts
Warning is shown for non nativescript plugins on `tns preview --bundle` command
Warning is not shown for non nativescript plugins on `tns preview --bundle` command
> fix: don't show warnings for non-nativescript plugins on `tns preview --bundle` command

- lib/common/mobile/ios/simulator/ios-simulator-application-manager.ts
- npm-shrinkwrap.json
- package.json
When using Xcode 10, the `xcrun simctl install ...` command fails every other time with error:
```
Error: Command xcrun with arguments simctl install 5516E083-C749-47A7-A6FC-2EE2E414D025 /Users/vladimirov/Work/nativescript-cli/scratch/app1/platforms/ios/build/emulator/app1.app failed with exit code 1. Error output:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Failed to load Info.plist from bundle at path /Users/vladimirov/Library/Developer/CoreSimulator/Devices/5516E083-C749-47A7-A6FC-2EE2E414D025/data/Library/Caches/com.apple.mobile.installd.staging/temp.ZdmYQa/extracted/Payload/app1.app
Failed to load Info.plist from bundle at path /Users/vladimirov/Library/Developer/CoreSimulator/Devices/5516 …
```
> fix: unable to install application every other time with Xcode 10

- npm-shrinkwrap.json
- package.json
Currently iOS Applications cannot be build with Xcode versions below 9. So forbid using such versions and show information to user that Xcode must be updated.
When you have Xcode 8, you can try `tns build ios` and it will fail at some point with a native error.
When you have Xcode 8, you can try `tns build ios` and it will fail with message that this Xcode is not supported and you have to upgrade it to build your app.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/3887
> feat: forbid working with Xcode below 9

- .vscode/launch.json
- lib/services/test-execution-service.ts
When CLI executes unit tests (for the NativeScript application), it forks a new Node.js process and communicates with it via IPC.
However, the Node.js fork method has an issue when you want to debug your main process - it passes the `--inspect[-brk]` option to the forked process as well. The main process had already used the port, so debugging fails.
In order to fix this, replace the `fork` with `spawn`.
> chore: enable debugging of unit test runner process

- lib/commands/preview.ts
- lib/constants.ts
- lib/declarations.d.ts
- lib/helpers/bundle-validator-helper.ts
- lib/helpers/livesync-command-helper.ts
- test/helpers/bundle-validator-helper.ts
No error message is shown when installeld `nativescript-dev-webpack` plugin does not support `hmr` option or `preview-sync` hook.
An error message is shown when installeld `nativescript-dev-webpack` plugin does not support `hmr` option or `preview-sync` hook.
> fix: validate bundle version on `tns preview --bundle` and `tns run --hmr` commands

- lib/commands/build.ts
"Sync to Playground" option is shown when env is not properly configured
"Sync to Playground" option is not shown when env is not properly configured
> fix: don't show "Sync to Playground" option on build command when env is not properly configured

- lib/services/livesync/livesync-service.ts
An error is thrown when some dependency is not installed on `tns preview` command
{N} CLI ensures all dependencies are installed on `tns preview` command
> fix: ensure all dependencies are installed on `tns preview` command

- lib/constants.ts
When the user executes `tns preview --hmr` and the project is with `nativescript-dev-webpack` version lower than 0.17.0, {N} CLI does not show descriptive message. We should to notify the user to ensure `webpack.config.js` file is properly updated after updating `nativescript-dev-webpack`.
> fix: show more descriptive message when `tns preview -hmr` command is executed and the project has webpack plugin with version lower than 0.17.0

- lib/common/services/livesync-service-base.ts
- lib/services/livesync/platform-livesync-service-base.ts
"Successfully transferred all files on device %s" message is shown on `tns debug ios --debug-brk` command on iOS simulator
"Successfully transferred all files on device FEE9701C-B925-4AF9-BCEC-862BEE21B4BA"  message is shown on `tns debug ios --debug-brk` command on iOS simulator
> fix: replace %s with deviceIdentifier on debug command

- lib/commands/debug.ts
- lib/common/declarations.d.ts
- lib/common/definitions/logger.d.ts
- lib/common/host-info.ts
- lib/common/logger.ts
- lib/common/test/unit-tests/host-info.ts
- lib/common/test/unit-tests/stubs.ts
- lib/common/verify-node-version.ts
- lib/constants.ts
- lib/definitions/system-warnings.d.ts
- lib/nativescript-cli.ts
- lib/sys-info.ts
- test/stubs.ts
- test/sys-info.ts
Drop support for macOS Sierra and below as we are no longer testing this OS. Drop a line on stderr on each CLI command and inform the user that this OS is not supported.
Change the public API (getSystemWarnings) to return objects with information about the severity of the warnings. This way the consumer can decide how to handle the warnings.
Fix an issue when getting macOS version from System Profile - the code was not working when version has two numbers (10.14 for example).
Add new method in logger that allows printing to stderr. It should be used instead of `console.error`, so we can make the code testable.
In case `tns debug ios --inspector` is called on macOS Sierra, stop the command with error, as the NativeScript Inspector package will no longer provide a built version for macOS …
> feat: drop support for macOS Sierra and below

- lib/common/commands/device/device-log-stream.ts
- lib/common/helpers.ts
- lib/common/mobile/ios/simulator/ios-simulator-device.ts
- lib/services/ios-debug-service.ts
- npm-shrinkwrap.json
- package.json
`tns debug ios --start` and `tns debug ios --inspector` command fails in some cases as CLI is not able to get the debug port from the device logs. The problem is that ios-sim-portable starts the log process with child_process.spawn, but this does not start the actual process. Fix the case by waiting for the first message on the stdout of the log process (handled in ios-sim-portable). This way the actual logic that parses the logs will start after the process has really started.
Fix a case where we fail the connection to socket with `undefined` error - show correct error in such case.
Fix `tns device log` command of iOS devices/simulators - it must show full logs from device, but instead a predicate had been passed. Remove it from there and pass it only where required.
`tns debug ios …
> fix: tns debug ios command fails in some cases

- test/project-service.ts
Remove project service integration tests as they are already covered by CLI functional tests.
> fix: remove project service integration tests

- lib/helpers/bundle-validator-helper.ts
- test/helpers/bundle-validator-helper.ts
`tns preview --hmr` fails when next is written as a version of `nativescript-dev-webpack`
`tns preview --hmr` does not fail when next is written as a version of `nativescript-dev-webpack`
> fix: validate correctly when `next` is written as a version of nativescript-dev-webpack in package.json

- lib/services/livesync/playground/qr-code-generator.ts
> chore: fix message shown on preview command

- npm-shrinkwrap.json
- package.json
Use native spawn for log process with ios10 simulators
LS on iOS10 Simulator doesn't work
LS on iOS10 Simulator does work
> fix: use native spawn for log process with ios10 simulators

- lib/common/definitions/mobile.d.ts
- lib/common/mobile/android/android-device-file-system.ts
- lib/common/mobile/android/android-device.ts
- lib/common/test/unit-tests/mobile/android-device-file-system.ts
- lib/definitions/livesync.d.ts
- lib/device-path-provider.ts
- lib/services/livesync/android-device-livesync-service-base.ts
- lib/services/livesync/android-device-livesync-service.ts
- lib/services/livesync/android-device-livesync-sockets-service.ts
- test/services/livesync/android-device-livesync-service-base.ts
1. `tns create myApp`
2. `tns run android`  & stop the command
3. `tns run android` & make some changes -> everything is ok
4. `tns run android` on another device
5. The changes from 3. are not applied
> fix: don't update local hashes on livesync

- lib/services/livesync/playground/preview-app-plugins-service.ts
- test/services/playground/preview-app-plugins-service.ts
Mark all plugins that are already in the Preview app as external. This
will prevent webpack from bundling them. Having two instances of one
plugin, may cause problems.
> fix-next(preview): externalize all plugins from the Preview app

- lib/definitions/platform.d.ts
- lib/services/prepare-platform-js-service.ts
- lib/services/prepare-platform-native-service.ts
- lib/tools/node-modules/node-modules-builder.ts
- lib/tools/node-modules/node-modules-dest-copy.ts
When building application in release mode, the `.ts` files of all plugins should be removed from the final application. Currently this is happening only for `tns-core-modules`. Do this for all the plugins.
Remove logic that deletes the `node_modules` directory of the `tns-core-modules` when it is copied to `platforms`. This is not required anymore and it breaks use-case when linking tns-core-modules.
Applications built in release have `.ts` files inside them.
Also you are unable to use a linked copy of `tns-core-modules`.
Applications built in release does NOT have `.ts` files inside them.
You can use symlink for tns-core-modules.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/4007
> fix: remove all .ts files when building in release

- lib/definitions/platform.d.ts
- lib/services/prepare-platform-js-service.ts
- lib/tools/node-modules/node-modules-builder.ts
Whenever we prepare node_modules (i.e. moving them to platforms dir), CLI executes the operation twice:
1. When prepare the JS part of the modules.
2. When prepare the native part of the modules.
The first part is a must for cases when you work with cloud builds, so we cannot skip it, but we can safely skip the second one. This improves the initial prepare of `tns-template-master-detail-ng` with around 20 seconds.
Node_modules are prepared twice on first `tns run`
Node_modules are prepared once.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/4010
> fix: prepare node_modules only once

- lib/services/livesync/livesync-service.ts
In case when `tns run android --hmr` command is executed and the app is uninstalled from device during the execution of command, {N} CLI installs the application again on device but the changes are not applied. When a change occurs during the execution of command, {N} CLI sends only `.hot-update` files on device. (without `bundle.js` and `vendor.js`). But in this specific case {N} CLI should send all files on device including `bundle.js` and/or `vendor.js`.
1. `run android --hmr`
2. make changes – applied 
3. Uninstall app without stop the proccess 
4. Make new changes and save 
5. The app will install without new changes
> fix: apply changes correctly when app is uninstalled from device during the execution of `tns run android --hmr` command

- lib/services/livesync/playground/preview-sdk-service.ts
"Cannot read property 'platform' of undefined" is thrown when the device report log before reporting itself.
We won't know the platform of the preview logs in such cases.
> fix: avoid nre when the device log is reported before the device itself during preview

- lib/common/verify-node-version.ts
`getNodeWarning` always returns a warning, even when there's no such. It returns object with empty message, when it has to return null.
> fix: getNodeWarning always returns warning

- lib/services/livesync/livesync-service.ts
`tns run --hmr` syncs changes only on one platform when iOS and android devices are attached
`tns run --hmr` syncs changes on both platforms when iOS and android devices are attached
> fix: sync on all platforms when `tns run --hmr` command is executed

- lib/commands/create-project.ts
- lib/common/prompter.ts
- test/project-commands.ts
> chore: update the interactive create descriptions based on the DevRel feedback.

- lib/definitions/livesync.d.ts
- lib/services/livesync/android-livesync-service.ts
- lib/services/livesync/livesync-service.ts
When the the update that fixes the error is send the app is restarted, but crashes again, because it doesn't manage to apply the patch.
The app is restarted and loads normally.
> fix: recover android application if with hmr and in ErrorActivity

- lib/common/definitions/mobile.d.ts
- lib/definitions/livesync.d.ts
- lib/services/livesync/android-device-livesync-sockets-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/livesync/platform-livesync-service-base.ts
In case HMR is used, webpack reports to CLI the already prepared files, so there's no need for CLI to do any preparation, just sync the files. Try sending them as soon as possible and if we fail, go through the normal worklfow.
Ensure the code is called only when webpack had produced files for us and we are with HMR enabled.
Applying a change when CLI is livesyncing with HMR takes from 1.5 to 5 seconds.
Applying a change when CLI is livesyncing with HMR takes from below 1 second.
> feat: speed-up livesync with HMR

- lib/services/livesync/platform-livesync-service-base.ts
- lib/services/platform-service.ts
`Installing...` msg is shown when app is installing on device.
`Refresing...` msg is shown when app is refreshing on device.
`Installing on device <id>` msg is shown when app is installing on device.
`Refreshing on device <id>` msg is shown when app is refreshing on device.
> fix: show deviceIdentifier on installing and refreshing messages

- lib/definitions/hmr-status-service.d.ts
- lib/definitions/livesync.d.ts
- lib/services/hmr-status-service.ts
- lib/services/livesync/android-livesync-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/livesync/playground/preview-app-livesync-service.ts
- lib/services/log-parser-service.ts
Hmr status is not correct when more than one webpacks are started.
Hmr status is correct when more than one webpacks are started.
Should be merged with this PR: https://github.com/NativeScript/nativescript-dev-webpack/pull/690
> fix: get correct hmr hash when more than one webpacks are started

- lib/services/ios-debug-service.ts
`tns debug ios --emulator --debug-brk` does not work
`tns debug ios --emulator --debug-brk` works
> fix: don't detach native debugger on debug command

- docs/man_pages/lib-management/plugin.md
- [x ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ x] All existing tests are passing: https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
`tns plugin -h` contains deprecated plugin commands `find` and `search`. This removes the commands from the help prompt.
See above.
Fixes #3834 .
> chore(plugin.md) - Remove find and search commands from man pages

- lib/common/definitions/mobile.d.ts
- lib/common/mobile/android/android-device.ts
- lib/common/mobile/android/android-emulator-services.ts
- lib/common/mobile/android/android-virtual-device-service.ts
If the user starts an android emulator from sidekick, {N} CLI persist the emulator in a dictionary. The started emulator is with id `emulator-5554` so {N} CLI adds a record with key `emulator-5554` in the dictionary.
If the user stops the emulator and starts an another one, the started emulator is again with id `emulator-5554`. {N} CLI checks that an emulator with id `emulator-5554` is persisted and returns the emulator's data. But the returned data is not correct because it belongs to the first started emulator. So we need to remove persisted emulator's data when the user stops the emulator (e.g deviceLost event is emitted).
The emulator's data is not removed on deviceLost event
The emulator's data is removed on deviceLost event
> fix: remove persisted emulator's data on deviceLost event

- lib/services/livesync/livesync-service.ts
We do not mention that the `hmr` option is not stable yet.
A few warnings are shown during livesync.
Related to #4058
> docs: add beta warnings for the unstable options during livesync

- lib/common/mobile/android/logcat-helper.ts
`TypeError: Invalid Version: null` error is shown is Sidekick when emulator is stopped immediately after start. This happens because emulator is stopped too early and it is not fully initialized. In this case reported emulator is with `version: null` and the semver comparison fails. So we need to ensure the device's version is not `null` before comparison.
`TypeError: Invalid Version: null` error is thrown in Sidekick when emulator is stopped immediately after start.
No error is thrown in Sidekick when emulator is stopped immediately after start.
> fix: don't throw `TypeError: Invalid Version: null` in sidekick when emulator is stopped immediately after start

- lib/commands/preview.ts
`tns preview gjdgkdfg` does not throw any error
`tns preview gjdgkdfg` throws an error
> fix: validate params passed to preview command

- lib/services/livesync/playground/preview-app-plugins-service.ts
- test/services/playground/preview-app-plugins-service.ts
If the local version of the plugin cannot be parsed by `semver`, the
check should be skipped and no warning shown.
fixes #4043
> fix(preview): skip check if local plugin version is invalid

- lib/common/constants.ts
The message that is shown when {N} CLI is not able to start an emulator is not meaningful/useful for sidekick.
The message that is shown when {N} CLI is not able to start an emulator is meaningful/useful for sidekick.
> fix: improve the message when not able to start an emulator so it can be useful for sidekick as well.

- lib/services/ios-project-service.ts
- test/ios-project-service.ts
- test/xcconfig-service.ts
> fix: update an old Xcode warning as now its applicable for all supported Xcode versions

- lib/common/mobile/android/android-virtual-device-service.ts
- lib/common/test/unit-tests/mobile/android-virtual-device-service.ts
When there are errors on avdmanager's stderr and no data on avdmanager's stdout, {N} CLI fallback to list avds from directory and returns both devices (from directory) and errors from avdmanager's stderr. However this is incorrect behavior. In case we fallback to list avds from directory, we need to reset errors output.
When there are errors on avdmanager's stderr and no data on avdmanager's stdout, {N} CLI fallback to list avds from directory and returns both devices (from directory) and errors from avdmanager's stderr
When there are errors on avdmanager's stderr and no data on avdmanager's stdout, {N} CLI fallback to list avds from directory and returns devices (from directory) and no errors
> fix: reset errors when fallback to list avds from directory

- lib/commands/test-init.ts
Currently `tns test init` command always print `Place your test files under app/tests`. However this is not correct when the project has `nsconfig.json` file. So this PR replaces the hardcoded `app/tests` with the correct location to tests folder.
`app/tests` folder is hardcoded even for projects with `nsconfig.json` file 
Respect `nsconfig.json` file and prints the correct location to tests folder.
> fix: show correct messages on `tns test init` command

- lib/bootstrap.ts
- lib/definitions/preview-app-livesync.d.ts
- lib/services/livesync/playground/devices/preview-devices-service.ts
- lib/services/livesync/playground/preview-app-livesync-service.ts
- lib/services/livesync/playground/preview-sdk-service.ts
- test/services/playground/preview-app-livesync-service.ts
- test/services/preview-devices-service.ts
- test/services/preview-sdk-service.ts
We want to expose `deviceFound` and `deviceLost` for preview devices as a public api so Sidekick can use them.
```
const tns = require("nativescript-cli");
tns.previewDevicesService.on("deviceFound", device => {
console.log("device found", device);
});
tns.previewDevicesService.on("deviceLost", device => {
console.log("device lost", device);
});
```
> feat(preview): add public API for deviceFound and deviceLost for preview devices

- lib/commands/test-init.ts
- resources/test/karma.conf.js
Rel to: https://github.com/NativeScript/nativescript-cli/issues/4071
`tns test <platform>` does not execute any unit tests when the project has nsconfig file
`tns test <platform>` executes unit tests when the project has nsconfig file
> fix(unit-testing): add correct files pattern in karma.conf.js when the project has nsconfig file

- lib/common/definitions/mobile.d.ts
- lib/common/mobile/device-log-provider-base.ts
- lib/common/mobile/device-log-provider.ts
- lib/common/test/unit-tests/stubs.ts
- lib/services/ios-debug-service.ts
Currently log process is not started when `--justlaunch` option is provided. This leads to error on `tns debug ios --justlaunch` command. Actually we need to start log process in order to get debugger port. On the other side we should not print any logs on the console when `--justlaunch` option is provided. So this PR starts log process when `--justlaunch` option is specified and doesn't print any logs on the console.
`tns debug ios --justlaunch` throws an error
`tns debug ios --justlaunch` does not throw an error
Rel to: https://github.com/NativeScript/nativescript-cli/issues/4076
> fix: start log process on `tns debug ios --justlaunch` command

- lib/bootstrap.ts
- lib/commands/preview.ts
- lib/common/declarations.d.ts
- lib/definitions/preview-app-livesync.d.ts
- lib/services/livesync/playground/preview-qr-code-service.ts
- lib/services/platform-environment-requirements.ts
- test/services/platform-environment-requirements.ts
```
cons tns = require("nativescript-cli");
```
```
const result = tns.previewQrCodeService.getPlaygroundAppQrCode();
```
or
```
const result = tns.previewQrCodeService.getPlaygroundAppQrCode({ platform: 'ios' });
```
or
```
const result = tns.previewQrCodeService.getPlaygroundAppQrCode({ platform: 'android' });
```
> feat(preview-api): expose public method for getting the qr code of playground app

- lib/services/project-templates-service.ts
- test/project-templates-service.ts
The CLI was not respecting its version when installing v2 templates. e.g. CLI 4.2.4 is installing 5.0.0 templates.
The CLI is installing the latest compatible version of the v2 templates
> fix: install the latest compatible v2 templates in stead of the latest tag

- npm-shrinkwrap.json
Upate the natives library, so CLI can work wiht Node.js 11.
When Node.js 11 is installed, CLI fails to execute any command with error:
```
Support for Node.js 11.0.0 is not verified. NativeScript CLI might not install or run properly.
ReferenceError: internalBinding is not defined
at fs.js:25:1
at req_ (D:\Rosen\Work\nativescript-cli\node_modules\natives\index.js:140:5)
at Object.req [as require] (D:\Rosen\Work\nativescript-cli\node_modules\natives\index.js:54:10)
at Object.<anonymous> (D:\Rosen\Work\nativescript-cli\node_modules\fstream\node_modules\graceful-fs\fs.js:1:99)
at Module._compile (internal/modules/cjs/loader.js:707:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
at Module.load (internal/modules/cjs/loader.js:605:32)
at tryModuleLoad …
```
> fix: update natives, so CLI can work on Node.js 11

- lib/base-package-manager.ts
- lib/definitions/pacote-service.d.ts
- lib/node-package-manager.ts
- lib/services/pacote-service.ts
- lib/yarn-package-manager.ts
- test/plugins-service.ts
Remove the last hardcoded `npm` command so yarn will be used all the time when it is set as package manager. Also remove `--dry run` logic and use `$pacoteService.manifest` instead.
rel to: https://github.com/NativeScript/nativescript-cli/issues/2737
> feat(yarn): implement get cache directory path and remove `npm --dry-run` logic

- lib/services/platform-service.ts
- test/platform-service.ts
As the preview command add only the .js part of the platform, we need to check nativePlatformStatus in order to decide correctly if platform add is necessary.
```
tns preview
tns platform add
```
throws an error "Platform already added" but actually no native platform is added.
```
tns preview
tns platform add
```
adds both js and native platform.
rel to: 
https://github.com/NativeScript/nativescript-cli/issues/4090
> fix(platform-add): respect nativePlatformStatus property from .nsprepare file when adding the platform

- lib/definitions/livesync.d.ts
- lib/definitions/preview-app-livesync.d.ts
- lib/services/livesync/livesync-service.ts
- lib/services/livesync/playground/preview-qr-code-service.ts
- test/services/livesync-service.ts
```
const qrCodeData = tns.liveSyncService.liveSyncToPreviewApp()
```
> feat(preview-api): expose public api for starting the livesync operation to preview app

- lib/services/android-plugin-build-service.ts
- vendor/gradle-plugin/build.gradle
Related to #4100
If there's a **before-plugins.gradle** file in the app it should be called before the plugin build.gradle
> Apply before-plugins.gradle file in the plugin build.gradle

- lib/services/android-plugin-build-service.ts
Detailed gradle logs are shown on plugin build even without passing log trace.
Detailed gradle logs are shown on plugin build only with log trace.
> fix: show the build plugin gradle logs only with log trace

- PublicAPI.md
- lib/services/extensibility-service.ts
There is no way to set a different path for loading the CLI extensions.
There is a property `pathToExtensions` which can be set on the `extensibilityService`.
> feat(extensibility): setting a custom path for the extensions

- lib/bootstrap.ts
- lib/services/extensibility-service.ts
Only a set of methods are exposed of the `extensibilityService`.
The whole `extensibilityService` class is exposed.
> feat(extensibility): expose extensibility class

- lib/declarations.d.ts
- lib/node-package-manager.ts
- lib/npm-installation-manager.ts
- lib/services/project-templates-service.ts
- test/node-package-manager.ts
- test/project-templates-service.ts
- test/services/android-debug-service.ts
- test/stubs.ts
`tns create NewApp --template https://github.com/NativeScript/template-drawer-navigation-ng#master` is throwing an error.
`tns create NewApp --template https://github.com/NativeScript/template-drawer-navigation-ng#master` is creating a new project based on the specified repo url.
related to #4096
> fix: fix project creation with github url passed as template

- npm-shrinkwrap.json
- package.json
Chokidar 1.7.0, which we are currently using, is unable to watch directories with names that contain glob symbols (like `(`, `*`, etc.). There are two ways to fix this:
- pass `disableGlobbing: true`, so all paths will be treated as strings.
- update chokidar to latest version, where the issue is fixed
Suggested solution is to update chokidar to latest version, so we'll get all other fixes listed [here](https://github.com/paulmillr/chokidar/blob/master/CHANGELOG.md)
Unable to LiveSync changes from project which has `(` in the dir name.
LiveSync works for projects which have `(` in the dir name.
Fixes/Implements/Closes https://github.com/NativeScript/nativescript-cli/issues/4129
> fix(deps): update chokidar, so we can watch dirs with `(`

- lib/definitions/preview-app-livesync.d.ts
- lib/services/livesync/livesync-service.ts
- lib/services/livesync/playground/preview-app-livesync-service.ts
- lib/services/livesync/playground/preview-app-plugins-service.ts
- test/services/playground/preview-app-livesync-service.ts
- test/services/playground/preview-app-plugins-service.ts
Release option does not make sense in the context of the preview app so it should be deleted from public api for livesync to preview app.
```
tns.liveSyncService.liveSyncToPreviewApp({
projectDir: "myProjectDir",
appFilesUpdaterOptions: {
bundle: false,
release: false,
useHotModuleReload: false   
},
env: {}
});
```
```
tns.liveSyncService.liveSyncToPreviewApp({
projectDir: "myProjectDir",
bundle: false,
useHotModuleReload: false,
env: {}
});
```
This way the api will be consisted with
```
tns.liveSyncService.liveSync(deviceDescriptors, {
projectDir: "myProjectDir",
bundle: false,
useHotModuleReload: false,
env: {},
....
});
```
> fix(preview-api): remove mandatory release option from IPreviewAppLiveSyncData interface

- lib/bootstrap.ts
- lib/commands/preview.ts
- lib/definitions/preview-app-livesync.d.ts
- lib/services/livesync/playground/devices/preview-devices-service.ts
- lib/services/livesync/playground/preview-app-log-provider.ts
- lib/services/livesync/playground/preview-sdk-service.ts
- test/services/preview-devices-service.ts
- test/services/preview-sdk-service.ts
No api for getting logs from preview app
```
tns.previewDevicesService.on("deviceLogData", (deviceId, log) => {
console.log(`received log ${log} from device: ${deviceId}`);
});
```
> feat(preview-api): expose api for getting logs from preview app

- lib/definitions/preview-app-livesync.d.ts
- lib/services/livesync/playground/devices/preview-devices-service.ts
- lib/services/livesync/playground/preview-app-plugins-service.ts
- test/services/playground/preview-app-plugins-service.ts
- test/services/preview-devices-service.ts
No api for getting warnings from device
```
const deviceWarnings = tns.previewDevicesService.getDeviceWarnings({ previewAppVersion: "19.0.0" });
console.log(deviceWarnings);
```
> feat(preview-api): expose public api for getting device's warnings

- lib/yarn-package-manager.ts
As --json flag is hardcoded for `yarn info` command, it always returns a json object in following format: { data: someResult }. As the other methods expect only `someResult` as a result from view command, we need to return `.data` property from `yarn info` output.
`tns doctor` does not return the correct components info when yarn is set as package manager.
`tns doctor` returns the correct components info when yarn is set as package manager.
Rel to: https://github.com/NativeScript/nativescript-cli/issues/2737
> fix: fix yarn view method to return correct data

- lib/services/livesync/playground/devices/preview-devices-service.ts
- test/services/preview-devices-service.ts
In case when some `.js` file is changed, preview app is restarted on device e.g preview app is stopped and started again. When the preview app is stopped, Pubnub reports the device as lost and when preview app is started, Pubnub reports the device as found. With this fix, we want to delay the emitting of deviceLost event. This way we'll give a chance to find the device before reporting it as lost.
> fix(preview-api): raise deviceLost event after timeout of 5 seconds

- lib/services/livesync/playground/preview-app-livesync-service.ts
When stopLiveSync method is called, we want to reset devices list and emit deviceLost event for all connected devices.
`deviceLost` event is not emitted when there are connected devices and `stopLiveSync` method is called
`deviceLost` event is emitted when there are connected devices and `stopLiveSync` method is called
> fix: reset devices list when stopLiveSync method is called

- npm-shrinkwrap.json
- package.json
- tslint.json
We are able to merge pull requests restricting the unit tests with `only`.
We are not able to merge pull requests restricting the unit tests with `only` as there is a tslint rule checking for such methods.
> chore: add `mocha-avoid-only` tslint rule

- lib/services/livesync/playground/devices/preview-devices-service.ts
> fix: reset deviceLostTimer after clearing the device's timeout

- lib/definitions/preview-app-livesync.d.ts
- lib/services/livesync/livesync-service.ts
- lib/services/livesync/playground/preview-app-constants.ts
- lib/services/livesync/playground/preview-app-livesync-service.ts
Usage:
```
tns.liveSyncService.on("previewAppLiveSyncError", data => {
console.log("LiveSync error: " + data);
});
```
No api exposed to get the errors from livesync operation
Expose an api to get the errors from livesync operation
> feat(preview-api): emit previewAppLiveSyncError when some error is thrown while livesyncing to preview app

- lib/bootstrap.ts
- lib/common/commands/package-manager-get.ts
No command for getting the current package manager.
`tns package-manager get`
Rel to: https://github.com/NativeScript/nativescript-cli/issues/2737
> feat(package-manager): expose `package-manager get` command

- lib/bootstrap.ts
- lib/common/helpers.ts
- lib/definitions/preview-app-livesync.d.ts
- lib/services/livesync/playground/preview-app-files-service.ts
- lib/services/livesync/playground/preview-app-livesync-service.ts
- lib/services/livesync/playground/preview-sdk-service.ts
- test/services/playground/preview-app-files-service.ts
- test/services/playground/preview-app-livesync-service.ts
Project is prepared when `tns preview` command is executed
Project is not prepared when `tns preview` command is executed
https://github.com/NativeScript/nativescript-cli/issues/4141
> Don't prepare the project on preview command

- lib/services/analytics/analytics-service.ts
When analytics are enabled, `undefined` file is created at the location where a command is executed. This is because the `$options.analyticsLoggingFile` is undefined, but we've set it as args to the spawned Analytics process. The value in the child process is the string "undefined", so that's why CLI always creates this file.
Pass the path to file only when it is passed by user.
When analytics are enabled, CLI always produces file called `undefined`, in which it saves the information what has been tracked.
When analytics are enabled, CLI will produce file with name specified by user with `--analyticsLogFile <name>`, in which it saves the information what has been tracked.
Part of the implementation of: https://github.com/NativeScript/nativescript-cli/issues/4152
> fix(analytics): undefined file is created on every command

- lib/services/analytics/analytics-constants.d.ts
Building the nativescript-cloud package fails with error:
```
node_modules/nativescript/lib/services/analytics/analytics.d.ts(67,9): error TS2304: Cannot find name 'AnalyticsLoggingMessageType'.
```
The problem is that the build of `nativescript-cloud` extension needs to get all interfaces from CLI and include them in the global scope of the `nativescript-cloud`, so it can be transpiled. Currently this is done by iterrating over all files in nativescript and searching for `.d.ts` files.
For each `.d.ts` file, we create a new entry in a `references.d.ts` file in the root of `nativescript-cloud`. When trying to transpile the project, it fails as one of the included references (`analytics.d.ts`) uses a type (enum in this case) that is not available in the included references.
Fix this by …
> fix: builing of nativescript-cloud package fails

- npm-shrinkwrap.json
- package.json
Remove unzip dependency from package.json of nativescript-doctor - Unzip dependency has a native dependency that do not allow us to support out of the box new versions of nodejs
Rel to: https://github.com/NativeScript/nativescript-cli/pull/4073
> feat(doctor): update doctor to 1.7.0 version

- lib/commands/test-init.ts
`tns test` command does not work on windows on projects with `.nsconfig` file
`tns test` command works on windows on projects with `.nsconfig` file
https://github.com/NativeScript/nativescript-cli/issues/4178
> fix: use correct files pattern in karma.config on windows

- lib/common/services/analytics/google-analytics-custom-dimensions.d.ts
- lib/definitions/project.d.ts
- lib/services/analytics/analytics-service.ts
- lib/services/analytics/google-analytics-provider.ts
Add analytics for code sharing projects usage
> feat(analytics): track code sharing projects usage

- lib/common/test/unit-tests/analytics-service.ts
- lib/services/analytics/analytics-service.ts
- test/services/analytics/analytics-service.ts
- test/stubs.ts
Currently projectType and isShared properties are tracked only when we send events to Google Analytics and when the caller sends the projectDir to the method. In fact we need to track them(based on the projectDir) for every hit in Google Analytics.
To achieve this, use the projectHelper, which tries to determine the projectDir. Track the projectType on every page and event send to Google Analytics.
When tracking pageviews in Google Analytics, the respective projectType is not tracked.
Also for some of the events, the projectType is not tracked.
ProjecType is tracked for every hit (when action is executed inside project dir or with `--path`)
> fix: project properties are not tracked on every analytics hit

- lib/constants.ts
- lib/services/analytics/analytics-service.ts
- lib/services/analytics/analytics.d.ts
We need information how many users have accepted the tracking, so add analytics for this.
> feat: add tracking for answer is we can track

- lib/definitions/project.d.ts
- lib/project-data.ts
- lib/services/analytics/analytics-service.ts
- test/project-data.ts
- test/services/analytics/analytics-service.ts
- test/stubs.ts
Expose `isShared` property from projectData, so it will be possible to check if a project is code-sharing when using CLI as a library.
Use the new property in the Analytics service as well. Add tests.
Related to issue: https://github.com/NativeScript/nativescript-cli/issues/4200.
> feat: expose isShared property from projectData

- README.md
We probably shouldn't have @next in the installation command for the CLI
> removing @next from install command

- lib/definitions/platform.d.ts
- lib/definitions/project.d.ts
- lib/services/android-project-service.ts
- lib/services/ios-project-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/platform-service.ts
- test/ios-project-service.ts
- test/stubs.ts
iOS build fails when `IPHONEOS_DEPLOYMENT_TARGET = 11.0;` is specified in `build.xcconfig`
iOS build doesn't fail when `IPHONEOS_DEPLOYMENT_TARGET = 11.0;` is specified in `build.xcconfig`
Rel to: https://github.com/NativeScript/nativescript-cli/issues/4197
> fix: build correctly for iOS when IPHONEOS_DEPLOYMENT_TARGET = 11.0; is specified in build.xcconfig

- lib/services/livesync/livesync-service.ts
- npm-shrinkwrap.json
- package.json
An error is thrown from sidekick when livesync to preview app is started more than 11 times
No error is thrown from sidekick when livesync to preview app is started more than 11 times
> fix: fix "MaxEventListeners detected" error when livesync is started more than 11 times from sidekick

- lib/device-sockets/ios/app-debug-socket-proxy-factory.ts
VSCode debugging is not working on iOS when a change in .js is applied. The problem is that the server is reused for the new connections, but VSCode waits for message 'Opened localhost...' which is printed from CLI only when creating the new server.
> fix: vscode debug is not working for iOS

- CHANGELOG.md
docs: update Changelog for 5.1.0
> docs: update Changelog for 5.1.0

- lib/common/mobile/ios/device/ios-application-manager.ts
- lib/common/mobile/ios/simulator/ios-simulator-application-manager.ts
When you've stopped on breakpoint in VSCode and apply a change in the code, CLI tries to restart application. However, at this point the command for killing the application may not kill it immediately and it needs 30 seconds. The problem is that the runtime loops indefinitely while on breakpoint. After some seconds (looks like 30), the OS kills the application. In order to resolve the issue, disconnect all sockets before stopping the application, so the runtime can successfully break the indefinite loop and after that application can be safely killed.
> fix: debugging in VSCode is not working on iOS Simulator

- .travis.yml
- .travis/add-publishConfig.js
- lib/definitions/platform.d.ts
- lib/definitions/project.d.ts
- lib/services/android-project-service.ts
- lib/services/ios-project-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/platform-service.ts
- npm-shrinkwrap.json
- package.json
- test/ios-project-service.ts
- test/stubs.ts
chore: merge release-patch (5.1.1) branch in release
> chore: merge release-patch (5.1.1) branch in release

- lib/services/android-device-debug-service.ts
- lib/services/debug-service-base.ts
- lib/services/ios-device-debug-service.ts
- test/services/ios-device-debug-service.ts
Using `tns debug ios --hmr` leads to incorrect behavior as the application and debug session are not restarted, but the new code is not visible in Chrome DevTools. The problem is that we are not using the latest DevTools, but the one used in Chrome 55. Switching to Bundled tools (included in user's Chrome version) fixes the behavior. In the past we were stuck with the Chrome 55 due to concerns that new Chrome versions may break the behavior.
To fix the issue, remove the getChromeDebugUrl from AndroidDeviceDebugService and IosDeviceDebugService, as they are now sharing the same logic, so all of it is in the base class.
Changes in code during `tns debug ios --hmr` are not visible in Chrome DevTools.
Changes in code during `tns debug ios --hmr` are visible in Chrome DevTools and you can …
> fix: `tns debug ios --hmr` does not refresh DevTools

- lib/services/livesync/playground/preview-app-livesync-service.ts
An unhandled promise rejection error is thrown from sidekick when livesync to preview app with bundle 
An unhandled promise rejection error is not thrown from sidekick when livesync to preview app with bundle
> fix: fix unhandled promise rejection error from sidekick when livesync to preview app with bundle

- lib/declarations.d.ts
- lib/definitions/debug.d.ts
- lib/definitions/livesync.d.ts
- lib/services/android-device-debug-service.ts
- lib/services/debug-service-base.ts
- lib/services/debug-service.ts
- lib/services/ios-device-debug-service.ts
- lib/services/livesync/android-device-livesync-service.ts
- lib/services/livesync/android-device-livesync-sockets-service.ts
- lib/services/livesync/ios-device-livesync-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/livesync/platform-livesync-service-base.ts
- test/services/debug-service.ts
- test/stubs.ts
The debugger attached event used for reconnecting the debugger in SideKick is fired on each LiveSync.
The debugger attached event used for reconnecting the debugger in SideKick is fired only when the app restarted and the debugger really needs to be reconnected.
related to: https://github.com/NativeScript/nativescript-cli/issues/4222
> fix: allow Debug + HMR using the public API

- lib/declarations.d.ts
- lib/device-sockets/ios/app-debug-socket-proxy-factory.ts
- lib/services/ios-device-debug-service.ts
Take a look at the below-mentioned issue.
We are printing the debug proxy port even if we reuse an existing proxy. In this way, VSCode can reattach to the same proxy after a JS file change and we are able to connect and disconnect unlimited number of clients. 
Related to https://github.com/NativeScript/nativescript-cli/issues/4236
> fix: fix debugger attaching after a page reload

- lib/common/commands/preuninstall.ts
- lib/common/declarations.d.ts
- lib/common/definitions/extensibility.d.ts
- lib/common/file-system.ts
- lib/declarations.d.ts
- lib/package-installation-manager.ts
- lib/services/extensibility-service.ts
- test/stubs.ts
The NativeScript CLI extensions and Inspector cache are not removed even when the CLI is uninstalled by the user.
These resources are removed along with the CLI.
Related to https://github.com/NativeScript/nativescript-cli/issues/4255
> fix: clean the installed extensions and inspector cache on intentional CLI uninstall

- lib/device-sockets/ios/app-debug-socket-proxy-factory.ts
The CLI crashes if you try to debug an app without having it running on the device.
The CLI shows a warning and suggests a manual app start.
Related to https://github.com/NativeScript/nativescript-cli/issues/4260
> fix: suggest manual app start instead of crashing on ios debug socket connection errors

- lib/definitions/livesync.d.ts
- lib/services/livesync/livesync-service.ts
The CLI is firing the `userInteractionNeeded` event both in `run` and `debug`.
The CLI is firing the `userInteractionNeeded` event only in `debug` as we have a workaround with a manual app start in `run`.
Related to https://github.com/NativeScript/nativescript-cli/issues/4261
> fix: require user interaction for developer disk image only in debug

- lib/services/livesync/playground/preview-app-plugins-service.ts
- test/services/playground/preview-app-plugins-service.ts
> fix(preview-publicApi): Add force option when getting the plugin's warnings

- lib/commands/preview.ts
- lib/definitions/livesync.d.ts
- lib/services/livesync/livesync-service.ts
- lib/services/livesync/playground/preview-app-livesync-service.ts
- test/stubs.ts
When preview is called with webpack from Public API, if you stop the livesync (via stopLiveSync method) while webpack is still working, in the output you'll see an error as webpack's child process exits with `null` exit code.
However, this error does not have any meaning for the user, so we shouldn't raise it.
Move the logging of the error to LiveSyncService's handler of `previewAppLiveSyncError` event - in the described case it will not be raised as LiveSyncService had already removed all listeners.
> fix: do not show error from preview initialization when stop is called

- resources/assets/image-definitions.json
SplashScreen generation fails for JS projects.
SplashScreen generation succeeds for JS projects.
Fixes/Implements/Closes https://github.com/NativeScript/nativescript-cli/issues/4272
> fix: splashscreen generation

- npm-shrinkwrap.json
- package.json
In case you use `tns run ios --path <path to app> --device <simulator GUID>`, CLI will try to stop the application, but may kill CLI instead. The problem is in ios-sim-portable, which incorrectly searches for application PID. Update the package to 4.0.7 where the issue is fixed.
https://github.com/telerik/ios-sim-portable/releases/tag/v4.0.7
On iOS Simulator:
* CLI is unable to stop application which has `grep` in the name, so LiveSync is not working in this case.
* CLI process is killed when `tns run ios --path <path to app> --device <device GUID` command is used.
CLI successfully syncs the application.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/4284
> fix: trying to stop app on simulator may kill CLI

- npm-shrinkwrap.json
- package.json
On slower mac machines, an error may be raised during restart of app on iOS Simulator. The problem is that we stop the application and try to start it after that. However, the stop method may be resolved before the application is actually killed. Trying to start it after that leads to undefined behavior and errors in some cases.
To fix this, update ios-sim-portable to 4.0.8 where a possible fix is applied.
On slower mac machines trying to use `tns run ios --emulator` leads to error while restarting the app.
CLI should be able to restart the app on all machines and `tns run ios --emulator` should work.
> fix: error may be raised during restart of app on ios Sim

- lib/base-package-manager.ts
- lib/services/android-plugin-build-service.ts
- test/services/android-plugin-build-service.ts
Rel to https://github.com/NativeScript/nativescript-cli/issues/4283
{N} CLI does not work when private `npm` registry is configured
{N} CLI works when private `npm` registry is configured
> fix: use `npm view` command to get gradle versions from registry in order to fix the problems when private npm registry is configured

- .travis.yml
Travis build does not stop when the grunt step fails
Travis build stops when the grunt step fails
> chore: stop travis build execution when grunt step fails

- lib/common/services/micro-templating-service.ts
- lib/config.ts
Some CLI commands are broken due to incorrect paths to resources.
- `postinstall` is broken as the path to common helpers is incorrect. Also we are not injecting correct constants and the generation of `.html` for `test init` command fails. Inject correct constants when generating help.
- `test init` command is broken as path to CLI's resource dir is not correct
`tns dev-post-install-cli` command fails.
`tns dev-generate-help` command fails.
`tns test init` command fails.
Mentioned commands are working.
> fix: incorrect paths to CLI resources and files break commands

- lib/commands/post-install.ts
- lib/common/commands/post-install.ts
- lib/common/commands/preuninstall.ts
- lib/common/definitions/config.d.ts
- lib/common/helpers.ts
- lib/common/test/unit-tests/helpers.ts
- lib/config.ts
- postinstall.js
- test/commands/post-install.ts
- test/post-install.ts
In case the CLI package is not installed globally, probably it is installed as a dependency of a project or as a dependency of other dependency.
In this case the postinstall actions have no meaning for the user, as probably CLI will be used as a library.
Skip all of the postinstall actions in such case. Remove the execution code of the old `post-install` command and move it to `post-install-cli` command.
Add unit tests. Remove a property from staticConfig - it has no meaning to be there, just place it in the postinstall command directly.
Handle case when CLI is installed globally with npm or yarn - in both cases the `npm_config_argv` will be populated with the original command. For example:
* `npm i -g nativescript`  - the `npm_config_argv` will be: `["i", "-g", "nativescript"]`
* `yarn …
> feat: skip postinstall steps in case CLI is not installed globally

- lib/common/mobile/mobile-core/devices-service.ts
- lib/common/test/unit-tests/mobile/devices-service.ts
During LiveSync operations (i.e. `tns run ...`), CLI may keep the CPU of the machine at a constantly high level even when it is not livesyncing. This is caused by the device detection changes that we are starting, which also checks for new emulator images.
It turnes out the command `avdmanager list avds` takes really high usage of CPU on some machines when there are available AVD images.
To fix this behavior split the current interval on two different ones - one will check for devices, which is run on 200ms and a second one which will check for emulator images, which will run once per minute.
Fix the `startDeviceDetectionInterval` method - it should just start the device detection instead of waiting for the first execution to receive results. This breaks the current behavior, so execute a …
> fix: high cpu usage during livesync

- lib/bootstrap.ts
- lib/declarations.d.ts
- lib/definitions/project.d.ts
- lib/services/android-project-service.ts
- lib/services/cocoapods-service.ts
- lib/services/ios-project-service.ts
- lib/services/prepare-platform-native-service.ts
- lib/services/xcconfig-service.ts
- lib/services/xcproj-service.ts
- lib/tools/node-modules/node-modules-dest-copy.ts
- test/cocoapods-service.ts
- test/debug.ts
- test/ios-project-service.ts
- test/npm-support.ts
- test/platform-service.ts
- test/plugin-prepare.ts
- test/stubs.ts
- test/xcconfig-service.ts
> chore: remove installPods property from platform's project interface

- lib/definitions/platform.d.ts
- lib/services/livesync/livesync-service.ts
CLI returns incorrect path when uninstalling the application from device and run `tns run ios` command again.
> fix: use correct build output path when building for device

- npm-shrinkwrap.json
- package.json
`tns devices --availableDevices` prompts to install Xcode Command Line Tools (with popup), when command line tools (Xcode) are not installed on the machine. Update the `ios-sim-portable` package, where the issue is resolved.
In case Xcode and Xcode Command Line tools are not installed, calling `tns run` or `tns devices --availableDevices` leads to a UI prompt (from the OS) to install the missing components.
The command lists the currently attached devices/available devices, and does not prompt to install anything.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/4327
> fix: prompt to install Xcode Command Line Tools when listing devices

- lib/common/http-client.ts
The current stuck request timeout does not handle the missing server
hello case but it fixes the problem with stuck requests other than PUT
and POST.
> fix: uploading big files with the $httpClient

- .gitignore
- .npmignore
- .travis.yml
- Gruntfile.js
Currently the Travis build of `next`, `rc` and `release-patch` versions takes way too long as the packaging and execution of unit tests is done twice - first time from `grunt pack` execution inside the script and the second time from the npm deploy provider.
To fix this introduce new Grunt task - `travisPack` - it checks if the build is from PR and in case it is, the grunt pack task is skipped. This way the `grunt travisPack` command in the `.travis.yml` script section will be skipped in case we are not in PR build, but the one from npm deploy step will still be executed.
Also delete some unused and not needed logic.
> chore: fix travis build of next/rc/release-patch versions

- resources/assets/image-definitions.json
Add missing image resources for generation of splashscreens and icons. The last released templates have different names of the images, which breaks the generation.
A permanent fix for this case will be applied later.
Resources generation fails for splashscreens:
```
tns create blankJs --template tns-template-blank
cd blankJs
tns resources generate splashes <path to image> 
```
Last command will fail.
Users are able to generate new splashscreens.
Fixes issue: https://github.com/NativeScript/nativescript-cli/issues/4347
> fix: add missing image resources for generation

- vendor/gradle-plugin/build.gradle
With Gradle 3.3.0 (used in tns-android 5.2.0-... ) dependencies checking is stricter and there are some problems in the resolution of the supportLibrary version when building plugins. Issue is raised when the plugin has any of the following:
* another compile dependency which is built with `compile` of android support library version that is not the same as the one we are using
* plugin defines in its gradle new version of android support library, that is different from the one specified in our build.gradle.
To resolve this, set all versions of `com.android.support` libraries to the passed supportVersion or 28.0.0
Also update other tooling versions to latest versions.
Unable to build .aar for plugins with rc version of Android runtime.
Plugins can be build.
Fixes issue …
> fix: set correct versions in plugin's build.gradle

- docs/man_pages/index.md
docs: add missing resources command in index
> docs: add missing resources command in index

- lib/config.ts
In case there's no ANDROI_HOME on user's machine, CLI tries to use its local copy of adb. However, the current path to adb is not correct and CLI does not work with any Android devices in this case.
Fix the path to local copy of adb.
When you do not have ANDROID_HOME set and Android device is attached, CLI does not discover it, i.e. `tns devices` will not show the devices.
When you do not have ANDROID_HOME set and Android device is attached, CLI will discover it, i.e. `tns devices` will show the device.
> fix: cli's local adb is not used

- lib/definitions/platform.d.ts
- lib/tools/node-modules/node-modules-builder.ts
- test/npm-support.ts
In case `--bundle` is passed CLI tries to clean the `tns_modules` directory produced from previous prepare operations. However, this is not required in latest versions as webpack cleans the directory on its own.
The current clean was required for Webpack before 0.14.0, particularly the one used with 3.x versions of NativeScript.
CLI tries to clean `tns_modules` dir when `tns prepare <platform> --bundle` is executed.
Logic for cleaning `tns_modules` dir is executed in `nativescript-dev-webpack` plugin.
> chore: skip tns_modules cleanup from CLI

- CONTRIBUTING.md
Minor updates to contributing.md
> docs: contributing.md update

- lib/bootstrap.ts
- lib/definitions/project.d.ts
- lib/services/cocoapods-platform-manager.ts
- lib/services/cocoapods-service.ts
- lib/services/ios-project-service.ts
- test/cocoapods-service.ts
- test/ios-project-service.ts
fixes https://github.com/NativeScript/nativescript-cli/issues/3604
> fix: remove duplicated platforms from project's podfile

- lib/common/declarations.d.ts
- lib/common/helpers.ts
- lib/common/test/unit-tests/helpers.ts
- lib/constants.ts
- lib/definitions/project.d.ts
- lib/project-data.ts
- lib/services/doctor-service.ts
- lib/services/platform-service.ts
- lib/services/project-data-service.ts
- test/npm-support.ts
- test/platform-commands.ts
- test/platform-service.ts
- test/services/doctor-service.ts
- test/services/project-data-service.ts
- test/stubs.ts
In NativeScript 5.2.0 we've deprecated support for short imports. Add ability in CLI to check if there are such imports in the application's code and report them to users. The logic will be executed whenever application is prepared for build/livesync or when `tns doctor` is executed inside project dir.
Create class with static variables for ProjectTypes. These values must not be changed as they are used in Analytics, so changing them will break the current reports.
Users should search their own code for short imports.
CLI warns users for used short imports in the application when `tns run <platform>` or `tns doctor` is executed.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/4375
> feat: detect and report short imports used in application

- lib/services/cocoapods-platform-manager.ts
No warning is shown when platform's version in project's podfile is replaced with another platform's version
Warning is shown when platform's version in project's podfile is replaced with another platform's version
Rel to: #3604
> fix: show warning when the platform's version in project's podfile will be replaced with another platform's version

- lib/services/cocoapods-platform-manager.ts
- test/cocoapods-service.ts
1. `tns create myPodApp --js`
2. `tns plugin add nativescript-imagepicker`
3. `tns plugin add nativescript-facebook`
4. Open `node_modules/nativescript-facebook/platforms/ios/Podfile` and replace the file's content with `platform :ios`
5. Open `node_modules/nativescript-imagepicker/platforms/ios/Podfile` and replace the file's content with `platform :ios, '9.0'`
Rel to: https://github.com/NativeScript/nativescript-cli/issues/3604
> fix: process correctly podfiles without platform's version

- lib/commands/test-init.ts
- lib/commands/test.ts
- lib/common/declarations.d.ts
- lib/common/errors.ts
- lib/definitions/project.d.ts
- lib/services/test-execution-service.ts
- test/services/test-execution-serice.ts
- test/stubs.ts
> fix: validate test init before executing the test command

- lib/services/cocoapods-platform-manager.ts
- test/cocoapods-service.ts
1. `tns create myApp --js`
2. `tns plugin add nativescript-imagepicker` && `tns plugin add nativescript-facebook`
3. Replace the content of `./node_modules/nativescript-imagepicker/platforms/ios/Podfile` with `platform: ios, '9.0'`
4. Replace the content of `./node_modules/nativescript-facebook/platforms/ios/Podfile` with `platform: ios, '10.0'`
5. Add Podfile in `./app/App_Resources/iOS` with the following content `platform: ios: '8.0'`
6. Execute `tns prepare ios`
7. Remove `./app/App_Resources/iOS/Podfile`
8. Execute `tns prepare ios`
Expected behavior: It should pass correctly and the content of `platforms/ios/Podfile` should be
```
...
platform :ios, '10.0'
end
```
Actual behavior: It fails with `[!] Invalid `Podfile` file: syntax error, unexpected end-of-input, …
> fix: add new line at the end of the platform's section in order to remove it correctly

- lib/common/definitions/mobile.d.ts
- lib/common/mobile/ios/device/ios-application-manager.ts
- lib/common/mobile/ios/ios-device-base.ts
- lib/common/mobile/ios/simulator/ios-simulator-application-manager.ts
- lib/common/services/lock-service.ts
- lib/common/test/unit-tests/stubs.ts
- lib/definitions/lock-service.d.ts
- lib/device-sockets/ios/app-debug-socket-proxy-factory.ts
- lib/services/livesync/ios-device-livesync-service.ts
connected to: https://github.com/NativeScript/nativescript-cli/issues/4301
> fix: ensure a single web client connected for debugging

- lib/common/helpers.ts
- lib/common/test/unit-tests/helpers.ts
- test/services/doctor-service.ts
- test/services/platform-environment-requirements.ts
When `tns doctor` detects errors in the configuration, it should print them to stdout and prompt the user to select how to resolve them.
In non-interactive terminal, it should just print the errors and fails as the prompter are not meaningful in non-interactive terminal - there's noone to answer them.
The logic works fine when you pipe the output of `tns doctor` to file for example (`tns doctor > out.txt`). CLI correctly detects the terminal as non-interactive, prints the errors and exits.
However, most of the CI environments are determined as interactive terminals by CLI. That's because CLI checks if the stdout and stdin of the current process are text terminal (TTY). CI environments set required flags, so the process seems like running in such text terminal.
When CLI thinks the process …
> fix: errors from `tns doctor` are not visible in CI environment

- lib/common/mobile/ios/ios-device-base.ts
- lib/common/services/lock-service.ts
- lib/constants.ts
- lib/device-sockets/ios/app-debug-socket-proxy-factory.ts
- lib/services/ios-debugger-port-service.ts
- test/services/ios-debugger-port-service.ts
connected to: https://github.com/NativeScript/nativescript-vscode-extension/issues/188
> fix: increase the debugger port timeout in order to support bigger apps

- lib/services/ios-project-service.ts
- npm-shrinkwrap.json
- package.json
- test/ios-project-service.ts
filesRelativeToProject is needed to maintain the default behaviour of the library and keep the library tests green.
The ".notadd" file should be added to the PbxFileReference section, but not to the PBXSourcesBuildPhase group.
Related to https://github.com/NativeScript/nativescript-cli/issues/4391
> fix: update node-xcode library

- .gitignore
- Gruntfile.js
- config/test-dependencies.json
- lib/bootstrap.ts
- lib/commands/test-init.ts
- lib/definitions/project.d.ts
- lib/services/test-initialization-service.ts
- npm-shrinkwrap.json
- package.json
Take a look at the issue below.
We update the unit testing dependencies to their latest versions on each CLI pack and then use these hardcoded version runtime. In this way, we keep them up-to-date and install only versions verified by our CI tests.
connected to: #4390
> feat: keep the unit testing dependencies up-to-date and stable

- lib/common/http-client.ts
Better fix than #4329
It is better to stop the timer once the handshake completes than to check the request type.
> fix: retry stuck requests

- lib/common/services/commands-service.ts
- lib/declarations.d.ts
- lib/definitions/project.d.ts
- lib/options.ts
- lib/project-data.ts
- test/options.ts
- test/stubs.ts
Implements: https://github.com/NativeScript/nativescript-cli/issues/4394
> feat: enable hmr by default for new projects

- lib/services/doctor-service.ts
- lib/services/project-data-service.ts
- package.json
- test/services/doctor-service.ts
In case you have a minified content or just several statements on the same line, we may print you a warning that you have short imports, in cases where you do not have such.
Fix this by splitting the content by new line and by `;` after that. This way, in case you have multiple statements on the same line, we'll separate them and should be able to check them correctly.
Also, ensure `node_modules` of the application are not analyzed.
NOTE: Currently in case you have a multiline string, like:
```
const lodash = require("lodash");console.log(`this is
multiline string
that has require "application" in it
and ends somewhere else`);
```
We'll detect the `that has require "application" in it` line as short import. Add test to show that this is the intended behavior at the moment, as fixing it …
> fix: warnings for short imports should be shown correctly

- lib/services/ios-project-service.ts
- test/ios-project-service.ts
In some cases NativeScript CLI fails on all iOS related commands (build, run, debug, etc.) with error: `NativeScript can only run in Xcode version 6 or greater`.
This happens when user has correct Xcode version, i.e. 9 or greater, but the `head` command on their machine does not support `-n` flag. This happens when the `head` command is overwritten by some tool, so the `head` executable is not the original one used by macOS.
CLI has some obsolete code to check the Xcode version AFTER it has verified it in the doctorService. Delete this code and use sysInfo's getXcodeVersion, which does not rely on `head` command.
CLI fails to execute iOS related commands when the `head` command is not the original one from macOS.
CLI is able to execute iOS related commands when the `head` command is not …
> fix: get Xcode version correctly

- lib/definitions/platform.d.ts
- lib/services/platform-service.ts
- lib/services/prepare-platform-js-service.ts
`skipCopyTnsModules` and `skipCopyAppResourcesFiles` were introduced in order to satisfy the needs of preview app. As the preview doesn't prepare the project anymore, we don't need this logic.
There is logic for `skipCopyTnsModules` and `skipCopyAppResourcesFiles`.
There is no logic for `skipCopyTnsModules` and `skipCopyAppResourcesFiles`.
Introduced here https://github.com/NativeScript/nativescript-cli/commit/5986b60a0be8e5208426d9b7fc72b63f4f981869
> fix: remove the logic for skipCopyTnsModules and skipCopyAppResourcesFiles

- lib/common/http-client.ts
Do not change the options object in the httpRequestCore method of the
$httpClient because if we do, we can't retry correctly the http requests 
(e.g. we delete the body property and when we retry the request, we don't have any body to send)
> fix: don't change the options in httpRequestCore

- lib/common/http-client.ts
- lib/services/doctor-service.ts
- lib/services/project-data-service.ts
- test/services/doctor-service.ts
> chore: merge release into master

- README.md
> I tried my best to make your readme a little better. I think it looks nice : )

- config/test-dependencies.json
- lib/commands/test-init.ts
- lib/common/declarations.d.ts
- lib/definitions/project.d.ts
- lib/services/test-execution-service.ts
- lib/services/test-initialization-service.ts
- resources/test/karma.conf.js
`tns test --bundle` command does not work
`tns test --bundle` command works
https://github.com/NativeScript/nativescript-cli/issues/4392
> feat: implement unit testing with bundle

- lib/common/mobile/android/android-emulator-services.ts
Sometimes when an emulator is started from sidekick, the error "cannot read property imageIdentifier of undefined" is thrown.
> fix: fix the "cannot read property imageIdentifier of undefined" error

- lib/services/doctor-service.ts
- test/services/doctor-service.ts
In some cases when there's minified code, CLI prints warning for short imports, while in fact there's no such thing in the code.
Fix the regular exepression to be more strict.
Also, instead of iterrating over each regular expression for core-modules directories, join them in a single RegExp. This improves the worst case scenario (i.e. when there are short imports for `xml` of `tns-core-modules`) with around 40%.
CLI prints warnings for short imports when there's `require` and `text/javascript` on one line.
CLI prints warnings only for actual requires.
> fix: warnings for short imports should not be shown for minified code

- lib/services/livesync/livesync-service.ts
`Hot Module Replacement (HMR) is currently in Beta. For more information about the current development state and any known issues, please check the relevant GitHub issue: https://github.com/NativeScript/NativeScript/issues/6398` is shown while we don't have any critical HMR issues.
No beta warnings are shown.
Related to: https://github.com/NativeScript/nativescript-cli/issues/4456
> fix: remove the HMR Beta warnings as all critical issue are fixed

- lib/definitions/livesync.d.ts
- lib/services/livesync/livesync-service.ts
In case there's no Developer Disk  Image on iOS device, applying a change in code during debug, leads to many crashes and incorrect behavior, as CLI raises `debuggerAttached` event incorrectly.
You are able to debug in Sidekick without Developer Disk Image 
> fix: raise debuggerAttached only if app is restarted

- lib/common/constants.ts
- lib/common/mobile/ios/device/ios-device.ts
- lib/common/mobile/ios/ios-device-base.ts
- lib/common/mobile/ios/simulator/ios-simulator-device.ts
- lib/definitions/hmr-status-service.d.ts
- lib/definitions/ios-debugger-port-service.d.ts
- lib/services/hmr-status-service.ts
- lib/services/ios-debugger-port-service.ts
- lib/services/livesync/livesync-service.ts
- test/services/ios-debugger-port-service.ts
If you LiveSync a crashing app, the CLI will wait 60 seconds for its debug port and log a warning for a manual app start.
If you LiveSync a crashing app, the CLI will start the app and stop looking for its debug port after the crash without logging any warnings.
Related to: https://github.com/NativeScript/nativescript-cli/issues/4441
> fix: do not wait 60 seconds for debugger port when the app is crashed

- .github/PULL_REQUEST_TEMPLATE.md
No info how to run e2e tests on PR.
Add info how to run e2e tests on PR.
> chore: add e2e test info in PR template

- lib/common/mobile/ios/simulator/ios-simulator-application-manager.ts
The Simulator logs in your app entry point might not be shown in the CLI output.
We listen for Simulator logs before we start the app and we won't miss any of them.
> fix: start iOS simulator logs before starting the app

- lib/commands/preview.ts
- lib/definitions/preview-app-livesync.d.ts
- lib/definitions/project.d.ts
- lib/project-data.ts
- lib/services/livesync/livesync-service.ts
- lib/services/livesync/playground/preview-sdk-service.ts
- lib/services/platform-environment-requirements.ts
- test/services/preview-sdk-service.ts
- test/stubs.ts
Currently the schema is hardcoded to `nsplay`. This PR adds support for passing schema and keys from the public api when livesyncing to `preview app`. If no schema is provided, {N} CLI checks if the `previewAppSchema` is added to `nsconfig.json`. If there is no `previewAppSchema` property in `nsconfig`, {N} CLI fallbacks to `nsplay`.
> feat: add ability to pass schema to preview app from nsconfig file

- lib/commands/debug.ts
- lib/common/definitions/mobile.d.ts
- lib/common/mobile/ios/ios-device-base.ts
- lib/services/livesync/ios-device-livesync-service.ts
When we try to get debug socket in `tns debug ios --debug-brk`, an additional app start is resuming the app and we are not able to debug the app start.
We are making an additional app start call only during LiveSync.
>  fix: debugging clients are now able to debug with debug-brk

- lib/common/mobile/android/android-device.ts
As the `release` property of android 'Q' devices is 'q' (not a version string as for the another devices), we need to convert it to version so all `semver` comparison are working correctly. 
Rel to: https://github.com/NativeScript/nativescript-cli/issues/4451
> fix: add support for android 'Q'

- lib/definitions/project.d.ts
- lib/services/ios-extensions-service.ts
- lib/services/ios-project-service.ts
> chore: add wanrning for extensions beta support

- lib/commands/post-install.ts
- test/commands/post-install.ts
When `sudo npm i -g nativescript` is used, postinstall tasks produce errors, which confuse the users. CLI is actually installed successfully, but error for EACCESS is often shown.
The problem is that npm executes the postinstall scripts with a special OS user - `nobody`. This user does not have permissions to write in users' directories, so generating html help or writing the user-settings.json file fails.
Npm's solution is to pass `--unsafe-perm` to the `sudo npm install -g nativescript` command, which forces the postinstall to be executed with root user.
Fix CLI's code to skip postinstall tasks in case sudo is used and `--unsafe-perm` is not passed.
`sudo npm install -g nativescript` fails with EACCESS, but CLI is installed correctly.
`sudo npm install -g nativescript` executes …
> fix: errors are shown on postinstall when using sudo

- npm-shrinkwrap.json
- package.json
- yarn.lock
In case you have incorrect JAVA_HOME, but you have `javac` in PATH, CLI's doctor checks will allow you to build, but Gradle will fail. Fix the logic to be the same as the one used in Gradle.
> fix: detect java correctly

- lib/bootstrap.ts
- lib/definitions/preview-app-livesync.d.ts
- lib/services/livesync/playground/preview-app-constants.ts
- lib/services/livesync/playground/preview-app-livesync-service.ts
- lib/services/livesync/playground/preview-qr-code-service.ts
- lib/services/livesync/playground/preview-schema-service.ts
- lib/services/livesync/playground/preview-sdk-service.ts
- npm-shrinkwrap.json
- package.json
- test/services/playground/preview-app-livesync-service.ts
- test/services/playground/preview-schema-service.ts
- test/services/preview-sdk-service.ts
- yarn.lock
* Respect the correct min supported versions from https://github.com/telerik/nativescript-preview-sdk/blob/master/src/preview-app-versions.js
* Fix exported getPlaygroundAppQrCode method to return correct data based on the schema
* Provide previewAppStoreId and previewAppGoogledPlayId to preview-sdk in order to show correct data on deprecated page from kinvey's preview app
Should be merged after this PR https://github.com/telerik/nativescript-preview-sdk/pull/30
> feat(kinvey): provide correct data to preview-sdk based on the schema

- lib/services/livesync/playground/preview-qr-code-service.ts
- lib/services/livesync/playground/preview-schema-service.ts
- test/services/playground/preview-schema-service.ts
- test/services/preview-sdk-service.ts
> fix: change ksplay to kspreview schema

- lib/services/livesync/playground/preview-schema-service.ts
- package.json
- test/services/playground/preview-schema-service.ts
> fix(kinvey): use correct store ids for preview and scanner apps

- lib/services/android-project-service.ts
Remove the old logic related to legacy structure of native android project as it is not needed anymore. (related to 3.4.0 release)
Rel to: https://github.com/NativeScript/nativescript-cli/issues/4504
> fix: remove legacy code related to old structure of android project

- lib/common/constants.ts
- lib/common/http-client.ts
In case 304 is returned, the cached version of the result should be used, so consider this response as success. NOTE: It can be returned only when specific header is sent in the request, so the caller actually expects to receive either 304 or 200 with new content.
Http requests returning 304 are considered as failed.
Http requests returning 304 are considered as successful.
> fix: handle HTTP 304 response status code

- lib/commands/add-platform.ts
- lib/commands/appstore-upload.ts
- lib/commands/build.ts
- lib/commands/clean-app.ts
- lib/commands/install.ts
- lib/commands/platform-clean.ts
- lib/commands/prepare.ts
- lib/commands/update-platform.ts
- lib/commands/update.ts
- lib/declarations.d.ts
- lib/definitions/platform.d.ts
- lib/definitions/project.d.ts
- lib/helpers/deploy-command-helper.ts
- lib/options.ts
- lib/services/livesync/livesync-service.ts
- lib/services/local-build-service.ts
- lib/services/platform-service.ts
- lib/services/prepare-platform-js-service.ts
- test/platform-service.ts
> chore: remove projectTemplate logic

- docs/build-jekyll-md.sh
- docs/man_pages/project/testing/build-android.md
- docs/man_pages/project/testing/build-ios.md
- docs/man_pages/project/testing/build.md
- docs/man_pages/project/testing/run-android.md
- docs/man_pages/project/testing/run-ios.md
- docs/man_pages/project/testing/run.md
- tsconfig.json
Short descriptions for all supported environment flags (info will be visible at docs.nativescript.org and via `help` command/flag)
> docs: add environment flags in CLI help

- docs/man_pages/project/testing/build-ios.md
- lib/commands/appstore-upload.ts
- lib/commands/build.ts
- lib/declarations.d.ts
- lib/definitions/project.d.ts
- lib/helpers/livesync-command-helper.ts
- lib/options.ts
- lib/services/ios-project-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/platform-service.ts
- lib/services/test-execution-service.ts
- test/services/android-project-service.ts
Enterprise applications that use iCloud fail to build in 5.x. 
(This was not an issue in prior versions.)
The error message is: 
```
error: exportArchive: exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided
```
Allow the user to pass a new `--i-cloud-container-environment` option (while doing a `--for-device` build), that accepts an environment string.
Fixes/Implements/Closes #4374.
> feat: add iCloudContainerEnvironment build option

- config/test-dependencies.json
- lib/commands/test-init.ts
- lib/common/declarations.d.ts
- resources/test/example.jasmine.ts
- resources/test/example.mocha.ts
- resources/test/example.qunit.ts
- resources/test/karma.conf.js
- tsconfig.json
https://github.com/NativeScript/nativescript-cli/issues/1798
> feat: add sample test in TypeScript for ts projects on test init command

- lib/services/android-project-service.ts
Rel to: https://github.com/NativeScript/nativescript-cli/issues/4504
> fix: support custom tagged android runtime versions

- lib/commands/run.ts
Shows up an appropriate message while trying to run app in non-project directory
If you try to run app in non-project folder with --path in command without existing folder, you will see exception and you couldn't understand what is the problem.
correct error for non existing folder
Closes #4280
> Shows an appropriate message while trying to run the app in a non-project folder

- lib/bootstrap.ts
- lib/commands/appstore-list.ts
- lib/commands/appstore-upload.ts
- lib/declarations.d.ts
- lib/services/apple-portal/apple-portal-application-service.ts
- lib/services/apple-portal/apple-portal-cookie-service.ts
- lib/services/apple-portal/apple-portal-session-service.ts
- lib/services/apple-portal/definitions.d.ts
- lib/services/itmstransporter-service.ts
- npm-shrinkwrap.json
- package.json
Rel to: https://github.com/NativeScript/nativescript-cli/issues/4527
> fix: fix upload to appstore for accounts without 2 factor authentication

- .travis.yml
- .travis/add-publishConfig.js
> chore: automate publish of webpack tag

- lib/services/android/gradle-command-service.ts
- test/services/android/gradle-build-args-service.ts
> fix: fix the unit tests execution with istanbul

- lib/bootstrap.ts
- lib/commands/appstore-upload.ts
- lib/constants.ts
- lib/declarations.d.ts
- lib/definitions/project.d.ts
- lib/definitions/xcode.d.ts
- lib/services/android-project-service.ts
- lib/services/ios-project-service.ts
- lib/services/ios/export-options-plist-service.ts
- lib/services/ios/ios-signing-service.ts
- lib/services/ios/xcodebuild-args-service.ts
- lib/services/ios/xcodebuild-command-service.ts
- lib/services/ios/xcodebuild-service.ts
- lib/services/platform-service.ts
- lib/services/xcproj-service.ts
- test/ios-project-service.ts
- test/services/ios/export-options-plist-service.ts
- test/services/ios/ios-signing-service.ts
- test/services/ios/xcodebuild-args-service.ts
- test/services/ios/xcodebuild-service.ts
- test/tns-appstore-upload.ts
> refactor: refactor ios build

- lib/declarations.d.ts
- lib/services/cocoapods-service.ts
- lib/services/ios-project-service.ts
- lib/services/xcconfig-service.ts
- npm-shrinkwrap.json
- package.json
- test/ios-project-service.ts
Currently CLI merges and prepares xcconfig files only for the current build configuration, i.e. debug or release. However, the `pod install` command works with both configurations. This leads to problem when some property is set in the project's (plugin's) build.xcconfig file as CLI will prepare the native iOS project only for one configuration. When `pod install` is executed, if the Pods project uses the property set in the build.xcconfig file, it will fail with error, as the value for debug and release will be different (i.e. it will be set only for one of them). Pods project does not support this behavior, so the build operation fails.
So, ensure CLI merges all xcconfig files for both debug and release configurations. This way, the Pods project will be in sync, so it should continue …
> fix: prepare xcconfig files for all conigurations

- lib/bootstrap.ts
- lib/commands/build.ts
- lib/commands/debug.ts
- lib/commands/deploy.ts
- lib/commands/prepare.ts
- lib/commands/preview.ts
- lib/commands/run.ts
- lib/commands/test.ts
- lib/commands/update.ts
- lib/common/helpers.ts
- lib/declarations.d.ts
- lib/definitions/platform.d.ts
- lib/definitions/project.d.ts
- lib/helpers/bundle-validator-helper.ts
- lib/helpers/livesync-command-helper.ts
- lib/options.ts
- lib/project-data.ts
- lib/services/livesync/playground/preview-app-livesync-service.ts
- lib/services/platform-service.ts
- lib/services/project-data-service.ts
- lib/services/workflow-service.ts
- test/debug.ts
- test/helpers/bundle-validator-helper.ts
- test/package-installation-manager.ts
- test/platform-commands.ts
- test/platform-service.ts
- test/services/playground/preview-app-livesync-service.ts
- test/services/project-data-service.ts
- test/stubs.ts
- test/update.ts
These changes are fully deprecating the Legacy Development Workflow and preparing the users for removing the its support in NativeScript 6.0.0.
We are fully supporting both the legacy prepare (copying the whole app folder and post-processing it with nativescript-dev-typescript, nativescript-dev-sass, etc.) and the webpack approach (using nativescript-dev-webpack and its plugins/loaders).
We are deprecating the legacy workflow as shown on the charts below:
Related to: https://github.com/NativeScript/nativescript-cli/issues/4548
> feat: deprecate the legacy workflow and recommend the new one

- lib/common/helpers.ts
Always split by "\n" as the string literals are always generating "/n" line terminators based on the below-mentioned ES specification.
More details: http://exploringjs.com/es6/ch_template-literals.html#_line-terminators-in-template-literals-are-always-lf-n
```
8.2.3 Line terminators in template literals are always LF (\n) #
Common ways of terminating lines are:
Line feed (LF, \n, U+000A): used by Unix (incl. current macOS)
Carriage return (CR, \r, U+000D): used by the old Mac OS.
CRLF (\r\n): used by Windows.
`All of these line terminators are normalized to LF in template literals.` That is, the following code logs true on all platforms:
const str = `BEFORE
AFTER`;
console.log(str === 'BEFORE\nAFTER'); // true
```
Related to: #4548
> fix: fix the workflow warnings on Windows

- lib/common/http-client.ts
Since there are no tests for `http-client` yet, it would be quite a lot of work to add them. Also, the method which was changed `useProxySettings` is private and therefore more difficult to test.
With a proxy set according to https://docs.nativescript.org/tooling/docs-cli/general/proxy-set when running unit tests with `tns test android` for example, requests to localhost are being made. Depending on the corporate proxy environment, those requests could be blocked or the proxy can't handle the request, since `localhost` is not a remote target. This makes running unit tests with NativeScript impossible in corporate proxy environments, causing exceptions interrupting the test execution. Also, it doesn't make sense to make requests to `localhost` through a proxy, so this will not have any …
> fix: use proxy only for remote requests

- lib/common/mobile/android/logcat-helper.ts
- lib/common/test/unit-tests/mobile/android/logcat-helper.ts
In case you have `keepSingleProcess` passed to logcat Stream (this option is passed when using CLI as a library - in this case we keep a long living logcat process alive and change only the filter for it by specifying different PIDs), in case the logcat process dies (for example device is disconnected), the process is not cleaned from CLI's internal cache.
This way, in case you try to start the logs again (in the example above - just attach the device again), they are not started as CLI thinks it has a process for this case. So, in case the logcat stream process dies, ensure we clean all the resources related to it.
Add unit tests for this case and remove calls to `type`/`cat` from the tests - there's no need to spawn actual child process in the tests.
When using CLI as a library …
> fix: logcat process is not restarted in some cases

- lib/definitions/cleanup-service.d.ts
- lib/detached-processes/cleanup-js-subprocess.ts
- lib/detached-processes/cleanup-process-definitions.d.ts
- lib/detached-processes/cleanup-process.ts
- lib/detached-processes/detached-process-enums.d.ts
- lib/services/cleanup-service.ts
In some cases it is required to execute some JS functions to clean used resources by CLI. Add an easy way to specify JS files which should be executed by the cleanup process.
Each JS action is defined by a JS File, which should be required, data that will be passed to the default exported function in the file and timeout - if the action cannot be executed for specified time (3 seconds is the default), the child process in which the JS action is executed will be killed.
> feat: allow executing JS funcitons on cleanup

- lib/commands/clean-app.ts
- lib/common/services/commands-service.ts
- lib/declarations.d.ts
- lib/options.ts
- lib/services/platform-service.ts
- test/platform-service.ts
https://github.com/NativeScript/nativescript-cli/issues/4518
> feat: show deprecated messages for things that will be dropped as of NativeScript v.6.0.0

- lib/options.ts
We decided to delete the warning message for `--bundle` option as it is too confusing with the messages for the new workflow.
> chore: remove the deprecation message for `--bundle` option

- docs/man_pages/project/testing/debug-android.md
Removing the obsolete steps needed to enable HMR - the Wiki should be deleted as well https://github.com/NativeScript/nativescript-angular/wiki/HMR
Removing BETA statements for HMR status
> docs: remove obsolete HMR steps

- lib/services/ios-project-service.ts
> fix: target argument passed to xcodebuild when using workspace

- lib/detached-processes/cleanup-process.ts
- lib/services/analytics/analytics-broker-process.ts
When CLI dies, the `analyticsBroker` and `cleanupProcess` processes receive disconnect event. At this point they have to finish their work and die silently after that.
However, this does not happen for `analyticsBroker` process as in the `disconnect` handler we call `process.disconnect` method. It fails, as the process is already disconnected. So the process hangs in undefined state and it leaks. The stareted cleanup process from it also leaks.
To fix this remove the disconnect call from the handler.
Also ensure injector is disposed before calling process.exit in the detached process's handler.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/4593
> fix: ensure analytics and cleanup processes are not leaking

- lib/common/logger/logger.ts
`--log trace` is broken as we are tring to iterate over object created with `Object.create(null)`. It uses the prototype of null, so it does not have `hasOwnProperty` method. Filter such objects from our checks in logger.
Also nativescript-plugin-firebase uses logger.out, which has been deleted, get it back for backwards compatibility and delete it in 6.0.0 release.
Related to https://github.com/NativeScript/nativescript-cli/issues/4602
> fix: logger changes broke trace and some hooks

- lib/services/plugins-service.ts
- test/plugins-service.ts
https://github.com/NativeScript/nativescript-cli/issues/4608
https://github.com/NativeScript/nativescript-cli/issues/4608 is addressed
> style: misleading warning message

- lib/common/definitions/logger.d.ts
- lib/common/logger/logger.ts
- lib/common/test/unit-tests/stubs.ts
- lib/declarations.d.ts
- test/stubs.ts
Several plugin use deleted logger methods in their hooks. Same is valid for `nativescript-cloud` extension.
To resolve this, get back the deleted methods, we'll delete them in 6.0.0 release.
Also, `nativescript-cloud` has an option `--workflow`, that is an object, while ours is boolean. This breaks its transpilation, so set ours to `any`.
> fix: make logger backwards compatible

- npm-shrinkwrap.json
- package.json
Update to `nativescript-dev-xcode` dependency. Previously the dependency was targeted to the last commit in the development repository.
> chore: update nativescript-dev-xcode to 0.2.0

- lib/services/workflow-service.ts
> fix: set correct link for legacy workflow warning

- lib/common/logger/logger.ts
- lib/services/plugins-service.ts
- npm-shrinkwrap.json
- package.json
- test/plugins-service.ts
> chore: merge release-patch in release

- lib/options.ts
Currently `tns build <platform>` command fails with error `Passing --bundle requires a bundling plugin. No bundling plugin found or the specified bundling plugin is invalid.`
> fix: set bundle option to webpack

- lib/definitions/project.d.ts
- lib/services/assets-generation/assets-generation-service.ts
- lib/services/project-data-service.ts
- resources/assets/image-definitions.json
Currently the App Store icon is generated with transparency alpha channel which is not permitted by Apple: for reference [Stack Overflow thread](https://stackoverflow.com/questions/25681869/images-cant-contain-alpha-channels-or-transparencies).
For this particular image the alpha channel is disabled.
Fixes/Implements/Closes https://github.com/NativeScript/nativescript-cli/issues/4584
> fix: generated App Store icon has alpha channel

- docs/man_pages/project/creation/create.md
- lib/commands/create-project.ts
- test/project-commands.ts
when vue flavor is selected, an app is created with the vue blank template 
when vue flavor is selected, two options are presented - Blank and SideDrawer
Fixes/Implements/Closes #4651.
> feat: add vue drawer navigation template to create project command

- lib/common/definitions/logger.d.ts
- lib/common/logger/logger.ts
- lib/common/test/unit-tests/stubs.ts
- lib/services/webpack/webpack-compiler-service.ts
- test/stubs.ts
`copy-webpack` plugin prints its info messages on `stderr` by default. This led to the problem that these messages are shown in errors tab in Sidekick.
When `{ verbose: false }` is provided as option to `copy-webpack` plugin, it doesn't print any information. So when `tns run android` is executed, no messages will be shown from `copy-webpack` plugin and thus no errors will be shown from Sidekick.
> fix: pass --env.verbose to webpack compiler

- lib/services/android-project-service.ts
- lib/services/ios-project-service.ts
- lib/services/platform/prepare-native-platform-service.ts
- lib/services/webpack/webpack.d.ts
- test/stubs.ts
Currently App_Resources are copied to platforms folder and after that NativeScript CLI  moves them to the correct places in native project and deletes the App_Resources folder in platforms. On the other side, nativescript-dev-webpack plugin copies the App_Resources to platforms folder only on initial start (not when some file is changed). This led to the problem that when native file is changed, NativeScript CLI moves App_Resources to the correct places in native project and deletes App_Resources folder inside platforms (the one that nativescript-dev-webpack plugin has previously copied on initial webpack's compilation). On the next native file change, NativeScript CLI tries to move the platforms/App_Resources to the correct places inside native project, but this directory doesn't exist. …
> fix: respect App_Resources directly from project

- lib/controllers/run-controller.ts
- lib/services/build-info-file-service.ts
`InstallationLookupFailed` error is thrown when trying to deploy on iOS device. The reason is that NativeScript CLI is not able to find applicationIdentifier from `projectData.projectIdentifiers` as the platform is not lower case.
For iOS simulator it is fine as the applicationIdentifier is not used when uploading files to the simulator.
> fix: fix `InstallationLookupFailed` error is thrown when deploying on iOS device

- lib/helpers/livesync-command-helper.ts
The project is prepared every time on initial sync, but buildAction prepares again and builds the project (buildAction is executed only when the project should be built). This led to the problem that project is prepares twice when buildAction is executed.
> fix: prepare the project only once per run

- lib/controllers/prepare-controller.ts
- lib/services/webpack/webpack-compiler-service.ts
- lib/services/webpack/webpack.d.ts
Implements: https://github.com/NativeScript/nativescript-dev-webpack/issues/911
> feat: set webpack in production mode based on `--release` option

- lib/common/services/commands-service.ts
- lib/declarations.d.ts
- lib/options.ts
- test/options.ts
Currently when you run `tns cloud run ...` the command executes local prepare without taking into account the value of `useLegacyWorkflow` value in nsconfig.json file.
The problem is that cloud commands have specific `--` options, which are set as `dashedOptions` on command level. During command execution the following actions happen:
1. CLI starts its execution and via `$injector` constructs new instance of `$options`.
2. In the constructor of `$options` we call `this.setArgv()`, which calls `yargs` package and constructs values based on the user input of `--` options.
3. `$injector` resolves `$commandsService` and constructs new object from it.
4. In the constructor of `CommandsService`, we call `$options.setupOptions` and pass the current projectData. `setupOptions` takes into account …
> fix: cloud run command does not respect useLegacyWorkflow flag

- lib/common/logger/logger.ts
Several logger methods have been deprecated, but their usage had been broken. Fix it until we delete them.
The current problem arises when we pass several args to the `logger.out` (or any deprecated method) - instead of passing args directly to `logger.info`, we need to spread them
`tns account` command prints incorrect table.
`tns account` prints correct table.
> fix: pass correct args when using deprecated logger API

- lib/common/verify-node-version.ts
In case you are using unsupported Node.js version CLI must show you error that this version is not supported and to inform you which is the supported range. Currently this is not working and CLI shows error for `Unexpected token`.
The problem is that CLI has some specific logic to check the Node.js version and the code should be pure ES5 syntax in order to work with old Node.js versions (by default CLI's code is ES6).
The current issue is caused by using string interpolation in the mentioned code. Fix the message to fix the problem.
Fixes https://github.com/NativeScript/nativescript-cli/issues/4665
> fix: incorrect error for non-supported Node.js version

- lib/controllers/run-controller.ts
- lib/helpers/livesync-command-helper.ts
`tns cloud run` doesn't build the project in cloud on native change.
`tns cloud run` builds the project in cloud on native change.
> fix: fix cloud run command

- lib/controllers/prepare-controller.ts
`tns run android --emulator –justlaunch ` throws an error `Unable to apply changes on device: emulator-5554. Error is: Cannot read property 'hasNativeChanges' of null.`
`tns run android --emulator –justlaunch` works correctly
> fix: fix run with --justlaunch

- lib/controllers/build-controller.ts
- lib/controllers/deploy-controller.ts
- lib/definitions/gradle.d.ts
- lib/definitions/run.d.ts
- lib/helpers/deploy-command-helper.ts
- lib/helpers/livesync-command-helper.ts
- lib/services/android-project-service.ts
- lib/services/android/gradle-build-args-service.ts
- lib/services/android/gradle-build-service.ts
- lib/services/platform/prepare-native-platform-service.ts
- lib/services/webpack/webpack.d.ts
- test/services/android/gradle-build-args-service.ts
- test/stubs.ts
`tns run android --emulator --release --key-store-path <pathToKeyStoreFile> --key-store-password <keyStorePassword> --key-store-alias <keyStoreAlias> --key-store-alias-password <keyStoreAliasPassword> ` throws an error `The "path" argument must be of type string. Received type undefined `
`tns run android --emulator --release --key-store-path <pathToKeyStoreFile> --key-store-password <keyStorePassword> --key-store-alias <keyStoreAlias> --key-store-alias-password <keyStoreAliasPassword>` works correctly
> fix: fix release run for android

- lib/common/logger/logger.ts
- lib/common/test/unit-tests/logger.ts
In case you try printing the following:
```
const obj1 = null;
this.$logger.info("value %s", obj1);
```
Our implementation fails with error: `Cannot read property hasOwnProperty of null`.
The problem is in the way we check for passed logger options in the args passed to `logger` methods. The `typeof null` returns object, so next parts of the code fail.
Also passed logger options are handled by priority, i.e. the first passed option should be used. This allows callers of methods that specify some logger options internaly, to overwrite their values. Add unit tests for this behavior.
Fix the case when same logger option is passed multiple times in different objects - currently only one of the instances is removed and the other one is included in the message visible to the user. Now all such …
> fix: logger fails to print null objects

- lib/services/webpack/webpack-compiler-service.ts
As we have an issue that the hmr changes are not applied after restarting the application, we  need to skip webpack's runtime chunks when sending files for the HMR updates.
> fix: handle correctly runtime files

- lib/controllers/prepare-controller.ts
- lib/controllers/run-controller.ts
- lib/definitions/project-changes.d.ts
- lib/services/platform/prepare-native-platform-service.ts
- lib/services/project-changes-service.ts
- test/project-changes-service.ts
- test/stubs.ts
Rel to: https://github.com/NativeScript/nativescript-cli/issues/4647
> fix: don't check all node_modules from `checkForChanges` method

- lib/common/mobile/mobile-core/devices-service.ts
In case CLI is used as a library, you need both Android and iOS to be setup in order to start simulator/emulator. The problem is that we check for errors in the setup before actually checking if we have found simulator/emulator with the specified name.
Change the logic and do not raise errors in case the specified name/id is found. This way you can start iOS Simulator without having any Android setup on local machine.
> fix: unable to start iOS simulator when Android is not setup

- lib/commands/init.ts
`tns init` command will be deleted in 6.0.0 release, so we need to show deprecation message when someone uses it.
Implements https://github.com/NativeScript/nativescript-cli/issues/4701
> fix: show deprecation message on tns init

- lib/services/webpack/webpack-compiler-service.ts
`tns debug` command doesn't show `webpack://` in file's tree inside chrome dev tools
`tns debug` command shows `webpack://` in file's tree inside chrome dev tools by default.
> fix: enable source maps by default

- lib/services/webpack/webpack-compiler-service.ts
Currently `inspector.modules.js` file is reported on change and this led to the problem that `inspcector-modules.js` file is transferred on every sync. As we need to transfer only `.hot-update` files when `--hmr` is provided, we should exclude all other files.
> fix: emit only `bundle.<hash>.hot-update.js` and `<hash>.hot-update.json` files when `--hmr` is provided

- resources/test/karma.conf.js
(Karma is compiling only in memory)
The unit testing command with `bundle` is failing when the `GenerateNativeScriptEntryPointsPlugin` plugin is used.
The Webpack plugins which require the files from the file system are removed when compiling in Karma.
> fix: disable the Webpack plugins which require the files from the file system

- npm-shrinkwrap.json
- package.json
Debugging on iOS Device is very slow with bundle workflow. The problem is in the way ios-device-lib handles the huge messages. Update the library to its latest version where this issue is resolved.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/4226
> fix: debugging on iOS Device is very slow

- lib/services/webpack/webpack-compiler-service.ts
Cannot read property 'sourceMap' of undefined error is thrown when no `--env` is provided.
> fix: fix cannot read property sourceMap of undefined

- lib/controllers/prepare-controller.ts
- lib/controllers/preview-app-controller.ts
- test/services/playground/preview-app-livesync-service.ts
Add `preview-sync` and `watchPatterns` hooks as some plugins relies on them.
> fix: add preview-sync and watchPatterns hooks

- lib/helpers/livesync-command-helper.ts
> fix: populate correctly prepareData and buildData when they are based on $options

- lib/services/webpack/webpack-compiler-service.ts
If you delete `node_modules` of application and try to execute `tns prepare` or `tns build`, the following error is thrown:
```
Error: Cannot find module '<path-to-project>/node_modules/webpack/bin/webpack.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
at Function.Module._load (internal/modules/cjs/loader.js:506:25)
at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
at startup (internal/bootstrap/node.js:285:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Executing webpack failed with exit code 1.
```
> fix: ensure dependencies are installed before spawning webpack

- lib/controllers/prepare-controller.ts
- lib/controllers/run-controller.ts
- test/controllers/prepare-controller.ts
Currently CLI provides the following watch patterns `node_modules/**/platforms/<platform>` to `chokidar`. The plugin developers have `symlinked` plugin's source code inside the plugin's demo projects. When the plugin's demo project is ran and a `.js` or `.ts` file is changed in `src` folder of a plugin, `chokidar` reports it as a changed file. It seems as an issue with the way how `symlinked` files are processed from `chokidar` itself. This led to a problem that when a file from plugin's src folder is changed, CLI receives changed event for this file twice - ones from `chokidar` and ones from `webpack's watcher`. After that CLI restarts the application as a change from "native watcher" is received. In order to fix this issue, we changed the patterns provided to choki as we removed the …
> fix: fix plugin's development workflow

- lib/common/mobile/mobile-core/devices-service.ts
- npm-shrinkwrap.json
- package.json
- resources/test/karma.conf.js
> chore: merge master branch

- lib/controllers/prepare-controller.ts
- lib/services/platform/add-platform-service.ts
- lib/services/platform/prepare-native-platform-service.ts
- lib/services/project-changes-service.ts
- lib/services/webpack/webpack.d.ts
- test/project-changes-service.ts
- test/stubs.ts
> fix: save correct .nsprepareinfo file on cloud commands

- .travis.yml
All other packages in Nativescript(e.g. Runtime, Angular...) have time in their version. We are using the time in the version to determine if we need to run tests. We run tests if the package has been released  within the 24 hours period since running the triggering job.
> Add time(hours, minutes and seconds) to cli version.

- lib/services/webpack/webpack-compiler-service.ts
> fix: extend process's max size only for `x64` processes

- lib/services/webpack/webpack-compiler-service.ts
The files on android device are transferred through socket. When the application is in errorActivity, the runtime reports to the CLI that the application is in broken state (e.g. didRefresh property). In this case NativeScript CLI transfers all fallback files (bundle.js and runtime.js). CLI has a logic to ignore all non-existing files when transferring them on the device. As the fallback files are reported with relative paths, CLI consider them as non-existing and doesn't transfer them on device. So in order to fix this issue, we need to make fallbackFiles with absolute paths.
To reproduce:
1. tns run android
2. Broke some xml file from the application
3. Fix the broken xml file
> fix: restore application when the broken xml file is fixed

- lib/helpers/livesync-command-helper.ts
When `tns run android --release --env.snapshot` command is executed, `{ skipWatcher: true }` option is provided. On the other side watch option has default true value so as a result we have { skipWatcher: true and watch: true }.  So a release run is started in watch mode. As the watch option is true, NativeScript CLI starts webpack in watch mode. This led to the problem that webpack reports emitted files before the snapshot generation is completed. (note: there is an another issue inside nativescript-dev-webpack plugin itself about the way how emitted files are reported - it should be fixed there.)
As a result, an async issue arise between snapshot generation and gradle build and the following error is thrown:
```
Warning: The static binding generator will generate extend from:vendor.js …
```
> fix: start webpack in non watch mode for release builds with snapshot

- CHANGELOG.md
> docs: update changelog for 5.4.1 release

- lib/common/mobile/ios/device/ios-device.ts
- lib/common/mobile/ios/ios-device-base.ts
- lib/common/mobile/ios/simulator/ios-simulator-device.ts
- package.json
With `tns cloud run ...` command (or with NativeScript Sidekick), you can use LiveSync on iOS device from Windows machine (with application built in the cloud). However, this approach does not work when the iOS device does not have developer disk image mounted (i.e. it has not been used on macOS).
The problem is that during establishment of socket connection, CLI tries to start the application. This is a precautions for cases when the application had crashed. In most of the cases when we reach to this code, the application is already up and running. However, calling `startApplication` fails on Windows and we never setup the socket connection.
So the HMR does not work at all.
Fix this by adding a try-catch block around starting of application when trying to setup the socket connection. …
> fix: hmr for iOS does not work on Windows

- lib/controllers/preview-app-controller.ts
The `kinvey-nativescript-sdk` plugin relies on `preview-sync` hook and mainly on platform property from `hookArgs`. This PR changes the workflow of `preview-sync` hook and makes it the same as in NativeScript v5.4.0. In NativeScript v5.4.0 the hook is executed when pubnub reports the device that the QR code is scanned with. This way we're able to get the platform from device and adds it to the `hookArgs` passed to the hook.
> fix: fix the workflow of preview-sync hook

- lib/helpers/platform-command-helper.ts
This PR fixes 2 issues:
`tns clean` command doesn't add the correct platform.
To reproduce:
1. `tns platform add ios@5.1.0`
2. `tns clean` 
Expected: The steps above should delete `ios@5.1.0` and install again `ios@5.1.0`
Actual:  The platform `ios@5.1.0` is deleted but `ios@5.4.0` is added instead.
`tns platform list` command doesn't work when there is already added platform. This is due to the fact that NativeScript CLI makes case sensitive comparison when getting already installed platforms.
> fix: fix `tns platform list` and `tns platform clean` commands

- npm-shrinkwrap.json
- package.json
As AppStore now requires new published apps to be build with Xcode 10 or later, set this as requirement for building applications.
Implements issue https://github.com/NativeScript/nativescript-cli/issues/4731
> feat: drop support for Xcode < 10

- lib/services/android-project-service.ts
Currently we copy all App_Resources from `./app/App_Resources/Android/*` to `./platforms/../app/src`. As there is src folder in `./app/App_Resources/Android/*`, we receive as a result inside platforms `./platforms/app/../src/src`.
> fix: fix  the way android appResources are processed

- lib/services/webpack/webpack-compiler-service.ts
NativeScript CLI v5.4.0 shows an warning when `--env.snapshot` is provided for debug builds. This PR keeps the same behavior for NativeScript v6.0.0.
> fix: show warning when --env.snapshot is provided for debug builds

- lib/controllers/deploy-controller.ts
NativeScript CLI doesn't respect correctly the built application package when there are connected device and simulator. That is the reason why `tns deploy ios --path TestApp --provision NativeScriptDevProfile –justlaunch` throws  the following error: ENOENT: no such file or directory, scandir '/Users/mivanova/Projects/TestApp/platforms/ios/build/Debug-iphonesimulator'
> fix: fix `tns deploy ios --justlaunch` when there are connected device and simulator

- lib/controllers/debug-controller.ts
- lib/controllers/run-controller.ts
- lib/definitions/livesync.d.ts
- lib/definitions/prepare.d.ts
- lib/helpers/deploy-command-helper.ts
- lib/helpers/livesync-command-helper.ts
- test/controllers/run-controller.ts
Enable passing iOS Code signing options to operations like run/debug, etc. Currently the provision and teamId options are not passed to the controllers, so we do not use them during project preparation.
To resolve this, include the buildData in the deviceDescriptors - this way we'll have all the codesigning data required for the specific device and we'll also allow having different codesign options for different devices.
Also remove outputPath from deviceDescriptors as we can use it directly from the buildData.
> fix: enable passing iOS codesigning options to LiveSync operations

- lib/services/webpack/webpack-compiler-service.ts
The memory of the Webpack process it not really increased.
The memory of the Webpack process is properly increased.
> fix: pass the max_old_space_size option to nodejs, not webpack

- lib/controllers/prepare-controller.ts
- lib/controllers/run-controller.ts
- lib/services/webpack/webpack-compiler-service.ts
- lib/services/webpack/webpack.d.ts
- test/controllers/prepare-controller.ts
TODO: rebase onto master, add more description, link issue in Webpack
Related to: https://github.com/NativeScript/nativescript-cli/issues/4607
> fix: try HMR refresh only when all emitted files are hot updates

- lib/controllers/prepare-controller.ts
- lib/services/webpack/webpack-compiler-service.ts
When `tns run` command is executed (without specified platform), NativeScript CLI starts 2 webpack processes - one for android and one for iOS. When a file is changed, android's webpack process generates for example `hash1.hot-update.json` and iOS's webpack process generates for example `hash2.hot-update.json`.  In this case NativeScript CLI transfers android's hot-update files on iOS devices and iOS's hot-update files on android devices. This led to different issues when livesyncing the application on connected devices. This PR fixes this behavior as ensures that android's hot-update files will be transferred only on android devices and iOS's hot-update files will be transferred only on iOS devices.
> fix: fix run command when no platform is provided

- lib/common/verify-node-version.ts
Currently when you are using a deprecated Node.js version, CLI prints warnings twice.
The problem is that there are two places in the code where we check Node.js version:
- In `tns` executable file - the code in it is pure ES5 and the idea is to stop users which have very old Node.js versions, whcih do not support ES6 syntax (CLI is transpiled to ES6 syntax).
- In `nativescript-cli` file - we call `initializeService.initialize`, which also checks Node.js version and prints the warnings
However, we do not need the warnings in both places. Separate the logic, so in `tns` file we'll just check if we should stop the users, i.e. it will take care only of versions which are not supported.
In `nativescript-cli` we'll continue calling initialize, which will take care of the warnings (in case …
> fix: warnings for Node.js version should be shown once

- lib/controllers/migrate-controller.ts
The tns tsconfig is always removed during tns migrate.
The tns tsconfig is removed only in non shared apps during tns migrate.
> fix(migrate): do not delete the tns tsconfig for shared apps as it contains a lot of custom code.

- lib/constants.ts
- lib/controllers/migrate-controller.ts
- lib/controllers/update-controller-base.ts
- lib/definitions/migrate.d.ts
This PR makes the following changes:
* install the latest nativescript-unit-test-runner
* install the latest karma-webpack
* update karma
* update karma.conf.js
* update karma-* plugins
> feat: migrate unit test related dependencies so `tns test` command can work out of the box with CLI v6.0

- lib/common/definitions/mobile.d.ts
- lib/common/mobile/android/android-application-manager.ts
- lib/common/mobile/application-manager-base.ts
- lib/common/mobile/device-log-emitter.ts
- lib/common/mobile/device-log-provider-base.ts
- lib/common/mobile/device-log-provider.ts
- lib/common/mobile/ios/device/ios-application-manager.ts
- lib/common/mobile/ios/simulator/ios-simulator-application-manager.ts
- lib/common/test/unit-tests/mobile/application-manager-base.ts
- lib/common/test/unit-tests/stubs.ts
- lib/services/livesync/platform-livesync-service-base.ts
- lib/services/log-source-map-service.ts
- test/services/log-source-map-service.ts
Currently it takes around half a second to parse each console message from the application. For callstacks, which contain a lot of lines, which we try to map to original file, it takes several seconds.
Also, at the moment, when the application reports that some log is from bundle.js/vendor.js, we parse the local files, which may not be the same files uploaded on the device. This may happen in cases where we have applied a hot module, the local bundle.js is changed and its source map is changed, but we have not uploaded it on the device yet.
The reason for the slowness is that we read the whole original file every time when we see lines from the logs that points to it. We also create a new SourceMapConsumer for it. This means, that if the stacktrace contains 10 lines pointing to vendor.js, …
> fix: device logs are parsed slowly

- lib/commands/test.ts
Device discovery was not started on test command when debug-brk option is provided. This led to the error "Unable to find device or emulator for specified options.".
> fix: fix test command with `--debug-brk` option

- lib/controllers/migrate-controller.ts
- lib/controllers/update-controller-base.ts
- lib/controllers/update-controller.ts
- lib/definitions/plugins.d.ts
- lib/services/plugins-service.ts
> fix: dependency won't be migrated if in devDependencies

- lib/controllers/run-controller.ts
- lib/definitions/livesync.d.ts
- lib/services/livesync/ios-livesync-service.ts
- lib/services/livesync/platform-livesync-service-base.ts
Currently when a native file is changed during livesync on android, NativeScript CLI doesn't show the "Successfully synced application" message. This is due to the reason that NativeScript CLI tries to transfer native file on device (for example AndroidManifest.xml). After timeout of 30seconds, the socket on android device throws "Socket connection timeout" error but CLI doesn't show it as the parsing of received errors is not correct. This PR fixes the followings:
* the behavior when native file is changed during liveSync
* the parsing of errors during livesync
* stops livesync process when an error occurs during livesync
> fix: fix native change during livesync

- lib/bootstrap.ts
- lib/controllers/prepare-controller.ts
- lib/controllers/run-controller.ts
- lib/declarations.d.ts
- lib/services/android-plugin-build-service.ts
- lib/services/watch-ignore-list-service.ts
- test/controllers/prepare-controller.ts
- test/services/android-plugin-build-service.ts
> fix: fix multiple installation on android device

- lib/commands/debug.ts
`tns debug android --start` should allow you to debug. However, immediately after opening the debug socket we set the cleanupService to clean the forwarded port once CLI process exits. As we have not set the cleanupService in long living mode, CLI calls injector.dispose and this cleans the debug socket.
To handle this, just set the cleanupService in long living mode.
> fix: debug android --start should allow to debug

- lib/controllers/run-controller.ts
In recent changes we've broken HMR - in order to get its status on device, we need to call refresh application and monitor the logs. However, the logic at the moment is - wait for logs and call refresh application after that. This leads to very slow hmr. Also this way application will not be restarted when the HMR fails as we do not monitor the logs at the point when the hmr cannot be applied.
> fix: hmr is working slowly

- lib/helpers/deploy-command-helper.ts
- lib/services/log-source-map-service.ts
Currently when `tns deploy ios --provision <provision>` is executed, CLI shows a prompt for teamId as the provision option is not respected.
> fix: respect --provision on deploy command

- lib/commands/appstore-upload.ts
Currently `tns publish` command doesn't exit as the webpack process is started in watch mode.
> fix: exit publish command after uploading package to appstore

- lib/controllers/prepare-controller.ts
Currently CLI respects the changes only in the followings package.json files:
* package.json from app folder
* package.json from root folder of the application
The changes from package.json files form NS plugins are not respected as they are not added to the watch's patterns.
> fix: add package.json files from nativescript plugins to watch patterns

- lib/commands/deploy.ts
Currently deploy command doesn't release the console as the watch option has default true value.
> fix: release the console on deploy command

- lib/common/project-helper.ts
Currently when prepare command is executed from plugin's directory, CLI throws an error that it is not able to find `webpack.config.js` file. This is due to the reason that CLI finds nativescript key in package.json and consider that directory as project dir. This PR fixes this behavior as checks if there is `id` inside nativescript key.
> fix: fix prepare from plugin's directory

- lib/controllers/prepare-controller.ts
- lib/controllers/preview-app-controller.ts
- lib/services/livesync/playground/preview-qr-code-service.ts
In some cases (for example `tns preview` and scan QR code simultaneously with several devices) we start multiple watchers per platform. We should always have single watcher per platform (one from webpack and one native in fact).
Handle preview initial sync once per device (in some cases PubNub reports the device multiple times). Also prepare all the files once per platform, not per each device.
> fix: handle preview issues

- lib/controllers/migrate-controller.ts
The migrate command updates `nativescript-vue` to the latest prerelease version - `2.3.0-rc.1`.
> refactor(migrate): bump the version of {N} vue to 2.3.0-rc.1

- lib/controllers/run-controller.ts
- test/controllers/run-controller.ts
Currently when stop method is called with empty array, the livesync process is stopped for all devices but the runOnDeviceStopped event is not emitted. This PR fixes this behavior as ensures the runOnDeviceStopped event will be emitted for all connected devices.
> fix: fix stop run on device when the method is called with empty array

- lib/services/webpack/webpack-compiler-service.ts
- lib/services/webpack/webpack.d.ts
Currently CLI has a logic to restart the application when one or more of the emitted files from webpack compilation is not hot update. When a lazy loaded code is changed in angular application and uglify option is provided, CLI always restarts the application. (as 0.js, 1.js are reported as changed). This happens due to the fact that CLI omits entry point files and runtime files from emitted files to check if all rest files are hot updates. As the lazy loaded chunks (`0.js`, `1.js`) are neither entry point files nor runtime files, they are not omitted and CLI decides that there is file that is not hot update and restarts the application. This PR changes this behavior and respects only chunk files from webpack compilation. Chunk files are all files except hot update files. Chunk files are: …
> fix: don't restart application when lazy loaded code is changed in angular app with uglify option

- lib/controllers/prepare-controller.ts
- lib/controllers/preview-app-controller.ts
- lib/services/ios-log-filter.ts
…
In case there are multiple devices with the same platform, `run command` fails with error `Cannot read property hasNativeChanges of undefined`. The problem is that we return incorrect prepare data.
Also we have a problem in `tns preview` when multiple platforms are used - all files are send multiple times to each device as we have too many started webpack processes (in case you scan fast with devices) and we are also adding handler of the prepare ready event per each device instead per platform. Fix this by handling the event only once per platform
> fix: preview and run do not work correctly 

- lib/controllers/preview-app-controller.ts
The `before-preview-sync` hook has incorrect args - instead of having `hookArgs`, it has an object with data. This causes issues in all plugins which are using it. Get back the correct structure and add `projectData` as it is being used by kinvey-nativescript-sdk's hook.
> fix: before-preview-sync hook has incorrect args

- lib/services/livesync/ios-livesync-service.ts
When you run your app on iOS device for the first time, we execute full sync operation with a zip file. This does not gets in our logic for setting source maps of the transferred files and CLI does not use its logic to parse device logs and show the exact lines from original files.
Fix this by setting the source maps in this case.
Related to https://github.com/NativeScript/nativescript-cli/issues/4604
> fix: iOS device logs are not using source maps initially

- lib/controllers/migrate-controller.ts
In case migrate command fails to migrate the project, currently it shows some generic message without saying what is the actual error. Also the command exits with code 0, which is indication it had succeeded.
Fix this by failing with more descriptive error message and exit code that is not 0.
> fix: migrate command failure should be handled correctly

- lib/common/services/hooks-service.ts
When hook throws an error, there's no easy way to find exactly what is failing as CLI overwrites the error and its callstack. As it is not trivial solution to stop CLI of doing this, when a hook fails, just log the error with its callstack. We know these errors always lead to stopage of CLI process, so we can safely print them.
> fix: show the actual error when hook fails

- lib/controllers/update-controller.ts
- lib/package-manager.ts
The `update` command is updating all dependencies from the project templates but it doesn't call their update scripts.
The `update` command is updating only the core-modules and the runtimes as it was before 6.0.0
> fix: make the update command behave similar to the logic before 6.0.0

- lib/controllers/migrate-controller.ts
In case you've installed `nativescript-unit-test-runner` , but you've not used `tns test init`, `tns migrate` command fails with error:
`Could not migrate the project! The error is: Error: ENOENT: no such file or directory, open '<project dir>/.migration_backup/karma.conf.js'`
Skip the migration of the `karma.conf.js` file in case it is missing. Also, ensure `karma-webpack` is always added by the migration when `nativescript-unit-test-runner` is migrated.
When you execute the following:
```
$ tns create myApp --js
$ cd myApp
$ npm i --save-dev nativescript-unit-test-runner
$ tns migrate
``` 
The command fails with error: `Could not migrate the project! The error is: Error: ENOENT: no such file or directory, open '<project dir>/.migration_backup/karma.conf.js'`
Command successfully …
> fix: migrate fails when karma.config.js is missing

- lib/controllers/build-controller.ts
- lib/controllers/run-controller.ts
- lib/services/platform/prepare-native-platform-service.ts
Currently we're attaching on `PREPARE_READY_EVENT` when run method is called. As Sidekick is long living process and run on device can be called more than once, we'll have more than one handlers for `PREPARE_READY_EVENT`. This means that we'll sync the changed files more than once. This PR fixes this behavior as ensures that we're attаching only once on `PREPARE_READY_EVENT` event and detaching from it on stop method.
Currently CLI provides deviceDescriptors only initially when `syncChangedDataOnDevices` method is called. As Sidekick can add additional deviceDescriptors, CLI doesn't respect them when files are changed and syncs only initially set deviceDescriptors.
Currently CLI throws an error for release cloud build as `this.$projectChangesService.currentChanges ` is undefined and CLI …
> fix: fix issues with Sidekick, cloud builds and multiple projects/devices

- lib/common/mobile/mobile-core/devices-service.ts
- lib/controllers/deploy-controller.ts
- lib/definitions/run.d.ts
- lib/helpers/deploy-command-helper.ts
- lib/helpers/livesync-command-helper.ts
Currently `tns cloud deploy` command starts local build as the provided buildAction through deviceDescriptor is not executed from deployController.
> fix: fix cloud deploy command

- lib/controllers/build-controller.ts
We do not print the build output location, when executing `tns build`.
We print the build output location, when executing `tns build`.
Fixes/Implements/Closes https://github.com/NativeScript/nativescript-cli/issues/4820.
> fix: build output location not printed

- lib/controllers/prepare-controller.ts
- lib/services/webpack/webpack-compiler-service.ts
CLI must install all project dependencies before running any hook as the hooks are commonly created during the installation of packages. In the current codebase we install the depenencies only during `run` operation, however we actually need this to be executed before each project preparation.
To fix the behavior move the installation of dependencies in the prepareController and remove it from webpack-compiler-service. Also remove hook which is no longer supported - prepareJS.
> fix: execute npm install before all hooks

- lib/common/mobile/ios/device/ios-application-manager.ts
Currently `tns debug ios` hangs when executed for device. The problem is that we pass `"waitForDebugger": false` to ios-device-lib binary, which can parse only strings. The value `false` is boolean, not string, so ios-device-lib binary crashes, but CLI does not understand this and hangs.
Fix this by ensuring we pass waitForDebugger as string.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/4828
> fix: `tns debug ios` should work on device

- docs/man_pages/general/migrate.md
- docs/man_pages/general/package-manager-get.md
- docs/man_pages/general/package-manager-set.md
- docs/man_pages/general/update.md
- docs/man_pages/general/usage-reporting.md
- docs/man_pages/index.md
> docs: introduce help for migrate command

- lib/controllers/migrate-controller.ts
> fix: add the link to blog post

- lib/services/project-changes-service.ts
Currently the application is built every time from sidekick when opening the app and starting cloud build. This happens as we decided that there are changes in app_resources as `prepareData.release` is undefined but `prepareInfo.release` is false. This way the check `prepareData.release !== this._prepareInfo.release` passes and we set `this._changesInfo.appResourcesChanged` to `true`.
> fix: don't build every time the application from sidekick when using cloud build

- lib/helpers/livesync-command-helper.ts
The snapshot tool was triggering another Webpack compilation (along with another snapshot generation) because of the dynamic `snapshot-entry`. In this way, the generated snapshot was deleted during the Gradle build causing an invalid build.
The watch is disabled for release build.
> fix: disable the `watch` in release builds as its triggering 2 snapshot generations

- lib/services/platform/add-platform-service.ts
Currently the icons of newly created apps are not displayed when running the application on iOS device. This happens as the icons are not included into `.pbxproject` file. This happens as the `prepareProject` method is not called due to this check https://github.com/NativeScript/nativescript-cli/blob/release/lib/services/platform/prepare-native-platform-service.ts#L35. This check is based on hasChangesRequirePrepare from `projectChangesService` which value is based on `appResourcesChanged` and `signingChanged` - https://github.com/NativeScript/nativescript-cli/blob/release/lib/services/project-changes-service.ts#L27. The values of those properties are not populated correctly initially when the application is without `platforms` directory.
This functionality was broken with this PR …
> fix: fix the missing icons in newly created apps on iOS devices

- lib/commands/build.ts
- lib/commands/debug.ts
- lib/commands/prepare.ts
- lib/commands/preview.ts
- lib/commands/run.ts
- lib/commands/test.ts
- lib/controllers/migrate-controller.ts
- lib/declarations.d.ts
- lib/services/platform/platform-validation-service.ts
> feat: skip migration check based on --force

- lib/controllers/run-controller.ts
- lib/definitions/livesync.d.ts
- lib/services/livesync-process-data-service.ts
Currently when livesync is started on iOS device from sidekick, {N} CLI persist that livesync is started for iOS platform. After that if the livesync process is started on android device, {N} CLI overrides the persisted platforms and stores that the livesync is started for Android platform. However, when the livesync is stopped, {N} CLI stops it only for android platform. This means that the iOS webpack process is alive and continues to report data. This led to the multiple livesync messages when syncing the changes.
> fix: stop all webpack processes from sidekick when stopping the livesync

- lib/controllers/prepare-controller.ts
Currently native watch is not started on cloud run command and from sidekick when cloud build is selected.
> fix: start native watch on cloud run command and from sidekick when cloud build is selected

- lib/controllers/migrate-controller.ts
- lib/definitions/migrate.d.ts
The Angular dependencies are not updated during `tns migrate` causing invalid dependencies state when migrating Angular 5 app. The invalid state is caused by the `nativescript-dev-webpack` plugin which updates the `@angular/compiler-cli` and `@ngtools/webpack` to `8.0.0` which are not compatible with Angular < 7.
`tns migrate` is not updating the Angular deps in order to ensure compatibiltiy between`@angular/compiler-cli`, `@ngtools/webpack` and the rest of the Angular dependencies.
> fix: update Angular deps during app migration

- lib/services/webpack/webpack-compiler-service.ts
https://node.green/#ES2018-features--RegExp-Lookbehind-Assertions
> fix: support node <= 8.9.4 (lookbehind is supported only with the `harmony` flag)

- docs/man_pages/project/configuration/platform-add.md
> docs: remove --sdk flag from documentation

- lib/controllers/migrate-controller.ts
Update nativescirpt-dev-webpack and ios-runtime to their latest versions. We'll require at least these versions when running the application.
> chore: update required deps for 6.0

- lib/controllers/run-controller.ts
> fix: fix the behavior when ddi is not installed on iOS device

- docs/man_pages/project/configuration/platform-add.md
The option has been deleted in CLI 6.0, but it is still available in the help.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/4873
> docs: remove --platform-template from CLI's help

- lib/options.ts
- test/options.ts
Currently `tns run android --release` throws an error that `--hmr` and `--release` cannot be used simultaneously. After parsing `this.yargsArgv = yargs(process.argv.slice(2))` command line options, only `--release` option is true as it is expected to be. For some reason after calling `this.argv = this.yargsArgv.options(<any>opts).argv`, `this.yargsArgv` is modified and `this.yargsArgv.hmr` is true which is not the expected behavior. It seems like a strange behavior of yargs. In order to fix it, we parse the command line only once and persist the `argv` object of initial parsed command line.
> fix: parse options correctly

- lib/commands/migrate.ts
- lib/commands/update.ts
> fix: migrate and update exit with code 0 when everything is up-to-date

- lib/controllers/prepare-controller.ts
- lib/controllers/preview-app-controller.ts
- lib/controllers/run-controller.ts
- lib/definitions/preview-app-livesync.d.ts
- lib/services/webpack/webpack-compiler-service.ts
- npm-shrinkwrap.json
- package.json
- test/controllers/run-controller.ts
The livesync process is stopped when a native change is made in app built in cloud on windows OS. This happens as CLI builds the app and after that tries to restart it. As the `platformLiveSyncService.restartApplication` is without try/catch, the CLI is not able to start the application due to missing developer disk image mounted on device. After that an error is thrown and the livesync process is stopped. This PR replaces `platformLiveSyncService.restartApplication` with `this.refreshApplication`. The `this.refreshApplication` method has try/catch and shows a warning `Unable to start application...`  when an error is thrown during restart process. On the other side, this method has a check if a naive change occurs, so no additional checks will be executed from the method in order to …
> fix: multiple errors in Sidekick

- docs/man_pages/project/creation/create.md
missing --template arg on `create` cmd examples.
This PR targets the `release` branch per https://github.com/NativeScript/nativescript-cli/pull/4900
> fix: missing --template arg

- docs/man_pages/publishing/apple-login.md
- docs/man_pages/publishing/appstore-upload.md
- docs/man_pages/publishing/publish-ios.md
- lib/bootstrap.ts
- lib/commands/apple-login.ts
- lib/commands/appstore-list.ts
- lib/commands/appstore-upload.ts
- lib/common/constants.ts
- lib/common/http-client.ts
- lib/declarations.d.ts
- lib/options.ts
- lib/services/apple-portal/apple-portal-application-service.ts
- lib/services/apple-portal/apple-portal-cookie-service.ts
- lib/services/apple-portal/apple-portal-session-service.ts
- lib/services/apple-portal/definitions.d.ts
- lib/services/itmstransporter-service.ts
- test/tns-appstore-upload.ts
Currently the users are not able to publish applications to AppStore if their accounts are with [two-factor authentication enabled](https://support.apple.com/en-us/HT204915). The current PR introduces support for publishing iOS apps for accounts with two-factor authentication enabled and shouldn't affect how publish command works for accounts without two-factor authentication. To support it, we need 2 additional options:
* appleApplicationSpecificPassword
* appleSessionBase64
The `--appleApplicationSpecificPassword` option is a password for user's Apple ID that let the user sign in to his account and securely access the information he stores from iTunes Transporter application. This option is mandatory for all accounts with two-factor authentication enabled. To generate an application …
> fix: ability to publish iOS applications for users with two-factor authentication enabled

- lib/commands/appstore-upload.ts
- lib/services/apple-portal/apple-portal-session-service.ts
- lib/services/apple-portal/definitions.d.ts
Currently `tns appstore list` command throws an error when account is with 2fa and `--appleApplicationSpecificPassword` option is not provided. We shouldn't throw an error in this situation as we don't need `--appleApplicationSpecificPassword` on `tns appstore list` command as we don't use third party application when executing this command. This option is mandatory only for `tns appstore upload` command where we use iTunesTransporter app when uploading the application.
Rel to: https://github.com/NativeScript/nativescript-cli/issues/4586
> fix: fix appstore list command for accounts with 2fa

- lib/commands/test.ts
- lib/controllers/run-controller.ts
- npm-shrinkwrap.json
- package.json
In short, the LiveSync crashes when the App is not started or installed on the device.
* Re-implements: https://github.com/NativeScript/nativescript-cli/pull/4020
* Imporves `tns test android` LiveSync performance (avoid waiting 30 seconds)
Related to: https://github.com/NativeScript/nativescript-cli/issues/4914
https://github.com/NativeScript/nativescript-cli/issues/4916
> fix: avoid getting crashed LiveSync when the fast sync fails

- lib/definitions/platform.d.ts
- lib/services/android-project-service.ts
- lib/services/ios-project-service.ts
- test/platform-commands.ts
- test/stubs.ts
> feat: Support .xcframework bundles

- lib/android-tools-info.ts
- lib/declarations.d.ts
- lib/definitions/android-plugin-migrator.d.ts
- lib/services/android-plugin-build-service.ts
- lib/services/android-project-service.ts
- lib/services/android/gradle-build-args-service.ts
- npm-shrinkwrap.json
- package.json
Implements issue https://github.com/NativeScript/nativescript-cli/issues/4926.
> feat: add support for Android SDK 29 for compilation

- lib/services/webpack/webpack-compiler-service.ts
Related to: https://github.com/NativeScript/nativescript-cli/issues/4936
> fix: include all chunkFiles in fallbackFiles in order to avoid wrong lazy Angular chunks

- lib/services/ios-project-service.ts
Pass full path instead of only file name to `getFsStats`
related to #4907
> fix(ios): isDynamicFramework check for `.xcframework`s

- npm-shrinkwrap.json
- package.json
Use ios-device-lib@0.6.0 version which can work with iOS 13 devices.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/4741
> feat: support Xcode 11 and iOS 13

- lib/services/ios-project-service.ts
There's a missing await in the check if an iOS Framework is dynamic. Linter rule (no-floating-promises) does not catch it, as it is not a pure call, i.e. linter will fail in case the code is:
```
this.isDynamicFramework(frameworkPath);
```
But it will not fail in case the method is called inside if statement (as it is in our code) or when you assing the value to a variable and do not await it anywhere:
```
const isDynamic = this.isDynamicFramework(frameworkPath);
```
Related to: https://github.com/NativeScript/nativescript-cli/issues/4906
> fix: add missing await for isDynamicFramework check

- lib/common/errors.ts
- lib/common/test/unit-tests/errors.ts
- lib/common/test/unit-tests/stubs.ts
- test/stubs.ts
`logger.out` has been removed before 6.0 release, but it has still been used in CLI's code. Remove its usages and add tests for `errors.beginCommand` (the one where the method has been used until now.
`ANDROID_HOME=/invalid tns doctor` - fails and in interactive terminal prompts you to select option. If you choose Manually configure, CLI will print error `this.$injector.resolve(...).out is not a function` (NOTE: In non-interactive terminal the same happens).
`ANDROID_HOME=/invalid tns doctor` - fails and in interactive terminal prompts you to select option. If you choose Manually configure, CLI will prints where are the system requirements.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/4958
> fix: remove usages of logger.out in CLI code

- npm-shrinkwrap.json
- package.json
Currently, in case you pass `--provision` to `tns prepare/build/run/debug/test` command and you have macOS Catalina installed, CLI fails with error: `Expected "SHA-1 hash: " or end of input but "S" found`.
The problem is that the `security` command used by `ios-mobileprovision-finder` package has a different output in macOS Catalina. To fix this, update the ios-mobileprovision-finder version.
Running `tns prepare ios --provision` fails on macOS Catalina.
CLI can parse certificates and provsions on macOS Catalina, i.e. `tns prepare ios --provision` shows correct output.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/4934
> fix: certificates and provision parsing should work on macOS Catalina

- lib/constants.ts
- lib/controllers/update-controller.ts
- lib/project-data.ts
- test/controllers/update-controller.ts
- test/project-data.ts
Add tracking in CLI analytics for React and Svelte project types. As we do not have templates for those two project types, when CLI detects a project from this type and the `tns update` command is executed, get the dependencies for update from the default hellow world JS template.
CLI does not track React and Svelte projects
CLI tracks projects as React when `react-nativescript` is added as dependency.
CLI tracks projects as Svelte when `svelte-native` is added as dependency.
Implements issue: https://github.com/NativeScript/nativescript-cli/issues/4947
> feat: add tracking for React and Svelte projecs

- lib/commands/appstore-upload.ts
- lib/common/services/xcode-select-service.ts
- lib/common/test/unit-tests/xcode-select-service.ts
- lib/declarations.d.ts
- lib/services/itmstransporter-service.ts
- test/tns-appstore-upload.ts
As `Application Loader` is no longer included in Xcode 11, CLI is not able to find the path to itmsTransporter and throws an error. However, `itmsTransporter` app is already part of `ContentDeliveryServices.framework` which is part of `SharedFrameworks` which are included in `Xcode 11` itself. So this PR returns the correct path to itmsTransporter app based on xcode's version.
Also this PR checks first if the path to itmsTransporter exists and after that builds the application.
Currently `getXcodeVersion` always returns `{ major: null, minor: null, patch: null }`. This method uses internally `sysInfo.getXcodeVersion()`. On the other side, `sysInfo.getXcodeVersion()` returns the xocde's version in format `major.minor.patch` - for example `10.3.4`. After getting the result of …
> feat(publish): ability to publish applications using Xcode 11

- lib/common/commands/preuninstall.ts
- lib/common/test/unit-tests/preuninstall.ts
- lib/constants.ts
In case CLI is uninstalled, open a feedback form, so the user might explain why they've uninstalled the product.
Add analytics tracking for the uninstall call. Remove the `disableAnalytics` property of the `dev-preuninstall` command - this way we'll receive information for the number of times the command has been executed (usually it is called from CLI's preuninstall script).
Also add custom data in the analytics, so we'll be able to generate report to see how many times users uninstall the CLI (actually executing `npm uninstall...`) and if this happens from interactive terminal.
When you execute `npm uninstall -g nativescript`, CLI removes several directories and does not collect any information about the action and why it has been executed by the user.
CLI collects information in …
> feat: open feedback form when CLI is uninstalled

- lib/controllers/update-controller.ts
As both React and Svelte projects have custom webpack.config.js files, when `tns update` replaces the `webpack.config.js` file, the project becomes unusable. We do not have default webpack.config.js files for these templates, so for the momennt skip the replacement of the file during `tns update` and print informational warning.
Executing `tns upate` in React-nativescript or Svelte project replaces the webpack.config.js with default one for our JavaScript template. This makes the projects unusable and broken.
CLI prints a warning during `tns update` that it will not update the `webpack.config.js` file as the project type is `React` or `Svelte`
Fixes comment https://github.com/NativeScript/nativescript-cli/issues/4947#issuecomment-524914184
> fix: tns update will not modify webpack.config.js of React/Svelte projects

- preuninstall.js
- test/preuninstall.ts
Currently the when the preuninstall step executes CLI's command, it exec's the process without inheriting the stdout. This way CLI always thinks the terminal is not interactive and never opens the feedback form.
Replace the exec with spawn and set "inherit" for stdout. This way CLI will determine if the terminal is in interactive mode correctly.
CLI never opens the required uninstall feedback form.
When `npm uninstall -g nativescript` is executed, CLI will open the feedback form.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/4974
> fix: open feedback form on preuninstall

- lib/constants.ts
- lib/services/subscription-service.ts
- test/services/subscription-service.ts
On postinstall CLI prompts you to subscribe to NativeScript newsletter. If you give your email, it is sent to eloqua form dev_uins_cli. The message tells we will send information for Progress products.
On postinstall CLI prompts you to subscribe to NativeScript newsletter. If you give your email, it is sent to eloqua form NativeScript_IncludeinEmail. The message tells we will send information for NativeScript.
Implements issue https://github.com/NativeScript/nativescript-cli/issues/4980
> docs: update privacy policy message based on the latest legal updates

- lib/common/helpers.ts
- lib/declarations.d.ts
- lib/services/cocoapods-service.ts
- lib/services/xcconfig-service.ts
- lib/services/xcproj-service.ts
- test/cocoapods-service.ts
Currently CLI executes `which pod` and `which xcodeproj` every time when `pod install` is executed e.g on every native change. Also, CLI checks if env is correctly setup on every "prepare" related command - e.g prepare, build, run, debug and test. However, [which xcodeproj](https://github.com/NativeScript/nativescript-doctor/blob/065325fc362262b197c065e621e66866f2d57b45/lib/sys-info.ts#L131)
and [pod --version](https://github.com/NativeScript/nativescript-doctor/blob/065325fc362262b197c065e621e66866f2d57b45/lib/sys-info.ts#L162) are included in the checks for correctly setup env. So these checks shouldn't be executed before each `pod install` as it aditionally slow down the prepare process.
Currently CLI checks if `xcproj` executable is available on user's machine in case when CocoaPods …
> fix: speed up the prepare process

- lib/common/commands/preuninstall.ts
- lib/common/declarations.d.ts
- lib/common/test/unit-tests/preuninstall.ts
- lib/detached-processes/detached-process-enums.d.ts
- lib/services/analytics/analytics-broker-process.ts
- lib/services/analytics/analytics-service.ts
- preuninstall.js
- test/preuninstall.ts
Introudce finishTracking method in `analyticsService` which will ensure all pending information is send to Google Analytics. This is required for some rare cases in which we want to be sure all the information has been sent.
CLI's analytics process is a detached one, so during `preuninstall` command, CLI just sends information to the detached process what should be tracked and finishes CLI's execution. After that `npm` starts removing the CLI package and its `node_modules`.
At this point the analytics process may still work and trying to send data, but as it relies on components in node_modules, which npm currently deletes, it fails to send information to Google Analytics.
To ensure correct data is send to Analytics, ensure tracking is finished before ending the preuninstall command.
In …
> fix: ensure data is sent to analytics on preuninstall 

- lib/commands/post-install.ts
At postinstall CLI prints long information to the users, who commonly do not read it. Print just a few lines with the most critical information.
> fix: update messages on postinstall

- lib/common/commands/device/list-devices.ts
- lib/common/constants.ts
- lib/common/definitions/mobile.d.ts
- lib/common/mobile/android/android-device.ts
- lib/common/mobile/android/android-virtual-device-service.ts
- lib/common/mobile/android/genymotion/genymotion-service.ts
- lib/common/mobile/device-emitter.ts
- lib/common/mobile/ios/device/ios-device-operations.ts
- lib/common/mobile/ios/device/ios-device.ts
- lib/common/mobile/ios/ios-device-base.ts
- lib/common/mobile/ios/simulator/ios-emulator-services.ts
- lib/common/mobile/ios/simulator/ios-simulator-device.ts
- lib/common/mobile/mobile-core/device-discovery.ts
- lib/common/mobile/mobile-core/devices-service.ts
- lib/common/mobile/mobile-core/ios-device-discovery.ts
- lib/common/test/unit-tests/mobile/android-emulator-service.ts
- lib/common/test/unit-tests/mobile/android-virtual-device-service.ts
- lib/common/test/unit-tests/mobile/devices-service.ts
- lib/common/test/unit-tests/mobile/genymotion/genymotion-service.ts
- lib/common/test/unit-tests/mobile/ios-simulator-discovery.ts
- lib/constants.ts
- lib/declarations.d.ts
- lib/device-sockets/ios/notification.ts
- lib/device-sockets/ios/socket-request-executor.ts
- lib/services/hmr-status-service.ts
- lib/services/ios-device-debug-service.ts
- lib/services/livesync/ios-device-livesync-service.ts
- npm-shrinkwrap.json
- package.json
- test/services/livesync/android-device-livesync-service-base.ts
Related to: https://github.com/NativeScript/nativescript-cli/issues/4966
> feat: support LiveSync to Wi-Fi devices

- lib/services/user-settings-service.ts
- test/services/user-settings-service.ts
Due to recent changes, trying to save a setting in the user-settings.json or to remove it from there is not working. This breaks all new users and the execution of commands like `tns usage-reporting enable/disable`, `tns error-reporting enable/disable`.
The problem is an infinite recursion in the userSettingsService, which should just call jsonFileSettingsService, but instead it calls itself.
Fix the recursion and add unit tests for the userSettingsService to ensure it acts as a proxy to jsonFileSettingsService.
`tns error-reporting enable && tns error-reporting disable` are not working. New users are unable to use CLI.
`tns <any command> --profileDir <some dir>` is not working (this is the same what happens for new users.
`tns error-reporting enable && tns error-reporting disable` are …
> fix: save and remove of user-settings are not working

- lib/controllers/company-insights-controller.ts
- test/config/config-json.ts
- test/controllers/company-insights-controller.ts
As we have implemented the caching in the server, there's no need to have local cache for getting company data.
> fix: remove local caching of getting company data

- lib/controllers/run-controller.ts
- lib/definitions/livesync.d.ts
- lib/services/livesync/ios-device-livesync-service.ts
Currently there is an issue when livesyncing the application when it is stopped on breakpoint. The problem is that the application is always restarted - most probably due to issue with "RefreshRequest" notification. However, this notification was added as we needed to support syncing on wifi devices. As debug command doesn't work with wifi devices, we'll force refresh with socket on debug command.
Rel to: https://github.com/NativeScript/nativescript-cli/issues/4966
> fix: force refresh with socket when debugging the application

- CHANGELOG.md
> chore: add changelog for 6.1.0. release

- lib/services/ip-service.ts
- test/services/ip-service.ts
> fix: add cache decorator when getting ip address

- lib/services/webpack/webpack-compiler-service.ts
When runnign webpack, we want to pass `--preserve-symlinks` option to the 	Node.js. However, currently we pass it to webpack process itself. Fix the order of args.
CLI passes `--preserve-symlinks` to the webpack itself, not to the Node.js.
CLI passes `--preserve-symlinks` to Node.js process which will run the webpack.
> fix: pass preserve-symlinks correctly

- lib/bootstrap.ts
- lib/definitions/project.d.ts
- lib/services/ios-extensions-service.ts
- lib/services/ios-native-target-service.ts
- lib/services/ios-project-service.ts
- lib/services/ios-watch-app-service.ts
- test/ios-project-service.ts
> fix: bundle indentifier warning in Xcode11

- lib/constants.ts
- lib/controllers/prepare-controller.ts
- lib/services/platform/add-platform-service.ts
- test/controllers/add-platform-controller.ts
- test/controllers/prepare-controller.ts
- test/services/platform/add-platform-service.ts
Fixes/Implements/Closes https://github.com/NativeScript/nativescript-cli/issues/5018
> feat: implement runtime version tracking

- README.md
- docs/man_pages/general/proxy-set.md
We are not using Docker and not mentioning its proxy settings.
We will start using Docker for snapshotting applications when the local tools are not available and we mention its proxy settings in the docs.
Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/1038
> docs: update proxy docs

- lib/controllers/deploy-controller.ts
- lib/services/webpack/webpack-compiler-service.ts
1) The `skipNativePrepare` flag is not passed during deploy in release.
2) The snapshot tools are executed and we will require their local setup even during cloud builds.
The snapshot tools are skipped during cloud build and the `skipNativePrepare` flag is properly passed during deploy in release.
> fix: skip snapshot tools based on skipNativePrepare

- lib/services/ios/export-options-plist-service.ts
- test/services/ios/export-options-plist-service.ts
Fixes #5034
I also added a test to help prevent this from happening again.
> fix(cli): add iCloudContainerEnvironment export option

- docs/man_pages/project/creation/create.md
- lib/commands/create-project.ts
- test/project-commands.ts
when vue flavor is selected, two options are presented - Blank and SideDrawer
when vue flavor is selected, three options are presented - Blank, SideDrawer and Tabs
Fixes/Implements/Closes #5032.
> feat: add vue tabs navigation template to create project command

- lib/common/test/unit-tests/logger.ts
Unit tests cannot be executed with node v12.11.0 due to the changes in `util.format`. If you have the following code:
```
const obj = { obj: 1 }
const formattedValue = util.format("%s", obj);
console.log(formattedValue);
```
```
[object Object]
```
```
{ obj: 1 }
```
However, the string interpolation is not changed i.e the following code:
```
console.log(`${obj}`)
```
will result in `[object Object]` no matter if it is executed with `node v12.11.0` or earlier.
> fix: fix unit tests with node v12.11.0

- lib/services/webpack/webpack-compiler-service.ts
- lib/services/webpack/webpack.d.ts
- test/services/webpack/webpack-compiler-service.ts
More info can be found here https://github.com/NativeScript/nativescript-dev-webpack/pull/1051.
Rel to: https://github.com/NativeScript/nativescript-cli/issues/3785
> fix: handle correctly the compilation errors from webpack

- lib/controllers/migrate-controller.ts
- lib/controllers/update-controller-base.ts
- lib/controllers/update-controller.ts
- lib/declarations.d.ts
- lib/package-installation-manager.ts
- lib/services/webpack/webpack-compiler-service.ts
- test/services/webpack/webpack-compiler-service.ts
- test/stubs.ts
Providing the `--env.snapshot` flag on Windows is throwing an exception.
The `--env.snapshot` flag is valid on Windows and it is generating snapshots in a docker container.
Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/1054 and https://github.com/NativeScript/nativescript-dev-webpack/pull/1055
> feat: support snapshots on Windows

- lib/bootstrap.ts
- lib/commands/build.ts
- lib/commands/debug.ts
- lib/commands/deploy.ts
- lib/commands/prepare.ts
- lib/commands/preview.ts
- lib/commands/run.ts
- lib/commands/test.ts
- lib/commands/update.ts
- lib/controllers/prepare-controller.ts
- lib/controllers/preview-app-controller.ts
- lib/declarations.d.ts
- lib/definitions/marking-mode-service.d.ts
- lib/options.ts
- lib/services/marking-mode-service.ts
- test/package-installation-manager.ts
- test/platform-commands.ts
- test/services/playground/preview-app-livesync-service.ts
- test/services/project-data-service.ts
- test/stubs.ts
- test/update.ts
> feat: deprecate `markingMode:full`

- lib/services/webpack/webpack-compiler-service.ts
#4684  PR Checklist
The `next` and `rc` versions of the Webpack plugin were not allowed.
The `next` and `rc` versions of the Webpack plugin are allowed.
> fix: allow pre-release versions of Webpack plugin 1.3.0

- lib/declarations.d.ts
- lib/helpers/platform-command-helper.ts
- lib/services/android-project-service.ts
- lib/services/ios-project-service.ts
- lib/services/webpack/webpack.d.ts
- test/helpers/platform-command-helper.ts
- test/stubs.ts
(Remove an outdated check from NativeScript 1.3)
Related to: https://github.com/NativeScript/nativescript-cli/issues/4681
> fix: do not reject platform update on different pbxproj files as they are always different

- lib/definitions/nativescript-dev-xcode.d.ts
- lib/definitions/xcode.d.ts
- lib/node/xcode.ts
Currently `nativescript-cloud` cannot be built with latest master branch of CLI due to the following errors:
```
node_modules/nativescript/lib/definitions/project.d.ts(476,96): error TS2503: Cannot find namespace 'IXcode'.
node_modules/nativescript/lib/definitions/project.d.ts(476,165): error TS2503: Cannot find namespace 'IXcode'.
node_modules/nativescript/lib/definitions/project.d.ts(479,128): error TS2503: Cannot find namespace 'IXcode'.
node_modules/nativescript/lib/definitions/project.d.ts(480,99): error TS2503: Cannot find namespace 'IXcode'.
```
The issue happens as `IXcode` interface is already used from project.d.ts file. As `nativescript-cloud` lib generates `references.d.ts` file with references to all `.d.ts` files from NativeScript CLI, we need a separate `.d.ts`  file for …
> fix: fix definition files so nativescript-cloud can be successfully built

- lib/constants.ts
- lib/definitions/gradle.d.ts
- lib/services/android-project-service.ts
- lib/services/android/gradle-build-args-service.ts
- lib/services/android/gradle-build-service.ts
- test/cocoapods-service.ts
- test/services/android-project-service.ts
- test/services/android/gradle-build-args-service.ts
- test/services/ios/export-options-plist-service.ts
- test/services/playground/preview-app-livesync-service.ts
- test/stubs.ts
Currently we do not tack data about Kotlin usage.
We track data about Kotlin usage.
The PR also includes some fixes for our unit tests on Windows.
Fixes/Implements/Closes https://github.com/NativeScript/nativescript-cli/issues/5060
> feat: introduce kotlin usage tracking

- lib/controllers/prepare-controller.ts
- lib/definitions/platform.d.ts
- lib/definitions/plugins.d.ts
- lib/definitions/project-changes.d.ts
- lib/definitions/project.d.ts
- lib/services/cocoapods-service.ts
- lib/services/ios-project-service.ts
- lib/services/platform/prepare-native-platform-service.ts
- lib/services/plugins-service.ts
- lib/services/project-changes-service.ts
- lib/tools/node-modules/node-modules-builder.ts
- test/cocoapods-service.ts
- test/ios-project-service.ts
- test/plugins-service.ts
Fixes/Implements/Closes https://github.com/NativeScript/nativescript-cli/issues/5061
> feat: initial implementation of pods override

- lib/services/test-execution-service.ts
- resources/test/karma.conf.js
Two different webpack compilations are started on `tns test` command - the one from `karma-webpack` and the second one from `nativescript-dev-webpack`. As the karma's webpack doesn't provide appPath to the env and there is a hardcoded `appPath` inside `webpack.config.js` (to `src` for example), it works only with that hardcoded path.
Rel to: https://github.com/NativeScript/nativescript-cli/issues/5070
> fix: pass appPath to the env from karma.conf.js

- lib/controllers/migrate-controller.ts
> feat: cache shouldMigrate result

- lib/services/cocoapods-service.ts
Currently if `overridePods` is enabled, but there is no `App_Resources/iOS/Podfile` an error is thrown.
The project to be prepared successfully.
> fix: error with missing AppResources Podfile and override pods

- test/cocoapods-service.ts
> test: add tests for cocoapods override feature

- lib/services/ios/xcodebuild-args-service.ts
- test/services/ios/xcodebuild-args-service.ts
The `-allowProvisioningUpdates` option is passed to `xcodebuild` no matter if building for device or for simulator.
According to the documentation of `xcodebuild`:
```
Allow xcodebuild to communicate with the Apple Developer website. For automatically signed targets, xcodebuild will create and update profiles, app IDs, and certificates. For manually signed targets, xcodebuild will download missing or updated provisioning profiles. Requires a developer account to have been added in Xcode's Accounts preference pane.
```
It seems it shouldn't be passed when building for simulator.
> fix: pass allowProvisioningUpdates to xcodebuild only when building for device

- lib/commands/build.ts
- lib/commands/debug.ts
- lib/commands/deploy.ts
- lib/commands/run.ts
- lib/commands/test.ts
- lib/common/helpers.ts
- lib/constants.ts
- lib/services/android/android-bundle-tool-service.ts
The errors for missing Android signing options with aab are misleading.
The Android signing is validated in the commands and the errors are more clear.
Related to: #5049
> fix: add more signing validations

- lib/commands/build.ts
`tns build android --aab` requires signing options.
`tns build android --aab` does not require signing options as we won't produce apks and deploy on device.
> fix: do not require signing when the aab will not be deployed by the CLI

- lib/services/webpack/webpack-compiler-service.ts
- test/services/webpack/webpack-compiler-service.ts
The NativeScript CLI persists the hash of the next hmr compilation locally and based on that decides if the reported hash is valid or not. However, in case when `tns run` command is executed, the application is randomly restarted on some devices. This happens as in this situation we have 2 webpack processes but the hmr hash is not persisted per platform.
Rel to: https://github.com/NativeScript/nativescript-cli/issues/5080
> fix: persist the next hmr hash per platform

- lib/services/assets-generation/assets-generation-service.ts
- lib/services/project-data-service.ts
Fixes/Implements/Closes https://github.com/NativeScript/nativescript-cli/issues/5063
> fix: resize image throws and error if no definition matched

- docs/man_pages/project/testing/build-android.md
- docs/man_pages/project/testing/build-ios.md
- docs/man_pages/project/testing/build.md
- docs/man_pages/project/testing/debug-android.md
- docs/man_pages/project/testing/deploy.md
- docs/man_pages/project/testing/run-android.md
- docs/man_pages/project/testing/run-ios.md
- docs/man_pages/project/testing/run.md
- docs/man_pages/project/testing/test-android.md
Related to: https://github.com/NativeScript/nativescript-cli/issues/5049
> docs: document --aab and --env.compileSnapshot in the commands help

- lib/definitions/preview-app-livesync.d.ts
- lib/services/livesync/playground/devices/preview-devices-service.ts
- lib/services/livesync/playground/preview-app-plugins-service.ts
- test/services/playground/preview-app-plugins-service.ts
The CLI requires hardcoded plugin versions from the Preview app.
The CLI supports any version formats from the Preview app (hardcoded, tag and range).
> feat: allow tag and range versions in the preview app plugin versions validation

- lib/services/webpack/webpack-compiler-service.ts
Currently CLI considers the hash that is the same as the previous as invalid and this way the application is restarted on device. As that hash is already handled, we should consider it as a valid hash.
Steps to reproduce :
```
`tns create ts_proj`  - choose ts tabs project
npm i tns-core-modules@rc --save --save-exact
npm i nativescript-dev-webpack@rc --save-dev --save-exact
node_modules/.bin/update-ns-webpack --deps –configs
tns run android
Change something in app.android.scss - the change is applied, no restart
Change something in app.ios.scss - application restarts
```
Rel to: https://github.com/NativeScript/nativescript-cli/issues/5105
> fix: handle correctly the situation when the compilation hash is the same as the previous one

- CHANGELOG.md
> chore: create changelog for 6.2.0 release

- lib/services/android-project-service.ts
- test/services/android-project-service.ts
In Android's resources you can have different `values-v<sdk version>` directories which are used at runtime to differentiate resources for API levels.
In CLI we had a logic to include in native build only the `values-v<sdk version>` directories which are equal or lower to the SDK used for building the application.
This means that if you are using compileSdk 28, but you have `values-v29` directory in your resources it shouldn't be included in the native build.
Due to many changes in the structure of App_Resources/Android and the gradle template in NativeScript 4.0, this logic has been broken.
Fix it and execute it on every prepare of App_Resources.
CLI prepares values-v<sdk> directories based on the current compileSdk
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/5120
> fix: values-v<sdk> directories are not prepared correctly

- lib/services/webpack/webpack-compiler-service.ts
Livesync doesn't work when `tns run ios --no-hmr` command is executed, same changes are synced and the application is reverted to its initial state. On first webpack compilation CLI stores the initial hash of the compilation but the stored hash is updated only in `hmr` mode. On the other side, CLI has a logic to return when the stored hash is the same as the current hash. So, when the changes are reverted to the initial state of the application, the current hash is the same as the first reported hash. This way, CLI doesn't execute any livesync logic after the reported changes from webpack process.
Rel to: https://github.com/NativeScript/nativescript-cli/issues/5132
> fix: fix livesync when `--no-hmr` option is provided and changes are reverted to the initial state of application

- lib/services/project-data-service.ts
- npm-shrinkwrap.json
- package.json
- resources/assets/image-definitions.json
- test/services/project-data-service.ts
In case we do not have some of iOS Resource images in our image-definitions.json file, we do not generate images for them. This was not the case prior 6.2.0 release, so fix the behavior by getting back the old logic - get the image size from the Contents.json and generate image for it.
Also add the images from the templates that are currently missing from our `image-definitions.json` file.
CLI does not generate image resources for iOS which are described in Contents.json, but are not described in CLI's image-definitions.json file.
CLI does not generate image resources for iOS which are described in Contents.json, but are not described in CLI's image-definitions.json file.
Fixes issue: https://github.com/NativeScript/nativescript-cli/issues/5126
> fix: generate iOS images when we have their sizes

- .npmignore
- generate_changelog.js
Add script to generate the changelog automatically. The script should be called from the root of the repository in the following way:
```
node generate_changelog.js <milestone> <GitHub Access Token which has read access to repository>
```
For example:
```
node generate_changelog.js 6.2.2 2d2156c261bb1494f7a6e22f11fa446c7ca0e6b7
```
The script uses GitHub's GraphQL API v4. More information about it can be found [here](https://developer.github.com/v4/).
The script is designed to work with current NativeScript CLI workflow:
- it generates changelog based on CLI's Changelog.md format
- it generates changelog only for issues, PR's added in the milestone are not included in the changelog
- issues with no-changelog label are not added to the milestone. A warning is shown for them.
- issues with …
> chore: add script for automatic changelog generation

- lib/controllers/preview-app-controller.ts
- lib/controllers/run-controller.ts
- lib/definitions/preview-app-livesync.d.ts
- lib/services/livesync/playground/preview-sdk-service.ts
- lib/services/log-parser-service.ts
- test/services/ios-debugger-port-service.ts
- test/services/log-parser-service.ts
1) We are not able to recover after an HMR crash on iOS. (it's working on Android just because the Preview app is requesting new files after crashes).
2) There's no indication when we've lost connection with the devices. The CLI is just not printing anything.
3) We are not printing any hints for starting the Preview app when there is an HMR status timeout.
4) The device-specific logs are misleading as they are not printed with a device name prefix.
5) Run with HMR is not assuming the HMR status timeout as HMR error and not retrying with full sync.
7) HMR updates are not chained causing wrong statuses and crashes from parallel updates.
8) HMR updates are not batched on fast changes leading to slow app updates.
1) We are executing HMR or full sync based on the previous HMR sync status.
2) …
> feat: reduce HMR crashes in Preview and recover properly after them

- docs/man_pages/project/testing/test-init.md
- lib/common/services/micro-templating-service.ts
- lib/common/test/unit-tests/services/help-service.ts
- lib/definitions/project.d.ts
- lib/services/test-initialization-service.ts
`tns test init --help` doesn't show the available unit testing frameworks as the constant `constants.TESTING_FRAMEWORKS` that is used from the `test-init.md` file was deleted. On the other side, `test-dependencies.json` file was introduced in order to list all supported frameworks. So, this PR gets the supported unit testing framework names from `test-dependencies.json` file and prints them from `test-init.md` file.
Rel to: https://github.com/NativeScript/nativescript-cli/issues/5113
> `tns test init --help` doesn't show the available unit testing frameworks

- lib/services/livesync/playground/preview-app-plugins-service.ts
- test/services/playground/preview-app-plugins-service.ts
In case when there are one or more plugin with native dependencies on preview command, we want to show a message that the users should use `tns run` command instead.
Rel to: https://github.com/NativeScript/nativescript-cli/issues/5155
> feat: improve the transition from preview to run command

- lib/controllers/preview-app-controller.ts
- lib/definitions/plugins.d.ts
- lib/services/plugins-service.ts
- test/ios-project-service.ts
- test/plugins-service.ts
- test/services/playground/preview-app-livesync-service.ts
In case there's a case-sensitive file system, the preparation of Podfiles does not work as we check for `iOS` dir in the plugins, but the actual dir is `ios`.
Fix the case, add unit tests and remove some unneeded unit test.
Also fix some unit tests.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/5159
> fix: prepare of pods should work on case-sensitive systems

- lib/common/dispatchers.ts
- lib/nativescript-cli.ts
- lib/services/project-changes-service.ts
- lib/services/webpack/webpack-compiler-service.ts
Improve log trace messages with:
1. Remove some `containsNewerFiles` logs which do not give any useful information
2. Add trace for messages send by webpack process to CLI and the data prepared by CLI from those messages.
3. Printing the sysinfo information is now formatted correctly.
4. Print the current CLI version as it is not included in the sysinfo.
5. Override of SIGINT handler seems like an error in the trace logs - fix it by removing the "Error:" part from it.
> chore: improve log trace messages

- lib/common/commands/doctor.ts
- lib/common/declarations.d.ts
- lib/definitions/platform.d.ts
- lib/services/doctor-service.ts
- lib/services/platform-environment-requirements.ts
- test/services/doctor-service.ts
Currently each project related CLI command checks the status of the machine. This takes between 4 and 9 seconds on different machines. Cache the result per project and based on the environment variables used in the checks.
In case `tns doctor` is called, force the check of the environment requirements. In case an issue is detected, remove the file with cached information for all projects - there seems to be issue with the configuration, so we need to check all projects again.
Implements issue https://github.com/NativeScript/nativescript-cli/issues/5180.
> feat: doctor improvements

- lib/services/ios-project-service.ts
* Extract .xcframework bundles from `XCFrameworks.zip` as they contain symlinks and cannot stay in an NPM package without being wrapped in an archive
* CodeSign frameworks in final executable -- It is required for UIKit for Mac
#PR Checklist
> feat: Support iOS Runtime for Catalyst

- lib/services/ios-project-service.ts
> fix: Add warning for missing modulemap in `src`

- lib/declarations.d.ts
- lib/services/versions-service.ts
Currently the `tns info` command fails when executed inside application in which `tns-core-modules` package is not available as dependency. This may happen in case you use only `@nativescript/core` package.
The problem is that CLI is trying to read the package.json of the `<project dir>/node_modules/tns-core-modules` and this operation fails.
To fix this, add checks for both `tns-core-modules` and `@nativescript/core` packages. Warnings/information will be shown only for the package used in package.json, i.e. in case you use `tns-core-modules`, we'll show information only for it.
`tns info` fails when executed in a project without `tns-core-modules` in it.
`tns info` succeeds when executed in a project without `tns-core-modules` in it.
Fixes issue …
> fix: `tns info` should work with scoped modules

- lib/common/mobile/android/android-emulator-services.ts
- lib/common/test/unit-tests/services/json-file-settings-service.ts
- npm-shrinkwrap.json
- package.json
In case you have emulator with API Level 29 and other older emulators, CLI should run the latest available (29), but it doesn't.
The problem is in the parsing of the string version - '9.0.0' is always newer than '10.0.0' which corresponds to API level 29. Fix the parsing, so now `tns run android` will correctly start latest available emulator in case there's nothing running.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/5200
> fix: emulator 29 is not started by default

- lib/services/android-project-service.ts
- lib/services/ios-project-service.ts
- npm-shrinkwrap.json
- package.json
- test/services/android-project-service.ts
There's no way to override the CLI build logic through a hook.
We could override the CLI build logic through a before build hooks.
Related to: https://github.com/NativeScript/nativescript-cli/issues/5205
> feat: expose before build hooks in order to support cloud builds without an extension

- lib/services/livesync/android-livesync-tool.ts
- test/services/livesync/android-livesync-tool.ts
In case there's a socket connection error during LiveSync for Android, we show a non-descriptive error message which confuses the users. Improve the messsage with suggestions what might cause the error.
In case you change your application identifier in `<path to App_Resources>/Android/app.gradle`:
```
android {
defaultConfig {
minSdkVersion 17
generatedDensities = []
applicationId = "org.nativescript.different"
}
aaptOptions {
additionalParameters "--no-version-vectors"
}
}
```
And run `tns run android` you'll see:  https://www.screencast.com/t/fWQeEVdQ
https://www.screencast.com/t/0CskhIc0IP
Fixes issue: https://github.com/NativeScript/nativescript-cli/issues/3818
> fix: improve message for Android socket connection error

- CHANGELOG.md
- lib/services/platform-environment-requirements.ts
- test/services/platform-environment-requirements.ts
There's no way to override the CLI env checks through a hook.
We are able to override the CLI env checks through a before `checkEnvironment` hooks.
Related to: https://github.com/NativeScript/nativescript-cli/issues/5210
> feat: add env check hook in order to allow cloud builds without any native local setup

- CHANGELOG.md
- lib/controllers/update-controller.ts
In the past `tns update` command worked with tags, but since 6.0 this was broken. The logic in Update Controller requires a valid package.json from template with same version. However, our templates do not have `next`, `rc`, etc. versions and passing tag to the command fails.
In order to fix this, construct the required template manually. For each of the packages we would update, check if the has a valid version with the same tag and get the current version behind this tag.
`tns update next` fails.
`tns update next` passes.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/5072
> fix: `tns update` command should work with npm tags

- lib/definitions/project.d.ts
- lib/project-data.ts
- lib/services/webpack/webpack-compiler-service.ts
- npm-shrinkwrap.json
- package.json
- test/project-data.ts
- test/services/webpack/webpack-compiler-service.ts
- test/stubs.ts
Currently CLI passes the webpack.config.js at the root of the application as config to the spawned webpack process. This file is managed by both the developers and nativescript-dev-webpack (when you update this package, you often have to update the file, which overrides any custom settings).
In order to allow easier upgrades and customizations, add an option in nsconfig.json (`webpackConfigPath`) to set the path to config file passed to webpack process. This way, the `webpack.config.js` can be managed by nativescript-dev-webpack and all customizations can be done in another file. The path to custom file can be set in nsconfig.json and CLI will pass it to webpack.
Implements issue https://github.com/NativeScript/nativescript-cli/issues/5218
> feat: allow setting custom webpack config file

- lib/services/ios-project-service.ts
When you do not have iOS native source code in `<path to App_Resources>/iOS/src`, CLI shows warning that there's no modulemap and you'll not be able to use the code through JavaScript. However, there's no code at all. Skip the preparation of native source code in case there's no native sources there.
Part of https://github.com/NativeScript/nativescript-cli/issues/5187
> fix: incorrect warning is shown when building for iOS

- lib/services/ios-project-service.ts
Currently in case you have native source code, it is added to the pbxproject's references. In case you remove the source code's directory, the files relations are not cleaned from the pbxproject, which makes the build fail. To fix this, instead of skipping the native code refrence for this folder, just call the method to add such pbxgroup and the nativescript-dev-xcode will cleanup the required resources.
Also fix the warning for modulemaps, it must be shown only when you have `.h` files and you do not have module.modulemap file at the root of the source code directory.
> fix: removed native code should be cleaned from native project

- lib/declarations.d.ts
- lib/definitions/plugins.d.ts
- lib/services/plugins-service.ts
- lib/tools/node-modules/node-modules-dependencies-builder.ts
- test/plugins-service.ts
- test/stubs.ts
- test/tools/node-modules/node-modules-dependencies-builder.ts
Currently in case you have multiple occurences of a NativeScript plugin in node_modules, most of the time the build of application fails. For iOS Xcode fails with duplicate resources (most commonly frameworks) and for Android the Static Binding Generator will fail in case the JavaScript of a plugin differs.
Improve the handling by checking the versions of NativeScript plugins. In case the same version is installed multiple times, show warning to the user and link only one of the versions to the native build.
In case multiple versions are detected, throw an error - currently we cannot support this case.
Implements issue https://github.com/NativeScript/nativescript-cli/issues/5214
> feat: improve detection of NativeScript plugins

- lib/bootstrap.ts
- lib/common/commands/package-manager-set.ts
- lib/declarations.d.ts
- lib/options.ts
- lib/package-manager.ts
- lib/pnpm-package-manager.ts
- test/package-installation-manager.ts
- test/plugins-service.ts
- test/services/extensibility-service.ts
you can choose pnpm as the package manager
> This PR add pnpm full support

- lib/common/declarations.d.ts
- lib/constants.ts
- lib/services/ios-project-service.ts
- lib/sys-info.ts
As from March 2020 iOS apps will have to be built with Xcode 10 in order to be uploaded to AppStore, deprecate the support for Xcode 10 and below - CLI will show warning in case such Xcode is used.
Implements issue https://github.com/NativeScript/nativescript-cli/issues/5230
> feat: deprecate support for Xcode 10 and below

- lib/common/dispatchers.ts
Related to: https://github.com/NativeScript/nativescript-cli/issues/5233
> feat: expose a resolveCommand hook allowing cloud publishing though a simple redirect

- CHANGELOG.md
> chore: update changelog for 6.4.0 release

- lib/definitions/plugins.d.ts
- lib/services/ios-project-service.ts
- lib/services/metadata-filtering-service.ts
- lib/services/plugins-service.ts
- lib/tools/node-modules/node-modules-builder.ts
- test/plugins-service.ts
Currently CLI fails when different versions of the same plugin are used. However, this introduces a lot of issues for Android, where the `nativescript-permissions` plugin is used by most of the other plugins. When they hardcode different version, CLI stops the build. However, this plugin is pure JS and does not have native part.
To resolve this, separate the checks for iOS and Android. For Android, the SBG may fail in case different versions of the plugin are detected. However, there's no easy way to determine this, so just make the checks and show debug messages.
For iOS the build will fail in case framework is linked multiple times from different locations, so group the plugins by frameworks and fail in case the same framework is listed multiple times by different plugins or by …
> fix: improve check for duplicated NativeScript plugins

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
Currently we cannot build projects for Android when Java 13 is installed. However, we do not detect this and later the build operation fails with non-descriptive error message.
Update nativescript-doctor to 1.13.0 where version 13 (and above) is correctly detected as not supported.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/5242
> fix: Java 13 is not supported, but is not detected as such

- CHANGELOG.md
- lib/services/webpack/webpack-compiler-service.ts
- npm-shrinkwrap.json
- package.json
In case you have external files set in the webpack.config.js (or resources copied with CopyWebpackPlugin), the `tns run ...` command does not LiveSync them to device. Webpack compilation is triggered, but as the emitted files are not hot updates, the hot update hash of the compilation is the same as the previous one. In this case CLI decides there's nothing to sync.
To fix this extend the check in webpack-compiler-service to be based not only on the comparison between previous and current hash, but on the emitted files as well - if there are files which are not hot updates, continue the execution even if the previous and current hash are the same. That's exactly the case with externals.
Fixes issue https://github.com/NativeScript/nativescript-cli/issues/5251
> NOTE: Current changes may …
> fix: external files are not livesynced

- lib/detached-processes/cleanup-process-definitions.d.ts
- lib/detached-processes/cleanup-process.ts
- lib/detached-processes/detached-process-enums.d.ts
- lib/services/cleanup-service.ts
- lib/services/ios-project-service.ts
Will be used in the ns-remote-builds plugin for cleaning the remote ENV vars on CTRL+C.
Bonus: unify the iOS buildData argument with the Android (unifying the build hooks API)
> fix: support request cleanup + options for the commands

- CHANGELOG.md
- lib/common/test/unit-tests/mobile/device-log-provider.ts
- lib/services/log-source-map-service.ts
- test/services/log-source-map-service.ts
Currently CLI tries to persist the formating of logs as close as possible to the real logs coming from device.
The logs from the applications contain `file:///<filePath>`. CLI replaces the `<filePath>` with the real local file path. However, due to the `file:///` prefix, the link is not clickable. For example, in case you use VSCode's terminal, you should be able to use Ctrl + Click on the link and this will lead you to the exact line where the stack trace points to.
To resolve this issue, replace the `file:///` with just `file: `.
When CLI parses the device logs, it tries to replace the file location with the real file path location. However, this does not work for platform specific files (in non-Angular projects) as we are using a virtual file system in webpack, which "lies" the file …
> fix: device logs parsing

- lib/common/test/unit-tests/mobile/device-log-provider.ts
- lib/services/log-source-map-service.ts
- test/services/log-source-map-service.ts
When --path is used, the logs from the device are not mapped correctly to the local platform specific files. Fix the check if file exists in the project.
> fix: file paths from device logs should be correct with --path

- docs/man_pages/general/package-manager-get.md
- docs/man_pages/general/package-manager-set.md
- docs/man_pages/start.md
- lib/common/commands/package-manager-set.ts
Improve the package-manager help and improve the message when you set a specific package-manager to point we want it to be available in PATH.
> fix: improve package-manager help and info messages

- lib/services/android/gradle-build-args-service.ts
- test/services/android/gradle-build-args-service.ts
There is no way to add additional gradlew parameters to a build.
We can now create `before-build-task-args` hooks where we can modify the `args` array that's passed to `gradlew`. 
For example, to use wix/Detox - we need to alter a projects `app.gradle` and build the app with `assembleAndroidTest` passed to `gradlew`. To do this, we have to manually run `tns prepare android` and then run the correct `gradlew` command with our additional parameters. With this change, we can do this with a hook (would need to add a condition in a real app): 
```js
module.exports = function(hookArgs, $errors, $injector) {
hookArgs.args.unshift('assembleAndroidTest')
hookArgs.args.push('-DtestBuildType=debug')
}
```
Implements #2481
> feat: allow modifying gradlew args in hooks

- vendor/gradle-plugin/gradle.properties
> fix: missing gradle properties option useAndroidX

- lib/services/doctor-service.ts
- lib/services/marking-mode-service.ts
- lib/services/versions-service.ts
- package-lock.json
- package.json
> fix(doctor): cannot read property 'filter' of null

- lib/controllers/prepare-controller.ts
- lib/definitions/project.d.ts
- lib/services/project-config-service.ts
- test/project-service.ts
- test/services/project-config-service.ts
- test/services/project-data-service.ts
- test/stubs.ts
Whenever the CLI has to generated a `nsconfig.json` for backwards compatibility - it's recommended to gitignore the file, however with this change, the file should get auto-delete when the cli exits.
> feat: clean up legacy nsconfig if created for bw compat

- lib/services/project-config-service.ts
- lib/services/webpack/webpack-compiler-service.ts
There is currently no way to get values from the `nativescript.config.ts` file in the webpack config unless you use a `.js` config file.
With this change, the path to the nativescript lib (exposing the public API of the CLI) is passed to the webpack env, and the webpack config can read useful data from the CLI - inlcluding values from a ts config file. For example, the following would get the values from the `nativescript.config.ts` (or .js).
```js
const nativescriptLib = require(env.nativescriptLibPath)
const nsConfig = nativescriptLib.projectDataService.getProjectData().nsConfig
console.log(nsConfig)
```
Or even using the config service directly:
```js
const nativescriptLib = require(env.nativescriptLibPath)
console.log(nativescriptLib.projectConfigService.readConfig()) …
```
> feat: pass current CLI public lib path to webpack env

- lib/bootstrap.ts
- lib/commands/config.ts
Allow getting and setting config values with a command.
```bash
ns config
ns config get id
ns config set id some.new.id
```
> feat: config manipulation commands

- .vscode/launch.json
- lib/definitions/project.d.ts
- lib/services/cocoapods-service.ts
- lib/services/ios-project-service.ts
- test/ios-project-service.ts
> fix: exclude unsupported architectures from cocoapods

- lib/services/cocoapods-service.ts
- test/ios-project-service.ts
* `VALID_ARCHS` cause problems with Xcode 12 due to the change mentioned in the [Xcode 12 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes) [search for `VALID_ARCHS` - even though listed under Deprecations this appears to not totally be the case - it has been found that they cause broad reaching problems when present in building projects with Xcode 12]
* This clears that value for any Cocoapods which may have that set and haven't yet removed it
* We may want to release as `7.1.0` of cli since this would probably affect users building with Xcode 11.x still
* Or the recommendation can be to use Xcode 12 with {N} 7 in general and release as 7.0.10 of cli
> fix(ios): remove VALID_ARCHS from cocoapods for xcode 12

- lib/commands/create-project.ts
- lib/constants.ts
- lib/declarations.d.ts
- lib/options.ts
- test/project-commands.ts
Depends on:
https://github.com/NativeScript/NativeScript/pull/8963
https://github.com/NativeScript/nativescript-app-templates/pull/170
N/A
add svelte as a template option when creating new project
> feat: add svelte support

- PublicAPI.md
A simple fix in the doubling of the word "the" in the PublicAPI.md file
> Small Update in PublicAPI.md

- lib/controllers/migrate-controller.ts
Related to/depends on https://github.com/NativeScript/NativeScript/pull/8963
> feat: migration rules for svelte-native

- lib/services/assets-generation/assets-generation-service.ts
> fix: alpha issue

- lib/services/ios-project-service.ts
After changing CFBundleName in Info.plist, the app is built, but can't be installed because of missing .ipa file.
App is built, installed and started, respecting the CFBundleName.
Fixes #5424
> fix: CFBundleName cannot be changed

- lib/controllers/update-controller.ts
- lib/definitions/project.d.ts
fixes #5440
We no longer specify the runtime versions in the templates, so when CLI tries to update the runtimes it fails.
The CLI no longer reads the non-existent nativescript key in the package.json, instead the runtime defaults to the latest version.
> fix: ns update version null

- lib/bootstrap.ts
- lib/commands/fonts.ts
- lib/constants.ts
- package-lock.json
- package.json
- yarn.lock
See https://github.com/NativeScript/rfcs/pull/21
> feat: fonts command

- lib/commands/create-project.ts
- test/project-commands.ts
Added a TypeScript template option for Vue in `ns create`.
> feat: vue-ts-template

- lib/config.ts
System requirements URL is not working.
The valid url shows up when your computer does not match the requirements.
Fixes #5432, #5352
> chore: update setup requirements link

- lib/services/project-service.ts
- test/project-service.ts
When running `ns create` a fresh project, the CLI initializes a new git repository and commits the initial files.
Implements #5467
> feat: initialize git repo on project create

- CHANGELOG.md
Changelog for 6.5.0 is missing, the changes are in 6.4.1.
Changelog for 6.5.0 is fixed.
Fixes #5312.
> docs: update 6.5.0 changelog

- lib/controllers/platform-controller.ts
The CLI breaks when the platforms folder is empty.
Shows a warning with instructions to clean the project in case of broken platforms folder.
Fixes #5145
> feat: handle empty platforms folder

- lib/definitions/project.d.ts
- lib/services/project-config-service.ts
- test/stubs.ts
After creating a new project based on a template, we write the default config. In some cases, the `appPath` is different for a template. 
Default config writes `appPath` based on what folder exists in the template project.
Possible appPaths: `app`, `src`.
Fixes #5465
> fix: default appPath in new project

- lib/definitions/project.d.ts
- lib/project-data.ts
- lib/services/project-data-service.ts
`projectData` gets re-initialized over and over again and the cache has no effect.
Initialize `projectData` only if it hasn't been initialized yet.
Fixes #5398
> perf: initialize project data if needed

- docs/man_pages/project/testing/build-android.md
- docs/man_pages/project/testing/build-ios.md
Result of `tns build android/ios -h` command does not include `--path` option.
Show `--path` option in result of `tns build android/ios -h` command.
Fixes #5339
> docs: show --path option on build help

- lib/controllers/update-controller.ts
The CLI catches error for invalid version in the argument after cleaning/backing up while update.
The CLI throws error immediately at update if the version in the argument is incorrect.
Fixes #3669
> perf: validate update version before backup

- lib/common/file-system.ts
If node is not properly installed documentation generating might fail, caused by node and the packages are in a system protected folder. The CLI does not have permission to create directory in system folders.
In case of node and packages are in a system protected folder, the documentation generation logs an error with help, how to run the command.
Fixes #5445
> fix: handle permissions error on directory creation

- lib/common/declarations.d.ts
- lib/common/test/unit-tests/analytics-service.ts
- lib/services/analytics-settings-service.ts
- lib/services/analytics/analytics-service.ts
The CLI asks for permission to send data to analytics and shows an outdated privacy policy link.
Removed privacy policy link
> chore: remove privacy policy link

- lib/controllers/update-controller.ts
Handle `ns update` validation without arguments. (default: latest)
> fix: ns update handle no arguments at tag validation

- docs/man_pages/general/doctor.md
- docs/man_pages/start.md
- lib/common/bootstrap.ts
- lib/common/commands/doctor.ts
- lib/common/declarations.d.ts
- lib/declarations.d.ts
- lib/services/doctor-service.ts
- lib/services/versions-service.ts
`ns doctor` checks your system for configuration problems for `ios` and `android`. 
`ns doctor <Platform>` can check the system configuration for `ios` and `android` separately.
> feat: platform specified doctor

- lib/controllers/migrate-controller.ts
- lib/services/project-config-service.ts
`ns prepare android` command fails if the `@nativescript/android` runtime package version has a leading caret or tilde: `^6.5.3`
CLI handles leading caret and tilde in android runtime package.  
Fixes #5500
> fix: handle caret and tilde in runtime versions

- lib/controllers/migrate-controller.ts
- lib/data/prepare-data.ts
- lib/services/marking-mode-service.ts
- lib/services/project-config-service.ts
> fix: 8.0.0 patches

- package-lock.json
- package.json
Projects using nativescript see the below deprecation warning upon install.  This is due to chokidar 3.4.1 relying on a deprecated version of fsevents.
Upgraded chokidar to 3.5.1 which upgrades fsevents to a non-deprecated version.  This version of chokidar also now supports Apple silicon: https://github.com/paulmillr/chokidar/releases/tag/3.5.0
> chore: Update chokidar to remove fsevents deprecation warning

- lib/services/project-templates-service.ts
- test/project-templates-service.ts
`ns create` will use the same template major version as the CLI. 
Fixes #5515.
> feat: default template version based on cli major

- README.md
- lib/commands/post-install.ts
- lib/services/platform-environment-requirements.ts
Slack invitation link to the NativeScript community channel in the docs.
Replaced Slack channel to the Discord channel in the docs.
> docs: replace Slack to Discord

- docs/man_pages/project/testing/run-ios.md
- lib/common/mobile/ios/simulator/ios-simulator-application-manager.ts
The `IOS_SIMULATOR_RUN_ARGS` environment variable allows specific command line arguments to be passed to the simulator when running an app.
This is _extremely_ useful when working (for example) with Firebase and having to debug events or other internals:
https://firebase.google.com/docs/analytics/debugview
The command line arguments `-FIRDebugEnabled` and `-FIRDebugDisabled` control the behaviour of Firebase in combination with its realtime event debugging console.
With this patch, enabling debugging is as easy as calling:
```bash
IOS_SIMULATOR_RUN_ARGS=-FIRDebugEnabled ns run ios
```
> feat: allow passing command line arguments running an app in the iOS Simulator

- lib/controllers/prepare-controller.ts
- lib/definitions/platform.d.ts
- lib/definitions/project.d.ts
- lib/services/plugins-service.ts
- lib/services/project-changes-service.ts
- lib/tools/node-modules/node-modules-builder.ts
- lib/tools/node-modules/node-modules-dependencies-builder.ts
- test/tools/node-modules/node-modules-dependencies-builder.ts
Along with that we simply need to have a cli parameter and an option in nativescript.config
@rigor789 could you help with the cli params? not sure where to do that.
Also i think we could even add ignored dependencies through the webpack config right? I dont remember how but we can modify the project data from there?
With this people can simply make it so that some deps are only used in dev (like vue-dev-tools and socketio) while not being present in production.
You can also make different releases for Google Play and Fdroid (what i am going for) where one would use non open source libs and the other would not (flavors on android)
> feat: allow to ignore native dependencies

- lib/project-data.ts
- lib/services/project-config-service.ts
- lib/services/project-service.ts
> fix: properly handle missing App_Resources

- lib/controllers/migrate-controller.ts
> fix(migrate): nativescript-unit-test-runner & missing basePath

- lib/services/karma-execution.ts
- lib/services/test-execution-service.ts
If you have a monorepo you can't run tests because it requires karma to be at the app level, which also requires you to install a lot of extra stuff at the local level (including webpack).
Use a parent karma if possible.
> feat: allow tests to run on monorepos

- lib/common/mobile/ios/simulator/ios-simulator-device.ts
When running an iOS simulator app, the NativeScript CLI sends an `AttachRequest` notification to the application right after launch. If the runtime hasn't had time to set up the event handler for this notification yet, it's silently lost, and the CLI never gets the port number for debugging. This causes HMR to not work, and worse, the application auto-restarts after a minute. (The console shows the error "NativeScript debugger was not able to get inspector socket port")
This seems to be a race condition based on how quickly the iOS runtime sets up its event handler vs. how quickly the CLI sends the `AttachRequest` notification after launching the app. For some reason, I went from not experiencing this issue at all to experiencing it nearly 100% of the time when using the simulator on my …
> fix: race condition when getting iOS inspector port

- vendor/gradle-plugin/build.gradle
I am writing a plugin which comes with kotlin files directly in its platforms folder (android/java/...)
Right now it wont build while building an app (building the plugin in tempPlugin). This enables kotlin for all!
> fix allow plugins to use kt files

- lib/services/livesync/android-device-livesync-service.ts
- lib/services/livesync/android-livesync-tool.ts
adds support to wsl via `export LIVESYNC_ADDR=hostIpAddr`
livesync always tries to connect to localhost
you can provide the LIVESYNC_ADDR to override the default ip address for livesync
Implements #5450.
> feat: support livesync in remote machine

- docs/man_pages/start.md
- lib/declarations.d.ts
- lib/definitions/project.d.ts
- lib/options.ts
- lib/project-data.ts
- lib/services/project-config-service.ts
- lib/services/webpack/webpack-compiler-service.ts
- test/options.ts
- test/services/project-config-service.ts
- test/services/webpack/webpack-compiler-service.ts
to set custom `nativescript.config` file name (relative, absolute, with or without .ts or .js)
read `ignoredNativeDependencies` from `nativescript.config``nativescript.config`
I added a test. What is weird to me is that some tests are failing.But i cant see how they could pass, like this one https://github.com/farfromrefug/nativescript-cli/blob/cdf912ecdbd01c34ab405df2e9e39268f982d71f/test/tools/node-modules/node-modules-dependencies-builder.ts#L536
> feat: `config` option

- docs/man_pages/start.md
- lib/commands/create-project.ts
- lib/commands/preview.ts
- lib/common/definitions/config.d.ts
- lib/config.ts
- lib/services/analytics/analytics-broker-process.ts
- lib/services/analytics/analytics-service.ts
- lib/services/platform-environment-requirements.ts
- test/services/platform-environment-requirements.ts
> chore: disable preview

- lib/services/plugins-service.ts
This happens when multiple deps have another common dependencies.
This fix has one direct consequences which makes app build faster. 
Before this native plugins where built multiple times.
As an example for [this](https://github.com/nativescript-community/ui-material-components/tree/master/demo-vue) app using my material components.
Before this commit :
```js
pluginsData 37 [
'@nativescript-community/css-theme',
'@nativescript-community/text',
'@nativescript-community/ui-material-activityindicator',
'@nativescript-community/ui-material-bottom-navigation',
'@nativescript-community/ui-material-bottomnavigationbar',
'@nativescript-community/ui-material-bottomsheet',
'@nativescript-community/ui-material-button',
'@nativescript-community/ui-material-cardview', …
```
> remove duplicate plugins data

- lib/services/ios/xcodebuild-args-service.ts
- test/services/ios/xcodebuild-args-service.ts
> fix: codebuild destination warning

- lib/common/http-client.ts
- lib/services/apple-portal/apple-portal-application-service.ts
- lib/services/apple-portal/apple-portal-session-service.ts
- lib/services/apple-portal/definitions.d.ts
With 8.1 cli ```ns publish ios``` resulted in 401
In previous cli versions it resulted in 404 because the endpoint for changing the team was removed by apple.
```ns publish ios --appleApplicationSpecificPassword ...``` 
```ns appstore```
now both work.
Fixes/Implements/Closes #5553.
> fix(ios-publish): accept body on http post and update to new api

- lib/definitions/metadata-filtering-service.d.ts
- lib/services/metadata-filtering-service.ts
This pull request allows plugins `native-api-usage.json` to provide blacklist  (useful for example to prevent huge .R to be included)
> feat: allow plugin blacklist metadata

- lib/services/log-source-map-service.ts
this PR fixes the `original` source file path when it already includes `app/`
> fix: fix source map path

- lib/services/cocoapods-service.ts
> fix(m1): cocoapods command when installed natively

- config/test-dependencies.json
- lib/commands/test-init.ts
- lib/controllers/migrate-controller.ts
- lib/services/test-execution-service.ts
- package-lock.json
- resources/test/karma.conf.js
- resources/test/test-main.js
- resources/test/test-main.ts
- resources/test/tsconfig.spec.json
- yarn.lock
`ns test init` prepares app for 2.0 unit-test-runner.
`ns test init` now prepares app for 3.0 unit-test-runner which is vastly improved and now includes optional code coverage reporting via convenient `--env.codeCoverage` flag.
> feat: unit-test-runner 3.0 with optional coverage report handling

- lib/commands/clean.ts
Fixed the information texts when using the clean command. The 'Cleanining project...' and 'Cleaned directory hooks' are showing at the same line
> Fixed breakline on clean command

- lib/controllers/build-controller.ts
Build time not shown in ios.
Build time is computed and logged irrespective of OS.
Fixes/Implements/Closes #2998.
> feat: compute and log build time

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
GitHub recently made the `label` fields required for the checkboxes.
> chore: fix issue forms

- lib/base-package-manager.ts
- lib/constants.ts
- lib/node-package-manager.ts
- lib/pnpm-package-manager.ts
- lib/services/android-plugin-build-service.ts
- lib/yarn-package-manager.ts
- vendor/aab-tool/README.txt
- vendor/gradle-plugin/build.gradle
fix: android buildtools 31+ errors
chore: bump aab tool
> feat(android): add gradle 7+ support

- lib/commands/test.ts
the test command does not exit when karma exits with error code 0
cli exits with code 0 when karma finishes it's execution
Fixes #5617.
> fix(test): exit test command if karma finishes execution

- lib/commands/plugin/build-plugin.ts
- lib/data/build-data.ts
- lib/declarations.d.ts
- lib/definitions/android-plugin-migrator.d.ts
- lib/definitions/build.d.ts
- lib/definitions/gradle.d.ts
- lib/options.ts
- lib/services/android-plugin-build-service.ts
- lib/services/android-project-service.ts
- lib/services/android/gradle-build-service.ts
- lib/services/android/gradle-command-service.ts
- package-lock.json
- test/services/android-project-service.ts
- yarn.lock
This simple PR add `--gradle` option to specify a custom gradle binary path
Solves https://github.com/NativeScript/nativescript-cli/issues/5550 
EDIT: renamed the option to `gradlePath`. makes more sense as i am about to add gradle option for args
> feat: --gradlePath argument support

- lib/commands/plugin/build-plugin.ts
- lib/data/build-data.ts
- lib/declarations.d.ts
- lib/definitions/android-plugin-migrator.d.ts
- lib/definitions/build.d.ts
- lib/options.ts
- lib/services/android-plugin-build-service.ts
- lib/services/android-project-service.ts
- lib/services/android/gradle-build-args-service.ts
In the same vibe as `gradlePath` this allows to pass gradle command parameters.
One note is that they have to be double quoted like this `--gradle '"-PsplitEnabled"'` or using `=` like this `--gradle="-PsplitEnabled"`
This is due to how `yargs` parses arguments
> feat: `--gradleArgs` option to pass gradle parameters

- lib/controllers/platform-controller.ts
- lib/controllers/prepare-controller.ts
- lib/definitions/platform.d.ts
- test/controllers/add-platform-controller.ts
Running the `platforms/android` project in AndroidStudio does not quite work without editing the run configurations to include appPath and appResourcesPath settings.
The missing settings are written to `gradle.properties` after adding the platform.
> fix: write project settings to gradle.properties

- packages/doctor/src/android-tools-info.ts
- packages/doctor/src/constants.ts
- packages/doctor/test/android-tools-info.ts
- packages/doctor/tsconfig.json
- tsconfig.json
> perf: doctor cache runtimeVersion

- lib/definitions/android-plugin-migrator.d.ts
- lib/services/android-plugin-build-service.ts
- lib/services/android-project-service.ts
- lib/services/ios-project-service.ts
- lib/services/platform-environment-requirements.ts
- lib/services/project-changes-service.ts
- lib/services/webpack/webpack.d.ts
- lib/tools/node-modules/node-modules-builder.ts
- lib/tools/node-modules/node-modules-dependencies-builder.ts
- test/services/test-execution-service.ts
- test/stubs.ts
- vendor/gradle-plugin/build.gradle
This allow a Nativescript plugin to depend on another nativescript native plugin code
> feat: build transient native dependencies

- lib/services/android-plugin-build-service.ts
Gradle versions are always read from `npm view`
Gradle versions are read from the locally installed runtime first before falling back to `npm view`.
> feat: read gradle versions from local runtime first

- lib/services/android-project-service.ts
Some dependencies are not in the sorted list because of the exit condition and a bug in the reducer.
All dependencies should be in the sorted list now, and sorted correctly.
> fix: topological dependency sorting

- lib/services/android-project-service.ts
- package-lock.json
- package.json
- packages/doctor/package.json
- packages/doctor/src/android-tools-info.ts
- packages/doctor/test/android-tools-info.ts
- packages/doctor/tsconfig.json
- yarn.lock
Building with build-tools 31 or 32 on `@nativescript/android` < 8.2 fails.
Building on < 8.2 now tries to use a supported targetSdk, compileSdk and buildToolsVersion, or otherwise fails with a message indicating the issue (missing build-tools in the correct range).
> fix(doctor): improve target and sdk compatibility detection on <8.2

- lib/services/apple-portal/apple-portal-application-service.ts
- lib/services/apple-portal/apple-portal-session-service.ts
- lib/services/apple-portal/definitions.d.ts
Current cli fails with 401 with ```ns publish ...``` and ```ns appstore``` becuase of changes in apple api
Ported over the changes from fastlane and called a different api to set the correct team id so the commands work again.
> fix(ios-publish) Changes in Apple API to set Team Id

- lib/services/ios-log-filter.ts
Some non-nativescript logs are shown when running, especially on a real device.
Only NativeScript logs (js) are shown.
fixes #3544
fixes #3727
fixes #5003
fixes #5310
fixes #5626
> fix: ios log filtering

- lib/controllers/migrate-controller.ts
`ns migrate` updates projects to Angular 13.2
`ns migrate` updates projects to Angular 14.1
> feat(migrate): use Angular 14.1

- lib/services/test-execution-service.ts
Usage of unit test runner v3+ with Node 18 would fail.
Usage of unit test runner v3+ with Node 18 will operate normally.
> fix(unit-test-runner): node 18 binding family

- lib/services/apple-portal/apple-portal-application-service.ts
- lib/services/apple-portal/definitions.d.ts
`ns appstore` and `ns publish ios` fail with error, because the apple api used was depreciated.
`ns appstore` and `ns publish ios` run.
ns appstore no longer shows the version numbers as it requires further calls with the new api to get this.
fixes #5677.
> fix(ios-publish): Update API calls to get applications

- lib/common/mobile/emulator-helper.ts
- package-lock.json
- package.json
- packages/doctor/package.json
- packages/doctor/src/android-tools-info.ts
- packages/doctor/test/android-tools-info.ts
- yarn.lock
> feat(doctor): add api 33 as supported

- lib/common/constants.ts
- lib/common/mobile/device-log-provider.ts
Additional devices will get assigned a different color to easily see which device the logs are coming from.
> feat: cleaner log output

- lib/controllers/prepare-controller.ts
- lib/definitions/project.d.ts
- lib/services/project-service.ts
- test/controllers/prepare-controller.ts
- test/project-commands.ts
If the project does not have an App_Resources, the build will fail/error out.
If the project does not have an App_Resources, defaults are pulled from the base template from npm before continuing the build.
> feat: ensure App_Resources exists before running

- lib/services/android-plugin-build-service.ts
- vendor/gradle-plugin/settings.gradle
As plugins are built in an isolated tempPlugin folder, it is currently not possible to link local projects in plugin builds similar to iOS. The following PR adds a `include-settings.gradle` plugin which can be used to link local android projects in plugin builds.
Related PR in android-runtime for app level settings.gradle plugin: https://github.com/NativeScript/android-runtime/pull/1731
> feat: include-settings.gradle plugin

- packages/doctor/src/android-tools-info.ts
CLI produces an incorrect error message that does not indicate that the reason for being unable to find a compatible android SDK version has anything to do with the range of android SDK versions which are interoperable with your current android runtime version. This will leave the user confused if they have a newer android SDK version installed than the most recent one (especially when the CLI is currently telling them to install "version x **or later**") which is compatible with their current android runtime version e.g. @nativescript/android version 8.1.1 + Android SDK version 31.
The error message produced when unable to find an Android SDK version compatible with your android runtime version will list out the android SDK versions compatible with your runtime version, and specifically …
> feat: more informative android compile SDK messages

- lib/services/webpack/webpack-compiler-service.ts
The hmr doesn't work properly in paths with the character '.'. Steps to reproduce: 
1. Create folder named **a.b-t14.32**
2. Enter on the **a.b-t14.32** folder
3. Create a ns project using angular template inside 
4. Run "ns run ios"
5. Change the app.ts file and save the changes.
Actual result:
The app doesn't restart
Expected result:
The app restart.
After change the app.ts file and save the changes the app restarts properly. 
The issue was happening on the wepack compiler service. The hash value wasn't being computed properly.
Before fix:
After fix:
> fix: hmr doesn't work properly in paths with the character '.'

- lib/services/cocoapods-service.ts
The EXCLUDED_ARCHS added for XCode 12 is applied for all XCode versions, even though it's not required for 13+ and causes build failures in some cases like #5702 
The workaround is only applied on XCode 12.
Fixes #5702
> fix: remove EXCLUDED_ARCHS workaround in xcode 13+

- lib/services/android-plugin-build-service.ts
- vendor/gradle-plugin/build.gradle
- vendor/gradle-plugin/gradle.properties
* copy paste for now. I think most could be refactored in the runtime and cli should include from there
* now kotlin, buildtools, … versions are define like in apps and use same defaults
* we dont modify the build.gradle for tempPlugin anymore. Instead we add the plugin as a native dep (to itself..) and just ignore the `aar` that we would build (which can already be there).
* now users can do almost anything they want in their plugin `include.gradle` and it will work (for example comments on the first line would break the build)
* now while building a tempPlugin we pickup any external aar we find the plugin `platforms` folder (main reason for this change)
> fix: android plugins now built using same “gradle” as apps

- lib/bootstrap.ts
- lib/commands/typings.ts
- lib/definitions/ios.d.ts
- lib/services/ios-project-service.ts
- lib/services/ios/spm-service.ts
- lib/services/ios/xcodebuild-args-service.ts
- lib/services/project-changes-service.ts
- package-lock.json
- package.json
- test/ios-project-service.ts
- test/services/ios/xcodebuild-args-service.ts
- yarn.lock
N/A
Implements https://github.com/NativeScript/nativescript-cli/issues/5698
Installing and using SPM packages is now possible through the `nativescript.config.ts`. Example: 
```ts
export default {
id: 'org.nativescript.spmtesting',
appPath: 'app',
appResourcesPath: 'App_Resources',
ios: {
experimentalSPMPackages: [
{
name: 'rive-ios',
libs: ['RiveRuntime'],
repositoryURL: 'https://github.com/rive-app/rive-ios.git',
version: '1.0.0'
}
]
},
android: {
v8Flags: '--expose_gc',
markingMode: 'none'
}
} as NativeScriptConfig;
```
This uses the new SPM feature published to `@rigor789/trapezedev-project` from this Trapeze PR: https://github.com/ionic-team/trapeze/pull/176
The config API is subject to change, so it's marked as experimental.
> **Note**: installing SPM dependencies from plugins is …
> feat: experimental SPM support

- lib/commands/appstore-upload.ts
- lib/constants.ts
- lib/declarations.d.ts
- lib/services/apple-portal/apple-portal-session-service.ts
- lib/services/apple-portal/definitions.d.ts
- lib/services/itmstransporter-service.ts
- package-lock.json
Currently any command that tries to login to apple with a username/passwrod will fail and lock the apple account.
e.g. `ns publish ios`. fastlane issue: https://github.com/fastlane/fastlane/issues/21071.
Current implementation does not support SMS verification. (#5714)
On Xcode >= 14 publish will fail because of the removal of iTMSTransporter. (#5704)
The Hashcash header is implemented allowing login.
The simple 1 phone registered SMS case is supported.
Now uses altool to push ipa if xcode>=14.
fixes #5714
fixes #5704.
> fix(publish): Various apple publish/sign in fixes.

- lib/bootstrap.ts
- lib/common/mobile/device-log-provider.ts
- lib/common/test/unit-tests/mobile/device-log-provider.ts
- lib/nativescript-cli.ts
- lib/services/timeline-profiler-service.ts
- test/ios-project-service.ts
Profiling requires installing an external tool (`timeline-view`) and piping the output of a run command into it to generate a timeline html view.
A timeline json file is generated automatically when timeline profiling is enabled (`profiling: "timeline"` in the nativescript config). The file is saved when the run is canceled with `ctrl+c`. The output json can be loaded into chrome devtools -> Performance and loading the json.
---
~~Commented out the `SIGINT` handling override - as it prevented listening for it for writing the timeline jsons - however this might cause side effects, so a different approach might be required.~~
~~For example and idle timeout, if no new traces come in within X seconds, it's automatically saved.~~
~~Another approach is listening for a keypress (for example `s` …
> feat(profiling): generate chrome compatible timeline data

- docs/man_pages/project/configuration/resources/resources-generate-icons.md
- lib/commands/generate-assets.ts
- lib/declarations.d.ts
- lib/definitions/project.d.ts
- lib/services/assets-generation/assets-generation-service.ts
- lib/services/project-data-service.ts
- resources/assets/image-definitions.json
Command `ns resources generate icons <source image path>` cannot generate app launcher icons ever since the adaptive icons addition (ic_launcher). Right now, developers have no ways to generate android launcher icons apart from using Android Studio.
Command `ns resources generate icons <source image path>` will generate all needed icons.
According to google, adaptive icons have few requirements:
- Both layers must be sized at 108 x 108 dp.
- The inner 72 x 72 dp of the icon appears within the masked viewport.
- The system reserves the outer 18 dp on each of the 4 sides to create interesting visual effects, such as parallax or pulsing.
In order to comply with these requirements, I updated `image-definitions.json` using the following concept:
1. Source image will also be used to create an …
> feat: Added support for generating android adaptive icons

- lib/controllers/migrate-controller.ts
> feat(migrate): 8.5.0 migrations

- lib/common/services/hooks-service.ts
closes https://github.com/NativeScript/nativescript-app-templates/pull/227
The hooks service is initialized and caches the hooksDirectories, however in some cases this might be an empty array (ie. when creating a new project, and the service is initialized before the project files exist yet).
We only cache when there's items in the `hooksDirectories` (since this means the projectDir was defined)
> fix: hooks not being called

- lib/services/xcconfig-service.ts
When using `xcodeproj` merge, it'll merge properties like:
```
// file 1
IPHONEOS_DEPLOYMENT_TARGET= 10.0;
// file 2
IPHONEOS_DEPLOYMENT_TARGET= 14.0;
//output
IPHONEOS_DEPLOYMENT_TARGET= 10.0; 14.0;
```
This causes an issue with Xcode 14.3 where this property is now being set for plugins as well
If both configs have `IPHONEOS_DEPLOYMENT_TARGET`, then we override instead of append
Fixes https://github.com/triniwiz/nativescript-plugins/issues/176
> fix: correctly merge IPHONEOS_DEPLOYMENT_TARGET in xcconfigs

- lib/services/project-cleanup-service.ts
ns migrate fails with 
``
TypeError: Cannot read properties of undefined (reading 'silent')
at ProjectCleanupService.<anonymous> (/Users/jcassidy/.nvm/versions/node/v18.13.0/lib/node_modules/nativescript/lib/services/project-cleanup-service.js:25:35)
``
Added null checks.
migrate works.
> fix: migrate failing because options passed to clean are null

- lib/services/xcconfig-service.ts
Values in the user's build.xcconfig are sometimes concatenated to the base values from the iOS template
build.xcconfig always takes precedence over default values (no merging)
> feat(ios): always override xcconfig with user values

- lib/services/ios/export-options-plist-service.ts
- test/services/ios/export-options-plist-service.ts
> feat(extension): initial per-extension provisioning

- lib/constants.ts
- lib/declarations.d.ts
- lib/definitions/project.d.ts
- lib/services/cocoapods-service.ts
- lib/services/ios-project-service.ts
- lib/services/ios/export-options-plist-service.ts
- lib/services/ios/ios-signing-service.ts
- test/services/ios/ios-signing-service.ts
This PR fixes the following open issue
https://github.com/NativeScript/nativescript-cli/issues/5520
https://github.com/NativeScript/nativescript-cli/issues/5244
- Currently, the NativeScript CLI does not support Podfiles for extensions. The final Podfile is wrapped with the main application target. However, extensions require their own unique targets.
- Additionally, it is currently not possible to build the iOS app with an extension and a provided team ID or provision.
- With this update, developers can now create a Podfile in each extension folder, similar to how they would for the main app. During the build process, the CLI will generate a new target with the extension name and merge it with the existing final Podfile. As a result, the Podfile, after the build, will contain plugins, …
> feat(extensions): add extension podfile and setup extension with provision

- lib/services/android-plugin-build-service.ts
> feat: allow android plugins to have cpp code

- lib/services/plugins-service.ts
- test/plugins-service.ts
NativeScript CLI hashes plugin files before preparing them, meaning that the next run of the CLI will have outdated hashes if the plugin changed any of its files during the prepare step.
This can lead to some cases of plugins not being prepared when they should because the known hashes (from `.ns-plugins-build-data.json`) match the hashes of a plugin that was not built yet.
This is notable when using yarn and some plugins from nativescript-community (_i.e._ [ui-lottie](https://github.com/nativescript-community/ui-lottie) and [ui-material-*](https://github.com/nativescript-community/ui-material-components)) because they don't ship a `.aar` in the tarball. After installing any dependency with yarn it'll reset the node_modules to a known state that will break the known hashes of the CLI. …
> fix: hash plugin files after prepare

- lib/services/ios-project-service.ts
This is an important fix because the name of the xcframework file might not be the actual name of the framework
> fix: get framework name from Info.plist

- lib/common/helpers.ts
- package-lock.json
- package.json
We're aliasing `cli-table` to `cli-table3`. This causes issues with certain package managers.
We no longer alias `cli-table` and instead use `cli-table3`. Upon checking our 3rd party deps, all of them are already using `cli-table3` so the primary reason this was aliased in the first place no longer stands.
> fix: remove cli-table aliasing

- lib/services/platform-environment-requirements.ts
- packages/doctor/src/constants.ts
when it has an error due to the environment, we have the error
```
Your environment is not configured properly and you will not be able to execute local builds.
Verify that your environment is configured according to the system requirements described at
https://docs.nativescript.org/environment-setup.html#macos-ios.
```
This does not correspond to the new documentation, since before we had everything on the same page and now on separate pages
Also this PR needs more changes, since we need
```
/setup/macos#setting-up-macos-for-ios
rather
/environment-setup.html#macos-ios
```
Here we can add the change to put
```
const anchor = platform ? `/${os}#setting-up-${os}-for-${platform.toLowerCase()}` : "";
```
Or we can change in the documentation
```
/setup/macos#setting-up-macos-for-ios
To …
```
> fix: setup docs links

- lib/services/pacote-service.ts
- package-lock.json
- package.json
The upgrade from the "pacote" package failed to account to a breaking change in v14.
https://github.com/npm/pacote/issues/241
We now provide "arborist" to pacote so we maintain the same behavior
Fixes https://github.com/NativeScript/NativeScript/issues/10412.
> fix: resolve pacote regression with creating app from a template directory

- lib/services/log-source-map-service.ts
Large files in the output directory can crash node/v8.
We skip reading files larger than 50mb as those are unlikely to be source code anyways. This doesn't affect anything but logs - where larger files would just log their actual stack traces rather than a source-mapped one. In practice source would rarely if ever be >50mb though.
> fix: skip log-source-maps for large files

- lib/services/ios/xcodebuild-args-service.ts
When Swift Packages are included, validations may run which break the build.
xcodebuild flag is now included during iOS development to avoid build interruptions as discussed here:
https://forums.swift.org/t/telling-xcode-14-beta-4-to-trust-build-tool-plugins-programatically/59305
> fix(ios): skip package validation on xcodebuild

- lib/definitions/ios.d.ts
- lib/services/ios/spm-service.ts
- lib/services/ios/xcodebuild-args-service.ts
Xcode will use min version target priorities from different levels which can ignore user defined xcconfig at times when not desirable.
Ensures deployment target from user defined xcconfig always takes precedence.
Merge https://github.com/NativeScript/nativescript-cli/pull/5782 first as this branches from there.
> feat(ios): ensure user defined xcconfig always takes priority

- packages/doctor/src/doctor.ts
- packages/doctor/src/sys-info.ts
- packages/doctor/test/sys-info.ts
- packages/doctor/typings/interfaces.ts
> fix: remove python six requirement

- lib/services/ios/xcodebuild-args-service.ts
- test/services/ios/xcodebuild-args-service.ts
> chore: fix tests

- docs/man_pages/project/configuration/open-android.md
- docs/man_pages/project/configuration/open-ios.md
- docs/man_pages/project/configuration/open.md
- docs/man_pages/start.md
- lib/key-commands/bootstrap.ts
- lib/key-commands/index.ts
Add open iOS/android command.
Generalize iOS open command to cater for non standard installations. Fix open command on windows ( detach from launched process )
Currently the start menu open on IOS does not deal with non standard installs of Xcode, e.g. using xcodes, this utilizes the existing services to figure out where the installation is.
On open android on windows the process is tied to the parent, so will not exit until Android Studio exits.
Leveraged the start / open functionality to add command `ns open <ios|android>`
Fixed the above issues.
Fixes/Implements/Closes #5754.
> feat(open): Add open ios/android

- lib/services/webpack/webpack-compiler-service.ts
> [fix]: provide appId to webpack config

- lib/services/plugins-service.ts
If a plugin contains invalid data like the wrong name according to package.json, a 'path' from 'undefined' ambiguous error occurs. 
This will now print the name of the invalid package to allow one to resolve effectively.
> fix(plugins): parse name issue with invalid plugins

- lib/device-sockets/ios/app-debug-socket-proxy-factory.ts
This solves the problem we had debugging in vscode on ios. The problem was that when an address was not set the plugin used 127.0.0.1 when forcing localhost it worked, but now I am migrating the old [`vscode-chrome-debug-core`](https://github.com/microsoft/vscode-chrome-debug-core)   to `vscode-cdp-proxy` which uses `ws` below and when using the `localhost` address it resolves it as 127.0.0.1 and the cli does not accept the connection.
I have tried chromeDevTool and it still works with this change
> fix host localhost for debug ios

- lib/common/services/auto-completion-service.ts
The command `ns autocomplete enable` doesn't work in the current version as the incorrect command is called to yargs to generate the script.
In addition the yargs script doesn't seem to work with the commands `ns tns`.
Also the existing script duplicates the contents of `.tnsrc` on enable/disable and it does not clean up what the previous implementation did. 
This should now implement `ns autocomplete enable/disable` so that it works for `ns/tns` as you would expect.
It cleans up the previous implementation and does not duplicate entries in `.tnsrc` on repeated enable/disable.
> fix(autocomplete): fix the generation of the autocomplete script and prevent duplication on enable/disable

- lib/bootstrap.ts
- lib/bun-package-manager.ts
- lib/commands/preview.ts
- lib/common/dispatchers.ts
- lib/constants.ts
- lib/package-manager.ts
- test/bun-package-manager.ts
- test/controllers/add-platform-controller.ts
- test/package-installation-manager.ts
- test/plugins-service.ts
- test/services/extensibility-service.ts
Based on the existing NPM and PNPM versions.
I added a test file, based on the `test/npm-package-manager.ts`.
Not tested via linking and using in a terminal yet.
Bun package manager is not supported.
Adds support for Bun package manager. Falls back to `npm` commands when Bun does not have an analogous command, like `search` and `view`.
Implements https://github.com/NativeScript/NativeScript/issues/10397
`ns package-manager set bun`, then use the `ns` CLI commands like normal.
> feat: add experimental bun package manager support

- lib/commands/typings.ts
You have to manually pass in the full path of the aar/jar files via `--aar/--jar`.
A new interactive menu for picking the aar/jar files based on a glob pattern provided as an argument:
```bash
ns typings android "androidx.media3:media3-*"
ns typings android "androidx.media3:media3-*:1.3.1"
```
> **Note:** the argument needs to be enclosed in quotes as otherwise your shell might try to expand the globs and fail.
Demo:
https://github.com/NativeScript/nativescript-cli/assets/879060/71acd160-f6ca-422d-ba0f-b0bcc64eb531
> feat: interactive typings generation for android

- lib/base-package-manager.ts
- lib/commands/typings.ts
- lib/common/mobile/android/android-virtual-device-service.ts
- lib/services/android-plugin-build-service.ts
- lib/services/android/gradle-command-service.ts
Various commands will fail on windows with EINVAL on the latest patch level of node due to node patch for CVE-2024-27980
Commands should execute correctly.
> fix(windows): make compatible with latest node patch levels

- lib/definitions/project.d.ts
- lib/project-data.ts
- test/project-data.ts
Currently the files generated during the build process take the project name from the basename of the directory the project is contained in.  
If (and only if) the new 'projectName' setting is present in the nativescript.config.ts file, the name specified there is used instead of the basename of the project directory.
Fixes/Implements/Closes #2107
(Note on iOS this requires an additional patch to @nativescript/webpack5 that will be linked below)
> feat: Add support for 'projectName' setting (#2107)

- lib/services/android-plugin-build-service.ts
- lib/services/android/gradle-build-args-service.ts
- package-lock.json
- package.json
- test/services/android/gradle-build-args-service.ts
- vendor/aab-tool/README.txt
- vendor/gradle-plugin/build.gradle
> feat: gradle 8, kotlin 2.0 & update bundletool

- lib/common/mobile/android/logcat-helper.ts
If you start the app through the launcher and the app is already open, we restart the logcat process and miss a few logs in the process. The current log line we're using to detect the start doesn't return the new PID at all and can conflict with apps with similar package names. This is a regression from #5755
We accurately use a specific regex (`/Start proc (?<pid>[0-9]+):(?<appId>.+?)\//`) to find the exact appId and PID.
> fix: use more accurate PID detection on restart for android

- .vscode/settings.json
- docs/man_pages/project/configuration/native/native-add-java.md
- docs/man_pages/project/configuration/native/native-add-kotlin.md
- docs/man_pages/project/configuration/native/native-add-objective-c.md
- docs/man_pages/project/configuration/native/native-add-swift.md
- docs/man_pages/project/configuration/native/native-add.md
- docs/man_pages/project/configuration/native/native.md
- lib/bootstrap.ts
- lib/commands/native-add.ts
You have to know where and how to add native source files to your project.
Provided commands
```shell
ns native add swift SomeClass
ns native add objective-c SomeOtherClass
ns native add java some.thing.SomeClass
ns native add kotlin some.thing.SomeOtherClass
```
> feat: native add command to add native source files to the project

- lib/controllers/migrate-controller.ts
ns migrate would go to 8.7.
ns migrate will now go to 8.8 in addition to bumping all associated dependencies.
> feat: migrate 8.8 and associated depedencies

- lib/base-package-manager.ts
- lib/common/mobile/android/android-virtual-device-service.ts
- lib/services/android-plugin-build-service.ts
- lib/services/android/gradle-command-service.ts
This is a follow up of https://github.com/NativeScript/nativescript-cli/pull/5802
When building on windows, the new `shell: true` option doesn't escape arguments anymore, meaning that any commands that had spaces in their path would not work. This includes npm/adb/avd paths and app paths (that get passed to gradle via arguments)
We now quote every command to preserve the previous behavior.
> fix: quote windows command line arguments

- lib/common/mobile/emulator-helper.ts
- packages/doctor/src/android-tools-info.ts
- packages/doctor/test/android-tools-info.ts
A fresh android studio install does not work as it installs build tools 35 by default. Android sdk 35 is currently unsupported by the CLI
Adds support for android 35
> feat: add android 35 support

- lib/commands/typings.ts
Use of '/' to split paths on windows results in error/ "undefined' being displayed.
Uses path.sep as per Issue  #5810.
> fix: typings  path separator on windows

- lib/services/ios/ios-signing-service.ts
If the cli finds multiple Apple team ids, it prompts you to choose one.
Then it prompts you to persist the value to either the `build.xcconfig` file or to the `platforms` folder.
If you choose the `platforms` option, it does save it there, but it never uses it, and on subsequent runs it prompts again.
With this change the persisted team id is used, if it is found in the list of acceptable team ids.
> fix: apple team id not being used when persisted to the platforms folder

- lib/controllers/prepare-controller.ts
- lib/data/prepare-data.ts
- lib/declarations.d.ts
- lib/definitions/prepare.d.ts
- lib/options.ts
- lib/services/webpack/webpack-compiler-service.ts
- test/controllers/prepare-controller.ts
See discussion:  https://discord.com/channels/603595811204366337/1276116878154268763
It seems to be the case that sometimes when an iOS app is updating it does not overwrite the old js files with the new versions, resulting in app crashes etc.
This adds a new flag `--unique-bundle` which instructs the cli to generate an id, which is then passed to webpack to be appended as a suffix to generated bundle names.
The cli then uses this id to set the main entry in the package.json in the resulting app.
Note:  In the discussion linked to above the files are generated with hashes, but then it becomes complicated to find the correct name of the main entry and I believe more brittle. An option would be to use something like the `webpack-manifest-plugin` to find the hashed value, or just assume a …
> feat: build flag to append generated suffix to bundles

- lib/key-commands/index.ts
Now user can specify a path to android-studio using NATIVESCRIPT_ANDROID_STUDIO_PATH
> feat: custom android-studio path to support nixos using new env.NATIVESCRIPT_ANDROID_STUDIO_PATH

- lib/commands/appstore-upload.ts
- lib/services/apple-portal/apple-portal-application-service.ts
- lib/services/apple-portal/apple-portal-session-service.ts
- lib/services/apple-portal/srp/srp-wrapper.ts
- lib/services/ios/export-options-plist-service.ts
- lib/services/ios/xcodebuild-service.ts
- package-lock.json
- package.json
- test/services/ios/export-options-plist-service.ts
- test/services/ios/xcodebuild-service.ts
Any operation in the CLI which requires an authentication to apple fails with a 401.
Apple authentication changed to a srp implementation, which resulted in the exiting code breaking with an error of 401 on anything that required authentication.
This PR uses a SRP implementation to perform the authentication in the apple way (it is not standard SRP) it consumes a new dependency (@foxt/js-srp) which performs the SRP calculations.
In addition to the authentication, this PR also Fixes:
* `ns appstore list` a further change in the apple api was causing this to fail.
* `ns publish` when providing a profile, changed it to use the `buildForAppStore` flag which results in the correct behaviour, also adding `signingStyle manual` to the export plist.
* `ns publish` without specifying a profile. …
> fix: apple authentication, appstore list, publish

- lib/services/webpack/webpack-compiler-service.ts
With PR #5817 the `options.env` is set, this seems to have the effect of removing appData from the environment which windows needs to complete a build.  Not sure if this is the best corrective action but adding it explicitly  here allows builds on windows to proceed.
Build succeeds on windows.
Note to test on windows with the latest alpha we also need PR https://github.com/NativeScript/ios-mobileprovision-finder/#22
> fix(windows): APPDATA is required for windows

- lib/common/mobile/android/android-ini-file-parser.ts
When setting up a new Mac I found that `ns run android` would not find and launch the android emulator, this is a result of the AVD config file having a space at the end of the key, which forces the code to rely on defaults, which did not match what android studio did in creating the VM.  This may be new android studio behaviour, as the previous code worked on my previous setups ( Win & Mac).
`ns run android` should launch the android simulator if it is not running.
> fix(android): emulator ini file parsing

- package-lock.json
- package.json
The previous  ios-device-lib was compiled with x64 only, so `ns device` failed silently on a new apple silicon Mac without Rosetta installed.
New ios-device-lib was compiled with x64 & arm so works without Rosetta.
> fix: ios-device-lib compiled with arm and x64

- lib/definitions/ios.d.ts
- lib/services/ios-project-service.ts
- lib/services/ios/spm-service.ts
Plugins cannot define their own Swift packages.
Plugins can now include a `nativescript.config.ts` at root of plugin directory to have any `SPMPackages` included in the build.
> feat: plugin nativescript.config support with SPMPackage inclusion

- lib/definitions/ios.d.ts
- lib/services/ios-project-service.ts
- lib/services/ios/spm-service.ts
Allows iOS widgets/extensions to utilize swift packages defined by `nativescript.config`
https://github.com/NativeScript/NativeScript/pull/10695
https://github.com/rigor789/trapeze/pull/1/files
> feat(ios): multi target support for swift packages

- lib/bootstrap.ts
- lib/commands/config.ts
- lib/commands/widget.ts
- lib/definitions/project.d.ts
- lib/services/project-config-service.ts
- lib/tools/config-manipulation/config-transformer.ts
- package-lock.json
- package.json
iOS Widget/Extensions currently require a lot of manual setup to integrate.
Introduces `ns widget ios` with prompts for a single command generator which even sets up a local shared Swift package to share Widget model/attributes between the host app and the widget (to not have to duplicate swift files). It also auto-updates config's to support them.
https://github.com/NativeScript/nativescript-cli/issues/4472
https://github.com/NativeScript/nativescript-cli/issues/5520
https://github.com/NativeScript/nativescript-cli/issues/5291
> feat(ios): 'ns widget ios' for single command widget generator

- docs/man_pages/project/configuration/widget-ios.md
- docs/man_pages/project/configuration/widget.md
- docs/man_pages/start.md
new widget command does not appear in the `ns --help` help.
Add `ns widget` to the help system.
> chore(docs): add widget to docs

- lib/common/verify-node-version.ts
- package.json
If feat/dep-updates is pushed to main, node >=22.12 is required and running on node < 22.12 will cause a crash.
Explicitly state the requirement for >=22.12, and allow the node version check code to run successfully on node < 22.12.
> chore: set min node version

- lib/color.ts
- lib/common/file-system.ts
- lib/common/opener.ts
- lib/common/verify-node-version.ts
- lib/services/assets-generation/assets-generation-service.ts
- lib/services/terminal-spinner-service.ts
- package-lock.json
- package.json
cli contains ESM only modules and therefore enforces node >= 22.14
ESM only modules are reverted and the requirement for 22.14 backed out.
> fix: support < 22.14

- lib/bun-package-manager.ts
- lib/node-package-manager.ts
When run application (without `node_modules`) is launched directly with the `ns run|debug xx` cli, we may encounter dependency issues because this flag causes npm to ignore `peerDependencies`, resulting in an incomplete `node_modules` path.
Documentation: https://docs.npmjs.com/cli/v11/using-npm/config#legacy-peer-deps
> fix: remove --legacy-peer-deps flag on install

- lib/services/assets-generation/assets-generation-service.ts
Right now, cli cannot generate assets the alpha of which is disabled.
Output:
```sh
ns resources generate icons ./icon.png
Generating icons ...
image.colorType is not a function
```
This behaviour broke during 8.9 update and update of `Jimp` dependency.
Cli will be able to generate assets the alpha of which is disabled (rgba: true).
> fix: icon generator color type error

- package-lock.json
- package.json
closes https://github.com/NativeScript/nativescript-cli/security/dependabot/234
closes https://github.com/NativeScript/nativescript-cli/security/dependabot/207
> fix(security): xml2js and braces

- .github/workflows/codeql.yml
This change include the addition of [CodeQL](https://codeql.github.com/) as the [SAST](https://en.wikipedia.org/wiki/Static_application_security_testing) tool for the project. It will run an analysis every day (73c264ae9a4508b3e59bc0fcab1e2cc1d3b5039b) and also on PRs and when landing commits to `main`.
**Changes related**
- [OSSF Scorecard Documentation | SAST](https://github.com/ossf/scorecard/blob/a25f108f4b0c1c5a6e6c4b99f4c4e0b0710555a9/docs/checks.md#sast)
**References**
- Report: https://ossf.github.io/scorecard-visualizer/#/projects/github.com/NativeScript/nativescript-cli
> Add CodeQL (SAST)

- lib/nativescript-cli.ts
`ns prepare android` etc. does not work on windows
The reason is that the latest versions of `shelljs` use `fast-blob` which does not support `\` as a path separator.
This wraps calls to `shelljs.cp` on windows and replaces the `\` with `/`.
> fix: windows glob paths used in copy operations not working.

- lib/commands/config.ts
When using `ns config set <any-key> <value>`, if <any-key> had no current value, prevent the throw by just ignoring to allow the value to still be set.
> fix(config): using set with undefined
